### ISSUE TITLE
Don't spam people on Github - Meaning, don't import @ people in comments.

### ISSUE THREAD

**Issue by Alexia** [widelands/widelands#3460]
You just spammed me with tons of email due to not sanitizing users in issue descriptions/comments during your import.

**Comment by gunchleoc** [comment]
I apologize for the spam, I did not expect the tool to tag people :(

I have created an issue at the tool so people who use it in the future will have a chance of being aware of the problem

https://github.com/termie/lp2gh/issues/8

Pull requests have been rotting there since 2015 though ;(
