### ISSUE TITLE
Link open issues on launchpad to this tracker

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3462]
For each open issue:

1. Follow the link to the issue on Launchpad
2. Double-check if it has the correct open/closed status here
3. Add a comment to the Launchpad issue "Migrated to <link to GitHub issue>"
4. Set the bug on Launchpad to "Won't Fix"

When this task is done, bugs should show up empty on Launchpad. If they don't double-check if the still open issues can be found here (Search both open and closed issues, create new GitHub issue if necessary).

**Comment by TinoM** [comment]
I've started with this. We should add the label "launchpad_done" to the github issue, so we don't loose track.
The label can be removed later.

**Comment by gunchleoc** [comment]
Sounds good to me.

I notices that you manually movde over attachments. Only do that if you really want to spend the time - attachments will still be available form Launchpad even when we deactivate the bug tracker over there. I think savegames might be worth grabbing, just in case.

**Comment by TinoM** [comment]
Yes, that was only a test. You can only attach pictures and archives to issues, not even patchfiles or savegames (perhaps when zipping them).

I am thinking of scripting this due to the huge amount of issues. But of course this would go against the manuel double check. What is your opinion on this?

**Comment by TinoM** [comment]
And by the way: On launchpad we had "Fix committed" and then "Fix released".
How do you want this mapped on Github? Do we close bugs with a fix commit or with the release of a milestone? e.g. #3455

**Comment by stonerl** [comment]
Fix committed == Issue Closed
Fix Released == Milestone Closed

**Comment by gunchleoc** [comment]
> Fix committed == Issue Closed
> Fix Released == Milestone Closed

Sounds good to me. We can delete those 2 labels once we're done.

And yes, savegames etc. will need zipping.

If you want to script this, maybe you can script the double-check too?

**Comment by gunchleoc** [comment]
Looks like "Fix committed" issues were left in open state by the migration script. So, I'll go through the issues assigned to the milestone first and clean them up, then we can add anything that's still "Fix committed" to the milestone and close them too.

**Comment by gunchleoc** [comment]
The milestone tickets are done.
