### ISSUE TITLE
Automate utils/fix_formatting.py

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3471]
Until now, bunnybot took care of running 'utils/fix_formatting.py` on every merge. We need to find a new solution for this.

If all else fails, have one designated person running it manually on their machine - `clang-format` results differ from machine to machine, so we can't just let everybody run it.

**Comment by gunchleoc** [comment]
This script should reduce the fallout if people run it locally: https://github.com/barisione/clang-format-hooks/

**Comment by stonerl** [comment]
Hmmm, maybe we can integrate this into a webhook?

**Comment by stonerl** [comment]
I try to incorporate this into a git-hook.

**Comment by stonerl** [comment]
Do we just want to add the scripts or add the repo as a git sub module?

**Comment by gunchleoc** [comment]
We cannot have developers run this on their local machines. The clang-format results will change depending on the machine, resulting in useless merge conflicts :(

**Comment by stonerl** [comment]
Why does this change depending on the machine? I'm currently testing this. It utilizes the .clang-format file in the root folder. The developers just need to add a pre-commit hook. I'll show you what I mean in my PR.

**Comment by gunchleoc** [comment]
Because every time I ran it, the results differed from what Bunnybot had produced. It seems that different versions of clang-format interpret the .clang-format file differently.

**Comment by gunchleoc** [comment]
I can't reproduce the problem with my machines any more, so I guess that they have fixed it.

The submodule makes it easy for maintenance, but it will be scary for newcomers, because now they have to learn how to deal with submodules too. So, I'd rather add this in a directory under utils with a link to the original repo.

The lua tabs formatting still produces differences, but clang-format doesn't any more.

We also run pyformat, which we could set up to run only if there are changed python files.

**Comment by gunchleoc** [comment]
Fixed in b1f5bebf4010f2e41fe6bb92fd2c397ac6357f9c
