### ISSUE TITLE
Problem with datadir in XDG mode

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3490]
When I build latest Widelands with XDG enabled (which is the default now), it tries to use the datadir from `/usr/share/widelands` (the datadir from Build 20 installed via the Manjaro's package manager) and fails to run, spitting out some Lua errors. I have to use the `--datadir` switch to keep it from doing that. Not sure if a bug or working as intended, but it took me a while to figure out what was wrong.

Reported on the forum: https://www.widelands.org/forum/topic/4604/?page=5#post-29870

**Comment by gunchleoc** [comment]
#3518 might be related

**Comment by Lucki** [comment]
> Not sure if a bug or working as intended,

That's working as intended:

> [There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable `$XDG_DATA_DIRS`.][1]

> [`$XDG_DATA_DIRS` defines the preference-ordered set of base directories to search for data files in addition to the `$XDG_DATA_HOME` base directory. The directories in `$XDG_DATA_DIRS` should be seperated with a colon ':'.][1]
> [If `$XDG_DATA_DIRS` is either not set or empty, a value equal to `/usr/local/share/:/usr/share/` should be used.][1]

[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
___

[2]: https://www.widelands.org/forum/post/29881/

> [The problem is that it tries to use the data directory (the one with images, music etc.) from an older version installed from the distro's repositories, instead of the one located together with the widelands executable (where it was compiled).][2]

He/She should just compile without XDG, set the variable as desired or as the best option use the `--datadir` switch as that's a development case.
