### ISSUE TITLE
Check Travis integration

### ISSUE THREAD

**Issue by TinoM** [widelands/widelands#3493]
The new Travis repository seems to enforce the normal 50 minutes limit for jobs.

Looking at the old (wideland-old) repository, it seems there was an exception for us, because there are many finished jobs > 50 minutes.

Maybe we can again ask for this as an OpenSource project?

**Comment by stonerl** [comment]
From what I read it is now possible to use caches. E.g. we can use ccache for the builds this could speed up the builds.

**Comment by stonerl** [comment]
Also, from what I read if we move our project from travis-ci.org to travis-ci.com we have the same execution time (120min) per job as private repos, since we are an open source project.

See here: [Open Source Accounts](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/)

**Comment by gunchleoc** [comment]
> From what I read it is now possible to use caches. E.g. we can use ccache for the builds this could speed up the builds.

I researched ccache a few years ago because my machine was slow and decided against it, because I couldn't be sure that the builds would reflect the current state of the project with 100% certainty. So, we should research this carefully to see if that is still a concern before using it.

**Comment by stonerl** [comment]
I use ccache on my Mac without problems. Also my Travis changes use ccache for macbuilds. The build time is reduced tremendous, from 40 minutes to 16.

I'm currently looking into the Linux builds.

**Comment by gunchleoc** [comment]
Since you have good experience with it, let's use it. Reducing the build time will be excellent :)

I found this: https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake

**Comment by stonerl** [comment]
Another question regarding the regression test. Do we need to run them in debug and release builds or would it be sufficient to run them in release only?

**Comment by gunchleoc** [comment]
It's better to run them in both modes. For example, if somebody adds an assert or other special debug code that has an unintended side effect, we could catch this via the tests if the code passes that point.

**Comment by stonerl** [comment]
Do we need to run the documentation test in every build? Wouldn't it be enough to have one dedicated job just for this?

Also, wouldn't it be sufficient to have just one job for the codecheck? If it throws an error, we then don't start the others.

**Comment by gunchleoc** [comment]
It would be sufficient to run them in 1 build, yes.

I just compared the old and the new list of builds, and we have lost some coverage for compiler versions under Linux:

```
CLANG_VERSION="3.4"
CLANG_VERSION="3.5"
CLANG_VERSION="7"
CLANG_VERSION="8"
clang 3.4
clang 7

GCC_VERSION="4.8"
GCC_VERSION="4.9"
GCC_VERSION="7"
GCC_VERSION="8"
gcc 4.8
gcc 5.4
gcc 7.4
```

**Comment by stonerl** [comment]
Regarding clang:
 
- clang 3.4 is build on trusty
- clang 7 is build on bionic
 
CLANG_VERSION="3.4 == clang 3.4
CLANG_VERSION="7" == clang 7
 
Regarding gcc:
 
- gcc 4.8 is build on trusty
- gcc 5.4 is build on xenial
- gcc 7.4 is build on bionic
 
GCC_VERSION="4.8" == gcc 4.8
GCC_VERSION="7" == gcc 7.4
 
So we lost clang 3.5 & 8 and gcc 4.9 & 8.
 
The version 8 of either can be added back in later. Any particular reasonfor re-adding clang 3.5 and gcc 4.9?
 
BTW. We gained coverage for clang 5 with macOS 10.13 and clang 3.9 with macOS 10.12


Sat Sep 21 14:49:19 GMT+02:00 2019 gunchleoc <notifications@github.com>:

**Comment by gunchleoc** [comment]
We originally checked the 2 oldest and 2 newest versions of the compilers. I think checking the LTS releases only should be fine also. Does Travis support building with Ubuntu Eoan, so that we can run GCC9?

**Comment by stonerl** [comment]
Currently, it doesn't. But we can add it via repositories. Will have a look into this later.

**Comment by gunchleoc** [comment]
Thanks!

I can look into skipping codecheck.

**Comment by stonerl** [comment]
About that website-tools. They are used for our website. So we only need to build them on bionic release. Since, that's what we run on our server. So we could omit building the website tools on all builds and add an extra job running on bionic with the default compiler and without the regression test just for the website tools.

**Comment by gunchleoc** [comment]
The website tools will also include the tool to create spritesheets, because I didn't want to have an extra compile switch for that. We will want that one available to artists who run older versions of Linux I guess. Let's wait and see if the latest builds will time out before making a decision on that.

**Comment by gunchleoc** [comment]
We ran into a timeout again in spite of all our efforts, so I have asked Travis and they have generously increased our timeout again for us :)
