### ISSUE TITLE
player-color on atlantean buildings too dark

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3496]
Since I started playing Widelands I noticed that the parts of atlantean buildings that use player-colours are reeealy dark. Especially with the standard blue it makes it look as if it's well after dusk. To me it makes the whole scenery look darker, at least on greenland terrains (maybe fighting severe depressions makes me extra sensitive to such things).

Making the player colors darker was a decision by the graphic artist at the time - the blue is not player color, it's there to darken the colors on purpose.

Migrated from https://bugs.launchpad.net/widelands-media/+bug/1652536

**Comment by tothxa** [comment]
Does this concern anyone else? I could make those blue military roofs lighter, but I like them the way they are. It's kind of a trade mark of the tribe IMO.

**Comment by frankystone** [comment]
Nordfrees implemented also individual player colors, so if someone thinks it's too dark he can change the color him/herself.
Moreover the look and feel of colors is highly hardware dependent.

I am in favor of closing this.

**Comment by tothxa** [comment]
Well, because of the underlying blue colour of the military roof, choosing your own colour doesn't help this. Also workers' clothes, flags, sails and cloth shaders on ship/ferry yards have white underlying colour. :)
