### ISSUE TITLE
Amazon models

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3499]
This bug is to keep track of graphics development for the amazons tribe.

Migrated from https://bugs.launchpad.net/widelands-media/+bug/1840761

**Comment by gunchleoc** [comment]
Sketches by Noordfrees
![wl-amazons](https://user-images.githubusercontent.com/4095570/65038912-ed159c80-d948-11e9-8a7a-9fabf1545353.png)
![wl-amazons2](https://user-images.githubusercontent.com/4095570/65038913-ed159c80-d948-11e9-8931-4cd30acb2c81.png)

**Comment by hessenfarmer** [comment]
Well, as only tapirs are missing I'd propose this issue to be closed
