### ISSUE TITLE
ASan crashes reset sound settings

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3507]
- Start Widelands, choose Options -> Sound, disable all five sound checkboxes. Also change some other settings.
- Close and restart Widelands. All settings were saved correctly, sound is disabled.
- Do something that causes an ASan error (tested with multiple development branches), or try force-quitting while the editor is loading
- Start Widelands. The sound settings are reset to the defaults; other changed options are unaffected.

Of course a crash means almost by definition undefined behaviour, so one can´t really expect everything to work correctly when the game crashes, but since only this one option section is affected (and I believe the sound settings were also not affected by crashes in b20), I consider this worth fixing.

**Comment by gunchleoc** [comment]
I am getting this tool

**Comment by stonerl** [comment]
This isn't related to the crash. If you delete your old config file, widelands creates a new one at start the only contains 2 values.

```
[global]
ai_training="false"
auto_speed="false"
```

The go to the options and press ok without changing any settings:

```
[global]
ai_training="false"
auto_speed="false"
xres="800"
yres="600"
fullscreen="false"
inputgrab="false"
maxfps="25"
snap_windows_only_when_overlapping="false"
dock_windows_to_edges="false"
animate_map_panning="true"
panel_snap_distance="0"
border_snap_distance="0"
autosave="900"
rolling_autosave="5"
nozip="false"
write_syncstreams="true"
auto_roadbuild_mode="true"
transparent_chat="true"
single_watchwin="false"
ctrl_zoom="true"
language=

[sound]
enable_ui="true"
volume_ui="128"
enable_message="true"
volume_message="128"
enable_chat="true"
volume_chat="128"
enable_ambient="true"
volume_ambient="128"
enable_music="true"
volume_music="64"
```

Close Widelands and start it again. The config gets reset to the following values during start:

```
# Automatically created by Widelands r24304[17e227d@master] (Release)

[global]
ai_training="false"
auto_speed="false"
xres="800"
yres="600"
fullscreen="false"
maxfps="25"
snap_windows_only_when_overlapping="false"
dock_windows_to_edges="false"
animate_map_panning="true"
panel_snap_distance="0"
border_snap_distance="0"
autosave="900"
rolling_autosave="5"
nozip="false"
write_syncstreams="true"
auto_roadbuild_mode="true"
transparent_chat="true"
single_watchwin="false"
```
