### ISSUE TITLE
Wrong/Misleading ToolTipText

### ISSUE THREAD

**Issue by jmoerschbach** [widelands/widelands#3510]
While playing first mission of the Atlanteans, wrong tooltiptext was visible. See screenshot.

OS: Win10
Version: Official Build20
Attachments: Savegame and screenshot
However, after restarting game and loading the savegame, it looks fine again
![tooltip](https://user-images.githubusercontent.com/10723431/65371915-1005c080-dc69-11e9-901b-8a80577c84ab.png)

[wrong tooltiptext.zip](https://github.com/widelands/widelands/files/3638569/wrong.tooltiptext.zip)

# To fix:
- [x] Allow more space in tooltips (problem does not reproduce)
- [ ] Fix German translation to shift the "ist" where it belongs

**Comment by gunchleoc** [comment]
This is the program being dieplayed:

    "return=skipped when site has corn and economy needs cornmeal and not economy needs blackroot_flour",

@hessenfarmer Can you check the German translation to tweak the sentence structure?

There is also a truncation issue, we need to allow longer tooltips here.

**Comment by jmoerschbach** [comment]
Hi @gunchleoc @hessenfarmer 
since I would like start contributing to this great project, maybe you can point me to the right location in the code a little bit more precisely and I can work on this myself? :)
I'm german too, so the translation issue should not be a big deal...

**Comment by gunchleoc** [comment]
@jmoerschbach Our translations are handled via Transifex, see https://www.widelands.org/wiki/TranslatingWidelands/

The tooltip code is in [bool Panel::draw_tooltip(const std::string& text)](https://github.com/widelands/widelands/blob/master/src/ui_basic/panel.cc#L1086).

I have just updated our README.md, which should be enough to get you going. Please let us know if we can improve the instructions or if you need any more help to work on this. Thanks for picking up this issue! :)

**Comment by jmoerschbach** [comment]
Hi @gunchleoc,
I successfully managed to download the code, compile and build trunk version :)
For testing purposes, I just hardcoded a very long string in the draw_tooltip method, so I could observe some improvement by increasing kTipWidthMax. However, even with the original value of 360, the problem does not exist in trunk version anymore (see screenshot, last scenario of the introduction maps: "economy").
Or maybe it cannot be reproduced that easily and the problem lies within the translatable text? It looks like it is rendered in a different way (in my first screenshot it looks more bold).
I am still struggling with transifex. I haven't been able to find the exact text. Do you know in which resource I need to look (I assumed "Widelands Main")
![tooltipcorrect](https://user-images.githubusercontent.com/10723431/65393714-ac70b580-dd84-11e9-8517-4c8a02907a36.png)
?

**Comment by gunchleoc** [comment]
Let's leave the C++ side like it is then and only fix the string in Transifex.

The production program strings are complicated to translate, because they are assembled out of sentence fragments. We have some special documentation for them: https://www.widelands.org/wiki/TranslatingWidelands/#production-program-messages

"Das Mahlen von Dunkelrüben", "Mais" and "Maismehl" are translated in *Tribes*, everything else should be in *Widelands Main*.

**Comment by hessenfarmer** [comment]
The nproblem is if we change the sentence structure (the order of the fragments this might lead to issues in other tooltips. Anyhow I will have a look into it.

**Comment by gunchleoc** [comment]
Let me know if we need to change the strings to allow for natural German sentence structure.

**Comment by hessenfarmer** [comment]
Ok I changed the translation slightly for the site has and site has not strings. the result for the given constellation in german should be:
"Das Mahlen von Dunkelrüben wurde übersprungen, weil das Gebäude folgende Waren hat: Mais, die Wirtschaft die Ware Maismehl braucht und die Wirtschaft die Ware Dunkelrübenmehl nicht braucht." 
This could be further improved (if wanted) by replacing "folgende Waren" with the list of wares string. Resulting in 
Das Mahlen von Dunkelrüben wurde übersprungen, weil das Gebäude Mais hat, die Wirtschaft die Ware Maismehl braucht und die Wirtschaft die Ware Dunkelrübenmehl nicht braucht."

**Comment by hessenfarmer** [comment]
Btw curently these strings are #267 and #268 in Widelands main on transifex

**Comment by gunchleoc** [comment]
We could split this in the engine into 2 strings, one for 1 ware, and the other for multiple wares. This would allow for more elegant translations.

**Comment by hessenfarmer** [comment]
In my second suggestion there is no need to change the engine I believe. If youi agree I'll implement that

**Comment by jmoerschbach** [comment]
Ah, ok now I understand the very first time what the tooltip actually is trying to say :D
In this particular case, it would be most comprehensive when it would just say
"Das Mahlen von Dunkelrüben wurde übersprungen, weil die Wirtschaft die Ware Dunkelrübenmehl nicht braucht", wouldn't it?

But I see that this is most probably a special case - when a site depends on more "intermediate" resources, the complete string is necessary.

I like @hessenfarmer 's last suggestion best. I've seen already his changes on transiflex. I just need pull and build trunk to have up to date localization status or is some more magic needed in order to test it? ;)

**Comment by gunchleoc** [comment]
I run a script about once per week to update the translations from Transifex. I have done so now, so the next time you pull or merge master and recompile, you will have it.

As an alternative, you can always download the current po file from Transifex and save it in the proper spot in the po directory, then recompile with translations. You can also use a tool like Virtaal to generate the .mo file, which then goes into the locale directory.

If you're happy with it, we can close this issue.

**Comment by hessenfarmer** [comment]
> 
> 
> Ah, ok now I understand the very first time what the tooltip actually is trying to say :D
> In this particular case, it would be most comprehensive when it would just say
> "Das Mahlen von Dunkelrüben wurde übersprungen, weil die Wirtschaft die Ware Dunkelrübenmehl nicht braucht", wouldn't it?

No it wouldn't. The tooltip is compiled from the exact conditions set in the Production program for skipping. In this particualr case the mill will only skip the "grinding balckroot" program if the economy does not need black root flour AND the economy does need corn flour AND it has enough corn. In any other case e.g. it does not have corn it will try to grind blackroot if blacckroot is available. 

> 
> But I see that this is most probably a special case - when a site depends on more "intermediate" resources, the complete string is necessary.
> 
> I like @hessenfarmer 's last suggestion best. 

@ GunChleoc so shall we give that a try?

**Comment by gunchleoc** [comment]
Yes, let's give it a try.

**Comment by jmoerschbach** [comment]
> 
> 
> > Ah, ok now I understand the very first time what the tooltip actually is trying to say :D
> > In this particular case, it would be most comprehensive when it would just say
> > "Das Mahlen von Dunkelrüben wurde übersprungen, weil die Wirtschaft die Ware Dunkelrübenmehl nicht braucht", wouldn't it?
> 
> No it wouldn't. The tooltip is compiled from the exact conditions set in the Production program for skipping. In this particualr case the mill will only skip the "grinding balckroot" program if the economy does not need black root flour AND the economy does need corn flour AND it has enough corn. In any other case e.g. it does not have corn it will try to grind blackroot if blacckroot is available.

Ah ok, thanks for the explanation. I looked into the lua script and think I understood it :)

> > But I see that this is most probably a special case - when a site depends on more "intermediate" resources, the complete string is necessary.
> > I like @hessenfarmer 's last suggestion best.
> 
> @ GunChleoc so shall we give that a try?

Ok, since I do not really know what exactly to do (and by "we" maybe @hessenfarmer meant actually himself?) maybe this should be assigned to him? However, I'll gladly test it as soon as it is fixed...

In the meantime I'll dig through c++ and lua code and focus on one of the other good first issues then.

**Comment by gunchleoc** [comment]
Excellent! Let me know if you have any questions. You can ask in the issue that you picked or on our forums.

**Comment by hessenfarmer** [comment]
Ok I changed the transifex strings. should work now for all combinations.

**Comment by gunchleoc** [comment]
Thanks!

**Comment by jmoerschbach** [comment]
Hi,
I just managed to test the translation fix on trunk version with new translation files.
It looks better, but unfortunately, even on trunk the problem with the too small tooltip I can now reproduce.
See screenshot (kTipWidthMax=360):
![grafik](https://user-images.githubusercontent.com/10723431/65719191-84939180-e0a5-11e9-85b6-085612b1069e.png)

Changing kTipWidthMax to 400, does result in increased width of the tooltip but that does not help:
![grafik](https://user-images.githubusercontent.com/10723431/65719205-8d846300-e0a5-11e9-9e28-df6044fc1cde.png)

So I guess there is still something wrong in the translation?

**Comment by jmoerschbach** [comment]
Hmm, in english it looks the same...
![grafik](https://user-images.githubusercontent.com/10723431/65746654-ae79a200-e0ff-11e9-9892-3cb01ff64f28.png)


Btw I think the english "translation" sentence structure should also be tweaked like the german version? :)

**Comment by gunchleoc** [comment]
Looks like a bug in the C++ code then

**Comment by hessenfarmer** [comment]
I believe this is a very special case and the issue lies within the following code
https://github.com/widelands/widelands/blob/a679819c79b7e263694e71f2de160db2ef7c8733/src/logic/map_objects/tribes/production_program.cc#L520  

reason is we are not handling the Negation of a condition correctly within the strings. So for the when condition we only can have positive strings (e.g. has ware economy needs) but not the negative one. The negative description is only used for "unless" conditions.

**Comment by jmoerschbach** [comment]
Thanks for the hint. I'll take a look :)

**Comment by jmoerschbach** [comment]
Hi,

I found the problem. Took me some while though (java developer with ahh very little knowledge of c++, yet...).

Problem is that not-conditions are masking the description and description_negation of the condition they "extend" from.

So, when changing 

https://github.com/widelands/widelands/blob/a679819c79b7e263694e71f2de160db2ef7c8733/src/logic/map_objects/tribes/production_program.cc#L291-L299

to

``` c++
// Just a dummy to satisfy the superclass interface. Returns an empty string.
std::string ProductionProgram::ActReturn::Negation::description(const Tribes& t) const {
	return operand->description_negation(t);
}

// Just a dummy to satisfy the superclass interface. Returns an empty string.
std::string ProductionProgram::ActReturn::Negation::description_negation(const Tribes& t) const {
	return operand->description(t);
}
```

(same as negating the return from evaluation in
https://github.com/widelands/widelands/blob/a679819c79b7e263694e71f2de160db2ef7c8733/src/logic/map_objects/tribes/production_program.cc#L287)

it looks better :)

![grafik](https://user-images.githubusercontent.com/10723431/65910004-195dfe00-e3ca-11e9-9af5-f2de6670bffb.png)

What is confusing now is: Tooltips for Not-Conditions should never have worked then, right?^^ Are they that rare to find in the game or why am I the first one to find this bug? :D

I'm not sure about any side effects, so some testing is needed of course. I'll create a proper pull request if you don't mind, for review and everything.

**Comment by gunchleoc** [comment]
Yes, this combination is rare and for this particular building it was introduces fairly recently. Thanks for finding it!

Do you want to create a branch or shall I?

**Comment by hessenfarmer** [comment]
thanks for fixing this. 
btw I would vote for having the original sentence fixed in the way we did for the german translation.
the wares list in the sentence the building has following wares: is compiled with and I believe so it would not harm to change it to e.g. the building has 3 x wheat and 2 x water
