### ISSUE TITLE
r24249[9e297d1@master] Assertion failed productionsite.cc, line 823

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#3538]
Please fill out the relevant sections below and delete the rest.

**Description**

I was playing my Map https://www.widelands.org/maps/unreal-waterflow-2
in single player mode. directly after loading I got:
Assertion failed: (&worker == working_positions_[main_worker_].worker), function get_building_work, file ../src/logic/map_objects/tribes/productionsite.cc, line 823.
Abort trap: 6

**To Reproduce**

Open the attached Save wile in some verion in Master, should crash almos immediately.
See complete Crashlog in Attached File.

**Expected behavior**

After saveloading every worker knows his place :-)

**Version:**
 - OS: macOS 10.14.6 (18G103)
 - Widelands Version: r24249[9e297d1@master] 

[Bug20191006.zip](https://github.com/widelands/widelands/files/3693982/Bug20191006.zip)

**Comment by hessenfarmer** [comment]
maybe this commit was the culprit
https://github.com/widelands/widelands/commit/5bf95ccbece41aca48abed735b4267f6773d6637

**Comment by stonerl** [comment]
Are we sure that the problem isn't the save game itself? I tried loading another one and that wasn't crashing. Also, when starting a new game and letting it run for some hours, I never encountered this assertion.

**Comment by stonerl** [comment]
> maybe this commit was the culprit
> [5bf95cc](https://github.com/widelands/widelands/commit/5bf95ccbece41aca48abed735b4267f6773d6637)

Nope, I reverted this commit and the game still crashes.

**Comment by klaus-halfmann** [comment]
Yep, still have the same Issue. Will check with the Debugger for some details

**Comment by klaus-halfmann** [comment]
* Some Bulding at 0% - cant out what kind of building, mmh
* main_worker_ is 0
* working_positions_.worker in NULL !
* Waiting for some worker to appear ...

task is "buildingwork"

I played a game now for about an hout _without_ that assert and found no Issues.
I think `working_positions_.worker` is null while waiting for workers to arrive

**Comment by klaus-halfmann** [comment]
@Noordfrees you added that assert, whats the sematic of it?
Can this happen diretly after load only, as some setup is still missing?

**Comment by Noordfrees** [comment]
The function with this assert gets called by a worker´s buildingwork task. This task should be started only for the main worker; this assert checks whether the worker calling it really is the main worker. For some reason, there is one atl-mine where only worker 2 is present but main_worker_ is 0. I have no idea yet how this can happen…

**Comment by klaus-halfmann** [comment]
AHH, this can can happen if you send the first Miner away, but it comes back as second/third miner! This usually is a transient state when you push miners from one mine onto another. I can stop the game directly after loading, and check for such a mine, lets see

**Comment by Noordfrees** [comment]
No, when you evict one worker the building instantly sets the main_worker_ to a different value if another worker is present, or -1 if there isn´t. When you send one worker away, the working position IDs of other workers do not change. The error already occurs during gameloading. The question is now whether your game was saved with wrong data or whether correct data is wrongly interpreted while loading

**Comment by stonerl** [comment]
Could this be one of our ominous save bugs. Like the one with the never arriving wares?

**Comment by klaus-halfmann** [comment]
OK, can we add a debuglog with the name and coordinated of the building?
or how I can I use a debugger to find it?

**Comment by klaus-halfmann** [comment]
Argh, I have overriden my second savegame with that bug ....

**Comment by Yeppisunatra** [comment]
Help me

**Comment by Yeppisunatra** [comment]
Thanks

**Comment by Noordfrees** [comment]
I had another look at this issue. The savegame still reproducably crashes with the assert in current master, and I still have no clue whatsoever why this can happen, or how to reproduce the issue. 
Since this bug was not reported again in the last five months, I'm in favour of closing this issue for now, and only taking care of it if it does happen again.

**Comment by Noordfrees** [comment]
Found again in #3857 
https://github.com/widelands/widelands/files/4567127/Turkey.wgf.zip
(not compatible with current master but with 5f07aaf)

**Comment by klaus-halfmann** [comment]
I was able to reproduce this bug now, in fact only one ATL Mine is needed.
[Test3538.zip](https://github.com/widelands/widelands/files/4569703/Test3538.zip)
Load Test3538#3.wgf and send away the second Miner in the GoldMine next to the HQ.
On _two_ attempts this resulted in the crash found in the second file. In one other attempt it resulted in a worsking savegame

singleplayer game on master git status
HEAD detached from 82ab4495cb

**Comment by klaus-halfmann** [comment]
Was able to rreporduce this now on master:
git log -n 3 commit a3ae263497cd094633e1bbd8abfe070688014d2d (HEAD, master)
[Test3538.zip](https://github.com/widelands/widelands/files/4569713/Test3538.zip)
Load Test3538#3.wgf (sngelpelyer) and send away the 2nd miner in that gold mine north of the QH
Save directly after that in 2 of three times this result in the crash, will no track this with a debugger
