### ISSUE TITLE
Wrong OpenGL resolution with macOS 10.15 Catalina

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#3542]
I Upgraded my OSX Computer to 10.14 Catalina.

I use MacPorts but the people there did not adopt it to Catlina, yet.
https://www.macports.org/install.php
They actually fight the first bugs here: https://trac.macports.org/search?q=Catalina

The relesed build 20 is fine.

I noticed some problems with master though:
- Display shows only 1/4 of the actual resolution -> Issue with retina display
   we had this with R20, too. So maybe we "just" need a fixed SDL Library or such
   Found now bugs for Catalina in sdl for now, closest thing I found was:
   https://bugzilla.libsdl.org/show_bug.cgi?id=3281
   R20 uses SDL version: 2.0.9 I have 2.0.10 but I cannot downgrade until macports works work for catalina :\

Can anyone direct me where the initial resoultion and pixels are dertemined?

I will collect other Issues herer once I hit them.

For now I will try a complete recompile to check if this fixes the Issue

**Comment by klaus-halfmann** [comment]
OK I installed MacPorts from the source, recompiled all my ports. 
But the Bug is still there :(. Dowgrading a Port ist not so easy:
https://trac.macports.org/wiki/howto/InstallingOlderPort. Maybe I try this tomorrow

**Comment by kencu** [comment]
Downgrading a port takes some initial setup, but after the first one, is easy.

You need to clone the entire macports repo somewhere. I put it in ```/opt``` to avoid permissions errors etc, but that's not the only place it could go. 
```
cd /opt
sudo git clone https://github.com/macports/macports-ports.git
```
once you have that, you have everything in macports history.

Then go to the folder you're interested in (which hopefully still exists, and in the case of libsdl2, it does) 
```
cd /opt/macports-ports/devel/libsdl2
```
now, find the commit you're interested in. 
```
git log .
```
will list them all. Look for the last commit before the update to 2.0.10, for example. Once you have that commit, copy it and then
```
sudo git checkout THECOMMITID
```
now, you're back where you wanted to be. If it's not too long ago, the Portfile will still work with the current MacPorts installation and other supporting ports. If it's from a LONG time ago, you might need to do some work to bring the Portfile into a usable state with the current situation.

Now, you can just install it right from where you are. If you don't specify a port, MacPorts will build the one in the current folder:
```
sudo port -v install
```
and you're good. But MacPorts will bug you about it being out of date every time you update your ports. So step 2 is to make yourself another repo:
```
sudo mkdir /opt/peggedports
cd /opt/peggedports
```
then make the devel folder 
```
mkdir devel
cd devel
```
an now copy the libsdl2 folder from the checked-out commit repo into your new repo
```
sudo cp -R /opt/macports-ports/devel/libsdl2 .
```
now you have it captured. Back up to the top directory
```
cd /opt/peggedports
```
generate a portindex
```
sudo portindex
```
and now, last step, edit your sources.conf file and put that new repo above the main macports repo. There is an example right in there to guide you:
```
bbedit /opt/local/etc/macports/sources.conf
```
save your changes with that file, and your pegged libsdl2 will be there forever until you change it. You can check that all it correct by asking port which libsdl2 it is using:
```
port file libsdl2
```
and it should show you
```
/opt/peggedports/devel/libsdl2/Portfile
```
and you're in business!

Back in the main repo, checkout master to clean up and get back to normal.
```
sudo git checkout master
```

**Comment by klaus-halfmann** [comment]
Thanks for you detailed descripton, I took a faster aproach and located the Portfile in gitlab. But trying to install it fails as some needed patchfiles can not be found any longer ...

```
5a95fbfd3617.patch does not exist in /opt/local/var/macports/distfiles/libsdl2
--->  Attempting to fetch 5a95fbfd3617.patch from https://distfiles.macports.org/libsdl2.
... 

Failed to fetch libsdl2: The requested URL returned error: 404 
```
OK so I removed all the patches and now have:
```
$ port installed libsdl2
The following ports are currently installed:
  libsdl2 @2.0.9_2 (active)
  libsdl2 @2.0.10_0
```

will recompile wiedelands now

**Comment by klaus-halfmann** [comment]
No Success:  
```
dyld: lazy symbol binding failed: Symbol not found: _SDL_RWseek
  Referenced from: /opt/local/lib/libSDL2_image-2.0.0.dylib
  Expected in: /opt/local/lib/libSDL2-2.0.0.dylib
```

will go back to libsdl2 @2.0.10_0 and investigat with a debugger?
@kencu any better idea how to proceed?

**Comment by kencu** [comment]
You can't do it like that. You have to do it the way I outlined to have any hope of it working, with all the patches in it's directory as it was at that point in time.

If you run into an associated port that refuses to rebuild successfully, go to the same commit point as where you found the libsdl2 version (ie keep the macports-ports repo at that same commit) and copy over the associated port as well (like perhaps libSDL2-image). Sometimes just a rebuild is all you need, but sometimes you need to roll the associated ports back to the older version as well.

It's not hard. You can do it!

**Comment by klaus-halfmann** [comment]
OK, I now did it the clean way:
```
**** SOUND REPORT ****
SDL version: 2.0.9
```

But the Bug is still here, So I am out of ideas.

<img width="979" alt="Bildschirmfoto 2019-10-11 um 11 21 55" src="https://user-images.githubusercontent.com/16598373/66640573-7dc65c00-ec19-11e9-90ec-02f39fc3f02e.png">

**Comment by klaus-halfmann** [comment]
@SirVer did / do we have any special tweaks for Retina Displays in Widelands?

**Comment by SirVer** [comment]
@klaus-halfmann not to my knowledge. It works on my retina without any issues too.

**Comment by klaus-halfmann** [comment]
OK I diggend into the code and (should not have been such a suprise) is using openGL to do most of the rendering. Deep don in the gears I found the `RenderQueue` but a that time all coordinates have become floats. So I will look around from some kind of global magnification factor which might be wrong. Not sure if SDL is still involved at that time.

And: Apple considers openGL deprecated and prefers metal, but it is still part of catalina.

**Comment by stonerl** [comment]
Cannot confirm this. There seems to be a problem with your system, I suppose.

**Comment by klaus-halfmann** [comment]
@stonerl  are you a) on Catalina? b) Do you have a Retina Display? c) are you using MacPorts?

I assume its the Mix of MacPorts and Catalina causing this one.

**Comment by stonerl** [comment]
a) yes
b) yes
c) no - homebrew

**Comment by klaus-halfmann** [comment]
Here is my list of libraries / versions:

libsdl2 @2.0.10
libsdl2_image @2.0.5
libsdl2_mixer @2.0.4
libsdl2_ttf @2.0.15
gettext @0.19.8.1_2
libiconv @1.16
zlib @1.2.11
libpng @1.6.37
boost @1.71.0
Python 3.7.3
glew @2.1.0 -- Most suspect
doxygen @1.8.16

Compiler: Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Will now check about the glew lib.

**Comment by klaus-halfmann** [comment]
My buest guess now is this call `SDL_GL_CreateContext(sdl_window);` in src/graphic/gl/initialize.cc 

But this is a mix of SDL2 and OpenGL so I have now idea whome to blame. I will ask josh the SDL Maintainer and @kencu for further help.

**Comment by jmroot** [comment]
This sounds like https://bugzilla.libsdl.org/show_bug.cgi?id=4822 -- probably worth mentioning there that it affects OpenGL as well as Metal.

**Comment by klaus-halfmann** [comment]
Hello @jmroot we got a Patch / Bugfix at https://hg.libsdl.org/SDL/rev/46b094f7d20e
I will change this in my local code, but I may need some advice how to do this.
Best would be a temporary patch so it kind of sticks

**Comment by klaus-halfmann** [comment]
@jmroot the above fix did the trick!. 
Will you need an offical Bug for Macports? on can we "sideuse" this one :-).
Please make this an official MacPorts patch.

Thanks to you and @kencu for the support.

**Comment by stonerl** [comment]
Maybe, just wait for the SDL developers to catch up and make a new release 2.0.11?

**Comment by TomQv** [comment]
Hi Guys, I have the same problem with a c#-Mono-App developed with Visual Studio Mac using the NSOpenGLView. With Catalina on Retina-Displays the Window.Frame size is now only a quarter of the actual size. With Mojave everything was fine. You found the problem in "SDL", what ever this is. Could you maybe point me in a direction, where I could find this with Visual Studio Mac and maybe how to solve that? 
Thanks Tom

**Comment by TomQv** [comment]
just found this:
https://github.com/ioquake/ioq3/issues/422
which solves the problem.
Thanks

**Comment by stonerl** [comment]
@klaus-halfmann could you give [this build](https://fosuta.org/widelands_10.9_r24263[d7a64b6@master].dmg) a try?

**Comment by stonerl** [comment]
This seems to be the [fix](https://hg.libsdl.org/SDL/rev/46b094f7d20e) in SDL.

**Comment by klaus-halfmann** [comment]
@stonerl confirm: your fix work for me, I will approve the PR now

**Comment by ryandesign** [comment]
libsdl2 2.0.12 includes the fix.

**Comment by gunchleoc** [comment]
Thanks for confirming! Closing this issue, since it has been fixed upstream.
