### ISSUE TITLE
REVDETECT-BROKEN-PLEASE-REPORT-THIS on current HEAD

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#3553]
I compile the current master and found REVDETECT-BROKEN-PLEASE-REPORT-THIS in VERSION

git status
On branch master
nothing to commit, working tree clean

commit e209f37cea9cdd8173d0c5a79527cd52f7347b47 (HEAD -> master)
Author: TinoM <TinoM@users.noreply.github.com>
Date:   Tue Oct 29 17:41:34 2019 +0100

git --version
git version 2.21.0 (Apple Git-122)

**To Reproduce**
* pull master or this particular commit over some older status
* ./compile.sh

**Expected behavior**
VERSION will always contain some reasonable identifier

**Additional context**
 - macOS 10.15 Catalina

will now recompile it completely

**Comment by stonerl** [comment]
PR #3552 should take care of this.

**Comment by klaus-halfmann** [comment]
OK my python --version is
Python 2.7.16
