### ISSUE TITLE
Compiling Warining regarding ships

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3563]
When compiling the latest master I get an this warning:

```
../src/logic/map_objects/tribes/ship.cc:898:15: warning: unused variable 'nr_all_old_dests' [-Wunused-variable]
        const size_t nr_all_old_dests = old_destinations.size();
```

@Noordfrees I think you touched the code the last time. Is this a leftover from old code?

**Comment by Noordfrees** [comment]
It´s not a leftover, but it´s used only for an assert in line 906.
I´m not sure how exactly the compiler treats asserts – would it be enough to surround the declaration with `#ifndef NDEBUG`, or would that then be a compile error in release builds?

**Comment by stonerl** [comment]
I guess an `#ifndef` would be sufficing.
