### ISSUE TITLE
Changing horizontal windows size

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3570]
**Describe the bug**
When opening the construction site window of a military building and clicking changing the number of soldiers that should be sent to this buildings, changes the horizontal size of the window. Either when the number changes from single to double digits or when the word 'soldiers' is changed to 'soldier'.

**To Reproduce**
1. Open the construction site windows of a military building.
2. Click on "Settings to apply..."
3. Reduce the number of soldiers to one
4. Windows changes size.

**Expected behavior**
Windows size shouldn't change.

@Noordfrees do you think we could have a minimum size for this tab? So that it will always have the size of the window when "12 soldiers" is displayed?

**Comment by Noordfrees** [comment]
Which number of soldiers results in the widest string may be i18n-specific; so iterating over all permitted values once, rendering a preview for each one and choosing the longest as fixed width for the textarea would do the trick. I don´t know how to get the rendered length of a string though

**Comment by stonerl** [comment]
I manually checked this. The widest rendering is the greek translation. This results in a window-with of 240 pixel.

I also saw the in-/decrease buttons start to move for languages like Japanese. So the windows size should be 240 and the buttons need to be on the left and right.

**Comment by gunchleoc** [comment]
@stonerl when merging, please make sure that attached issues have the next milestone assigned to them :)
