### ISSUE TITLE
 Widelands crash on every attempt to load a map for playing

### ISSUE THREAD

**Issue by schnedann** [widelands/widelands#3574]
**Describe the bug**
Widelands crash on every attempt to load a map for playing
The issue was first reported by me here:
https://bugs.archlinux.org/task/64501
And was verified and reproduced by others too

**To Reproduce**
start widelands
e.g. choose training Mission, select one of them, a screen with a progressbar appears, but the whole game crashes without any further notice

**Expected behavior**
A playable game opens?

**Screenshots**
![Bildschirmfoto_2019-11-15_21-29-11](https://user-images.githubusercontent.com/32240716/68973707-38d0af00-07ef-11ea-9ccc-90b85880d1c8.png)

This is esentially the screen you see right in the second, widelands just disappear without any further notice

**Version:**
 - OS: Archlinux
 - Kernel 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
 - Widelands Version:  "Build 20"

Archlinux Package Information
Repositorium             : community
Name                     : widelands
Version                  : 20-3
Beschreibung             : A realtime strategy game with emphasis on economy and transport
Architektur              : x86_64
URL                      : http://widelands.org/
Lizenzen                 : GPL
Gruppen                  : Nichts
Stellt bereit            : Nichts
Hängt ab von             : sdl2_mixer  sdl2_image  sdl2_net  sdl2_ttf  sdl2_gfx  lua  glew  python  boost-libs
Optionale Abhängigkeiten : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : widelands-data
Größe des Downloads      : 212,46 MiB
Installationsgröße       : 294,26 MiB
Packer                   : Felix Yan <felixonmars@archlinux.org>
Erstellt am              : 2019-11-12T02:48:26 CET
Verifiziert durch        : MD5-Summe  SHA-256-Summe  Signatur

Additional info:
* package version 20-3

if started from commandline there is some more information: it ends with "Speicherzugriffsfehler" which means Memory Access Error in German

This is Widelands Version build-20 (Release)
Set home directory: /home/myname/.widelands
Adding directory: /usr/share/widelands
selected language: (system language)
using locale de_DE.UTF-8
Graphics: Try to set Videomode 2560x1440
Graphics: OpenGL: Version "4.5 (Compatibility Profile) Mesa 19.2.4"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 0
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 2
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384
Graphics: OpenGL: ShadingLanguage: "4.50"
**** GRAPHICS REPORT ****
VIDEO DRIVER x11
pixel fmt 370546692
size 3840 2160
**** END GRAPHICS REPORT ****
Style Manager: Loading templates/default/init.lua ... took 1ms
Style Manager: Reading button styles ... took 2ms
Style Manager: Reading slider styles ... took 0ms
Style Manager: Reading tabpanel styles ... took 0ms
Style Manager: Reading editbox styles ... took 0ms
Style Manager: Reading dropdown styles ... took 0ms
Style Manager: Reading scrollbar styles ... took 0ms
Style Manager: Reading style templates took 3ms
**** SOUND REPORT ****
SDL version: 2.0.10
SDL_mixer version: 2.0.4
**** END SOUND REPORT ****
SoundHandler: loaded song "music/intro_00.ogg"
SoundHandler: loaded song "music/menu_00.ogg"
Initializing economy serial
?? Running Lua for world:
? Resources: 0ms
? Terrains: 4ms
? Immovables: 146ms
? Critters: 220ms
?? took: 370ms
Loading the world took 374ms
?? Running Lua for tribes:
? Ships: 7ms
? Wares: 16ms
? Immovables: 28ms
? Workers: 275ms
? Warehouses: 10ms
? Productionsites: 280ms
? Trainingsites: 9ms
? Militarysites: 13ms
? Partially finished buildings: 0ms
? Tribe infos: 12ms
?? took: 651ms
Loading the tribes took 651ms
Reading Elemental Data ... took 0ms
Reading Player Names And Tribe Data ... took 0ms
Reading Heights Data ... took 0ms
Reading Terrain Data ... took 1ms
Reading Map Objects ... took 4ms
Reading Player Start Position Data ... took 0ms
Reading Resources Data ... took 0ms
Reading Map Version Data ... took 0ms
Reading Allowed Worker Types Data ... took 0ms
Reading Allowed Building Types Data ... took 0ms
Reading Node Ownership Data ... took 0ms
Reading Exploration Data ... took 0ms
Reading Flag Data ... took 0ms
Reading Road Data ... took 0ms
Reading Building Data ... took 0ms
Reading Flagdata Data ... took 0ms
Reading Roaddata Data ... took 0ms
Reading Buildingdata Data ... took 0ms
Second and third phase loading Map Objects ... took 1ms
Reading Players View Data ... MapPlayersViewPacket::read: WARNING: Could not open "player/1/view/unseen_times_1" for reading. Assuming that the game is from an old version without player point of view. Will give player 1 knowledge of unseen nodes, edges and triangles (but not resources).took 0ms
Reading Player Message Data ... took 0ms
Reading Wincondition Data ... took 0ms
Reading Objective Data ... took 0ms
Reading Scripting Data ... took 0ms
Reading map images ... took 0ms
WidelandsMapLoader::load_map_complete() for 'Basic Control' took 8ms
Writing Elemental Data ... took 0ms
Writing Player Names And Tribe Data ... took 0ms
Writing Port Spaces Data ... took 0ms
Writing Heights Data ... took 1ms
Writing Terrain Data ... took 0ms
Writing Player Start Position Data ... took 0ms
Writing Player Message Data ... took 0ms
Writing Resources Data ... took 1ms
Writing Map Version ... took 0ms
Writing Allowed Worker Types Data ... took 0ms
Writing Allowed Building Types Data ... took 0ms
Writing Flag Data ... took 0ms
Writing Road Data ... took 0ms
Writing Building Data ... took 0ms
Writing Map Objects ... took 6ms
Writing Wincondition Data ... took 0ms
Writing Node Ownership Data ... took 0ms
Writing Exploration Data ... took 0ms
Writing Players Unseen Data ... took 0ms
Writing Scripting Data ... took 3ms
Writing Objective Data ... took 0ms
Writing map images ... took 0ms
MapSaver::save() for 'Basic Control' took 12ms
atlanteans trainingsites: We have used up 40% on 1 sites, there are 1 without
atlanteans trainingsites: Assigning 60% to each of the remaining 1 sites
barbarians trainingsites: We have used up 25% on 1 sites, there are 1 without
barbarians trainingsites: Assigning 75% to each of the remaining 1 sites
empire trainingsites: We have used up 35% on 2 sites, there are 1 without
empire trainingsites: Assigning 65% to each of the remaining 1 sites
frisians trainingsites: We have used up 40% on 1 sites, there are 1 without
frisians trainingsites: Assigning 60% to each of the remaining 1 sites
[sync] Reset
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by frankystone** [comment]
I can confirm this when using the source from launchpad, but not when using the source from github (https://github.com/widelands/widelands/tree/build-20).

As far i understand the PKGBUILD downloads the source from launchpad:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/widelands

I think changing the source from launchpad to github will be sufficient.

**Comment by frankystone** [comment]
Seems to be fixed. Feel free to reopen this bug again
