### ISSUE TITLE
crash on local multiplayer

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3577]
When entering a local multiplayer the screen stays empty (no players & map) for the clients, and if the host changes some settings the client crashes.

Version:     r24275[6118f81@master]

@Notabilis didn't you change something in the network code lately?

Console output:
```
Resolved network name 'DESKTOP-5VB0FAD:7396' to 2003:df:7716:4d00::f4a
[NetClient]: Trying to connect to 2003:df:7716:4d00::f4a:7396 ... [BufferedConnection] Trying to connect to 2003:df:7716:4d00::f4a:7396 ... success.
success.
[BufferedConnection] Starting networking thread
libc++abi.dylib: terminating with uncaught exception of type WException: [../src/network/bufferedconnection.cc:297] [BufferedConnection] Error when receiving data from host (error 54: Connection reset by peer)
Abort trap: 6
```

**Comment by Notabilis** [comment]
Unfortunately I can't reproduce the bug, for me it works fine. Are you doing your local game with only a single computer / on localhost or over the LAN?

I pushed branch #3579 that might fix the problem, can you please test it?

**Comment by stonerl** [comment]
We were playing over LAN. The Host was a Windows 10 machine and the client a Mac. I'm going to test it later this week since I need access to the windows computer.
