### ISSUE TITLE
improve installing and loading of the game

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3581]
**Is your feature request related to a problem? Please describe.**
On my old machine i still have a mechanical HDD during install and loading the tribes this consumes a lot of time to load or save the thousands of tribes graphic files. 

**Describe the solution you'd like**
The install and loading time should be improved by just saving compressed folders to the HDD and decompress them at loadtime. should be combined with the feature to only load the tribes needed.

**Comment by gunchleoc** [comment]
We already have an open issue for the tribes: https://github.com/widelands/widelands/issues/3346

Loading the tribes will also become faster when we finish creating spritemaps.

Compression will be more work and I don't expect it to happen for Build 21.

**Comment by hessenfarmer** [comment]
Ok I will reevaluate after all spritesheets finished
