### ISSUE TITLE
CIs instable

### ISSUE THREAD

**Issue by jmoerschbach** [widelands/widelands#3585]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
CIs (especially Travis) oftentimes fail where they should not. Usually it is only one or two of the many build configurations that fail while all the others succeed.

**To Reproduce**
1. create a pull request to trigger CI

**Expected behavior**
If no real problem exists (compile error, formatting problem, failing test due to codechange), all build configurations should succeed.

**Version:**
Travis CI environment

**Additional context**
See for example

- https://travis-ci.org/widelands/widelands/jobs/614169005?utm_medium=notification&utm_source=github_status

- https://travis-ci.org/widelands/widelands/jobs/614278136?utm_medium=notification&utm_source=github_status

It is always saying
Caught exception (of type '10WException') in outermost handler!

**The exception said: [/home/travis/build/widelands/widelands/src/wlapplication.cc:371] Failed to initialize SDL, no valid video driver: No available video device**

This should not happen. Please file a bug report on version r52[9c09168@HEAD](Release).

and remember to specify your operating system.

**Comment by stonerl** [comment]
I'm not sure whether we can change any of this or not. Most of the time (90%) it is the xfvb.service that is, for some reason, not running anymore and therefor letting the test fail.

**Comment by jmoerschbach** [comment]
is there really nothing we can do? Almost every time a CI build is triggered, at least one of the build configuration fails. quite annoying...

**Comment by gunchleoc** [comment]
Since we can't fix the instabilities in the CI environment, I have changed the code to log and exit(0) rather than throw an exception.

**Comment by stonerl** [comment]
Well, it kind of worked, I guess. But I assume we can't do anything when xvfb dies during the test suite run?

[https://travis-ci.org/widelands/widelands/jobs/629354906](https://travis-ci.org/widelands/widelands/jobs/629354906)

**Comment by gunchleoc** [comment]
We could use a different return code and check for that return code when running the test suite to make it ignore the problem.
