### ISSUE TITLE
Artifacts: add single player text

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3588]
Currently, artifacts messages talk about team achievements: 

>Your team found a new artifact.

Even when no teams are selected. This needs to be adapted for single users.

**Comment by Joesalmon1985** [comment]
Okay, I'm interested in trying to fix this.

**Comment by stonerl** [comment]
@Joesalmon1985 thanks allot. The file in question is this one:

https://github.com/widelands/widelands/blob/master/data/scripting/win_conditions/artifacts.lua
