### ISSUE TITLE
Multiplayer load map when all players are ready.

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3599]
**Is your feature request related to a problem? Please describe.**
This request may tie in to #3597. Currently, when a relevant game data has been loaded the screen stay black and the game is paused until all players have entered the game. This can sometimes lead to confusion on the players side that are waiting for the game to start.

**Describe the solution you'd like**
Instead of going directly to the game and pause with a black screen, have the loading screen stay on top and display a text like __Waiting for other players...__

@Noordfrees since you implemented #3597 do you think this is feasible, without too much hassle?

**Comment by Noordfrees** [comment]
I assume that the loading screen for MP games is created by gamehost.cc or gameclient.cc respectively (needs verifying). I don´t know which function(s) is/are running while waiting for players, but it should be possible either to
- implement into these functions that unsetting the ProgressWindow is delayed until everything´s ready, or
- just open a new ProgressWIndow directly after the loading screen closes.

**Comment by Noordfrees** [comment]
Related:
https://www.widelands.org/forum/topic/5105
We should keep showing the loading screen while the players' starting conditions are being set up (especially for Discovery / New World)
