### ISSUE TITLE
Territorial Time: End game ahead of the 4 hour mark when in Peaceful Mode

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3600]
**Is your feature request related to a problem? Please describe.**
Territorial Time (TT) ends after 4 hours when none of the parties has been able to conquer more than 50% of the land for at least 20 minutes. Since we allow Peaceful Mode for TT, it may happen that players have conquered all available land, but since they are not allowed to attack, they have to wait for the 4hours to end.

**Describe the solution you'd like**
When one party has more land than other parties conquer so that they weill never overturn the leading one, end the game ahead of time.

Eg. party A has 42% party B has 38 and C party 19%. The game should be ended because neither B nor C can conquer enough land to overtake party A.

**Implementation steps**
- [ ] use the existing check for land, to determine whether a party has more land than is left for others to conquer and end the game

**Comment by gunchleoc** [comment]
We should implement this for the next milestone. If we can't make it, https://github.com/widelands/widelands/commit/ee67729691daebd7c39924e83454ecc9194391a7 will have to be reverted.
