### ISSUE TITLE
Hunting down old issues which are fixed already

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3607]
This is to track any old issues that can be closed as they are not longer valid 
please add them in the format `- [ ] #0000 @yourname`:
if you already closed it, because you are sure mark it in this list. 
if a commit or Pullrequest can be iddentified which solved the problem it should be added as comment to the issue as "fixed by #0000" or "fixed by commit a123244"
if possible/known set the milestone in which the bug has been fixed.

- [x] #1514 @hessenfarmer  
- [x] #1032 @hessenfarmer 
- [x] #1674 @stonerl
- [ ] #3351 @stonerl 
- [x] #1703 @stonerl
- [x] #3095 @stonerl
- [x] #508 @hessenfarmer
- [x] #310 @hessenfarmer
- [x] #1073 @hessenfarmer
- [x] #2016 @hessenfarmer
- [x] #3161 @hessenfarmer
- [x] #2939 @hessenfarmer
- [x] #3051 @hessenfarmer
- [x]  #1651 @hessenfarmer
- [ ]  #1657 @hessenfarmer
- [x]  #1310 @hessenfarmer

**Comment by hessenfarmer** [comment]
[ ] #1674 @stonerl

**Comment by stonerl** [comment]
Just add them to the first Post.

**Comment by stonerl** [comment]
I also pinned this issue. So, it will appear on top of the issue list.

**Comment by hessenfarmer** [comment]
as this has not been used any further I'll close this
