### ISSUE TITLE
Help & tips enhancements

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3612]
This is a Meta-Issue to handle improvements in the help. Please add them to the list. If an issue already exists, add it here.

- [x] add helptext/tip for SHIFT/CTRL buttons regarding gamespeed
- [x] add helptext/tip SHIFT/CTRL buttons regarding map scrolling
- [x] add helptext/tip for map scrolling

**Comment by pospec4444** [comment]
I'm not a writer, what about this?
20753d33b1cb9d945624962ad7b732064a9d4d24

**Comment by gunchleoc** [comment]
_"Speed up or slow down game time with %1%. -> _"Speed up or slow down game time **by** %1%.

Rest looks good :)

**Comment by pospec4444** [comment]
OK, so it will be formatted as:

> Speed up or slow down game time **by** `Page Up/Page Down`.

Please, confirm.

**Comment by gunchleoc** [comment]
Ah, my bad. Leave it as it is!
