### ISSUE TITLE
improve frisian immovable helptexts

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3617]
A lot of immovables, especially tribes immovables need helptexts. Some older helptexts need to be improved. especially we should add a comment to flowering immovables that honey can be collected there. this should ideally implemented as specific to frisians

**Comment by Abuali1049** [comment]
! [IMG_٢٠١٩١٢٢٧_١٥٢٤٤٠] (https://user-images.githubusercontent.com/59299417/71564716-667b6a00-2ab6-11ea-8f59-14807c44e1a0.jpg)

**Comment by hessenfarmer** [comment]
frisian part is fixed by #4361 
rest is duplicate to #3448
switched back to v1.0 to show correct point of embodiment
changed the title as well

**Comment by hessenfarmer** [comment]
closed as already implemented
