### ISSUE TITLE
Update Tutorial 1 for new game speed UI

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3623]
The game speed behaviour changed with https://github.com/widelands/widelands/pull/3611

Double-check whether the tutorial needs changing and implement the changes.

**Comment by pospec4444** [comment]
[Here](https://github.com/widelands/widelands/blob/eb7f6cdd58d941de7564ce44be4d3c5d437c29a9/data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua#L226) is the text in question.

Screenshot of the same:
![Screenshot from 2020-03-10 17-42-08](https://user-images.githubusercontent.com/2467395/76336774-c4b69b80-62f6-11ea-84ce-598b47a03045.png)

What about adding another sentence? For example: `Change is rapid with pressed Ctrl and smooth with pressed Shift.`

Btw, shortcuts `CTRL + Page Up` / `SHIFT + Page Up` are not described in in-game help.

**Comment by gunchleoc** [comment]
+1 for adding it to the in-game help "Controls" section too.

**Comment by pospec4444** [comment]
> +1 for adding it to the in-game help "Controls" section too.

Hmm, I'm a bit confused where to track this change. Here #3612?

**Comment by gunchleoc** [comment]
Yes, that's correct. You can work on both in 1 branch though if you want.

**Comment by Noordfrees** [comment]
I guess this is fixed by the mentioned PR
