### ISSUE TITLE
Legacy lookup table is called during the game

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3630]
TribesLegacyLookupTable is called during running a game. This class is meant for savegame compatibility only, so https://github.com/widelands/widelands/issues/3529 that was fixed with https://github.com/widelands/widelands/pull/3549/ needs to be fixed in a different manner.

**Comment by hessenfarmer** [comment]
@gunchleoc is this still valid after the unification of world and tribes?

**Comment by hessenfarmer** [comment]
@Noordfrees I believe this issue is nop longer valid. as we further went down this street anf it is not revertable anymore
