### ISSUE TITLE
Multiplayer savegame distribution very slow

### ISSUE THREAD

**Issue by hbeni** [widelands/widelands#3633]
**Describe the bug**
The distribution of saved multiplayer games is very slow. It takes minutes to transfer some 100k files between two machines in a 100Mb/s wired LAN.

**To Reproduce**
- Play in multiplayer
- save the game
- reload

**Expected behavior**
I expect the transmission to complete in few seconds, depending on the connection speed.

**Version:**
 - OS: Debian testing
 - Widelands Version: build-20 (Release)

**Comment by mahendra9911** [comment]
hu

**Comment by gunchleoc** [comment]
@Notabilis Any idea where the bottleneck is?

**Comment by Notabilis** [comment]
Yes, it is in our code. My last branch was a preparation for fixing this, when the branch "Refactor gamehost" is merged I will prepare a branch that fixes this bug.

**Comment by gunchleoc** [comment]
refactor-gamehost has been merged https://github.com/widelands/widelands/commit/3a428bd93712294d6f09634541a01d053e2b7da9

**Comment by Notabilis** [comment]
Thanks for the notification, I pushed a branch proposing a fix for this.

**Comment by hessenfarmer** [comment]
fixed by #3649
