### ISSUE TITLE
Bug under Ubuntu 19.04 (ppa) with Blackrootfarms

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#3634]
When I build a blackrootfarm (Atlanteans), it keeps staying at 88% finished until you cut all ways to the construction site and rebuild it. The last item that's left to complete the blackroot farm is a plank. Please fix this bug as soon as possible, because it is very unpleasant to play with this bug.

**Comment by klaus-halfmann** [comment]
Hello  @PinPhreek thanks for you bugreport. Unfortunlally this is a know Issue (at least in the current development version). In complex econonmies sometimes planned wares do not arrive. A simple workaround is to decrease the ware for a short time and then increase it, this normally should fix the issue.

To aid us in finding the bug please supply us with as much information as you can gather:
* Version of Widelands you are playing
* Savegame at the time when it happend, or even better: some minutes before
* Screeshot of the building in question.

If you can spend even more time, I can show  you hot to get or build a debugversion.
Output form that version can help us even more to find this.

@gunchleoc I dont have a duplicate for this, but Im sure we had this reported already.

**Comment by PinPhreek** [comment]
Hello @klaus-halfmann,
I'm using Widelands **_Version build-20 (Release)_**, which is the newest one I could find without compiling from github. Unfortunately I have overwritten my savegame file, so you would get a version of my game just an hour after the bug occured. I played the campain "From Nemisis to Genisis".
![image](https://user-images.githubusercontent.com/34819140/71645400-25fb3680-2cd8-11ea-9154-74283c867055.png)
I hope I could help you.

**Comment by frankystone** [comment]
This is indeed an annoying bug. Unfortunately it is unclear when, or how, this bug happens.

See #1085

**Comment by gunchleoc** [comment]
Thanks for reporting! I'll close this now, because it's a duplicate.
