### ISSUE TITLE
Make "Out of Resources" messages less noisy

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3639]
**Is your feature request related to a problem? Please describe.**

"Out of resources" messages can still be too noisy, especially for the lumberjacks. C.f. https://www.widelands.org/forum/topic/4704/

**Describe the solution you'd like**
I have 2 ideas:

1. Add button to adjust general threshold for each building type in the Building Statistics window
2. Mute/unmute individual buildings

**Comment by stonerl** [comment]
I'd say we have this option on a per building basis. Maybe with an option in the settings to enable or disable these message by default, so the user can decide whether s/he wants to disable or enable the messages for buildings during the game.

**Comment by stonerl** [comment]
I would close this one favoring #2036

**Comment by stonerl** [comment]
Just realized the other one might be targeting a different problem.

**Comment by simply-peachy** [comment]
> I'd say we have this option on a per building basis.

This could also be applied to attacks detected by military buildings, which are sometimes noisy but the [player doesn't want to hear about](https://www.widelands.org/forum/post/32102/).
