### ISSUE TITLE
Won dialog messed up

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3640]
Don't know if this is already in build20, but i think the won dialog is somehow messed up, at least with german translation:

1. The String 'Spielerinformation' is on the right side of the table. I guess it should be on top of the table?
2. In this game the one who won is shown in the last row of the table, although he was player 1. I think the table should be sorted either by playernumber, or the player who won should be in the first row?

This is Widelands Version r5663[3a428bd@master] (Release)

![won_dialog](https://user-images.githubusercontent.com/6730556/71922449-36555a80-318b-11ea-84a5-6a1ef072f24f.png)

**Comment by hessenfarmer** [comment]
Hi,
as far as I know the player info (original text) contains additional info for some win conditions. so perhaps we should rename it to additional info instead. so it is not the headline of the table but an optional column and we could think of formatting it differently. 
furthermore the table is sorted by the time the final message is compiled so if scripting checks first for the winner and afterwards for the loser it is displayed like above as far as I remember. Needs to be investigated if it can be sorted by result first and then by time.

**Comment by gunchleoc** [comment]
I agree that this can be improved. The right-hand side should optimally be filled by detailed information from the win condition, and it concerns the currently selected player.
