### ISSUE TITLE
Autosave leads to flickering

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3641]
**Describe the bug**
When the game makes an autosave, the screen shows a wooden background with the 'Tips'-banner for a short time (fewer than a second, but long enough to see the banner).

'Tips'-banner = the small white banner which is seen when loading/starting a game, containing some tips.

**To Reproduce**
Start a new game and wait for an autosave

**Expected behavior**
Don't know if this was intended, but the flickering is a bit confusing because the intermediate screen is shown just for a very short time.

**Version:**
This is Widelands Version r5663[3a428bd@master] (Release)
Arch linux

**Comment by stonerl** [comment]
It seems this issue and #3624 are related.

**Comment by Noordfrees** [comment]
The saveloading progress window is now shown always when saving as a side effect of d8a789f . But on my slow machine an autosave often takes about 5-10 seconds, so I´m in favour of keeping it.

**Comment by frankystone** [comment]
Do i understand this correctly: When an autosave is made, the intermediate screen is shown as long the autosave last?

If this is true: I noticed the string "Saving the Game" (or similar) after the intermediate screen appears at the bottom left of the screen (when the game is shown again and runs further). Is it possible to have this string in the intermediate screen inside the tips banner (or just as a string without the tips banner) instead of showing it after the autosave was made? 
At least the string shouldn't be shown anymore.

**Comment by Noordfrees** [comment]
Removing the "Saving the game" string from the corner is easy. Replacing the tips with this string might be tricky, I´ll see what I can do…

**Comment by Noordfrees** [comment]
Ouch. What you see during autosaving is actually *always the same* ProgressWindow which is created once when starting the game and sticks around until you return to the main menu. Modifying it is not a very safe thing to do…
Depending on the game type, the ProgressWindow can be created from a dozen different places. These code paths could use some general restructuring, simplifying and redundance-cleanup, but I don´t really have time for this ATM
