### ISSUE TITLE
update.sh creation broken

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3643]
compile.sh does not create an update script if the working tree is not clean. To check this, it runs `git status` and checks for `"${STATUS##*nothing to commit, working tree clean*}"`.

On my machine (ubuntu 19.10 with nds and de_DE locales), git status returns "nichts zu committen, Arbeitsverzeichnis unverändert".
Therefore no update script is created…

**Comment by gunchleoc** [comment]
`git status -s` will come up empty if there are no changes, we should use that instead.
