### ISSUE TITLE
Extend keyboard support for dropdowns

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3656]
Dropdowns should get the following additional keyboard support:
- [ ] When pressing Up while the first element in the list is highlighted, go to the last element
- [ ] When pressing Down while the last element in the list is highlighted, go to the first element
- [ ] Home and End should jump to the first/last element in the list
- [ ] PageUp/PageDown should go up/down by `max_list_items_` entries
- [ ] Perhaps in dropdowns with <10 elements, allow selecting the individual elements with the keys 1-9
- [ ] Perhaps mousewheel movement support when pointing on a closed dropdown

**Comment by gunchleoc** [comment]
> When pressing Up while the first element in the list is highlighted, go to the last element
> When pressing Down while the last element in the list is highlighted, go to the first element

I don't find the round-robin intuitive - hit the key once too many accidentally and you're somewhere you don't expect to be. Home and End will serve for that just fine :)

I like the other suggestions.
