### ISSUE TITLE
compiling a downloaded zip won't work

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3657]
**Describe the bug**
Compilation fails if one tries to compile a downloaded zipped branch without having a git repo.

**To Reproduce**
1. Choose a branch. I used https://github.com/Noordfrees/widelands/tree/3652-editor-loader-ui
2. Click on 'Clone or download -> Download zip'
3. Extract the zip file to a folder without git versioning
4. Run ./compile.sh  -r -w -t

The following error occurs:

> -- Adding linker flags for GLVND.`
> fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
> Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
> bzr: ERROR: Kein Zweig: »/home/kaputtnik/widelands-3652-editor-loader-ui/«.
> Traceback (most recent call last):
>   File "/home/kaputtnik/widelands-3652-editor-loader-ui/utils/detect_revision.py", line 118, in <module>
>     print(detect_revision())
>   File "/home/kaputtnik/widelands-3652-editor-loader-ui/utils/detect_revision.py", line 110, in detect_revision
>     rv = func()
>   File "/home/kaputtnik/widelands-3652-editor-loader-ui/utils/detect_revision.py", line 96, in detect_bzr_revision
>     revno = run_bzr('revno')
>   File "/home/kaputtnik/widelands-3652-editor-loader-ui/utils/detect_revision.py", line 95, in run_bzr
>     return _communicate_utf8(['bzr', subcmd], cwd=base_path).strip()
>   File "/home/kaputtnik/widelands-3652-editor-loader-ui/utils/detect_revision.py", line 30, in _communicate_utf8
>     output = subprocess.check_output(cmd, **kwargs)
>   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.8/subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['bzr', 'revno']' returned non-zero exit status 3.

As a result, all executables have the prefix: WL_VERSION, e.g.:

WL_VERSIONtest_scripting
WL_VERSIONtest_ai
WL_VERSIONtest_economy

**Expected behavior**
compilation should work.

**Version:**
 - OS: archlinux
 - Widelands Version: arbitrary

Having a widelands version without a revision number is may not good, but if it is possible to download a zipped version of a branch it should be possible to compile it, even if some one don't have git installed.

Maybe we can have a version file which is part of the project and get updated on each compilation. So detect_revision() can just read this file?

**Comment by hessenfarmer** [comment]
Hm,
this looks like having 2 problems the first line is about a git error, but the rest of the traceback is about a failing attempzt to identify a bazaar version. Normally everything should fail safely and provide fianlly the REVDETECT-BROKEN Version. 
BTW the order is search for a WL_VERSION file, try to find git version, try BZR version, deliver revdetect.
I have no glue however why this is failing this way.

**Comment by hessenfarmer** [comment]
I just tried this on my windows machine with a downloaded zip. and it reverted to REVDETECT-BROKEN string. only thing is I haven't installed bazaar anymore.
