### ISSUE TITLE
Unable to load save game due to economy error

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#3658]
Widelands version r24376[98e57ac@master] (Release) on Ubuntu 19.10. Trying to load a saved game results in an error: Fatal exception: economies: player 3: error reading economy data for ship Bounty: economy: Representative flag/ship has economy serial 2767, but the data packet has 1955

The save was using the same version of the game, and appeared to save OK.

Stdout, stderr, map and save attached.
[stdout.txt](https://github.com/widelands/widelands/files/4114516/stdout.txt)
[stderr.txt](https://github.com/widelands/widelands/files/4114517/stderr.txt)
[Save.zip](https://github.com/widelands/widelands/files/4114533/Save.zip)
[Kralle1.zip](https://github.com/widelands/widelands/files/4114531/Kralle1.zip)

**Comment by simply-peachy** [comment]
Looks like the last autosave is also broken, attaching in case it helps.
[autosave.zip](https://github.com/widelands/widelands/files/4114547/autosave.zip)

**Comment by simply-peachy** [comment]
[replays.zip](https://github.com/widelands/widelands/files/4114590/replays.zip)

**Comment by Noordfrees** [comment]
Thanks for reporting, will investigate.
Did you also start this game with this version of Widelands or is this an older game which was saved and reloaded multiple times?

**Comment by simply-peachy** [comment]
Game was started and played with the same version.

**Comment by Noordfrees** [comment]
Found it :)
Player 3 has two ships at the same location, "Siena" and "Bounty", both if them waiting expedition ships. The saveloading code assumes that this doesn´t happen.
I´ll write some code so ships can be disambiguated in this case in the future, but this savegame is unfortunately beyond recovery :(

**Comment by simply-peachy** [comment]
That was prompt! I must have created an expedition in an alternate reality which would confuse any game. I keep frequent autosaves so I only lost a little playtime and was victorious anyway :-D

Thanks!
