### ISSUE TITLE
Flickering census strings on invisible map movement

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3660]
**To Reproduce**
1. Start a game
2. Ensure the map is at 1x zoom level. Enable census and stats.
3. Press Ctrl-0 to reset zoom

**Expected behavior**
Nothing should happen, because the zoom is already at 1x

**Actual behavior**
The census and stats strings disappear, and reappear after ~1s, as if there was a map movement

**Version:**
 - Ubuntu 19.10
 - current master, Release

**Comment by stonerl** [comment]
I think I saw something similar with the soldiers' overlay.

**Comment by gunchleoc** [comment]
Confirmed.

We switch of the strings during zooming because the rerendering is very expensive, so it's a performance hack. We could look into checking whether the zoom level has changed at all before switching them off.
