### ISSUE TITLE
Game crashes on constructionsite completion due to wrong inputqueue request

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3695]
**Describe the bug**
The attached savegame reproducably crashes as soon as the tavern csite at 112×246 is completed.

**To Reproduce**
1. Load the savegame
2. Give the tavern (screen center, next to the outpost) highest priority for the remaining wares
3. Wait until it completes

**Version:**
 - OS: Ubuntu 19.10
 - r24429[873d4d2@master]

**Additional context**
Error message:
~~~~
Fatal exception: [../src/logic/map_objects/tribes/productionsite.cc:416] frisians_tavern (8911) has no InputQueue for 2
FATAL ERROR - game crashed. Attempting emergency save.
~~~~

**Comment by Noordfrees** [comment]
[LongLongWay.wgf.zip](https://github.com/widelands/widelands/files/4214938/LongLongWay.wgf.zip)

**Comment by hessenfarmer** [comment]
My fault. I need to provide savegame compatibility code. 
Reason is I changed the order of the wares in the tavern to make it prefer fruit.

**Comment by hessenfarmer** [comment]
this savegame is weird as the taverns in construction as well as the drinking halls expect honey instead of fruit. With which version this was created?

**Comment by Noordfrees** [comment]
8217940 . The savegame was created at So 09 Feb 2020 13:14:53 CET (according to the filesystem) and if I remember correctly I saved it only this once (not reloaded and resaved since).

**Comment by hessenfarmer** [comment]
found it and coreected it now it works. problem is that if we change the order of includes in tribes/init.lua the ware index is different and we can't generic compat code for this. 
I need to fix the order in my amazon branch as well as I wanted to have it nicely and sorted everything alphabetically.

**Comment by gunchleoc** [comment]
Saving DescriptionIndex instead of descr().name() is unstable, so the fix is only temporary. I'll have a real fix soon.
