### ISSUE TITLE
Accessibility ideas for eye tracking

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3706]
From the forum: https://www.widelands.org/forum/topic/4642/

- Add buttons for things that need a right-click
- Add navigator buttons for scrolling the map (where - bottom of minimap?)
- Hover actions are difficult - button to toggle all tooltips on?

**Comment by Noordfrees** [comment]
1 – a little button with an X in the corner of every window's titlebar would be nice
2 – let's have an option to enable scrolling the map when the cursor is near the edges
3 – I don't understand, the tooltips are shown the moment the mouse points on an item, and the TT doesn't go away when you move the mouse only a bit

**Comment by gunchleoc** [comment]
I like your suggestions :)

For 3, maybe it's difficult to keep the eyes still long enough? I don't know how the apparatus works though, so I'm just guessing.

**Comment by Niektory** [comment]
I suspect the problem with tooltips is that you need to move your eyes to read them (as they don't show up exactly at the cursor's location, and some are quite large), but when you do, the mouse cursor moves as well causing them to disappear.
