### ISSUE TITLE
Allow player to manage expedition wares

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3708]
Allow player to

1. Add wares to expeditions and (duplicate of https://github.com/widelands/widelands/pull/3692)
2. To set their ware priority

Forum discussion: https://www.widelands.org/forum/topic/4686/

**Comment by Noordfrees** [comment]
What exactly is the difference between 1) and the feature of #3692 ?
Priority buttons would be nice, though I don't see the point of decreasing the default wares (just as in constructionsites by the way…)

**Comment by gunchleoc** [comment]
Oh, I see you already have selecting the wares in there, so it's redundant in this issue.

**Comment by Niektory** [comment]
> Priority buttons would be nice, though I don't see the point of decreasing the default wares (just as in constructionsites by the way…)

Well, it allows you to temporarily send some wares away if you realize some other place needs them more urgently.

**Comment by simply-peachy** [comment]
> Well, it allows you to temporarily send some wares away if you realize some other place needs them more urgently.

It also provides consistency.
