### ISSUE TITLE
Lua coroutine errors don't show up in regression tests output

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3716]
When our testsuite fails due to a lua coroutine error, this error does not cause widelands to crash and therefore does not show up in the log output. 
On travis this leads to the build stalling without any log output that gives a clue to the failure type.

Suggestions:
- improve regression_test.py to identify coroutine errors in the output
- throw a wexception when a coroutine error is found

**Comment by gunchleoc** [comment]
Coroutine errors ave special handling at the moment that they send a message and pause the game. I guess this is useful wile creating scenarios. How about adding a command line switch for the testsuite to skip this special code?
