### ISSUE TITLE
Assertion failed after loading build 20 savegame in master

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3719]
**To Reproduce**
1. Host a multiplayer game and load [this build 20 save](https://github.com/widelands/widelands/files/4250184/assertion_failed.wgf.zip)
2. Wait a few seconds
3. Widelands crashes with assertion failed:
```
widelands: ../src/logic/player.cc:924: Widelands::Economy* Widelands::Player::create_economy(Widelands::WareWorker): Assertion `economies_.count(serial) == 0' failed.
```

**Version:**
 - OS: Manjaro
 - Widelands Version: r24441[cabdba2@master]

**Additional context**
- [Full terminal output and backtrace](https://github.com/widelands/widelands/files/4250155/assert.log)

**Comment by Noordfrees** [comment]
Confirmed. The economy savegame code output (a82ffd1) says:
~~~~
Savegame compatibility: Splitting economy 24 into ware economy 24 and worker economy 4294967290
Savegame compatibility: Splitting economy 767 into ware economy 767 and worker economy 4294967289
Savegame compatibility: Splitting economy 306 into ware economy 306 and worker economy 4294967288
Savegame compatibility: Splitting economy 312 into ware economy 312 and worker economy 4294967287
Savegame compatibility: Splitting economy 233 into ware economy 233 and worker economy 4294967286
Savegame compatibility: Splitting economy 1449 into ware economy 1449 and worker economy 4294967285
Savegame compatibility: Splitting economy 472 into ware economy 472 and worker economy 4294967284
Savegame compatibility: Splitting economy 697 into ware economy 697 and worker economy 4294967283
Savegame compatibility: Splitting economy 1515 into ware economy 1515 and worker economy 4294967282
Savegame compatibility: Splitting economy 1491 into ware economy 1491 and worker economy 4294967281
Savegame compatibility: Splitting economy 1384 into ware economy 1384 and worker economy 4294967280
Savegame compatibility: Splitting economy 1344 into ware economy 1344 and worker economy 4294967279
Savegame compatibility: Splitting economy 1429 into ware economy 1429 and worker economy 4294967278
Savegame compatibility: Splitting economy 1464 into ware economy 1464 and worker economy 4294967277
Reset economy serial to 4294967291
[…]
Reset economy serial from 4294967292 to 4294967291
~~~~

For some reason the running serial is being reset to a very very high value, causing an overflow and hence the assert when a few new flags and buildings are placed by an AI. The expected value would be 1516.
I have no idea why this should happen. I only know that I never claimed that this compatibility code would work reliably…

**Comment by Niektory** [comment]
I tried to do some debugging.
[This code](https://github.com/widelands/widelands/blob/master/src/map_io/map_flag_packet.cc#L130-L140) seems to expect that the set `all_economy_serials` contains all the "high" serials created, but it seems not all serials are included in it, and it has some gaps. If encounters the first gap and assumes the serial below this gap is a "low" serial, but some "high" serials still remain. The method that creates the "high" serials is called in both [map_flag_packet.cc](https://github.com/widelands/widelands/blob/master/src/map_io/map_flag_packet.cc#L69) and [ship.cc](https://github.com/widelands/widelands/blob/master/src/logic/map_objects/tribes/ship.cc#L1368), but only the former adds them to `all_economy_serials`, and the ones created only in ship.cc are not included, hence the gaps.

**Comment by Noordfrees** [comment]
Good find :)
But perhaps it would be better to rewrite the compat code instead so that old-style eco N is split into ware eco N and worker eco (kInvalidSerial / 2 + N) (assuming that no savegame has an economy with serial >2mrd). Then we wouldn't need to bother  about keeping this serials table and resetting the serial to an appropriate value. Not sure how compatible this solution would be with games started with b20 and already continued&resaved with master though.

**Comment by gunchleoc** [comment]
Attached PR works fine with Build20 savegames, but not if they have been resaved in the meantime. Do we care? If the answer is no, the PR can go in.

* [Build 20.wgf.zip works](https://github.com/widelands/widelands/files/4257487/Build.20.wgf.zip)
* [Build 20 resaved.wgf.zip crashes with assert failure](https://github.com/widelands/widelands/files/4257488/Build.20.resaved.wgf.zip)

**Comment by Noordfrees** [comment]
The current compatibility hack is extremely unstable for b20 saves after resaving the a couple of times. The most important thing IMHO is that b20 savegames can be continued with b21 without problems. Since we never guarantee development versions to be stable I'm in favour of discarding compatibility just for b20 saves resaved within the last three months, in favour of providing better long-term compatibility for original b20 saves.

**Comment by gunchleoc** [comment]
I agree with your reasoning, so let's have it :)
