### ISSUE TITLE
Make autosave message better visible

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3737]
During game autosaves no ProgressWindow is being displayed any more. The only indicator why the game seems to be hanging is a small, sometimes poorly visible string in the lower left corner which may be obscured by open windows.

Suggestions:
- Re-enable the progress window for autosaves like for manual saves
- Draw the progress string on top of windows etc, make it larger, and make the background semi-opaque; perhaps even move it from the corner to the screen center

**Comment by gunchleoc** [comment]
> make the background semi-opaque

Already implemented, just untick the box:

![transparent](https://user-images.githubusercontent.com/4095570/76197011-40bfbf00-61e3-11ea-82d7-2f06e064b245.png)

Shall we make it the default and remove the option?

**Comment by Noordfrees** [comment]
Doesn't this option apply only to the chat window? I always have the stock window open in the lower left corner and it hides the autosave message regardless whether this option is on or off…

**Comment by gunchleoc** [comment]
The save handler is technically sending a chat message ;)

**Comment by Noordfrees** [comment]
Then this is a bug? This 'chat message' is always hidden behind the stock window. It should be drawn on top instead.

**Comment by gunchleoc** [comment]
+1 for drawing it on top.
