### ISSUE TITLE
Compiler warnings in read MapViewPacket

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3738]
Currently there are a lot of compiler warnings visible on appvehor. (line 2450 ff). Regarding some variables incompatibilities

**Comment by jmoerschbach** [comment]
Hi,

I think this was introduced via 66434890add4717bc05b040f7a990054ca794b36 by @gunchleoc 
For example changing https://github.com/widelands/widelands/blob/510e0dd1b40214dffbbd9d89ea57625d95e073d4/src/map_io/map_players_view_packet.cc#L166

back to 
```C++
"Found %lu trailing bytes in \"%s\"", 
```
fixes the warning on windows.

Maybe she can explain the intention behind this change? I suppose there was a warning on linux? But as far as I can see, on non-windows-machines the macro is expanded to "lu" so why does it need to be more sophisticated on windows (whatever PRIu64/PRIu32 exactly is)?

**Comment by jmoerschbach** [comment]
Ok, I think I understand the rationale behind this. Depending on _WIN32 / _WIN64 the macro either expands to lu or llu, respectively.
But since the parameter in question is always cast to long unsigned int this will always be a warning on _WIN64...

**Comment by gunchleoc** [comment]
The problem is that `size_t` is  a different data type on different operating systems, so we have to use the macro `PRIuS` instead. Maybe I used it for the wrong variable.
