### ISSUE TITLE
Bugs in Multiplayer setup UI

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3739]
1. if you load a match, it shows "no team" everywhere even when there are teams. (by the way it's confusing with the colors. i recommend to replace team colors by team numbers again)
2. and it also reveals the tribes of random tribe. which should be still shown as random.

**To Reproduce**
Load a multiplayer savegame with teams in it

Reported on the forum: https://www.widelands.org/forum/topic/4755/?page=2#post-31883

**Comment by Niektory** [comment]
This is where the teams are (not) set in the UI:
https://github.com/widelands/widelands/blob/82ab4495cbed04fb47740351d8528554a4b142a2/src/ui_fsmenu/launch_mpg.cc#L526-L528
Apparently the information used on that screen is saved in `MapPlayerNamesAndTribesPacket`, but it doesn't include team information, which is saved in `GamePlayerInfoPacket` and is not easily accessible.
