### ISSUE TITLE
find_unused_includes.py broken

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3747]
Travis reports a number of superfluous includes in #3662 . Among others it complains that `editor/scripting/operators.h` includes `editor/scripting/constexpr.h`, which is the only include there. However this include is required for two reasons:
- The classes defined in `operators.h` inherit from `Assignable`, which is included from `scripting.h` via `constexpr.h`
- `constexpr.h` defines some `static const VariableType` constants which are used in `operators.h`

**Comment by gunchleoc** [comment]
https://travis-ci.org/widelands/widelands/jobs/659777309

At least now I know that the Travis configuration is working and allowing the job to fail as we improve the script :)

**Comment by gunchleoc** [comment]
>     * The classes defined in `operators.h` inherit from `Assignable`, which is included from `scripting.h` via `constexpr.h`

It is correct not to detect those, because one should include `scripting.h` instead if nothing else was needed from `constexpr.h`
 
>     * `constexpr.h` defines some `static const VariableType` constants which are used in `operators.h`

Fixed in the linked PR
