### ISSUE TITLE
'<' and '>' in player name crash the editor

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3760]
**Describe the bug**
'<' and '>' characters in player names result in a crash in the editor player menu.

**To Reproduce**
1. Open the editor
2. Press P
3. Enter one of the characters in the field for a player's name

**Expected behavior**
Either we should allow all characters since richtext doesn't make sense there; or chars reserved for richtext should be silently ignored, as happens e.g. when entering 'ä'

**Version:**
 - Ubuntu MATE 19.10
 - a9d183e

**Additional context**
Error message
~~~~
Caught exception (of type 'N2RT15SyntaxErrorImplE') in outermost handler!
The exception said: Syntax error at 1:64: expected an allowed tag, got '</font'. String continues with: '<</font></p></rt>'

This should not happen. Please file a bug report on version r24470[a9d183e@master](Release).
and remember to specify your operating system.
~~~~

**Comment by gunchleoc** [comment]
The only nasty characters that we need to disallow are <>, and we have a function to replace them with `&lt;` and `&gt;`. ä is no problem, because we're using Unicode.

**Comment by Noordfrees** [comment]
> ä is no problem, because we're using Unicode.

Then why are keystrokes of 'ä' and similar chars silently ignored? I can't enter third-level chars like '»' (AltGr+y) either. Another bug?

**Comment by gunchleoc** [comment]
> > ä is no problem, because we're using Unicode.
> 
> Then why are keystrokes of 'ä' and similar chars silently ignored? I can't enter third-level chars like '»' (AltGr+y) either. Another bug?

I can't reproduce this problem on my Ubuntu.

**Comment by Noordfrees** [comment]
Tried it again and found that some chars work, others don't.

These work: `@|~{[]}\^!"$%&/()=?#'+*-.,_:;` `

These don't: `€§µßöäüÖÄÜ°´` as well as all other AltGr-modified chars

My keyboard layout is "Deutsch Deutsch (ohne Akzenttasten)". Btw the Compose key doesn't work either in WL.

**Comment by gunchleoc** [comment]
I can type AltGr-modified characters just fine. I guess you're the one who will have to debug this, because I can't reproduce the problem. I expect that it will be some form of general SDL modifier key handling problem on your system.

**Comment by Noordfrees** [comment]
Seems so… had a look at the code and it seems that input handling is delegated completely to the `SDL_Textinput` library which I never liked for reasons like this here. Perhaps I'll have some time soonish to try and find a workaround for that…
