### ISSUE TITLE
Add hyperlinks to Tribal Encyclopedia

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3769]
It would be helpful to be able to navigate the Tribal Encyclopedia using hyperlinks.

For example, the Empire's Barracks page lists materials needed to build it (Planks, Marble Columns, Cloth etc.). Now if you want to read up on any of them you have to switch to the Wares tab and find them manually. It would be nice to be able to just click them to go to their respective pages.

Same for workers, tools and everything else that lists things that have their separate pages.

**Comment by gunchleoc** [comment]
I have started to do some groundwork for this in https://github.com/gunchleoc/widelands/tree/refactor-wordwrap - we need to make elements in rendered text clickable first.
