### ISSUE TITLE
Daily PPA is failing

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3770]
For example, this one: https://launchpad.net/~widelands-dev/+archive/ubuntu/widelands-daily/+build/18833438

```
dh_install --fail-missing
dh_install: Please use dh_missing --list-missing/--fail-missing instead
dh_install: This feature will be removed in compat 12.
dh_install: Cannot find (any matches for) "usr/share/metainfo/org.widelands.Widelands.appdata.xml" (tried in ., debian/tmp)

dh_install: widelands missing files: usr/share/metainfo/org.widelands.Widelands.appdata.xml
dh_install: Cannot find (any matches for) "usr/share/applications" (tried in ., debian/tmp)

dh_install: widelands missing files: usr/share/applications
dh_install: Cannot find (any matches for) "usr/share/icons" (tried in ., debian/tmp)

dh_install: widelands missing files: usr/share/icons
dh_install: missing files, aborting
debian/rules:66: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:10: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-arch subprocess returned exit status 2
```

I suspect it has something to do with moving the appdata information from `debian` to `xdg`

**Comment by gunchleoc** [comment]
I have pushed a commit directly to master to see if it fixes the PPA https://github.com/widelands/widelands/commit/eb162f395869f31bcdcfc91a6f6f199efca4233e

**Comment by gunchleoc** [comment]
Of course it wasn't that easy. I have created a branch at Launchpad so I can test over there and will port the fix back over here when it's done.

https://code.launchpad.net/~widelands-dev/widelands/fix-ppa

**Comment by gunchleoc** [comment]
Should be fixed by https://github.com/widelands/widelands/commit/7e06a7f5ea98ec90ac50b319612b3267d1887d61

**Comment by Noordfrees** [comment]
The PPA is working again isn't it?
