### ISSUE TITLE
Typo in Sphinx documentation comment (PlayerBase::get_workers() method)

### ISSUE THREAD

**Issue by pospec4444** [widelands/widelands#3775]
**Describe the bug**

**To Reproduce**
1. Go to [documentation on get_workers method](https://www.widelands.org/documentation/autogen_wl_bases/?highlight=workers#wl.bases.PlayerBase.get_workers)
2. Returns section reads `the number of wares`

**Expected behavior**
Returns section reads `the number of workers`

**Version:**
 - OS: Ubuntu 18-04
 - Documentation Version: Last updated on Mar 14, 2020. Created using Sphinx 2.1.2.

**Additional context**
https://github.com/widelands/widelands/blob/6728300a2bde67d632e2f5ae78b52722c4aa9d23/src/scripting/lua_bases.cc#L874-L883

**Comment by frankystone** [comment]
fixed via #3781
