### ISSUE TITLE
XDG can unexpectedly turn WL_INSTALL_DATADIR useless 

### ISSUE THREAD

**Issue by Polynomial-C** [widelands/widelands#3776]
Since commit d1b47e73af34bee0f2a38ade58d9ef575afff59b there is support for XDG_DATA_DIR which was later enabled by default in commit ebe684c674149acd3e8991312899063b363cad36
Now the XDG code silently overrides (WL_)INSTALL_DATADIR in [src/wlapplication.cc](https://github.com/widelands/widelands/blob/master/src/wlapplication.cc#L975) if the path given there is not the first one contained in XDG_DATA_DIR.

This has two implications: 
- The first one is, that the built `widelands` binary will never look for its data files in the correct path unless called with the `--datadir` command line option because the data got installed into the path given with WL_INSTALL_DATADIR during build.
- The second one is that even if we happen to have chosen a path for WL_INSTALL_DATADIR that is contained in XDG_DATA_DIR the built `widelands` binary will only find its data files if the path happens to be the first in XDG_DATA_DIR. Imagine what happens if a user manually adds another path as first one to his XDG_DATA_DIR environment variable.

Why do I even come up with WL_INSTALL_DATADIR? Because the top [CMakeLists.txt](https://github.com/widelands/widelands/blob/master/CMakeLists.txt#L70) file contains a comment that explains what happens if this variable is unset or if it contains a relative or absolute path.
This variable is quite handy for package maintainers if the `widelands` binary is supposed to get installed into `/usr/bin` for example. Now I can put an absolute path into WL_INSTALL_DATADIR (like `/usr/share/widelands/data`) and the binary could always find its data files no matter where it gets installed but only if there wasn't this strange behavior if XDG is enabled.

This has already been reported in issue #3490 but that one got closed without any real resolution.

As a long term solution I'd like to suggest using [GNUInstallDirs](https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html) in the cmake files for installation into the Linux file system.

**To Reproduce**
1. `cmake -DCMAKE_INSTALL_PREFIX=/usr -DOPTION_BUILD_WEBSITE_TOOLS=OFF -DUSE_XDG=ON -DWL_INSTALL_BASEDIR=/usr/share/widelands -DWL_INSTALL_DATADIR=/usr/share/widelands/data`
2. build the project and move the binary to `/usr/bin/`
3. Run it and watch the error message about missing `i18n/fonts.lua` file

**Expected behavior**
The binary finds its data files

**Version:**
 - Gentoo Linux current ~amd64
 - Widelands Version: 5841c3146ea4e7e15479e6ca1592bfbea97fceb3

**Comment by gunchleoc** [comment]
Thanks for reporting this :)

We will still need to have the `--datadir` option working after we fix this, so that people can mod the data files freely without needing a second installation.

**Comment by Polynomial-C** [comment]
Small correction... when a path is found in XDG_DATA_DIR then `/widelands` is being appended to it in [src/wlapplication.cc](https://github.com/widelands/widelands/blob/master/src/wlapplication.cc#L979). So datafiles can only be found with XDG if the path being given in WL_INSTALL_DATADIR matches a leading path in XDG_DATA_DIR and ends with `/widelands`.
