### ISSUE TITLE
SDL2_INCLUDE_DIR-NOTFOUND

### ISSUE THREAD

**Issue by hoijui** [widelands/widelands#3783]
On Debian testing here.

Even though I have `libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev` installed,
I got:

```
$ cmake ..
...
-- SDL2_INCLUDE_DIR is SDL2_INCLUDE_DIR-NOTFOUND
-- SDL2MAIN_LIBRARY is /usr/lib/x86_64-linux-gnu/libSDL2main.a
```

I am assuming, this is the case because the headers get installed here:

```
/usr/include/x86_64-linux-gnu/SDL2/SDL.h
/usr/include/SDL2/SDL_image.h
/usr/include/SDL2/SDL_mixer.h
/usr/include/SDL2/SDL_ttf.h
```

No idea why like this, but this workaround works:

```
cmake -DCMAKE_INCLUDE_PATH=/usr/include/x86_64-linux-gnu/SDL2/ ..
...
-- SDL2_INCLUDE_DIR is /usr/include/x86_64-linux-gnu/SDL2
-- SDL2MAIN_LIBRARY is /usr/lib/x86_64-linux-gnu/libSDL2main.a
```
tested sing latest widlelands git version (4f9327af70595111a34548751bef37bc8de70eaf)

It would be nice if we can somehow spare other users to have to figure this out themselves.
could this be added to compile.sh maybe?
or just.. somehow a better workaround that cna be put directly into the CMakeLists.txt file?

**Comment by gunchleoc** [comment]
The path is specific to your system, so we better dig into doing this properly with CMake.

Can you try to see if [sld2.diff.txt](https://github.com/widelands/widelands/files/4359058/sld2.diff.txt) fixes it?

**Comment by spth** [comment]
I ran into the same issue (on Debian testing). Apparently Debian already has a fix in their widelands package:

**Describe the bug**
A clear and concise description of what the bug is.

SDL include path detection is broken in widelands build infrastructure. This results in build failure on system with current SDL versions.

**To Reproduce**
Steps to reproduce the behavior:

Invoke compile.sh on a system with current SDL.

**Expected behavior**

widelands builds

**Screenshots**

Error message: "CMake Error: The following variables are used in this project, but they are set to NOTFOUND. […]/widelands/src/SDL2_INCLUDE_DIR[…]"

**Version:**
 - OS: Debian testing
 - Widelands Version: git from today

**Additional context**

This error was reported against Debian before (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951281). The Debian widelands source package has been patched to fix the issue: https://sources.debian.org/patches/widelands/1:20-2/use-sdl2-cmake-integration.patch/

I guess widelands itself could be fixed the same way.

**Comment by Noordfrees** [comment]
It seems that out PPA is also encountering this issue here. 
@spth @hoijui I pushed a commit that *might* fix this issue (1912c287fba73f73c6985f6201ae7ca168b1b9d3), can you please test whether compiling latest master works now?

**Comment by spth** [comment]
Thanks. works for me.

P.S.: However, the discussion in the Debian bug report indicates that widelands is trying to detect SDL in a non-standard way. Apparently SDL now has cmake integration that should be used instead of a FindSDL2 module.

**Comment by Noordfrees** [comment]
Great that it works now :)
I guess our CMake integration could do with some cleanup, but I have no experience with this and well, as long as it works I'd rather not touch it…

One more request: The PPA has now successfully built for Focal. I'd be very happy if you could also give it a quick try to check whether the package from the daily PPA can be installed and started correctly

**Comment by jmoerschbach** [comment]
Hi,
was #3872 which closed this issue tested on Windows10 with MinGW?
I cannot build master:
`./compile.sh -t -w -s -a
`

`-- Found SDL2 configuration file
-- SDL2_INCLUDE_DIRS: /mingw64/include/SDL2
-- SDL2_LIBRARIES: -L/mingw64/lib  -lmingw32 -lSDL2main -lSDL2 -mwindows
-- Not using AddressSanitizer.
-- Detected mingw32-w64
-- Version of Widelands Build is r24632[0a35b58@master](Debug)
-- Configured windows resource file
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Jonas/widelands/build
`

`cc1plus.exe: warning: /mingw64/include/SDL2: No such file or directory [-Wmissing-include-dirs]
../src/base/scoped_timer.cc:22:10: fatal error: SDL_timer.h: No such file or directory
   22 | #include <SDL_timer.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
`
(Some more SDL include errors follow)

However, when I replace 
https://github.com/widelands/widelands/blob/0a35b585129e7b539d6a5ba3035dd2118a0038bf/CMakeLists.txt#L112-L139

with
`find_package(SDL2 REQUIRED)`
`SET(SDL2_LIBRARIES ${SDL2_LIBRARY})`
`SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})`

everything works fine again. Is the intended fallback not working for windows?

**Comment by Niektory** [comment]
Well, [it works on AppVeyor](https://ci.appveyor.com/project/widelands-dev/widelands/builds/33490871/job/q6m1829g3224xsdk?fullLog=true).

The code first looks for the configuration file `SDL2Config.cmake` or `sdl2-config.cmake`. If it is found, it uses it to import SDL2. If it is not found, the `FindSDL2.cmake` module is used as fallback.

In this case it seems that the config file was found and contains the expected variables (so the fallback is not triggered) but the include directory it points to (`/mingw64/include/SDL2`) doesn't exist. This should not happen... Did you try reinstalling SDL2?

**Comment by jmoerschbach** [comment]
No, I did not. Actually, I am quite happy that I've got a running toolchain (well, used to have...^^).
For now, I can live with my "hack" of cmake-file.
The required include path exists on my system.
Absolute path is C:\msys64\mingw64\include\SDL2

Where is SDL2Config.cmake/sdl2-config.cmake supposed to be? Is it "shipped" with cmake itself or is it part of our widelands repo? (Sorry, very little knowledge here with cmake...)
It is for sure not in widelands\cmake\Modules where I would expect it to be

**Comment by Niektory** [comment]
The config file should be supplied with SDL2. It should be [somewhere in those locations](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure).

Perhaps `/mingw64/include/SDL2` throws it off and it looks in  `C:\mingw64\include\SDL2` instead of `C:\msys64\mingw64\include\SDL2`. Maybe some sort of path translation is missing at some point, or maybe SDL2 just wasn't installed correctly. I don't know how it's supposed to work in the MinGW environment.

**Comment by hessenfarmer** [comment]
Hi Jonas,
I had an issue with an update build. But it worked with cmake and ninja in a clean build now.

**Comment by jmoerschbach** [comment]
Hi,

thanks, I can verify that building via cmake/ninja directly works just fine as @hessenfarmer states.
Therefore, I do not think my SDL/mingw setup is faulty...

Maybe the compile.sh needs some adjustment?
Feel free to close this again - I have now two possibilities to make it work (patch the CmakeLists.txt or build using cmake/ninja directly) which is fine for me

**Comment by jmoerschbach** [comment]
sorry, forget what I said above... it was too late when I tested yesterday. I forgot to revert the patched cmake file. Building directly via cmake/ninja does not work on my machine either. So I think @Niektory is right and there is something wrong with my sdl installation.

I will investigate further when I have time.
Closing this again...

**Comment by Niektory** [comment]
If you're using MSYS2, then updating the SDL2 package will probably help (see https://github.com/msys2/MINGW-packages/issues/6348)

**Comment by hessenfarmer** [comment]
@jmoerschbach did you check whether your msys64/mingw64/include/SDL2 folder not only exists but contains all the header files missing? Maybe something in the filesystem broke

**Comment by jmoerschbach** [comment]
yes, all the header files are there. As mentioned, I can build fine with the exact same toolchain/sdl2 installation just by patching the cmakelist.txt as mentioned above ;)

I will try to update sdl2 as soon as I figured out how to do that with msys^^

**Comment by hessenfarmer** [comment]
What is your current version of SDL2 
you can find out with pacman -Q
mine is mingw-w64-x86_64-SDL2 2.0.12-4 respectively mingw-w64-i686-SDL2 2.0.12-4

if you need to update you could try pacman -S mingw-w64-x86_64-SDL2 or see whether your MSYS2 is up to date with pacman- Syyuu

**Comment by jmoerschbach** [comment]
Thanks @hessenfarmer!
My sdl version was mingw-w64-x86_64-SDL2 2.0.10-1. Upgraded complete msys2 which updated a lot of packages in the end.
After downgrading boost once again as described in the [wiki](https://www.widelands.org/wiki/BuildingWidelandsUnderWindowsNew/#cmake-cant-find-the-boost-package) I now can build again! So it was my sdl installation after all as @Niektory already assumed ;)
