### ISSUE TITLE
Editor: Suggested Teams truncated

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3786]
The editors map loading screen shows at the bottom right a section "Suggested Teams". This section is truncated at the right and shows only "Suggested T". The rows of teams are also truncated:

![suggested_teams](https://user-images.githubusercontent.com/6730556/77223440-dbfa5200-6b5c-11ea-9fbc-46b778631671.jpg)
 
**To Reproduce**
1. Start the editor 
2. Open Load Map menu
3. Choose the map 'The Nile' or any other map with suggested teams.

**Expected behavior**
The section "Suggested Teams" should be as wide as the map description, that is the whole space at the right of the table of maps. 

**Version:**
 - OS: Archlinunx
 - Widelands Version: r75[97cef98@master] (Release)

**Additional context**
This applies only to the editor, not when starting a new game over "New Game/Choose a map"

**Comment by gunchleoc** [comment]
The box will need a different resize mode when it's being added.
