### ISSUE TITLE
Too many soldiers recruited when target set to 0

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3794]
**Describe the bug**
Barracks keep recruiting soldiers when they are not needed and the economy target is set to 0.

**To Reproduce**
1. Start a new game with the Fortified Village starting condition and Barbarians.
2. Build Barracks. Don't build any roads yet except Warehouse-Barracks.
3. Wait until a few Axes are delivered to the Barracks. The Barracks will not recruit any soldiers.
4. Open the economy options and set the demand for soldiers to 0. Still no soldiers will be recruited.
5. Build a road to the Citadel (so Warehouse-Barracks-Citadel are connected).
6. Now the Barracks will keep recruiting soldiers indefinitely (until it runs out of Axes).

**Expected behavior**
The Barracks should not recruit soldiers if the economy target is set to 0 and there are plenty of soldiers in the connected Warehouse.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: r24503[257910c@master] (Release)

**Additional context**
I used Barbarians as an example but the same problem occurs with other tribes too.
It can also occur with starting conditions other than Fortified Village, but may be harder to reproduce.

**Comment by Noordfrees** [comment]
Looks like a regression of https://bugs.launchpad.net/widelands/+bug/1236538

**Comment by Noordfrees** [comment]
The fix for that one is still there
https://github.com/widelands/widelands/blob/master/src/economy/economy.cc#L770
but it might have been overwritten accidentally by some change to `Economy::create_requested_worker` (edit:) or more likely some function related to target quantities and economy needs/doesn't need

**Comment by Noordfrees** [comment]
Ah found it. The error is in Economy::needs_ware_or_worker, where this is not being checked at all. Should be an easy fix…
