### ISSUE TITLE
Remove Ctrl-F10

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3801]
Does anyone actually use the Ctrl-F10 hotkey to quit Widelands (rather than e.g. Alt-F4)? If not, let's remove it.
If yes, we should consider changing either this hotkey or the screenshot key (Ctrl-F11) (or both) because it's too easy to try to make a screenshot, miss the correct key by a centimetre and boom, Widelands exits.

**Comment by gunchleoc** [comment]
+1 for removing it, since standard keyboard shortcuts are available from the OS anyway.
