### ISSUE TITLE
Additional expedition wares do not arrive

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#3817]
Attached save has an expedition awaiting wares: one trunk and two planks marked as "coming", but they have not arrived. After adding the additional wares I made some minor changes to the road network near the port area, but that's the only change I can think that might have affected routing. The roads were heavily congested as the expedition was begun.

Ubuntu 19.10
Widelands r24525[b2e6914]
Map [Tasmanian Black War](https://www.widelands.org/maps/tasmanian-black-war/)
[Expedition-Trunk-Waiting 1.wgf.zip](https://github.com/widelands/widelands/files/4400489/Expedition-Trunk-Waiting.1.wgf.zip)
[replays.zip](https://github.com/widelands/widelands/files/4400498/replays.zip)

**Comment by Niektory** [comment]
Hmm, I can't view the replay. `REPLAY: Lost synchronization at time 2000`

**Comment by simply-peachy** [comment]
It looks like replays are broken :-\

**Comment by Niektory** [comment]
Yeah, I'll bisect and open a separate issue for that.

**Comment by simply-peachy** [comment]
[Map, save, replay](https://github.com/widelands/widelands/files/4406337/expedition.zip)
Port on the HQ island is the location of the expedition, which is started around 3hrs 2 mins. Again with additional wares; three never seemed to arrive.

Note that during replay if you open the port's expedition tab during this replay, it segfaults -  I think after the first additional ware arrives, or is selected.

**Comment by Niektory** [comment]
It seems it happens pretty often. To reproduce in 01ae086, load [this save](https://github.com/widelands/widelands/files/4549290/trident_of_fire_expedition.wgf.zip), start an expedition and add 5 logs.

**Comment by klaus-halfmann** [comment]
Confirm I have seen simliar Problems while testing https://github.com/widelands/widelands/pull/3857, @Noordfrees on my first replays you may find this. Later on I stopped using this feature as it a) is quite cumbersome to configure and b) has the Issue described here.

The Expedition however started once I removed all the wares marked as coming.
Maybe an Expedition should preconfigure some wares (logs, stones, ...) that are
already found in the Harbour. In real life Ships always carried and still carry some
less valuable, additional cargo in case they are not fully loaded.

**Comment by Noordfrees** [comment]
Mh… I'll have a look at this issue and #3820 later…

**Comment by Noordfrees** [comment]
> Maybe an Expedition should preconfigure some wares (logs, stones, ...) that are
already found in the Harbour. In real life Ships always carried and still carry some less valuable, additional cargo in case they are not fully loaded.

I like this concept a lot, but how to choose which wares to use? The game does not have a concept of "preciousness" (except as AI hints, which should not be used for logic decisions), and this must not be hardcoded. Suggest a good way to choose the materials to pre-select and I'll implement this as a feature for b22…

**Comment by Noordfrees** [comment]
This issue is *evil*. The Request for each additional item is created correctly, a Transfer is started from the HQ to the port, the Request is removed to the economy – and the transferred object never arrives. And I have no idea why so far…

**Comment by Noordfrees** [comment]
Ahhhh… every additional item has been requested by one specific InputQueue. But when they arrive, they are put into the *first* empty InputQueue which may be a different one than the one that requested this individual ware instance. So I guess this could be fixed by forcing the ExpeditionBootstrap to recalculate every InputQueue's Request status when an item arrives. Eek
