### ISSUE TITLE
Empire01 doesn't start on master (`new_objectives` not defined)

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3826]
On current master (2ce3222), starting the first empire scenario fails with
```
Trying to run: map:scripting/init.lua: Fatal exception: lua: [../src/scripting/lua_errors.cc:22] [../src/scripting/lua_errors.cc:22] [string "scripting/texts.lua"]:135: attempt to call a nil value (global 'new_objectives')
stack traceback:
	[string "scripting/init.lua"]:14: in main chunk
FATAL ERROR - game crashed. Attempting emergency save.
```

**Comment by frankystone** [comment]
new_objectives is defined in messages.lua

messages.lua is loaded in misssion_thread.lua, but texts.lua (which throws this error) [is loaded before mission_thread.lua](https://github.com/widelands/widelands/blob/master/data/campaigns/emp01.wmf/scripting/init.lua).

I would suggest to load __all__ system scripts (those not belonging to a scenario) should be loaded via init.lua.

**Comment by hessenfarmer** [comment]
#3807 is the culprit as it moved this function from richtext_scenarios.lua to messages.lua
However I fully support the suggestion of frankystone
