### ISSUE TITLE
Unable to join multiplayer LAN game

### ISSUE THREAD

**Issue by m8522s** [widelands/widelands#3830]
**Describe the bug**
I open a multiplayer game with a regular map. When I try to join a local multiplayer game, the "Multiplayer Game Setup" always tells me:
> The host has not yet selected a map or saved game.

This happens for all maps (although I only tried a few) in version master-6928.

**To Reproduce**
1. Start first instance of Widelands
2. Go to Multiplayer > LAN / Direct IP > Host a new game.
3. Choose a map
4. Start second instance of Widelands 
5. Go to Multiplayer > LAN / Direct IP > Host to connect: 127.0.0.1
6. Next window indicates "The host has not yet selected a map or saved game" in the top right corner.

**Expected behavior**
The second instance of WL or another client joins the game and can choose color and tribe.

**Screenshots**
![unable_to_join_game](https://user-images.githubusercontent.com/43844394/78591486-c87d0580-7843-11ea-8d27-8c23034314b6.png)

**Version:**
 - OS: Windows 7
 - Widelands Version: master-6928

**Comment by Noordfrees** [comment]
Thanks for reporting. I cannot reproduce on Ubuntu 19.10 with 15a7afbb37c52dfb5d3714dfa70832d694feb41c and there were no changes to the networking code recently so this is probably a Windows-related issue

**Comment by frankystone** [comment]
Also can't reproduce with 15a7afb (Debug).

Windows 7 has reached EOL since January 2020. If a windows 10 user can't confirm this, this bug should be closed, because supporting old OSs is out of scope for widelands.

**Comment by frankystone** [comment]
Can you provide a screenshot of the screen where the open LAN games are listet?

Normally one can just click on an entry in the list and then click on "Join Game".

**Comment by m8522s** [comment]
The game appears in the list of games. Also I can highlight it and click "Join this game". 
![list_of_games](https://user-images.githubusercontent.com/43844394/78647222-8cd15280-78ba-11ea-87a4-42bf823f2288.png)
In the next window I get the "master has not selected a map" issue as described above.

Unfortunately I don't have a Windows 10 computer at hand to validate this behavious.

**Comment by klaus-halfmann** [comment]
I can confirm this happens on  WINDOWS 10 with "Version-master-6950_Release_x46", too.
I allowed widelands in the Firewall and used 127.0.0.1. Will try localhost or ::1 later

**Comment by klaus-halfmann** [comment]
Makes no difference what kind of IP-Adress I use. a Wrong IP will fail but a correct one (evene IPv6) connects, but then shows that behaviour.

Test OSX (Host) <- Windows (client), OK
Test Windows (host) <- OSX (client) failes

So it must be the hosting function on windows
Log Output show nothing unexpected 
(The broadcast function does not work on either side, did not check this any further)

Log on widows side does not help me either:

[LAN] Trying to open both sockets.
[LAN] Started an IPv4 socket on UDP port 7394.
[LAN] Started an IPv6 socket on UDP port 7394.
[LAN] Will broadcast to 255.255.255.255.
[LAN] Will broadcast for IPv6.
[Host]: starting up.
[NetHost] Opening a listening IPv4 socket on TCP port 7396
[NetHost] Opening a listening IPv6 socket on TCP port 7396
[NetHost] Using the new acceptors
[LAN] Trying to open both sockets.
[LAN] Started an IPv4 socket on UDP port 7395.
[LAN] Started an IPv6 socket on UDP port 7395.
[LAN] Will broadcast to 255.255.255.255.
[LAN] Will broadcast for IPv6.
[NetHost] Starting networking thread
Received QUERY packet from 192.168.254.32
Map/Save is a directory! No way for making it available a.t.m.!
[NetHost] Stopping networking thread
[NetHost] Closing a listening IPv4 socket.
[NetHost] Closing a listening IPv6 socket.
[LAN] Closing an IPv4 socket.
[LAN] Closing an IPv6 socket.
[LAN] Closing an IPv4 socket.
[LAN] Closing an IPv6 socket.
SoundHandler: Closing 1 time, 22050 Hz, format 32784, 2 channels
SoundHandler: SDL_AUDIODRIVER wasapi

As I cannot build on windows I am out of ideas now, sorry,

**Comment by Notabilis** [comment]
Thanks for testing and for the log output. It seems the host is starting and listening fine. However, there is no report of a client connecting, e.g., `[BufferedConnection] Accepting connection from <IP>`. Is this log from a time where the client should have connected? If that is the case, the connection never seems to reach the Widelands host. Strange that the client goes to the next screen, though, seems like it got some kind of response by someone(???).
Have you looked at the output on the client side? For my client it looks like the following:

`Received GAME packet from <IP>`
`[NetClient]: Trying to connect to <IP>:7396 ... [BufferedConnection] Trying to connect to <IP>:7396 ... success.`
`success.`
`[BufferedConnection] Starting networking thread`
`[Client] SETTING_MAP '' ''`
`[Client] SETTING_MAP 'Crater' 'maps/Crater.wmf'`
`[Client] Pong!`

Have you tried changing the map after connecting the client? Does this change anything?
Are chat messages working?

**Comment by m8522s** [comment]
Changing the map doesn't change anything. And no, chat messages aren't working.

**Comment by frankystone** [comment]
Sarching the web i found that windows might forbid connections to localhost, but i am not a network expert :-D

https://stackoverflow.com/questions/24340450/localhost-on-windows-7

https://stackoverflow.com/questions/30334289/cant-open-localhost-in-microsoft-edge-project-spartan-in-windows-10-preview

**Comment by m8522s** [comment]
The issue also happens, when I run Widelands on two different hosts (both Windows 7).
Anything else I can test? Would a Wireshark dump help in troubleshooting?

**Comment by Notabilis** [comment]
The problems with localhost you found on the web seem to only affect connections to the local webserver. Turns out: If you don't run one, you can't connect to it. I don't think it is related to our problem, though, since we are running our own server.

Thanks for testing again, admittedly it is no big surprise that changing the map isn't working. Have you tried playing over the internet (using the metaserver)? If that works, we can reduce the amount of code that might be wrong.

Ohhh... You know how to use Wireshark? Great, I wasn't expecting that! That should indeed help in figuring out what is going on. Please capture packets on "any" adapter or on the network interface you are using (loopback? lan?), and set the capture filter to:
`udp.port==7394 || udp.port==7395 || tcp.port==7396`

Also, you could take a look at the console output of the game. I think (not sure) that there should be a file name "stdout.txt" in the folder `C:\Users\[username]\.widelands`. If you don't find it, never mind.

**Comment by klaus-halfmann** [comment]
I can debug this ont the client side (OSX) should be somewher int netclinet (maybe some of my refacorings for last year broke it?) I would start ceckin in netclient...cc unless you can give me some better locations for a breakpoint. Will try to setup such a session
 now

Whta kaputtnik found is only related to browsers, not the network dircectly and the windows 10 firewall ask me to allo connections.

**Comment by klaus-halfmann** [comment]
* From the Code I see that we have a dependency to BOOST_VERSION in bufferedconnection.cc
* This time I used the name found by the broadcast, semms to work though. (using ipv4)
* I see that the socket is create, next I see that I drop out of mainmenu or such
* I can fallow the code upto boost::asio::async_write in BufferedConnection::start_sending() but then I am lost

Conclusion: Nothing is ever received on the windows side, possible reasons
* Version of boost / asio on server siede?
* Special WIndow security interfering with widelands
* ???

Any more I can do?

**Comment by m8522s** [comment]
Here is a Wireshark capture of a client (192.168.1.70) joining a game of a host (192.168.1.13). I also attached the stdout.txt file.
During testing the Windows firewall was switched off.

[stdout.txt](https://github.com/widelands/widelands/files/4449197/stdout.txt)
[bug_3830.zip](https://github.com/widelands/widelands/files/4449199/bug_3830.zip)

By the way, the capture filter is
`udp port 7394 or udp port 7395 or tcp port 7396`
The other one was a display filter ;-)

**Comment by klaus-halfmann** [comment]
13 Broadcasts "QUERY" + LAN_PROMOTION_PROTOCOL_VERSION=1
    // What an ugly part of our code :-)
13 Broadcasts NetGameInfo "GAME" 0,0 LAN_PROMOTION_PROTOCOL_VERSION=1 LAN_GAME_OPEN=1
    + Version="master-6928_Release_x64" Hostname="manila" with no map
13 Broadcasts NetGameInfo "GAME" 0,0 LAN_PROMOTION_PROTOCOL_VERSION=1 LAN_GAME_OPEN=1
    + Version="master-6928_Release_x64" Hostname="manila" map="Crater"
70 Broadcasts "QUERY"  + LAN_PROMOTION_PROTOCOL_VERSION=1
13 Broadcasts NetGameInfo "GAME" 0,0 LAN_PROMOTION_PROTOCOL_VERSION=1 LAN_GAME_OPEN=1
-- all expected so far
70 sends SYN to Port 7396
13 sends SYN, ACK from Port 7396
70 sends ACK
-- assuming this is the normal TCP inital handshake, OK
70 sends PSH (Push Flag) with "Tim" clientVersion="master-6928_Release_x64"
     // from GameClientImpl::send_hello() , should be handeled by GameHost::welcome_client()
70 sends ACK
-- EOF 

So I would assume in the WIndow version this command is never received so nothing further happens :-( . I found no Windows specific code anyway along this path.

@msarig  please download and use a debug version (as you used a release verison)
Whoever "Tim" is should be carefull about dataprivacy in network debugging ;-)

Can anybody here debug on windows? Lets check why GameHost::welcome_client() is not called

**Comment by m8522s** [comment]
Same issue happens in a debug version. I tried Widelands-master-6951-Debug.
However, I'm not sure what a debug version does exactly. Please guide me.

Don't worry about Tim and data privacy. He is my son and most likely the youngest Widelands fan ever (7 years).

**Comment by Notabilis** [comment]
I am currently assuming that there is something not working in the *accept() code on the Windows side. I don't know where, though. I don't think it is your refactoring, that would have also affected the Linux builds. Maybe this is the first time that my new Boost code is run on Windows? The log shows that it is used...

Thanks for the log output and the Wireshark trace. I think the interpretation of it is correct: The data is send and even received by the network stack (so I guess no firewall problem) but doesn't make it to the game logic.
Indeed it was a display filter, sorry. I (nearly) never use the capture filter, so I ignored the difference.

The debug version has some more checks (asserts) in it, that are assumed to always hold. If one of it would have failed, the game would have crashed with a useful error message. So there is no special action required on your part except using it normally.

Greetings to Tim, glad he enjoys the game. If there is anything that is too difficult for him (or some suggestions or so), feel free to report it. I guess much of our bug reporters and forum participants are much older, so his perspective could be interesting.

Has one of you tried to play the game online? Except for the accept()-code it should use mostly the same code paths, so if online gaming works on windows I guess we have our culprit. Next step would than be to switch to the old accept()-code and test that one.

I set up a branch for good old printf-debugging (more outputs, no other changes), but it will take some time until the automatic windows builds are available: https://github.com/widelands/widelands/pull/3836

**Comment by Notabilis** [comment]
Windows builds of the printf-branch are available, if someone wants to test them:
32bit: https://ci.appveyor.com/project/widelands-dev/widelands/builds/32049145/job/5k57yvistq4ofcsi/artifacts
64bit: https://ci.appveyor.com/project/widelands-dev/widelands/builds/32049145/job/kh4sx6efh5k6ali8/artifacts

If you use them, then I am highly interested in the log output of the host.

**Comment by klaus-halfmann** [comment]
Just use the debug version and report stdout.txt, it should report more logs.
It someteimes is slower as of additional debugging code and extra tests.
I will start my Window machine agian, lets see what happend.

**Comment by m8522s** [comment]
Just reproduced the issue with Widelands-master-6959-Debug-x64. I attached both `stdout.txt` files from the host and the client.

[stdout_client.txt](https://github.com/widelands/widelands/files/4455091/stdout_client.txt)
[stdout_server.zip](https://github.com/widelands/widelands/files/4455096/stdout_server.zip)

As soon as the client received the "The host has not yet selected a map" message, I close the client software (that is line 69 in `stdout_client.txt`).

**Comment by klaus-halfmann** [comment]
Got a similar file, but it way to big. give me wome time to "condense" it

**Comment by klaus-halfmann** [comment]
Sorry I found nothing notewhorthy in the logs. @Notabilis that was really excessive logging, maybe  we had to many logs? I will check now for known bugs in boost asio on windows.

**Comment by klaus-halfmann** [comment]
For windows we use mingw-w64-x86_64-boost-1.72.0-1
on OSX I use boost @1.71.0_1 (devel) 
Doc are here https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio.html
Repo is here: https://github.com/boostorg/asio
Found no +/- matching issues there?

@Notabilis can we for the build to use an older version?

**Comment by Notabilis** [comment]
Jup, that logging indeed was pretty excessive. Sorry for that, but it worked. The lines that were repeated ... a few ... times shouldn't have been repeated at all.
It is indeed the new accept code that is failing under Windows for some reason (specifically the call to `acceptor::async_wait()`). It should have blocked and waited for a connection, but for some reason it did not, resulting in the (output) loop. Unfortunately, my error "handling" of the failure only consisted of trying again without any error output.

I pushed a commit to the debug-branch which should produce some error output when the wait-call fails. I will past the link here if he build is complete.
It will be excessive logging again, I fear. But we only need the part behind the output of `acceptor.async_wait() failed:`. There should be some description of the error before the next code position is reported.

> can we for the build to use an older version?

I don't quite understand what you want to do. If you want to build with an older version of boost, then I guess it would be possible, but I have no idea how to make appveyor do so.

**Comment by klaus-halfmann** [comment]
Played an Online game with @Niektory today, he has boost 1.72 and told me that version does not cause the issue. Thanks for you explanation, I felt a little stupid scanning 17k of logs :-)

**Comment by Niektory** [comment]
Yes, hosting and joining a localhost game works fine for me in Manjaro Linux with boost 1.72.0. Tested both 3547a299542d3cac26716c6a7161414750bb2487 (master-6928) and 15a7afbb37c52dfb5d3714dfa70832d694feb41c (current master).

**Comment by Notabilis** [comment]
Thanks for testing. So I guess we can assume that the problem is indeed only on Windows.

The 32bit Windows build of the branch is done. Can someone please test it with Windows? Optimally two tests would be great: One while hosting a game but no client connecting, a second one where the client tries to connect. Interesting is whatever appears behind the string `acceptor.async_wait() failed:` in the log output of the host.
https://ci.appveyor.com/api/buildjobs/rxxne8ukd9pk456c/artifacts/Widelands-master-6964-Debug-x86.exe

**Comment by klaus-halfmann** [comment]
Here you are: will check myself on the OSX side

[no_connect_stdout.txt](https://github.com/widelands/widelands/files/4460101/no_connect_stdout.txt)
[connect_stdout.zip](https://github.com/widelands/widelands/files/4460108/connect_stdout.zip)

**Comment by klaus-halfmann** [comment]
Here is what I found:

[BufferedConnection] Starting networking thread
[BufferedConnection] Error when receiving data from host (error 10054: Eine vorhandene Verbindung wurde vom Remotehost geschlossen)
[BufferedConnection] Closing socket
[BufferedConnection] Stopping networking thread
[Client]: disconnect(CONNECTION_LOST, )
[BufferedConnection] Closing network socket.
[LAN] Closing an IPv4 socket.
[LAN] Closing an IPv6 socket.
):182 ../src/network/nethost.cc

Where in the client code should I find that close? 
Looks like some handshae failed in the end?

Will debug again on the client side (on master) later ...

**Comment by m8522s** [comment]
Just completed testing with Widelands-master-6964-Debug-x86:
[connect_stdout.zip](https://github.com/widelands/widelands/files/4460614/connect_stdout.zip)
[no_connect_stdout.zip](https://github.com/widelands/widelands/files/4460615/no_connect_stdout.zip)
[stdout_client.txt](https://github.com/widelands/widelands/files/4460616/stdout_client.txt)

**Comment by Notabilis** [comment]
Sooo...
Thanks for testing again. If I read the logs right, the error even happens before a client tries to connect. Regarding the closed connection of the client: I wouldn't be surprised if there is no normal code path for it and it is only one of the strange effects of this bug. Seemingly, we somehow get a working TCP connection (as also seen in the Wireshark capture), even though the accept call always fails. However that is possible...

Unfortunately, the error output I added to the branch uses std::cout instead of log(). This works fine when running the game from the command line, but unfortunately the output doesn't end up in the stdout.txt. However, I was able to run the Windows version on my computer under Linux with wine and was able to recreate the error. There I got this error message:
> acceptor.async_wait() failed:system:10057

Based on the Windows documentation this is `WSAENOTCONN`, that is, the function call failed since there is no connection. Yeah, thanks, we know, we are calling this function to create a connection... I wasn't able to find anything related to this error code and accept() online, either.
If you want, you can open a console window in the Widelands folder under Windows and start the program from the console, this will then hopefully print the same error message to the console.

I tried to look in the boost code which Windows functions are really called when I use the boost function, but I wasn't able to figure out their code or what is called.

Currently I am leaning towards removing the new accept code (for all boost versions and operating systems) and using the one for the older boost version. I consider the old one less elegant code wise, but when it works that is the more important criteria. Any opinions or other suggestions about that?

**Comment by Noordfrees** [comment]
> Any opinions or other suggestions about that?

I am not familiar with the networking code, but especially as a feature freeze and a new release are approaching, I would vote to re-enable less elegant code that was known to work correctly if it fixes this bug.

**Comment by klaus-halfmann** [comment]
We efinitly should fix this, as local LAN gaming on windows _is_ broken.
Last known Status: @Notabilis wanted to rollback this part of the code,
as we have no Idea if boost:asio is broken on windows.

Do we have any hardcore windows developer around who could debug this?

**Comment by klaus-halfmann** [comment]
@msarig we have a branch with a fix pending. lets test this once we got a binary
https://ci.appveyor.com/project/widelands-dev/widelands/builds/32274152
based on
https://github.com/widelands/widelands/pull/3859

**Comment by m8522s** [comment]
@klaus-halfmann Yes! In this release the LAN gaminig feature is working. I tried on Windows 7 with Widelands-master-7103-Release (64bit). Thanks for the fix.

**Comment by Noordfrees** [comment]
Fixed in #3859
