### ISSUE TITLE
Multiplayer map with more than 8 players

### ISSUE THREAD

**Issue by m8522s** [widelands/widelands#3831]
**Describe the bug**
The "Multiplayer Game Setup" shows only 8 players, even if the map has more than eight. Since I cannot modify player 9, 10, etc. the button "Start game" stays inactive and the game refuses to start.
If this is related to screen resolution: my display can go up to 1280x1024.

**To Reproduce**
1. Go to Multiplayer > LAN / Direct IP > Host a new game
2. Choose a map with more than 8 players, e.g. "Rounds Ultra"
3. The first eight players show up. 

**Expected behavior**
The list of players should be scrollable so I can configure all players.

**Screenshots**
![map_with_15_players](https://user-images.githubusercontent.com/43844394/78592363-4b529000-7845-11ea-89c5-c8ef237b3a2d.png)

**Version:**
 - OS: Windows 7
 - Widelands Version: build-20, master-6928, bzr9110

**Comment by Noordfrees** [comment]
We don't officially support more than 8 players yet. The possibility to set up to 16 players in a map was added only for testing purposes. However we should either fix the UI (preferred) or remove this possibility for b21.

**Comment by Noordfrees** [comment]
Marking as urgent because a PR for this is open

EDIT: it was already like this in b20 so it is not such a big problem if we now retarget to b22
