### ISSUE TITLE
Automated code review for widelands

### ISSUE THREAD

**Issue by ghost** [widelands/widelands#3834]
Hi!
I am a member of the team developing **monocodus** — a service that performs automatic code review of GitHub pull requests to help organizations ensure a high quality of code.
We’ve developed some useful features to the moment, and now we’re looking for early users and feedback to find out what we should improve and which features the community needs the most.

We ran **monocodus** on a pre-created fork of your repo on GitHub https://github.com/monocodus-demonstrations/widelands/pull/1, and it found 4 places to fix according to clang-tidy checks. I hope that this information will be useful to you and would be happy to receive any feedback here or on my email alena@monocodus.com

If you want to try our service, feel free to follow the link: https://www.monocodus.com
The service is entirely free of charge for open source projects. Hope you’ll like it :)

**Comment by Noordfrees** [comment]
Hello @gingerDevilish,  
while the idea of a bot that suggests code style improvements sound good to me, the demo in the linked PR does not really convince. One of the four comments there is a matter of code-style taste, but the other three suggestions are semantics changes and may likely result in compile errors. 
Also the diff for the PR you chose as a demonstration is very large so the bot should probably have picked up far more than just these 4 issues.

No offence meant, I personally do like your idea, but it seems that your bot may still need to read some C++ coding guides.

**Comment by Noordfrees** [comment]
No replies here for 1½ weeks, did I scare them off?

**Comment by gunchleoc** [comment]
@gingerDevilish In case you're interested, we're running our own clang-tidy as a GitHub action now: https://github.com/widelands/widelands/blob/master/.github/workflows/build.yaml#L9

This gives us full control over which checks we want to run, and we can run it offline too.
