### ISSUE TITLE
Player can be resurrected and has no fog of war.

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3849]
**Describe the bug**
We had a very interesting bug. A player got defeated because his last warehouse got destroyed and then relegated to spectator. The fog of war was lifted, and he could see everything. He had a few minutes after he got defeated a warehouse that was under construction was finished and the player got back into the match.

This was kind of unexpected. Also, the resurrected player had no fog of war anymore and had an advantage over the others.

Edit:

The player also can look into others buildings but cannot attack.

**Comment by Noordfrees** [comment]
What exactly does "got back into the match" mean – was the player able to build buildings and stuff? What did the end-of-game table say about this player's state?

**Comment by stonerl** [comment]
> was the player able to build buildings and stuff?
Yes.
He got the "You got defeated" message but after the warehouse was finished he got back into the game. 

I'll upload the replay as soon as the game is finished.

**Comment by hessenfarmer** [comment]
This has been reported some times before. Personally I didn't know how to fix that, until #3742. Discussion in forums was unclear whether to fix it at all, cause if you manage to get a constructionsite with all wares to build a warehouse why should you be defeated. 
So for me there are 2 solutions: 
a) just destroy all port and warehouse constructionsites, as well as expedition ships once the last existing warehouse/port has been destroyed. This would be my preferred solution. as it would be consistent.
b) allow ressurection by having a full constructionsite or an expedition ship left. In this case we need to check for this possibilities before lifting the fog of war so a real resurrection can take place.     
  
I believe a) is easier and more consistent, but offers less options. Should be discussed in the forums imho. I'll try to find some old thread for this.

**Comment by stonerl** [comment]
Here is the replay. The player in question is the green one.

[Archive.zip](https://github.com/widelands/widelands/files/4477761/Archive.zip)
