### ISSUE TITLE
Hotkey clashes

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#3851]
Using revision 2ebfb8146897d27e18f9a856099aba9513629e59 hotkey `G` clashes with "toggle general statistics" and "Goto from Messages", `Esc` clashes with "Close window" and "Exit game".

Since `Enter` is also used as a Goto jump I suggest that `G` can be dropped for Goto. `Esc` seems to be a good fit to close windows. Perhaps `F10` can be used for exit game?

I can make the necessary changes once it's been agreed how to proceed.

**Comment by Noordfrees** [comment]
In the editor we have the `H` hotkey to open the main menu, IMHO we should make this consistent in the game: Drop `Esc` for the menu (both in editor and normal game) and introduce `H` for this in games.

I vote to keep the `G` for Goto because `Enter` is also a chat hotkey. How about changing the general stats hotkey to `A` (which is not used anywhere yet)?

**Comment by Niektory** [comment]
Funny, I was about to open a similar issue about the `G` hotkey. :) Changing it to `A` would work.

I'm not sure about the `Esc` behavior. Bringing up the menu with `Esc` is pretty common in games, and I think it's fine if it does that if no window is focused. But I'm not against changing it.

A related problem I think is the fact that there is no visual difference between focused and unfocused windows, so you're often not sure where your keypress will go. But that's another issue: #3852

**Comment by simply-peachy** [comment]
I never use the close window hotkey because a) focus is unknown and b) I often have windows I want to stay open, and those I will want to close, so it'd require too much attention to watch focus change as I close windows. Much easier for me to just right-click each window I want to close, whether I can see window focus or not. Others may play differently, however. I'm sure some folk play with no windows open during normal gameplay and find a close window hotkey to be very helpful.

What about a modifier? `Esc` for close window, `Ctrl-Esc` for game menu, or vice-versa?

**Comment by Noordfrees** [comment]
Many games use `Delete` for closing windows. How about using this one instead of `Esc`? Then we could use `Esc` only for the menu (and get rid of `H` for consistency).

Edit: On a side note, it would also be good IMHO to have a hotkey to close all windows (e.g. `Shift+Delete`), but this would be a bit more coding work

**Comment by Niektory** [comment]
`Delete` sounds problematic. It is used for archiving messages, and probably in editboxes too.

**Comment by Noordfrees** [comment]
Ah right, I had forgotten that. How about `Backspace` or `F4` then?

**Comment by Niektory** [comment]
I wrote that bringing up main menu with `Esc` is common in games. However, closing windows with `Esc` is common in GUIs in general. Plus, `Esc` is a very easily accessible key. I think the main menu is opened only occasionally, and closing windows is potentially done more often. So I think one of these would make the most sense:
1. `Esc` - close windows or open main menu (current behavior); `F10` - open main menu
2. `Esc` - close windows; `F10` - open main menu (simply-peachy's original proposal)

**Comment by Niektory** [comment]
There's more clashes in the Seafaring Statistics. `W` is used for "Watch the selected ship", but also for "Hide Workarea Overlaps". `O` is used for "Open the selected ship's window", but also for "Objectives". `G` we already covered.

**Comment by Noordfrees** [comment]
Marking as urgent because a related PR is open
