### ISSUE TITLE
Inconsistent version numbers across platforms

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3862]
Currently builds use several different versioning schemes:
- `r24562[faaa1e2@master]` - git clone & compile.sh
- `master-7109_Release_x64` - AppVeyor
- `bzr9271[trunk]` - Launchpad (?)

These are all the same version. This is confusing for users, for example when trying to synchronize versions for multiplayer.

**Comment by Noordfrees** [comment]
IMHO all builds should contain at least the git hash. Some distinction between the build platforms would be good, so we should have something like e.g. 
`r24562[faaa1e2@master]`
`7109_Release_x64[faaa1e2@master]`
`bzr9271[faaa1e2@trunk]`

Our python script to detect bzr revisions could probably be adapted to filter out the git hash from the commit message. For appveyor, @TinoM might know how to adjust the naming scheme…

**Comment by Niektory** [comment]
Hmm... The Ubuntu PPA still uses this format:
```
-- Version of Widelands Build is bzr9327-202006051231(Release)
```
What did I miss...?

**Comment by Noordfrees** [comment]
This looks like a [launchpad setting](https://code.launchpad.net/~widelands-dev/+recipe/widelands-daily): 
`# bzr-builder format 0.3 deb-version 1:20-ppa0-bzr{revno}-{time}`
