### ISSUE TITLE
Wrong ratio of Granite:Marble produced by Empire Marble Mine

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3863]
**To Reproduce**
1. Load the savegame: [marble_mine_test.wgf.zip](https://github.com/widelands/widelands/files/4504655/marble_mine_test.wgf.zip)
2. Observe the Marble Mine. It will keep executing the `mine_granite` program, mining in the ratio 3 Granite : 1 Marble until input wares run out. The `mine_marble` program (which would produce 1 Granite and 3 Marble) is never executed. The mine's behavior is the same whether the economy needs only granite, only marble, or both.

In this case the mine is "stuck in the `mine_granite` loop", and this is what usually happens. But I also observed "stuck in `mine_marble` loop" behavior occasionally on other maps. I'm guessing this depends on the exact timing when production starts.

**Expected behavior**
I can think of two behaviors that would make sense:
1. `mine_granite` should only be executed when the economy needs Granite, and `mine_marble` only when the economy needs Marble.
2. Granite and Marble should always be mined in the same ratio (2:2 or whatever is desired). In this case there's probably no need to have two separate programs at all.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: r24564[5703fc9@master] (Release), the same behavior also observed in Build 20

**Comment by Noordfrees** [comment]
> `mine_granite` should only be executed when the economy needs Granite, and `mine_marble` only when the economy needs Marble.

+1

**Comment by frankystone** [comment]
Does this apply also to other mines wich produces more than one ware? E.g the [atlanteans crystalmine](https://github.com/widelands/widelands/blob/master/data/tribes/buildings/productionsites/atlanteans/crystalmine/init.lua#L61)?

**Comment by Niektory** [comment]
The Crystal Mine also repeats executing one program until there is no more demand for the respective resource, even when all 3 resources are in demand. But at least every program checks for a different demand so the player still has control over which ones can run, unlike the Marble Mine.

**Comment by hessenfarmer** [comment]
yes this applies to the atlanteans crystalmine as well. I think the new stats introduced by me could be the culprit. Just checking this.

**Comment by Niektory** [comment]
I think this is older, I reproduced the same problem in Build 20.

**Comment by hessenfarmer** [comment]
ok I suspect the return=no_stats lines to erroneously return in the main loop rather then in the subcommand. However i believe they aren't needed anymore so I'll try what happens without them

**Comment by hessenfarmer** [comment]
ok as suspected this explains the preference of one tool (the first one) in the toolsmithies as well. had been there since b20 as nobody realized that these returns ended the main loop not only the subloop.   
will fix this.
