### ISSUE TITLE
Worker request not saved in savegame

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3866]
Bug reported on forum see https://www.widelands.org/forum/post/32641/

to reproduce best use a minimal start condition. Create 1 or 2 buildings without proper workers where no tools are available as well. save the game. close and reload the saved game. build a toolsmithy. No tools are built although the smithy could  work.

**Comment by Noordfrees** [comment]
I cannot reproduce this one. I only built the basic infra (lumberjack, forester, quarry, reed yard, well, limekiln, dismantle lumberjack, build woodhardener, build a fisher and a hunter (both of which stay unoccupied). Saved and reloaded, built a metal workshop → an *Angel* was produced and a fisher recruited who occupied the fishers hut.

**Comment by hessenfarmer** [comment]
strange, as it happened to me exactly like for blind3rdeye. When I am at home I'll provide a savegame for this. I am on windows so might it be the case we have some issue with different compiler here?

**Comment by Niektory** [comment]
I can reproduce this reliably.

Good savegame: [poor_barb2.2.wgf.zip](https://github.com/widelands/widelands/files/4510046/poor_barb2.2.wgf.zip)
If you load this one and connect the Metal Workshop, it **will** produce a Felling Ax for the vacant Lumberjack's Hut (after it's completed).

Bad savegame: [poor_barb2.3.wgf.zip](https://github.com/widelands/widelands/files/4510048/poor_barb2.3.wgf.zip)
If you load this one and connect the Metal Workshop, it **will not** produce a Felling Ax for the vacant Lumberjack's Hut.

How to produce the bad savegame:
1. Load the good savegame.
2. Wait until Lumberjack's Hut is completed.
3. Save.

**Comment by Noordfrees** [comment]
I can reproduce with this savegame. Will investigate…

**Comment by Noordfrees** [comment]
Notes to self.

Findings so far: 
A PlannedWorkers instance with 2 requests is created (one for 1 carrier and 1 for 1 felling_ax). Without reloading, these requests are properly added to the economy and eventually found by the metalworkshop's call to Economy::needs_ware_or_worker(). As expected so far.
On saveloading, the PlannedWorkers and its Requests are correctly saved and recreated, but for some reason, Economy.requests_ is empty. Why is the request not added to the economy after loading?

**Comment by Noordfrees** [comment]
Heureka! Big, big error related to ware requests being added to worker economies on loading

Edit: Should be an easy fix though

**Comment by hessenfarmer** [comment]
do you need another savegame / replay? 
As I have it here it is anyway
[worker_request_bug.zip](https://github.com/widelands/widelands/files/4511793/worker_request_bug.zip)
