### ISSUE TITLE
barbarian poor hamlet does not work as intended

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3867]
Barbarian poor hamlet can't be solved without dismantling a lumberjack which is not intended.

Proposed solution change the workorder of the metal workshop to first build firetongs and not felling ax. This should not have effect on normal gameplay

**Comment by Noordfrees** [comment]
I would not consider this a bug. Just stockpile logs, then dismantle the lumberjack, build a woodhardener, produce blackwood, (if needed dismantle the woodhardener then and rebuild the lumberjack).
This starting condition *can* be solved as it is, and as it's intended to be really the absolute minimum I'd vote to keep it as it is.

**Comment by hessenfarmer** [comment]
But it is the only one that needs dismantling. I believe we should fix it as described to be consistent with empir for example.

**Comment by Noordfrees** [comment]
Does this apply only to poor hamlet or also to struggling outpost? SO should be playable without this, but for PH I'd prefer a starting condition that is really the absolute minimum with which building a complete economy is possible in any way.

**Comment by hessenfarmer** [comment]
In principle I agree. However as dismantling is only necessary due to the player not having exact control over the economy this has already led to forum discussion. As said this is different to empire where the dismantling of buildings is not necessary only due to the build order of the toolsmithy (it is still necessary to exchange workers). So to keep consistency we should change either barbarians or empire to introduce the same behaviour. I vote for barbarians.
edited to clarify

**Comment by hessenfarmer** [comment]
it is only applicable to PH as SO has tools not iron

**Comment by Noordfrees** [comment]
I would vote to make empire minimal start harder instead of barbarians easier.

**Comment by hessenfarmer** [comment]
best solution would be to give players control over their economy. (i.e. disconnecting a building from  economy would delete the request for the worker which would delete the request for the tool) However this bug is not as essential as the other one that turned up.

**Comment by Niektory** [comment]
> Barbarian poor hamlet can't be solved without dismantling a lumberjack which is not intended.

It can be solved without dismantling or reloading. The trick is:
- Disconnect the road to the Wood Hardener **before** it is completed. The builder will find his way back to the Warehouse without a road.
- When you want the Lumberjack to change houses follow these steps:
1. Disconnect **both** of them.
2. Evict the Lumberjack.
3. Wait for the Lumberjack to enter the Warehouse.
4. Connect **only** the house you want him to go to.

Replay: [barb_poor_all_tools_replay.zip](https://github.com/widelands/widelands/files/4510401/barb_poor_all_tools_replay.zip)

**Comment by Niektory** [comment]
But I still agree with:

> best solution would be to give players control over their economy. (i.e. disconnecting a building from economy would delete the request for the worker which would delete the request for the tool)

**Comment by hessenfarmer** [comment]
@Niektory 
thanks for the hint however you need to know the mechanics under the hood to figure this out. 
@all 
From a players point of view it is neither intuitive nor is dismantling as you won't expect the felling ax get produced (as shown in the conversation in the forum). this would result in at least one or 2 frustrating failing attempts for barbarians, until you may figure out you need to dismantle the lumberjack. I believe this should not be the intent of this SC to frustrate players, cause the game is not doing what could reasonably be expected.  
My proposed solution would just cover/hide this behaviour like it is hidden for the empire as well.

**Comment by frankystone** [comment]
I agree with hessenfarmer. I never played this starting condition but i guess it is difficult at all for a normal player.

**Comment by Noordfrees** [comment]
That it's difficult is quite the point of a minimal starting condition…
How about leaving it as it is for b21, and if more people complain then "The new minimal starts are unbeatable" we can still change it for b22 then.

**Comment by hessenfarmer** [comment]
the reason for this proposal was that there was a complaint in the forum already. second argment was to have this consistent with the empire where the same situation as for barbarians arose with the quarry and stonemason. in empire you get away cause of the order of tools to be built. in barbarian you had to dismantle, cause nobody would figure out the solution by niektory without knowledge of the code. you still can make enough mistakes to fail I believe.

**Comment by frankystone** [comment]
> That it's difficult is quite the point of a minimal starting condition…

Yes, but it's not a reason to make artificial more difficult :-)

If the proposed solution does not have any effect on normal game play, lets have it i would say. Has to be testet anyway.
