### ISSUE TITLE
Build failure regression last night

### ISSUE THREAD

**Issue by spth** [widelands/widelands#3868]
Yesterday, at about 19:00 I build widelands from git, which worked fine for me.

Today, at about 13:00 I tried again (git pull, ./update.sh or ./compile.sh), it failed:
~~~~
FAILED: src/base/CMakeFiles/base_random.dir/random.cc.o 
/usr/bin/c++  -DUSE_XDG -DWL_USE_GLVND -I../src -Isrc -isystem /usr/include/x86_64-linux-gnu/SDL2 -g    -std=c++11 -fext-numeric-literals  -g -DDEBUG -fsanitize=address -fno-omit-frame-pointer -Wredundant-decls -Wall -Wpedantic -Wdeprecated-declarations -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winit-self -Winvalid-pch -Wlogical-op -Wmissing-include-dirs -Wno-undef -Wold-style-cast -Woverlength-strings -Wpacked -Wpointer-arith -Wsign-promo -Wsync-nand -Wtrampolines -Wundef -Wunused -Wunused-macros -Werror=format-security -Werror=return-type -Werror=shadow -Werror=uninitialized -MD -MT src/base/CMakeFiles/base_random.dir/random.cc.o -MF src/base/CMakeFiles/base_random.dir/random.cc.o.d -o src/base/CMakeFiles/base_random.dir/random.cc.o -c ../src/base/random.cc
In file included from ../src/io/streamwrite.h:27,
                 from ../src/base/random.cc:30:
../src/io/machdep.h:23:10: fatal error: SDL_endian.h: Datei oder Verzeichnis nicht gefunden
   23 | #include <SDL_endian.h>
~~~~

**Comment by Niektory** [comment]
a6d0c1050eaebf7c0445323ce2dd3c5aec888a09 must have broken it.

What is your operating system and SDL version? Could you post the whole build output (all messages)?

**Comment by spth** [comment]
I use current Debian GNU/Linux testing, which has SDL 1.2.12.

Full output of update.sh:
[log.txt](https://github.com/widelands/widelands/files/4510442/log.txt)

**Comment by Noordfrees** [comment]
SDL1 is outdated, Widelands requires SDL >= 2.0. Please upgrade and try again.

**Comment by Niektory** [comment]
That's my bad, I should've asked about SDL2. They're separate and can both be installed at the same time.

This is related to #3743 and #3783

**Comment by spth** [comment]
SDL2 is 2.0.10.

**Comment by Noordfrees** [comment]
Can you check where exactly the SDL2 headers are installed? Which files are present in `/usr/include/x86_64-linux-gnu/SDL2` or `/usr/include/SDL2`?

**Comment by Niektory** [comment]
Does this file list correspond to your system? https://packages.debian.org/bullseye/amd64/libsdl2-dev/filelist

**Comment by spth** [comment]
> Can you check where exactly the SDL2 headers are installed? Which files are present in `/usr/include/x86_64-linux-gnu/SDL2` or `/usr/include/SDL2`?

Nearly all are in `/usr/include/SDL2`. `/usr/include/x86_64-linux-gnu/SDL2` has only `_real_SDL_config.h`and  `SDL_platform.h`.

**Comment by spth** [comment]
> Does this file list correspond to your system? https://packages.debian.org/bullseye/amd64/libsdl2-dev/filelist

Yes.

**Comment by Noordfrees** [comment]
> > Can you check where exactly the SDL2 headers are installed? Which files are present in `/usr/include/x86_64-linux-gnu/SDL2` or `/usr/include/SDL2`?
>
> Nearly all are in `/usr/include/SDL2`. `/usr/include/x86_64-linux-gnu/SDL2` has only `_real_SDL_config.h`and `SDL_platform.h`.

Hm… CMake detects `/usr/include/x86_64-linux-gnu/SDL2` as your include dir so perhaps you could try deleting the build dir (`rm -r build`) and recompiling from scratch using CMake instead of compile.sh with `SDL2_INCLUDEDIR` = `/usr/include/SDL2` to CMake?

**Comment by Noordfrees** [comment]
Oh I just noticed that /usr/include/SDL2 is not even part of 
https://github.com/widelands/widelands/blob/master/cmake/Modules/FindSDL2.cmake
I guess adding this directory there should be enough?

**Comment by spth** [comment]
> Hm… CMake detects `/usr/include/x86_64-linux-gnu/SDL2` as your include dir so perhaps you could try deleting the build dir (`rm -r build`) and recompiling from scratch using CMake instead of compile.sh with `SDL2_INCLUDEDIR` = `/usr/include/SDL2` to CMake?

`SDL2_INCLUDEDIR=/usr/include/SDL2 cmake`worked for me.

**Comment by Niektory** [comment]
Could you please check if #3872 builds without problems (after deleting the `build` dir)?

**Comment by spth** [comment]
#3872 builds for me.

**Comment by Niektory** [comment]
That's good news. Thanks for testing.
