### ISSUE TITLE
Trainers are impatient

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3876]
After optimizing the fail cycle of all work programs which now fail before sleep. we fail very quickly in training while not supplied fully and constantly. leading to massive soldier traffic between HQ/warehouse and trainingsite. So trainers should be more patient (allow more fails) then in the past. So I propose to increase trainer patience by factor 2.

**Comment by tppq** [comment]
Build 21 or later?

**Comment by Noordfrees** [comment]
IMHO this is not critical so I'd say b22

**Comment by tppq** [comment]
Trainer patience select the amount of failed training before layoffs begin. They do not affect the rate.

**Comment by hessenfarmer** [comment]
@tppq 
correct. But the rate of how fast the training attempts fail has been increased by the fail before sleep change. In the past we tried a trainings step, we slept 20 or so and then we failed, then the next step. now we fail, try the next and after all failed we wait until 10 secs after the first fail and repeat. Trainer patience should take this into account imho. But I am ok with having it in b22.

**Comment by tppq** [comment]
>  But the rate of how fast the training attempts fail has been increased by the fail before sleep change.

That explains it. Thanks for telling.

**Comment by tppq** [comment]
@hessenfarmer , would you happen to have a pointer to the issue where the fail cycle optimization was done?

**Comment by hessenfarmer** [comment]
I think it was with 
https://github.com/widelands/widelands/commit/b2e84e87410a273e145039819a23012e02d2bf1c

**Comment by tppq** [comment]
Thanks. I should also check #1663 , might be related.
