### ISSUE TITLE
Unreachable port on Trident of Fire

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3878]
On the Trident of Fire map, a ship can find a port space, build a port there and not be able to reach it afterwards.

The problem is probably caused by the port space being reachable from two different disconnected bodies of water. So an expedition can find it from both sides, but wares can only be transported from one side afterwards.

This might be the same problem that happened in #1481 

**To Reproduce**
1. Load [this save](https://github.com/widelands/widelands/files/4534219/trident_of_fire_port_space.wgf.zip)
2. Build the port at the expedition ship's location.
3. Try to build something next to the port. Nothing will be transported from the base port.

**Expected behavior**
Wares should be transported between the two ports.
OR
The expedition should not find port space there if it can't reach it afterwards.

**Screenshots**
Base port on the bottom, new port on the top of the screenshot.
![shot0003](https://user-images.githubusercontent.com/4470900/80292115-e4ddd500-8753-11ea-9dcb-b0cb6e7cece0.png)

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: e78209ca80a823b75b1cb540c5c7fa96a521a045 (master); Build 20 affected too, as well as 5d8cc188412f433659cceb07a02781fd400bdeb3 (Noordfrees:shipping-tweaks-b21)

**Comment by Noordfrees** [comment]
Expedition ships keep a lookout for any port space in their vision field. The water fields where the portdock will be placed on are only looked for when the warehouse is completed. IMHO the cleanest solution would be to allow portdocks to be part of multiple fleets. edit: Or better that a warehouse can have multiple portdocks → then we'll need to allow users to choose in the UI in which ocean they want to start expeditions though
