### ISSUE TITLE
Shipwright builds ship outside work area

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3883]
The shipyard has a working radius of 6 according both to the work area display and the in-game help, but its shipwright is building a ship 7 fields from the shipyard.
![shot0000](https://user-images.githubusercontent.com/48293446/80500313-57c29800-896e-11ea-9cda-6a672327998c.png)
[shipwrightbug.wgf.zip](https://github.com/widelands/widelands/files/4546432/shipwrightbug.wgf.zip)

**Comment by frankystone** [comment]
See also #1076

**Comment by Noordfrees** [comment]
Here the shipwright is unable to start building a ship even though there's water nearby. Perhaps the working area radius is counted from the base flag rather than the building's main position?
![shot0000](https://user-images.githubusercontent.com/48293446/89054128-99415580-d358-11ea-845d-0dbffe33af55.png)

**Comment by gunchleoc** [comment]
> Perhaps the working area radius is counted from the base flag rather than the building's main position?

Yes it is https://github.com/widelands/widelands/blob/69ffe0b7e64d70756e73db1a538feb2e26b798f7/src/logic/map_objects/tribes/production_program.cc#L1293

**Comment by Noordfrees** [comment]
Thanks! I have opened a one-liner PR to fix this issue.
