### ISSUE TITLE
Singleplayer Launch Game menu does not cleanup

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3886]
The launch game menu does not cleanup after reentry.

**To Reproduce**
1. Enter Singleplayer -> New Game -> Choose a 8 Players map -> OK
2. Make some changes, e.g. Set you as fifth player, set you as team 3, disable players 1,2,3, and 6,7,8 so that you are second player
3. Click on Back 
4. now choose a two players map -> OK

Result:
Some of the settings made for the previous map are applied now, f.e. your team will be 3, you will be the second player.

'Resetting' the screen can only be done by going two times back, so start by clicking on 'Singleplayer'.

During testing i have managed to have a launch game screen where one players name is missing, don't know how.

**Expected behavior**
The launch game screen should be 'clean' whenever one had chosen a new map. That is it should be shown as this is the first time one entered this screen. 

**Version:**
 - OS: archlinux
 - Widelands Version: [44281e5]

**Comment by Noordfrees** [comment]
Might be fixed by #3847

**Comment by jmoerschbach** [comment]
yeah, I will make sure this is being fixed as I currently somewhat happen to rewrite the entire start single game ui in #3847 ...
