### ISSUE TITLE
Objective headings in tutorial not translated

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3900]
I found this at least in the seafaring tutorial:

![objectives](https://user-images.githubusercontent.com/6730556/81329939-9a3b5180-909f-11ea-839f-1153bb01f717.jpg)

I guess that the headings applied with `objective_text` has no underscore, e.g. [here, which corresponds to the screenshot](https://github.com/widelands/widelands/blob/8af3e6373a87a39aaf1c7ef9bcd12467896ea0a2/data/campaigns/tutorial03_seafaring.wmf/scripting/texts.lua#L253)

Start the seafaring tutorial with non english translation and play until you stumble over translation mismatched windows.

Didn't looked if the headings are translated in the po files.

**Comment by Noordfrees** [comment]
Confirmed. The strings don't show up on transifex. This forces us to break string freeze :(
