### ISSUE TITLE
Manually zipped files show up in load game screen

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3902]
Not really a bug, but sometimes annoying.

A manually zipped savegame shows up in Load Game screen as a normal savegame and shown twice (first and second row):

![zipped_savegames](https://user-images.githubusercontent.com/6730556/81376854-a4436b80-9104-11ea-80da-3170e7e5f22b.jpg)

If one adds additional content to the zipped file (e.g. console output as a text file), it will be shown as "Incompatible: NAME"

**Describe the solution you'd like**
It should be considered to hide files with extension '.zip' in the Load Game menu.

Downside: It is not possible to delete such files within the Load Game menu anymore then.

**Alternative**
As an alternative: Show all files with extension '.zip' as incompatible, although they aren't incompatible. Doing it this way there will be a clear distinction between manually zipped files and 'normal' savegames. It would then also be possible to delete such files within the load game screen.

**Comment by Noordfrees** [comment]
The campaign.conf also shows up as incompatible in the load screen. Ideally it should display only files with the .wgf extension.
