### ISSUE TITLE
segfault in choose a map

### ISSUE THREAD

**Issue by pabordel** [widelands/widelands#3914]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
when i try to sort the list of maps wideland crash

**To Reproduce**
1. Go to 'single player'
go to 'new game'

2. Click on 'map name' or 'Size' or 'Pl.'

4. See error :
This is Widelands Version bzr9309-202005200618 (Release)
Set home directory: /home/paj/.widelands
Set configuration file: /home/paj/.widelands/config
Adding directory: /usr/share/games/widelands/data
selected language: (system language)
using locale fr_FR.UTF-8
Byte order: little-endian
Graphics: Try to set Videomode 1680x1050
Graphics: OpenGL: Version "3.1 Mesa 19.0.8"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 0
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384
Graphics: OpenGL: ShadingLanguage: "1.40"
**** GRAPHICS REPORT ****
 VIDEO DRIVER x11
 pixel fmt 370546692
 size 1680 1050
**** END GRAPHICS REPORT ****
Style Manager: Reading style templates took 5ms
**** SOUND REPORT ****
SDL version: 2.0.8
SDL_mixer version: 2.0.2
**** END SOUND REPORT ****
Songset: Loaded song "music/intro.ogg"
Songset: Loaded song "music/menu.ogg"
┏━ Running Lua for world:
┃    Resources: 3ms
┃    Terrains: 6ms
┃    Immovables: 84ms
┃    Critters: 53ms
┗━ took: 147ms
Loading the world took 152ms
┏━ Running Lua for tribes:
┃    Ships: 188ms
┃    Wares: 38ms
┃    Immovables: 85ms
┃    Workers: 485ms
┃    Warehouses: 78ms
┃    Productionsites: 250ms
┃    Trainingsites: 50ms
┃    Militarysites: 84ms
┃    Partially finished buildings: 1ms
┃    Tribe infos: 44ms
┗━ took: 1305ms
Loading the tribes took 1305ms
atlanteans trainingsites: We have used up 40% on 1 sites, there are 1 without
atlanteans trainingsites: Assigning 60% to each of the remaining 1 sites
barbarians trainingsites: We have used up 25% on 1 sites, there are 1 without
barbarians trainingsites: Assigning 75% to each of the remaining 1 sites
empire trainingsites: We have used up 35% on 2 sites, there are 1 without
empire trainingsites: Assigning 65% to each of the remaining 1 sites
frisians trainingsites: We have used up 40% on 1 sites, there are 1 without
frisians trainingsites: Assigning 60% to each of the remaining 1 sites
Songset: Loaded song "music/ingame_07.ogg"
lastserial: 0
Songset: Loaded song "music/menu.ogg"
selected language: en
using locale en_US.utf-8
selected language: en
using locale en_US.utf-8
Songset: Loaded song "music/menu.ogg"
Erreur de segmentation

**Version:**
 - OS: mint 19.3 (ubuntu 18.04.3 + 64bits)
 - Widelands Version: bzr9309-202005200618 (Release)

**Comment by Noordfrees** [comment]
Probably a side effect of #3907 . Mea culpa, will fix…
