### ISSUE TITLE
Smugglers scenario desyncs

### ISSUE THREAD

**Issue by tppq** [widelands/widelands#3927]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Smugglers scenario crashes because of desync, soon after started.

**To Reproduce**
Start a network play (I did this via LAN), choose Smugglers scenario, wait for others to join, start.

**Expected behavior**
I expect to start playing (like placing buildings, roads etc on map)

**Version:**
 - OS: Debian buster
 - Widelands Version: 237b030f270b9a6f8a25b3d639cf48cc509051a5 (current master, May 30th 2020)

**Comment by Noordfrees** [comment]
I cannot reproduce, runs fine with four LAN clients using the same version. Can you provide the output and a replay?

**Comment by tppq** [comment]
I cannot reproduce this either anymore. Unsure what was wrong.
