### ISSUE TITLE
Improve "food infrastructure" objective in emp02.wmf scenario

### ISSUE THREAD

**Issue by pospec4444** [widelands/widelands#3930]
### No objective after food infrastructure objective

Player can get stuck waiting for next objective after building food infrastructure.

- Player is instructed to explore to east and build marble mine in mountains
- When the mine is built, next objective is assigned (build food infrastructure)
- When food infrastructure is built (at least one brewery _and_ at least one tavern OR inn _and_ at least one fishers/hunters house OR piggery OR bakery), the campaign scenario waits until player sees field `38, 33`. After that, "mine infrastructure" objective starts

**Problem:** Nothing motivates him to explore in that direction.
**Proposed solution:** Intermediate objective (e.g. "Explore to the south of marble mountains") which would trigger the "mine infrastructure" objective.
**Alternative:** Drop following code: https://github.com/widelands/widelands/blob/237b030f270b9a6f8a25b3d639cf48cc509051a5/data/campaigns/emp02.wmf/scripting/mission_thread.lua#L106-L108

### Possible deadlock: out of marble columns

Player is instructed to build various food facilities:

> Build a tavern to produce some food to sustain our miners.
> 
> - Of course this means you will need more resources for preparing this food – like fish, meat or bread.
> - To provide these foodstuffs, you can build a fisher’s house, a hunter’s house, a farm, a mill and a bakery.
> 
> Build a brewery and a winery to supply the miners with some good and strong drinks.
> 
> - Maybe you will also need a piggery, a vineyard and some wells.
> - It’s up to you what you want to build. But remember – coal and iron mines need beer, marble and gold mines need wine and all mines need at least rations, which are produced out of bread OR meat OR fish.

**Problem:** Player might try to build all types of buildings and run out of marble columns during the process. Multiple construction sites might get stuck waiting for marble columns.
**Proposed solution:** Allow player to build Stonemason's house.
**Alternative:** Increase initial stock of marble columns.

________________________________________________
**Version:**
 - OS: Debian GNU/Linux 10 (buster)
 - Widelands Version: r24619 (237b030@master)
________________________________________________

Let's discuss if this would be an improvement or not.

Save file: [An Outpost for Exile - deadlock.zip](https://github.com/widelands/widelands/files/4711108/An.Outpost.for.Exile.-.deadlock.zip)

**Comment by hessenfarmer** [comment]
I am in favor of the primary suggestions made. (intermediate objectives, allow stonemason after marblemine is built.)
Would you like to create a Pull request for this?

**Comment by pospec4444** [comment]
I can create a pull request when I'll have some spare time.
