### ISSUE TITLE
Ships don't have the same name in networkgaming

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3947]
**Describe the bug**
The ships of the same tribe are named different between participants of a multiplayer game. On my computer a ship was named `Aslaug` on the second participant's computer `Ullr`. 

**To Reproduce**
1. Start a multiplayer game on a map with seafaring
2. Build one ship.
3. Ship has different names on each participant's computer

**Expected behavior**
The ships should have the same names on all participants computers.

**Version:**
 - OS: macOS, Windows (I guess Linux as well)
 - Widelands Version: [918c7c7f392638870f952e268334776922588dba]

**Additional context**
The problem is especially severe when a game gets reloaded from a save game. A user might think s*he lost some ships.

**Comment by Noordfrees** [comment]
`Player::remaining_shipnames_` is declared as an `std::unordered_set<std::string>`. Changing this to `std::set` should be enough because string comparisons in sets and the index selection in `Player::pick_shipname()` are deterministic across platforms&compilers
