### ISSUE TITLE
Lua scripts cross-manipulate textdomains

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#3964]
In tutorial 3 (seafaring) there's a window where the translation is not shown, alerting the player that the second ship is ready and shipbuilding should be stopped. It corresponds to the function 'shipyard_production', which is the only function in tutorial03_seafaring.wmf/scripting/texts.lua.

**Comment by Noordfrees** [comment]
I cannot reproduce, all strings in this window are translated for me. Which version and which language are you using?

**Comment by frankystone** [comment]
Can't reproduce also.

Language: German
Version: [e5f5c91@master] (Debug)

**Comment by s-tdh** [comment]
I'm using Dutch on 8808716.
On second attempt, I couldn't reproduce either...  The only difference is that the first time, I was taking my time to review some translations.  Is it possible that there was some sort of race condition?  Or an incidence of cosmic radiation?  I'm pretty sure I saw that window in English.

**Comment by gunchleoc** [comment]
Pulling form Transifex was buggy and didn't fetch everything, so we're force pulling now. Maybe you got caught up in that.

**Comment by s-tdh** [comment]
The po-file was present and well (and complete), that was not the problem.  I tried it again, and now I got the English messages again.  I can prove I'm not going crazy:

![#3964](https://user-images.githubusercontent.com/67842810/86593744-51abf180-bf85-11ea-809d-ad13382d2edb.png)
[#3964.wgf.zip](https://github.com/widelands/widelands/files/4878901/3964.wgf.zip)

Saved game attached hoping that's useful - wait a minute and the message triggers.  What I did differently was sailing around the second small island first, where the port space is disabled.  I can't think of anything else that might have triggered the untranslated messages.  (I'm using a debug build, if that's of interest.)  Maybe this is hard to debug?  I remember previous bugs where texts in Lua didn't show their translations.

**Comment by hessenfarmer** [comment]
ok at least this can be confirmed for the savegame attached. 
I don't know how to reproduce though.

**Comment by Noordfrees** [comment]
My guess is that the game was started with a version where the translation for this string was missing, so this would be a special case of #3966

**Comment by hessenfarmer** [comment]
I don't think so as in my tests this message got translated in a new locale as it is implemented as function.

**Comment by s-tdh** [comment]
I tried a few more times.  Playing at 1× speed I often, though not always, trigger this issue.  At 5× speed I got it once, but apparently at higher speeds (5 or 10) it seldom triggers.
My last tests were with minimal effort (building the port and shipyard, clicking 'OK') while still triggering the bug, so sailing around the second island doesn't seem to be involved.

**Comment by Noordfrees** [comment]
I found the reason. The function that returns the message table is evaluated at runtime, so the strings are translated using whichever textdomain happens to be set at the time of evaluation.
If you open the encyclopedia, the help scripts will change the textdomain, so the game looks for the tutorial message in `widelands` or whatever is then set. The solution is that ALL scripts in `data/scripts` must ALWAYS reset the textdomain to the previous value after they have localized what strings they need to.
