### ISSUE TITLE
shipconstruction_frisians texture broken in Tribal Encyclopedia

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3968]
When looking at the Frisian "Ship Under Construction" entry in the Tribal Encyclopedia, the texture looks broken (see screenshot).

I tried the following fixes that did not work:

- Revert the texture to a state prior to running `optimize_pngs.py`
- Resave the texture with GIMP.

@Noordfrees Would you like to take a look? I'd like this fixed for Build 21 if possible.

![shipconstruction_frisians](https://user-images.githubusercontent.com/4095570/86898062-1d107500-c100-11ea-94af-391dd07709cb.png)

**Comment by Noordfrees** [comment]
??? 
This is how it looks for me:
![wl-shipcfri](https://user-images.githubusercontent.com/48293446/86967765-5cc07680-c16b-11ea-8a54-ca5224c098c4.png)
No idea what might be the cause…

**Comment by frankystone** [comment]
This is what it looks like for me as well. I guess this is caused by frisians shipconstruction images are  spritemaps, but the shipconstruction sites images of other tribes are not.

**Comment by Niektory** [comment]
I linked a fix. If you want a workaround for build 21 without C++ changes, set `representative_frame = 0` in `data/tribes/immovables/shipconstruction_frisians/init.lua`.
