### ISSUE TITLE
CTRL click behavior for enhancing/dismantling a building

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3981]
When using CTRL click for enhancing or destroying a building, all wares in buildings stock are lost.

Change this so that 'preserve wares' is default when using CTRL click.

See discussion round about [this post](https://www.widelands.org/forum/post/33669/). At least for me this post is the most important argument to change this:

> Ctrl normally just skips the "are you sure" dialog in building interaction. so as the default settin in this dialog is preserve wares I would have expected that the result is the same as just clicking ok without any modification.
> So the current behaviour is not what I have expected due to long time experience in the game.
> 
> By this I strongly support to change this to keep the wares if ctrl + enhance or ctrl + dismantle is pressed.

**Version:**
 - OS: all
 - Widelands Version: build 21

**Comment by gunchleoc** [comment]
+1

**Comment by matthiakl** [comment]
Instead of hardcoding the behavior, why not add an option to the game options tab to select, whether wares should be preserved on Ctrl+click? Then everyone can adapt it to his own playstyle.

**Comment by frankystone** [comment]
I would like to have this in v1.0. In a recent game i just lost some wares because i was used to use STRG click when dismantling to skip the confirmation dialogue.

Counting the votes there are three for a change and one against...
