### ISSUE TITLE
Campaign scenario selection screen text overlaps at 800x600 resolution

### ISSUE THREAD

**Issue by scx** [widelands/widelands#3985]
## Describe the bug

UI is barely tested when it comes to window mode and low resolution (800x600). E.g. text does not fit in the box.
It applies mainly to the scenario description. Difficulty selector is affected as well.

### Bug 1

1. Run **Widelands** in window mode (800x600)
2. Select `Single Player`
3. Select `Campaigns`
4. Select `Empire`

### Bug 2

1. Run **Widelands** in window mode (800x600)
2. Select `Single Player`
3. Select `Campaigns`
4. Select `Frisians`
5. Select `Difficulty`

## Actual behavior

![widelands-21-rc1-window-scenario](https://user-images.githubusercontent.com/510369/87438218-8e17c700-c5ef-11ea-9ffa-f00502773c98.png)

![widelands-21-rc1-window-scenario-difficulty](https://user-images.githubusercontent.com/510369/87438608-0c746900-c5f0-11ea-90d6-b54a1248f3bc.png)

## Expected behavior
There should be a scroll bar, like in the `campaign` screen.

![widelands-21-rc1-window-campaign](https://user-images.githubusercontent.com/510369/87438244-96700200-c5ef-11ea-8e35-51fba0d0694c.png)

## Version:
 - OS: EL7
 - Widelands Version: `Build 21~rc1`, flatpak

## Additional context

`Build 20` is not affected, but only because descriptions are shorter there. There is also no difficulty selector.

**Comment by gunchleoc** [comment]
The bug is that `scenario_difficulty_header_`and `scenario_difficulty_`belong in `ScenarioDetails`, not in `FullscreenMenuScenarioSelect`, so they are not included in the correct `UI::Box`.

**Comment by hessenfarmer** [comment]
Would it be reasonable to use some of the Space above, as it seems we are using one third just for the Headline

**Comment by scx** [comment]
The first issue is that `scenario_details_` doesn't take into account `scenario_difficulty_` and `scenario_difficulty_header_`, which were added in `Build 21`.

https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/scenario_select.cc#L157-L166

It should be pretty easy to fix ([widelands-build21-scenario-select.patch.txt](https://github.com/widelands/widelands/files/5013661/widelands-build21-scenario-select.patch.txt)):
```
diff --git a/src/ui_fsmenu/scenario_select.cc b/src/ui_fsmenu/scenario_select.cc
index af2ded6..7889012 100644
--- a/src/ui_fsmenu/scenario_select.cc
+++ b/src/ui_fsmenu/scenario_select.cc
@@ -154,7 +154,9 @@ void FullscreenMenuScenarioSelect::layout() {
 	header_box_.set_size(get_w(), tabley_);
 	table_.set_size(tablew_, tableh_);
 	table_.set_pos(Vector2i(tablex_, tabley_));
-	scenario_details_.set_size(get_right_column_w(right_column_x_), tableh_ - buth_ - 4 * padding_);
+	scenario_details_.set_size(get_right_column_w(right_column_x_), tableh_ - buth_ - 6 * padding_ - scenario_difficulty_.get_h() - scenario_difficulty_header_.get_h());
+	scenario_details_.set_desired_size(
+	   get_right_column_w(right_column_x_), tableh_ - buth_ - 6 * padding_ - scenario_difficulty_.get_h() - scenario_difficulty_header_.get_h());
 	scenario_details_.set_pos(Vector2i(right_column_x_, tabley_));
 	scenario_difficulty_.set_size(get_right_column_w(right_column_x_), scenario_difficulty_.get_h());
 	scenario_difficulty_.set_pos(
```
[Link](https://pastebin.com/raw/10vkxiDy)

Before:
![widelands_build21_scenario_select_before](https://user-images.githubusercontent.com/510369/89142657-547c1100-d548-11ea-9d44-a9bdd1b58b3b.png)

After:
![widelands_build21_scenario_select_after](https://user-images.githubusercontent.com/510369/89142668-5ba31f00-d548-11ea-8543-ed1b96f722cb.png)

The second problem is much more complicated. The point is, the drop-down list may be placed too close to the bottom. Please note that this depends on the screen resolution/window size.

We can move everything up a bit, just like @hessenfarmer  suggested.
https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/load_map_or_game.cc#L40
It have to be more than 11 for sure, but it could be less than 17. I think 14 would be a good value.

https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/load_map_or_game.cc#L42
Alternatively, we can change the table height to about 5500/10000 of the window height.

We can also consider taking the height of the expanded list into account when positioning it, but that is going to be damn hard to do with the current layout. We would have to take into account the maximum number of elements there, and the distance between the box and the bottom of the window.

**Comment by scx** [comment]
## Patches

### Patch 1

[widelands-build21-scenario-select.patch.txt](https://github.com/widelands/widelands/files/5014113/widelands-build21-scenario-select.patch.txt)
```
diff --git a/src/ui_fsmenu/scenario_select.cc b/src/ui_fsmenu/scenario_select.cc
index af2ded6..7889012 100644
--- a/src/ui_fsmenu/scenario_select.cc
+++ b/src/ui_fsmenu/scenario_select.cc
@@ -154,7 +154,9 @@ void FullscreenMenuScenarioSelect::layout() {
 	header_box_.set_size(get_w(), tabley_);
 	table_.set_size(tablew_, tableh_);
 	table_.set_pos(Vector2i(tablex_, tabley_));
-	scenario_details_.set_size(get_right_column_w(right_column_x_), tableh_ - buth_ - 4 * padding_);
+	scenario_details_.set_size(get_right_column_w(right_column_x_), tableh_ - buth_ - 6 * padding_ - scenario_difficulty_.get_h() - scenario_difficulty_header_.get_h());
+	scenario_details_.set_desired_size(
+	   get_right_column_w(right_column_x_), tableh_ - buth_ - 6 * padding_ - scenario_difficulty_.get_h() - scenario_difficulty_header_.get_h());
 	scenario_details_.set_pos(Vector2i(right_column_x_, tabley_));
 	scenario_difficulty_.set_size(get_right_column_w(right_column_x_), scenario_difficulty_.get_h());
 	scenario_difficulty_.set_pos(
```

[Link](https://pastebin.com/raw/6NAixqxh)

### Patch 2

[widelands-build21-scenario-select-difficulty.patch.txt](https://github.com/widelands/widelands/files/5014114/widelands-build21-scenario-select-difficulty.patch.txt)
```
diff --git a/src/ui_fsmenu/load_map_or_game.cc b/src/ui_fsmenu/load_map_or_game.cc
index 0dca298..e3922d5 100644
--- a/src/ui_fsmenu/load_map_or_game.cc
+++ b/src/ui_fsmenu/load_map_or_game.cc
@@ -37,11 +37,11 @@ FullscreenMenuLoadMapOrGame::FullscreenMenuLoadMapOrGame()
 void FullscreenMenuLoadMapOrGame::layout() {
 	// UI coordinates and spacers
 	tablex_ = get_w() * 47 / 2500;
-	tabley_ = get_h() * 17 / 50;
+	tabley_ = get_h() * 14 / 50;
 	tablew_ = get_w() * 711 / 1250;
 	tableh_ = get_h() * 6083 / 10000;
 	right_column_x_ = tablex_ + tablew_ + right_column_margin_;
-	buty_ = get_h() * 9 / 10;
+	buty_ = get_h() * 84 / 100;
 	butw_ = (get_w() - right_column_x_ - right_column_margin_) / 2 - padding_;
 	buth_ = get_h() * 9 / 200;
 	right_column_tab_ = get_w() - right_column_margin_ - butw_;
```

[Link](https://pastebin.com/raw/fJcRNR9c)

## Not expanded

### Before
![widelands_build21_scenario_select_before](https://user-images.githubusercontent.com/510369/89149352-8a2af500-d55c-11ea-8f5f-c6aeb4149890.png)

### After
![widelands_build21_scenario_select_after](https://user-images.githubusercontent.com/510369/89149363-8f883f80-d55c-11ea-92dc-9fab20be1413.png)


## Expanded

### Before

![widelands_build21_scenario_select_before_expanded](https://user-images.githubusercontent.com/510369/89149385-9d3dc500-d55c-11ea-859d-599738680930.png)

### After

![widelands_build21_scenario_select_after_expanded](https://user-images.githubusercontent.com/510369/89149394-a333a600-d55c-11ea-81fa-8ef855d151c2.png)
