### ISSUE TITLE
Keyboard speed control is too difficult on some Laptop keyboards

### ISSUE THREAD

**Issue by scx** [widelands/widelands#3986]
## Describe the bug
Speed control is some kind of broken. `Page Up` and `Page Down` doesn't work as expected when you use numeric keypad.

## To Reproduce

1. Run any scenario
2. Use `Page Up`/`Page Down` on your numeric keypad when `Num Lock` is off.

## Expected behavior

According to UI, it should speed up/down the game.

## Actual behavior

`Home`, `End`, `Page Up` and `Page Down` on numeric keypad are used to navigate the map.

## Version:

 - OS: `EL7`
 - Widelands Version: `Build 21~rc1`, `flatpak`

## Additional context

It is hard to say if this is a bug or not. The problem is the ambiguity of UI description.
Anyway, this can be problematic on notebooks that don't have normal navigation keys (e.g. Lenovo Legion, ASUS ROG, etc). They provide a numeric keypad instead.

![asus-rog](https://www.any-pc-part.com/images/products/APPKRASGL504CBLACK.jpg)

**Comment by gunchleoc** [comment]
The only way to fix this is to remove map navigation via the number pad, and then we can expect somebody else to not like that.

This is an issue where these is no one-size-fits-all solution, we could

1. Add an option, or
2. Improve the encyclopedia texts and/or teach it in Tutorial 1

**Comment by scx** [comment]
> The only way to fix this is to remove map navigation via the number pad, and then we can expect somebody else to not like that.

You can always use 4 arrow keys to navigate (both standard navigation keys and these on numeric keypad).

> This is an issue where these is no one-size-fits-all solution, we could
> 
> 1. Add an option, or
> 2. Improve the encyclopedia texts and/or teach it in Tutorial 1

Personally, I'd prefer the first solution.

**Comment by Noordfrees** [comment]
Personally I'd also prefer to use Numpad-3/9 for controlling the game speed. +1 for an option

**Comment by Noordfrees** [comment]
Alternatively, our old wishlist item of configurable hotkeys would also solve this issue

**Comment by scx** [comment]
> Alternatively, our old wishlist item of configurable hotkeys would also solve this issue

I started working on solving this problem. We can slightly modify this code:
https://github.com/widelands/widelands/blob/build21/src/wui/quicknavigation.cc#L72-L84

I would like to add an option in `Options` under the `Game` tab.
https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/options.cc#L225
I would call it "_Use NumPad only for navigation_" or something like that.

We could add `numpad_quicknavigation` in config variables.
https://github.com/widelands/widelands/blob/build21/src/wlapplication.cc#L825
It should be disabled by default.

We probably should use a checkbox control (`UI::Checkbox`).
https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/options.h#L158
https://github.com/widelands/widelands/blob/build21/src/ui_fsmenu/options.cc#L657

Alternatively, we can use a drop down list (`UI::Dropdown<>`) with 3 options: _None_ (quick navigation is completely disable), _Basic_ (we use 2, 4, 5, 6, 8 keys for quick navigation) and _Full_ (we use all NumPad keys for quick navigation, including 1, 3, 7 and 9).

Anyway, I think this might be a pretty good temporary solution until we introduce key mapping.

**Comment by scx** [comment]
Temporary patch: [widelands-build21-numpad-quicknavigation.patch.txt](https://github.com/widelands/widelands/files/5012258/widelands-build21-numpad-quicknavigation.patch.txt)

```
diff --git a/src/ui_fsmenu/options.cc b/src/ui_fsmenu/options.cc
index 79bfaa6..0a94aae 100644
--- a/src/ui_fsmenu/options.cc
+++ b/src/ui_fsmenu/options.cc
@@ -223,6 +223,7 @@ FullscreenMenuOptions::FullscreenMenuOptions(OptionsCtrl::OptionsStruct opt)
      /** TRANSLATORS: This refers to to zooming with the scrollwheel.*/
      ctrl_zoom_(&box_game_, Vector2i::zero(), _("Zoom only when Ctrl is pressed")),
      game_clock_(&box_game_, Vector2i::zero(), _("Display game time in the top left corner")),
+     numpad_quicknavigation_(&box_game_, Vector2i::zero(), _("Use NumPad only for quick navigation")),
      os_(opt) {
 
 	// Buttons
@@ -276,6 +277,7 @@ FullscreenMenuOptions::FullscreenMenuOptions(OptionsCtrl::OptionsStruct opt)
 	box_game_.add(&single_watchwin_);
 	box_game_.add(&ctrl_zoom_);
 	box_game_.add(&game_clock_);
+	box_game_.add(&numpad_quicknavigation_);
 
 	// Bind actions
 	language_dropdown_.selected.connect([this]() { update_language_stats(false); });
@@ -342,6 +344,7 @@ FullscreenMenuOptions::FullscreenMenuOptions(OptionsCtrl::OptionsStruct opt)
 	single_watchwin_.set_state(opt.single_watchwin);
 	ctrl_zoom_.set_state(opt.ctrl_zoom);
 	game_clock_.set_state(opt.game_clock);
+	numpad_quicknavigation_.set_state(opt.numpad_quicknavigation);
 
 	// Language options
 	add_languages_to_list(opt.language);
@@ -417,6 +420,7 @@ void FullscreenMenuOptions::layout() {
 	single_watchwin_.set_desired_size(tab_panel_width, single_watchwin_.get_h());
 	ctrl_zoom_.set_desired_size(tab_panel_width, ctrl_zoom_.get_h());
 	game_clock_.set_desired_size(tab_panel_width, game_clock_.get_h());
+	numpad_quicknavigation_.set_desired_size(tab_panel_width, numpad_quicknavigation_.get_h());
 }
 
 void FullscreenMenuOptions::add_languages_to_list(const std::string& current_locale) {
@@ -596,6 +600,7 @@ OptionsCtrl::OptionsStruct FullscreenMenuOptions::get_values() {
 	os_.single_watchwin = single_watchwin_.get_state();
 	os_.ctrl_zoom = ctrl_zoom_.get_state();
 	os_.game_clock = game_clock_.get_state();
+	os_.numpad_quicknavigation = numpad_quicknavigation_.get_state();
 
 	// Last tab for reloading the options menu
 	os_.active_tab = tabs_.active();
@@ -655,6 +660,7 @@ OptionsCtrl::OptionsStruct OptionsCtrl::options_struct(uint32_t active_tab) {
 	opt.single_watchwin = opt_section_.get_bool("single_watchwin", false);
 	opt.ctrl_zoom = opt_section_.get_bool("ctrl_zoom", false);
 	opt.game_clock = opt_section_.get_bool("game_clock", true);
+	opt.numpad_quicknavigation = opt_section_.get_bool("numpad_quicknavigation", false);
 
 	// Language options
 	opt.language = opt_section_.get_string("language", "");
@@ -694,6 +700,7 @@ void OptionsCtrl::save_options() {
 	opt_section_.set_bool("single_watchwin", opt.single_watchwin);
 	opt_section_.set_bool("ctrl_zoom", opt.ctrl_zoom);
 	opt_section_.set_bool("game_clock", opt.game_clock);
+	opt_section_.set_bool("numpad_quicknavigation", opt.numpad_quicknavigation);
 
 	// Language options
 	opt_section_.set_string("language", opt.language);
diff --git a/src/ui_fsmenu/options.h b/src/ui_fsmenu/options.h
index 9be5e46..2d88c9f 100644
--- a/src/ui_fsmenu/options.h
+++ b/src/ui_fsmenu/options.h
@@ -67,6 +67,7 @@ public:
 		bool single_watchwin;
 		bool ctrl_zoom;
 		bool game_clock;
+		bool numpad_quicknavigation;
 
 		// Language options
 		std::string language;
@@ -156,6 +157,7 @@ private:
 	UI::Checkbox single_watchwin_;
 	UI::Checkbox ctrl_zoom_;
 	UI::Checkbox game_clock_;
+	UI::Checkbox numpad_quicknavigation_;
 
 	OptionsCtrl::OptionsStruct os_;
 
diff --git a/src/wlapplication.cc b/src/wlapplication.cc
index a1f4d33..19bf9d8 100644
--- a/src/wlapplication.cc
+++ b/src/wlapplication.cc
@@ -825,6 +825,7 @@ bool WLApplication::init_settings() {
 	get_config_bool("single_watchwin", false);
 	get_config_bool("ctrl_zoom", false);
 	get_config_bool("game_clock", true);
+	get_config_bool("numpad_quicknavigation", false);
 	get_config_bool("inputgrab", false);
 	get_config_bool("transparent_chat", false);
 	// Undocumented. Unique ID used to allow the metaserver to recognize players
diff --git a/src/wui/interactive_gamebase.cc b/src/wui/interactive_gamebase.cc
index db79c7a..2324750 100644
--- a/src/wui/interactive_gamebase.cc
+++ b/src/wui/interactive_gamebase.cc
@@ -32,6 +32,7 @@
 #include "logic/map_objects/tribes/ship.h"
 #include "logic/player.h"
 #include "network/gamehost.h"
+#include "wlapplication_options.h"
 #include "wui/constructionsitewindow.h"
 #include "wui/dismantlesitewindow.h"
 #include "wui/game_chat_menu.h"
@@ -375,10 +376,15 @@ bool InteractiveGameBase::handle_key(bool down, SDL_Keysym code) {
 	if (InteractiveBase::handle_key(down, code)) {
 		return true;
 	}
+	const bool numpad_quicknavigation = get_config_bool("numpad_quicknavigation", false);
 
 	if (down) {
 		switch (code.sym) {
+		case SDLK_KP_9:
 		case SDLK_PAGEUP:
+			if (code.sym == SDLK_KP_9 && ((code.mod & KMOD_NUM) || numpad_quicknavigation)) {
+				break;
+			}
 			increase_gamespeed(
 			   code.mod & KMOD_SHIFT ? kSpeedSlow : code.mod & KMOD_CTRL ? kSpeedFast : kSpeedDefault);
 			return true;
@@ -389,7 +395,11 @@ bool InteractiveGameBase::handle_key(bool down, SDL_Keysym code) {
 				toggle_game_paused();
 			}
 			return true;
+		case SDLK_KP_3:
 		case SDLK_PAGEDOWN:
+			if (code.sym == SDLK_KP_3 && ((code.mod & KMOD_NUM) || numpad_quicknavigation)) {
+				break;
+			}
 			decrease_gamespeed(
 			   code.mod & KMOD_SHIFT ? kSpeedSlow : code.mod & KMOD_CTRL ? kSpeedFast : kSpeedDefault);
 			return true;
diff --git a/src/wui/mapview.cc b/src/wui/mapview.cc
index 131a3b6..1e5d39c 100644
--- a/src/wui/mapview.cc
+++ b/src/wui/mapview.cc
@@ -598,6 +598,7 @@ Widelands::NodeAndTriangle<> MapView::track_sel(const Vector2i& p) {
 }
 
 bool MapView::scroll_map() {
+	const bool numpad_quicknavigation = get_config_bool("numpad_quicknavigation", false);
 	// arrow keys
 	const bool kUP = get_key_state(SDL_SCANCODE_UP);
 	const bool kDOWN = get_key_state(SDL_SCANCODE_DOWN);
@@ -610,25 +611,25 @@ bool MapView::scroll_map() {
 	kNP(1) kNP(2) kNP(3) kNP(4) kNP(6) kNP(7) kNP(8) kNP(9)
 #undef kNP
 
-	   // set the scrolling distance
-	   const uint8_t denominator =
-	      ((SDL_GetModState() & KMOD_CTRL) ? 4 : (SDL_GetModState() & KMOD_SHIFT) ? 16 : 8);
+	// set the scrolling distance
+	const uint8_t denominator =
+		((SDL_GetModState() & KMOD_CTRL) ? 4 : (SDL_GetModState() & KMOD_SHIFT) ? 16 : 8);
 	const uint16_t scroll_distance_y = g_gr->get_yres() / denominator;
 	const uint16_t scroll_distance_x = g_gr->get_xres() / denominator;
 	int32_t distance_to_scroll_x = 0;
 	int32_t distance_to_scroll_y = 0;
 
 	// check the directions
-	if (kUP || kNP7 || kNP8 || kNP9) {
+	if (kUP || kNP8 || (numpad_quicknavigation && (kNP7 || kNP9))) {
 		distance_to_scroll_y -= scroll_distance_y;
 	}
-	if (kDOWN || kNP1 || kNP2 || kNP3) {
+	if (kDOWN || kNP2 || (numpad_quicknavigation && (kNP1 || kNP3))) {
 		distance_to_scroll_y += scroll_distance_y;
 	}
-	if (kLEFT || kNP1 || kNP4 || kNP7) {
+	if (kLEFT ||  kNP4 || (numpad_quicknavigation && (kNP1 || kNP7))) {
 		distance_to_scroll_x -= scroll_distance_x;
 	}
-	if (kRIGHT || kNP3 || kNP6 || kNP9) {
+	if (kRIGHT || kNP6 || (numpad_quicknavigation && (kNP3 || kNP9))) {
 		distance_to_scroll_x += scroll_distance_x;
 	}
 
```

[Link](https://pastebin.com/raw/8yqeq6Zd)

**Comment by scx** [comment]
@stonerl @gunchleoc @Noordfrees 
Do you have any idea how to name this feature?

Disabled:
- Use `SDLK_KP_2`, `SDLK_KP_4`, `SDLK_KP_5`, `SDLK_KP_6`, `SDLK_KP_8` for quick navigation
- Use `SDLK_KP_3` and `SDLK_KP_9` for speed down/up game

Enabled:
- Use `SDLK_KP_1`, `SDLK_KP_2`, `SDLK_KP_3`, `SDLK_KP_4`, `SDLK_KP_5`, `SDLK_KP_6`,  `SDLK_KP_7`, `SDLK_KP_8`,  `SDLK_KP_9` for quick navigation

Temporary description:
_Use NumPad only for quick navigation_

**Comment by scx** [comment]
What about this one?: _Use NumPad for directional navigation only_

**Comment by Noordfrees** [comment]
We should keep the terminology consistent. We use the term *quick navigation* only for jumping with `Strg+1.9`/`1-9` and ','/'.'. The use of Numpad-2/4/6/8 is termed *scrolling*. So IMHO we should call the option something like "Allow diagonal scrolling with the numeric keypad"

**Comment by gunchleoc** [comment]
Check the first tutorial and use what it's called there.

**Comment by scx** [comment]
> We should keep the terminology consistent. We use the term _quick navigation_ only for jumping with `Strg+1.9`/`1-9` and ','/'.'. The use of Numpad-2/4/6/8 is termed _scrolling_.

Sorry about that. I am not familiar with the Widelands terminology.

> So IMHO we should call the option something like "Allow diagonal scrolling with the numeric keypad"

I am ok this this. What about the variable name?
- `numpad_diagonalscrolling`
- `scrolling_diagonal`
- something else

**Comment by gunchleoc** [comment]
`numpad_diagonalscrolling` sounds good to me.

**Comment by scx** [comment]
![widelands_build21_numpad_diagonalscrolling](https://user-images.githubusercontent.com/510369/89127099-4c41b880-d4eb-11ea-9216-626320e43a39.png)
PR on the way.
