### ISSUE TITLE
Extract information from MapObjectProgam

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3989]
Extract available information from Worker, Immovable and Productionsite programs to

* Simplify the Lua API
* Automate some AI hints
* Enhance the Encyclopedia

Branches:

- [x]  Deduce building outputs from worker and productionsite programs and remove `outputs` table https://github.com/gunchleoc/widelands/tree/parse-production-outputs PR: https://github.com/widelands/widelands/pull/3983

- [x]  Deduce whether a building collects a ware from map https://github.com/widelands/widelands/pull/4618
- [x]  Deduce AI mining hints https://github.com/widelands/widelands/pull/4489
- [x]  Deduce which resources/bobs/immovables are collected from/placed on the map https://github.com/widelands/widelands/pull/4618

**Comment by frankystone** [comment]
Maybe related: #3956

**Comment by hessenfarmer** [comment]
closing this as all Tasks mentioned above have been implemented.
resetted the version impelemented to v1.0
