### ISSUE TITLE
emp02: mission completion text inside Lutius' quotes

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#3996]
In the second Empire campaign scenario, the last message about returning to Fremil: "You have completed this mission. ..." is inside Lutius' quotes.

I have a small patch that fixes this.  Should I attach it or do you want a pull request?

**Comment by hessenfarmer** [comment]
Well this mesage is in Lutius diary in every empire mission so if we change this we shoud change it consistently

**Comment by gunchleoc** [comment]
Branch + pull request would be easiest for us, if you can take the time. Thanks!

**Comment by hessenfarmer** [comment]
After a second look I got the issue with this.
Fixed it.
thanks for reporting
