### ISSUE TITLE
Dolomites description, missing article

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#4015]
After the recent string fixes commit, I noticed the hint of the map 'Dolomites' is missing an article:

"There is **a** lot of flat ground on the mountains..."

This single letter would be a valuable contribution to Widelands and is totally proportionate with the length of this bug report. :) (I also doubt the 'on' is correct, but I don't know what would be good.)

**Comment by gunchleoc** [comment]
How about "The mountains have an abundance of flat ground"

**Comment by s-tdh** [comment]
I'm no native English speaker, but that does sound better.

Also, I really like the joke that this flat ground is vertical - it _is_ true in the real Dolomites.
