### ISSUE TITLE
Upgrade button for foreign captured building

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#4019]
Playing emp04 on today's master branch (1.0~git57[7173bf0@master]).  I captured a Barbarian fortress and I noticed it had an 'upgrade' button, like this:
![upgrade_foreign_military_site](https://user-images.githubusercontent.com/67842810/88466528-dfac3580-cebc-11ea-9fc7-c996a8ede609.png)
Being curious, I clicked it, then the game crashed with an assertion error:
`widelands: ../src/logic/game.cc:781: void Widelands::Game::send_player_enhance_building(Widelands::Building&, Widelands::DescriptionIndex, bool): Controletest 'building.descr().type() == MapObjectType::CONSTRUCTIONSITE || building.owner().tribe().has_building(id)' faalt.
Aborted
`

I could only reproduce this by playing this scenario again from the start without loading.  At the moment of the screenshot I saved the game and loaded again, but the button was gone.  As an experiment, I also tried a new game where I gave my Barbarian adversary a fortress (trough the Lua console) close to my border, but upon conquering it it did not produce an upgrade button.  I even tried giving my foe a warehouse and a fortress construction site (played as Empire in spot 1 against Barbarian on The Pass Through the Mountains, loaded this: [milconstr.lua.txt](https://github.com/widelands/widelands/files/4976643/milconstr.lua.txt)), but to no avail.  This seems to be an annoying little bug to reproduce...

**Comment by Noordfrees** [comment]
The only check whether a player can actually enhance an enhancable building is done in `wui/buildingwindow.cc:250` (`if (owner.is_building_type_allowed(enhancement)) {`). Apparently the scenario's messing around with setting allowed building types breaks it. Adding a check for `owner.tribe().has_building(enhancement)` should probably be enough

**Comment by hessenfarmer** [comment]
I don't understand what is meant with messing around of allowed building types. 
I always assumed allow_buildings all should only allow the buildings of the tribe. 
if this is not the case it will affect almost any of the scenarios

**Comment by Noordfrees** [comment]
Checked the code – allowing buildings works on buildings the tribe has *and on all militarysites* – otherwise enemy milsites couldn't be conquered. That's why `allow_buildings("all")` will also allow barbarian citadels for empire. So the check for `has_building()` when creating the enhance button will be enough.

**Comment by hessenfarmer** [comment]
Ok well done and well spotted. Never realized that.

Thanks for fixing
