### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#4020]
I can't imagine this not being known, but I can't find any bug reporting this:
There are a number of strings that are not translated/translatable:
- Ship names
- Custom buildings in campaigns (Vesta's temple in emp04, Imperial warehouse in fri02 - interestingly the broken forester etc. in emp04 are translated).

**Comment by klaus-halfmann** [comment]
Thanks @s-tdh for finding this and all the other "small" things. Fact is that playtesting is a boring task and checking all translations even more dull. So such errors are only notices by +/- new developers/testers using a foreign language. I must admit I did it in once for relase 20 and after 3 days I gave up. Perhaps we should add a hint "Howto report bugs" in every tutorial, so we get more reports like your one.

Keep on poking us with all the "small" things we should fix, so we can improve this game.

**Comment by hessenfarmer** [comment]
That is indeed not a "small" or trivial one. Custom buildings are translated if they have the same name as the original building, cause they use the translated string of the original Building (emp04 foresters, farms, mills, etc. ) if the strings are altered they are not translated because they don't belong to any textdomain.

**Comment by Noordfrees** [comment]
It would be enough to add `'../../data/campaigns/%(name)s/scripting/*/*.lua',` to `buildcat.py:114` and to set the scenario's textdomain in each of the buildings' `init.lua`s

**Comment by hessenfarmer** [comment]
ok I'll try that and provide a PR.

**Comment by hessenfarmer** [comment]
@Noordfrees 
Would it make sense if you could incorporte this in the stack textdomains branch

**Comment by gunchleoc** [comment]
For the shipnames, I have a branch on that that I never proposed for review: https://github.com/gunchleoc/widelands/tree/localizeable-shipnames

**Comment by Noordfrees** [comment]
Is this branch functional, or what's the reason why you didn't propose it?

Localizing shipnames would make #3947 a tiny bit harder to fix. These two should probably be fixed in one branch IMHO.

**Comment by gunchleoc** [comment]
The reason I didn't propose it is that I have too many branches that I can't get through code review, so I have to prioritize.
