### ISSUE TITLE
Incompatible Scenarios

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4026]
Several of our scenarios are no longer compatible since #3980: 

```
 Reading Map Objects ... WidelandsMapLoader::load_map_complete() for 'A Place to Call Home' took 46ms
Fatal exception: map objects: 

UnhandledVersionError: Deeses Speel is mit eener ollen Versioon vun Widelands sekert worden un kann nich mehr laden, of dat is eene neje Versioon, wat Widelands noch nich mit klaarword.

Packet Name: MapObjectPacket
Saved Version: 1
Current Version: 2
FATAL ERROR - game crashed. Attempting emergency save.
lastserial: 0
```

We need to either reinstate the MapObjectPacket compatibility code, or go through **all** maps and resave them with build21 if necessary.

@gunchleoc

**Comment by hessenfarmer** [comment]
does this affect maps from the homepage as well?

**Comment by Noordfrees** [comment]
Yes, it does. So we have just broken map compatibility – the support for older MapObject package versions has to be reinstated and must stick around for ever and ever.

**Comment by gunchleoc** [comment]
Yep, looks like I ripped out too much. We need to:

* Add packet version check to:
  * Ship::Loader::load(FileRead& fr, uint8_t /* packet_version */)
  * MapObject::Loader* Worker::load
* Allow the old version number in src/map_io/map_object_packet.cc
