### ISSUE TITLE
No Smelter is available but Smelting Works got occupied

### ISSUE THREAD

**Issue by pospec4444** [widelands/widelands#4043]
There was no smelter available, but smelting works got occupied anyway. Smelter came from Headquarters (he _wasn't_ reported there).

**Steps to reproduce the behavior**
(Note: I was testing emp02 scenario and randomly noticed it.)
1. Add `empire_smelting_works` to `p1:allow_buildings` in https://github.com/widelands/widelands/blob/b9b7dd7d30079e506e6f6b6da5b046610918f5e3/data/campaigns/emp02.wmf/scripting/starting_conditions.lua#L5-L10
2. Compile and run `$ ./widelands --scenario=campaigns/emp02.wmf`
3. Check number of your Smelters (should be 0)
4. Build Smelting Works, Smelter comes out of nothing

**Expected behavior**
Smelting Works report "Worker is missing"

**Screenshots**
![image](https://user-images.githubusercontent.com/2467395/89066730-3a86d680-d36e-11ea-8fb0-b088db8b01e5.png)
![image](https://user-images.githubusercontent.com/2467395/89066761-45da0200-d36e-11ea-96ea-343e5418531a.png)

**Version**
 - OS: Ubuntu
 - Widelands Build 1.0~git24706[c0eea95@master](Release)

**Comment by Noordfrees** [comment]
You have some fire tongs in your initial stock, don't you?

**Comment by pospec4444** [comment]
> You have some fire tongs in your initial stock, don't you?

Oh, of course I do. My fault.
