### ISSUE TITLE
Scenario details textarea uses scrollbar inconsistently

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4060]
Admittedly, a rare cornercase. Found this while testing #4054; this only seems to happen with very specific MultilineTextarea dimensions and row counts.
The description of emp01 in low german needs a scrollbar:
![shot0001](https://user-images.githubusercontent.com/48293446/89333884-efcecc80-d695-11ea-9c97-ee699265a1e8.png)
And so does emp02, but only barely:
![shot0002](https://user-images.githubusercontent.com/48293446/89333933-07a65080-d696-11ea-9533-b1476e498905.png)
emp03 doesn't need one:
![shot0003](https://user-images.githubusercontent.com/48293446/89333945-0ecd5e80-d696-11ea-969f-325a0820da7f.png)
And selecting emp02 *again* – it suddenly doesn't need one:
![shot0004](https://user-images.githubusercontent.com/48293446/89333984-1bea4d80-d696-11ea-8b55-a146d7bb8c52.png)

**Expected behaviour:**
The same text in the same bounds should either always or never use a scrollbar.

**Comment by gunchleoc** [comment]
I don't consider this a bug - it's a matter of taste. The MultilineTextarea has an autodetect mode, and it is working properly.

**Comment by Noordfrees** [comment]
If this autodetect mode causes the same situation to sometimes have a scrollbar and sometimes not I would consider the autodetect mode buggy…

**Comment by gunchleoc** [comment]
You did not put the 2 screenshots that demonstrate the actual bug next to each other, so I didn't see that the exact same text is sometimes with and sometimes without.
