### ISSUE TITLE
UI::Box can't handle deletion of child members

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4062]
See discussion in https://github.com/widelands/widelands/pull/3847 and https://github.com/widelands/widelands/pull/4023

**Comment by jmoerschbach** [comment]
Is this real a UI::Box issue or rather a UI::Panel issue?

**Comment by gunchleoc** [comment]
UI::Panel can handle deletion, but we might need to change both classes for implementing this; e.g. the panel could send a notification for the box to pick up. That's just an idea though without looking at the code in detail.
