### ISSUE TITLE
Editor: List of maps defaults to filename

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4067]
The list of maps defaults to show the filenames, not the name of the maps. This leads to confusion if one is using non English localization because the filenames are in English.
Two more things to mention:
The checkbox 'Show original (english) names' is useless in the initial state. It becomes only useful after hitting 'Show map names'.
The String "Folder ..." on the right side of the list appears only after either hitting 'Show original...' or 'Show map names'

**To Reproduce**
1. Start editor
2. Press STRG+l
 
**Expected behavior**
1. The list should show the names of the maps in initial state so the localization makes sense.
2. The String "Folder ..." should be shown in initial state

**Version:**
 - OS: Arch Linux
 - Widelands Version: 1.0~git107[4c338cc@master] (Debug)

**Comment by Noordfrees** [comment]
Next to the toggle button for the map/file names, there's also a checkbox "show real map names" which doesn't seem to do anything. Either the button or the checkbox should be removed.

**Comment by frankystone** [comment]
The checkbox is working, but only if the map names are shown (not if map filenames are shown, which is the initial state). Checking the box shows the English names of the maps, if one has set another language. So one can switch between localized map names and english map names. This should stay :-)

**Comment by Noordfrees** [comment]
Okay didn't see that in a quick test. Perhaps we should combine them into a dropdown with three options though – File Names, English Map Names, Localized Map Names
