### ISSUE TITLE
yet another lua error in wood gnome.

### ISSUE THREAD

**Issue by matszpk** [widelands/widelands#4072]
Yet another lua error in wood gnome mode:
\[../src/scripting/lua_errors.cc:22] Error in format: boost::bad_format_string: format-string is ill-formed stack traceback:  [string "scripting/win_conditions/wood_gnome.lua"]:82: in local '_game_over'  [string 'scripting/win_conditions/wood_gnome.lua"]: 130: in function <[string "scripting/win_conditions/wood_gnome.lua"]:32>

This error happened when player wins.

Widelands build 21. OS: Arch Linux.

**Comment by Noordfrees** [comment]
Which language are you playing in? I cannot reproduce and would suspect that a translator messed up the printf placeholders

**Comment by matszpk** [comment]
I am playing widelands in Polish language.

**Comment by Noordfrees** [comment]
Okay, the string `%1$s had %2$s` is translated as `%1$s miał $2%s.` Strange that our translations validator didn't notice that error…
@Niektory @gunchleoc

**Comment by Niektory** [comment]
The bad translation was 6 years old and marked as reviewed. I corrected it now in Transifex.

**Comment by gunchleoc** [comment]
The validator tool can get confused sometimes if the placeholders aren't followed by blank space - like the "%-Chance" in German it can't deal with.

It's a third-party tool, so we can't fix the tool.
