### ISSUE TITLE
AI builds shipyard on non-seafaring map

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4087]
Build21: The AI has built a shipyard on a non-seafaring map (Crater).
Savegame: https://www.widelands.org/forum/topic/4924/?page=1#post-34170

@tibor95 

See also #1689

**Comment by gunchleoc** [comment]
Is this the inverse of https://github.com/widelands/widelands/pull/4082?

**Comment by Noordfrees** [comment]
Nope, allows_seafaring detection is working correctly here: the human player can't build shipyards. I would guess that the AI is skipping the needs_seafaring check again.

**Comment by tibor95** [comment]
I can see two possible causes:

- Shipyard is not recognized as shipyard (BuildingAttribute::kShipyard), we have no assert making sure that just one building is recognized as a shipyard, do we?
- Map::allows_seafaring() returned true by mistake

I am not aware of any change in the AI lately that could cause this, but I will investigate...

EDIT: third possibility:

- kShipyard is not handled in "normal productionsites" category, but in some other and is assigned a score. Search for " // finally normal productionsites" comment in default_ai.cc and see few rows below. I think we had such discussion lately

**Comment by tibor95** [comment]
sorry, It is not exact to say that it is about scoring, but more about placement of buildings. But still, look up the comment mentioned above and check...

**Comment by gunchleoc** [comment]
*  we have no assert making sure that just one building is recognized as a shipyard

That shouldn't matter. What matters if the `BuildingDescr::needs_seafaring()`, which the AI needs to check against its `map_allows_seafaring_`, and not how many of them there are.

**Comment by tibor95** [comment]
OK,
but we already have such check in DefaultAI::check_building_necessity(), I have to debug this. Hopefully this will be reproducible....

**Comment by tibor95** [comment]
I am trying to get this issue on master - no luck so far... do you think I should try build-21 branch  instead?

**Comment by hessenfarmer** [comment]
My guess is we didn't adapt the AI to 

https://github.com/widelands/widelands/commit/a82ffd16e32b448b495580ad75dd97bbcf992157#diff-8b3fb4754ea59e427f4dd87588d46c97

**Comment by hessenfarmer** [comment]
well my first guess seems to be wrong as the AI should use the correct info from the logic code.
I already asked the bug reporter in the forum if he saved and reloaded, because my next gues would be we don't save this info and do not generate it after reloading , but I am not sure about that

**Comment by tibor95** [comment]
I am just compiling build-21. My ques is somehow wrong data dir

**Comment by hessenfarmer** [comment]
First strange thing is that this is a nethost savgame. Might be unrelated though

**Comment by hessenfarmer** [comment]
After long attempts to solve this it seems that a clean reinstallation solved this issue

**Comment by Noordfrees** [comment]
Reported again: https://www.widelands.org/forum/post/34498/ (didn't look at the replay)

**Comment by tibor95** [comment]
Networkgame again? Does this ever happen on single player game?
