### ISSUE TITLE
Error when window size higher than primary monitor's

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4092]
When the window size is set to a size larger than the primary monitor's resolution the game fails to start with a confusing error message:
```
Video Error
SDL should report 4 bytes per pixel, but 1 were reported instead.
Please check that everything's OK with your graphics driver.
```

**To Reproduce**
1. Set the highest possible resolution in the options screen and disable fullscreen, quit the game.
2. Change your primary monitor/display to a smaller one.
3. Try to start the game again.

OR if you don't have monitors of different sizes:

1. Enter a resolution higher than your monitor's and disable fullscreen in the config file.
2. Try to start the game.

**Expected behavior**
The game should start. The window size may be reduced if necessary, although it's not always optimal (for example when you have a second, larger monitor which you want to play on).

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24751[90d9b7e@HEAD] (Release)

**Log**
```
Graphics: Try to set Videomode 1920x1200
Graphics: OpenGL: Version "4.6.0 NVIDIA 430.64"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 16
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384
Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
**** GRAPHICS REPORT ****
 VIDEO DRIVER GLVND x11
 pixel fmt 21464
 size 24816 39408561
**** END GRAPHICS REPORT ****
ERROR: SDL should report 4 bytes per pixel, but 1 were reported instead.
Please check that everything's OK with your graphics driver.
```

**Comment by Noordfrees** [comment]
I got this before (using `--xres` and `--yres`) and I believe this is an SDL bug, not sure if we can do something about this…

(code is in `src/graphic/graphic.cc`)

**Comment by Niektory** [comment]
OK, I see what's going on. `SDL_GetWindowDisplayMode()` fails, but we don't do error checking, so we read uninitialized memory and get funny values. The failure just means that SDL couldn't find a fullscreen mode suitable for our window. If we're not in fullscreen we shouldn't care. Maybe it's not even the right function to use here.
