### ISSUE TITLE
Add new commandline parameter for the locale dir

### ISSUE THREAD

**Issue by TinoM** [widelands/widelands#4097]
Currently only the datadir is a parameter and widelands expects the localedir to be in the datadir.
It does no longer crash with a missing localedir, but it would be nice to be able to specificy the localedir independently.

On my windows development machine, the locale dir with the translation get build in the build dir, while the datadir resides in the git checkout dir.
I've added an extra xcopy to my build script to copy the translations and modified .gitignore, but it would rather not.

@gunchleoc you have been working on this, but i am not sure, if and what branch is valid?

I've also checked: widelands does not accept a windows symbolic link named "locale" in the datadir on windows.

**Comment by hessenfarmer** [comment]
well in my machine it accepts a real symbolic link, but you need to create this in a specific way with the commandline tool "mklink" 
if you don't add this to git it should work

**Comment by gunchleoc** [comment]
I guess I misunderstood another of your comments that landed in my inbox today which stated that it was already fixed on Windows, so I deleted the branch. It didn't work anyway.

What I was trying to do was to move the link creation from `compile.sh` to CMake.
