### ISSUE TITLE
Player vision packet is too slow

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4109]
Writing new Europa map with Build 21:

```
Writing Exploration Data ... took 18ms
Writing Players Unseen Data ... took 70ms
```

And on Master:

```
Writing Players View Data ... took 13565ms

```

This is far too slow. I have started working on this https://github.com/gunchleoc/widelands/tree/speedup-player-vision-packet

**Comment by Noordfrees** [comment]
Perhaps writing all the details for `kPreviouslySeen` fields only would already give a good bonus?

**Comment by Noordfrees** [comment]
I have to update the packet saveloading anyway while working on #1344 so I'll also have a look at speeding things up there
