### ISSUE TITLE
Missing localization for Territorial Time

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4132]
The localization of wincondition of territorial time isn't applied:

![localization](https://user-images.githubusercontent.com/6730556/90332026-9f227200-dfb9-11ea-909d-2eae3471f419.png)

All other winconditions are translated. Tested only German.

The corresponding po-file has the localized string in it.

**To Reproduce**
1. Start a new game
2. Click on Wincondition and move the mouse over Territorial Time 

**Version:**
 - OS: arch linux
 - Widelands Version: 1.0~git24782[eb895b9@master] (Release)

**Comment by Noordfrees** [comment]
That string was changed recently and probably just hasn't been pulled from Transifex yet.

Edit: the string in the PO file is still the old version

**Comment by frankystone** [comment]
Sorry

**Comment by Noordfrees** [comment]
No problem. The last translations sync was two weeks ago – @gunchleoc

**Comment by gunchleoc** [comment]
I'll go ahead and pull them now.

Note that there might still be gaps if the bug that caused us to force pull from Transifex is still around - I don't want to force pull unless we need it, because it blows up the diffs with lots of changed timestamps.

**Comment by Noordfrees** [comment]
Looks like the commit updated only the POT files. Apparently force-puling is necessary.

**Comment by gunchleoc** [comment]
Translation pulling issue with https://github.com/widelands/widelands/commit/a8e3e60a77c4ca768d65cc7672953a3264b2cb8f
