### ISSUE TITLE
Building help Healing text is not translated

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4138]
In the buildinghelp the text
"Garrisoned Soldiers heal 130 Health point per second" is not translated

**Comment by gunchleoc** [comment]
Not just that one - any string fetched with ngettext in Lua has this problem.

**Comment by Noordfrees** [comment]
That error was such a stupid simple typo that I pushed the fix directly to master

**Comment by gunchleoc** [comment]
Love those typos! *headdesk*
