### ISSUE TITLE
tribes filtering introduced bug with custom Building, ware or worker images

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4139]
In a custom scenario map the game doesn't parse the images correctly it throws an error that no suitable animations were found
" Failed adding ware 'ax_sharp: Error while loading ware type 'ax_sharp': [D:/development/Widelands_Git/fork_bal/src/scripting/lua_errors.cc:22] Error loading animation 'idle' for map object 'ax_sharp': Animation in directory 'map:scripting/tribes/ax_sharp/' with basename 'idle' has no images for mandatory scale '1' in mipmap - supported scales are: 0.5, 1, 2, 4"

1. open the map market_trading in single player 
2. start the game

**Comment by gunchleoc** [comment]
That's because `dirname = "test/maps/market_trading.wmf/" .. path.dirname(__file__)` only works within the test suite setup. If you want to run a test suite map as a normal game, you'll have to fix the path.

Can you reproduce this bug with a normally run game, with a map designed to be played and not so be used specifically for the test suite?

**Comment by hessenfarmer** [comment]
Ok I forgot that I changed the path to "map:" .. path.dirname(__file__) to get the relevant error message.

See also https://www.widelands.org/forum/topic/4926/

**Comment by hessenfarmer** [comment]
from the error message it seems like the program is expecting mipmaps but we only have an old style idle_00.png in there

**Comment by gunchleoc** [comment]
That error message is misleading - it's much more likely that it's looking in the wrong directory.

**Comment by frankystone** [comment]
One may can try this scenario.

It consists only of internal data and uses an atlantean farm as a headquarter named "custom_building".

This throws two errors, one regarding missing animations, the second is an assert.
[test custom buildings.zip](https://github.com/widelands/widelands/files/5109439/test.custom.buildings.zip)

But maybe i am doing something wrong...

**Comment by gunchleoc** [comment]
Thanks for the files.

You are doing nothing wrong, this is definitely a bug.

I will look into this after https://github.com/gunchleoc/widelands/tree/pluggable-tribes-helptexts and https://github.com/gunchleoc/widelands/tree/world-filtering have been merged, because it will be easier to fix then.

**Comment by gunchleoc** [comment]
WIP branch: https://github.com/gunchleoc/widelands/tree/4139-scenario-animations

It fixes the problem for the animations, but the menu icons and helptexts will need fixing too. I need to wait now for the 2 branches mentioned above. Otherwise, I'll get massive merge conflicts.

**Comment by frankystone** [comment]
Thanks, no need to hurry :-)

**Comment by hessenfarmer** [comment]
Well I can't confirm this bug anymore as I managed to load the scenario (and watch the trading function for the first time ;-)).
I just had to provide the correct prefix of the path (in my case: ""maps/My_Maps/market_trading.wmf/" .. path.dirname(__file__)")

I learned that in the dirname we can't use "map:" as it is dependent on the Game and while registering/loading the Game isn't available yet. 

So I believe this can be closed 
@frankystone can you confirm that the scenario can be loaded with the correct path in the dirname? Maybe your testscenario needs top be adapted to the new units syntax (the market_trading.wmf is loadable but not completely converted yet as well)

**Comment by frankystone** [comment]
> I just had to provide the correct prefix of the path (in my case: ""maps/My_Maps/market_trading.wmf/" .. path.dirname(**file**)")

The error of missing images is gone after applying the base path. But now i get other errors. See below.

> I learned that in the dirname we can't use "map:" as it is dependent on the Game and while registering/loading the Game isn't available yet.

I didn't used "map:".

> @frankystone can you confirm that the scenario can be loaded with the correct path in the dirname? Maybe your testscenario needs top be adapted to the new units syntax (the market_trading.wmf is loadable but not completely converted yet as well)

Now i get
~~~~
FATAL EXCEPTION: lua: [/home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_errors.cc:22] Building: 'custom_building' is not available for Player 1's tribe 'barbarians'
~~~~

Here is my adapted test scenario. Maybe you can get it make work. I am tired...

[test custom buildings.zip](https://github.com/widelands/widelands/files/5886147/test.custom.buildings.zip)

**Comment by hessenfarmer** [comment]
Well, there has been an update while unifiying tribes and world in the custom scenario building part.
your map is missing a init.lua file in the tribes folder which extends the tribes units.lua file for an example you might have a look here:
https://github.com/widelands/widelands/blob/a846817ed8a75d18ad4a84a8fc28c5375efc15a4/test/maps/market_trading.wmf/scripting/tribes/init.lua#L1

even more complicated example is here:
https://github.com/widelands/widelands/blob/644799e13538c1542a1bac788b8db6e95fca0ed8/data/campaigns/atl02.wmf/scripting/tribes/init.lua#L1

this file contains some basic values for different items of a scenario like helptexts, Preciousness, default amount, and of course the name of the unit. Furthermore it defines the position in the warehouse / economy tableview.

Edit: the sentence about using the map: prefix was due to my logical error in the thread of this bug. So I was not accusing you to have used it. Just for clarification

**Comment by frankystone** [comment]
Thanks, it is working now. But trying to start the scenario as a zipped file fails again. Moreover much more warnings are thrown:

~~~~
DIRNAME:        maps/My_Maps/test custom buildings.wmf/scripting/tribes/farm_test/
[00:09:57.542 real] WARNING: Unused key "aihints" in LuaTable. Please report as a bug.
[00:09:57.542 real] WARNING: Unused key "conquers" in LuaTable. Please report as a bug.
[00:09:57.542 real] WARNING: Unused key "destructible" in LuaTable. Please report as a bug.
[00:09:57.542 real] WARNING: Unused key "heal_per_second" in LuaTable. Please report as a bug.
[00:09:57.542 real] WARNING: Unused key "icon" in LuaTable. Please report as a bug.
[00:09:57.542 real] WARNING: Unused key "size" in LuaTable. Please report as a bug.
[00:09:57.542 real] INFO: ┗━ took 2697ms
[00:09:57.543 real] WARNING: Unused key "animation_directory" in LuaTable. Please report as a bug.
[00:09:57.543 real] WARNING: Unused key "animations" in LuaTable. Please report as a bug.
[00:09:57.543 real] WARNING: Unused key "roads" in LuaTable. Please report as a bug.
[00:09:57.543 real] WARNING: Unused key "spritesheets" in LuaTable. Please report as a bug.
[00:09:57.543 real] ERROR: ##############################
[00:09:57.543 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'barbarians': [/home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_errors.cc:22] tribe barbarians: Failed adding building 'custom_building': [/home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_errors.cc:22] Error loading animation 'idle' for map object 'custom_building': Animation without image files. For a scale of 1.0, the template should look similar to this: 'directory/idle_1_??.png' for 'directory/idle_1_00.png' etc.
~~~~

Not sure if applying `"maps/My_Maps/somename.wmf" .. dirname(__file__)` is sufficient.

**Comment by Noordfrees** [comment]
If I remember correctly, animation files within a zipped directory are not and never were properly supported. Directories used by Widelands may only be zipped in a handful of narrowly defined usage cases, and this is not one of them. In other cases a zipfile might work but will more likely not. As a rule, never use zips if you want to modify anything manually.

**Comment by hessenfarmer** [comment]
Well I need to test this then as it is hard to tell without trying it myself.
Can you attach the zip in the actual state again

**Comment by hessenfarmer** [comment]
Ok I fiddled around with the version available, and got it working. There wasn't much wrong with it except the that the folder name contained spaces. With underscores instead of spaces and a proper init.lua for the tribes folder it worked well 
[test_custom_buildings.wmf.zip](https://github.com/widelands/widelands/files/5889582/test_custom_buildings.wmf.zip)
![grafik](https://user-images.githubusercontent.com/43039887/106188216-f8b4dc80-61a6-11eb-861c-131c4bfcd1dc.png)

**Comment by frankystone** [comment]
Thanks, but i give up.

Nevertheless having a hard coded path seems not the correct approach to me.

**Comment by hessenfarmer** [comment]
> Thanks, but i give up.

sorry to hear that.      

> 
> Nevertheless having a hard coded path seems not the correct approach to me.     
    
Agreed. 
@Nordfrees Shall we close this one and open a new one for this ?

**Comment by hessenfarmer** [comment]
@Noordfrees still I think we should close this as the bug is solved and only a wishlist item remains: supporting relative paths in scenario unit filesystems
