### ISSUE TITLE
Assertion `tribe().has_ware(ware)' failed in Ware Statistics

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4141]
```
widelands: ../src/logic/player.cc:1512: const std::vector<unsigned int>* Widelands::Player::get_ware_production_statistics(Widelands::DescriptionIndex) const: Assertion `tribe().has_ware(ware)' failed.
```
[Backtrace](https://github.com/widelands/widelands/files/5109252/has_ware_assertion_failed.txt)

**To Reproduce**
1. Start a game.
2. Click Statistics -> Wares from the bottom menu.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24798[8db5858@master]

**Comment by josephomorrow** [comment]
Updated to 1.0~git24809[2f77c9a@master] (Release) Still crashes when attempting to open production-stats window from bottom menu or by pressing "P".

terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
/home/Joseph/bin/widelands_play: line 2: 146238 Aborted                 (core dumped) ./widelands

Where is that core dumped?

**Comment by frankystone** [comment]
You will need revision 7ee32e9 (one after yours) to check if it works for you.
