### ISSUE TITLE
Editor: Rethink editors load map behavior

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4142]
I think most of the maps authors do work on their own maps. To open the wanted map there are two possibilities:

1. load it directly when passing it as argument to the command line. Downside: tab completion do not work (at least for me), so one has to remember and write down the full path the map
2. load it after starting widelands and click on Editor. Downside: To get to the wanted map, one has to click "Editor" -> "Mainmenu" -> "load map (or STRG-l)" -> "Double click on My Maps".

I believe at least Windows user do not use the commandline, so they have to do many clicks to get the map they want to edit.
 
**Describe the solution you'd like**
Move the shipped maps to a subfolder, so that "My Maps" is shown after hitting STRG-l and add a virtual folder "Shipped Maps" which shows, well, the shipped maps. This saves one double click for a user.

**Describe alternatives you've considered**
In build 17 or earlier, there was an intermediate menu after starting the editor. This menu had buttons "Start New Map", "Edit previous edited map", "Load Map" (or so). This would be my preferred solution.

Another solution would be to show the "Load Map" menu directly after starting the editor and add a button "Start New Map" in this menu.

**Comment by gunchleoc** [comment]
When https://github.com/widelands/widelands/pull/4080 is done, we could add a dropdown menu in the main menu.
