### ISSUE TITLE
Road program needs textures to be in first texture atlas

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4146]
**Is your feature request related to a problem? Please describe.**

In `build_texture_atlas`, there is some hard-coding for loading all terrain and road textures to get them into the first texture atlas. The `RoadProgram` then depends on all road textures being in the first atlas. There is an assert to ensure this: `assert(*gl_texture == texture.blit_data().texture_id);`.

Removing the hard-coded loading and the assert will cause the road program to pick the wrong texture in debug builds.

This is all good enough at the moment, although it will load some unneeded textures. However, things will break when we implement modding support, at which point this will turn into a bug.

**Describe the solution you'd like**
I think it would be good to keep the texture atlas switching to a minimum. Maybe give roads/terrains a separate image cache/texture atlas group?

**Comment by hessenfarmer** [comment]
It seems this is already a bug as in a current debug build I get the error of this assertion see #4190

**Comment by gunchleoc** [comment]
I think we could solve this by giving roads/terrains their own image cache.

**Comment by frankystone** [comment]
This should have been fixed by: https://github.com/widelands/widelands/pull/4389

See also: https://github.com/widelands/widelands/issues/4190
