### ISSUE TITLE
Mac OS Nightlies broken

### ISSUE THREAD

**Issue by SirVer** [widelands/widelands#4154]
I was on vacation last week and some merge has broken my build setup for the mac os nightlies on both of my machines. The modern one is complaining about OpenGL, while the older one is complaining about being unable to find ICU.

Reminder: I am manually building a version of widelands for Mac OS and upload them here: https://www.widelands.org/~sirver/wl/macos_daily/. They are linked from our download page in the wiki. I have two machines to do that: one builds nightlies that work on mac os 10.7 (released in july 2011) and up and the other one builds for Mac OS 10.9 (released oct 2013) and up. I do not track how much they are downloaded and/or used.

I am sure I can figure these build issues out, the question is if it makes sense to do that or if it is fine to retire the Mac OS nightlies I am uploading? I remember seeing some attempts to build nightly widelands on CI (i.e. #4121), which seems a much better option going forward. Where are we with that? @gunchleoc @Noordfrees

**Comment by hessenfarmer** [comment]
The culprit most probably is
https://github.com/widelands/widelands/pull/4100
this requires a cmake version newer then 3.7 to find the libraries with cmake delivered find files. 
@gunchleoc managed to build and upload .dmg files for the latest mac-os on github (currently 10.15) 
so if you could get the nightlies fixed they still might deliver support for older machines I believe.

**Comment by gunchleoc** [comment]
We do have working nightlies on GitHub now, like this one: https://github.com/widelands/widelands/actions/runs/221338805

They come with 2 drawbacks though:

- People need to get a GitHub account before they are allowed to download
- Only MacOs 10.5 is supported

So, I think it would be good to keep your nightlies working too. Our build code with working dependencies: https://github.com/widelands/widelands/blob/master/.github/workflows/build.yaml#L98

I did not touch the `buildapp.sh` script, so maybe all you need is a CMake upgrade like hessenfarmer suggested.

**Comment by SirVer** [comment]
I confirmed that it was indeed #4100 that broke my setup (thanks @hessenfarmer for the hint!). On one machine updating cmake was all that was needed, the other one needed a little more work, but it seems I am back on having a working setup. I will keep this open until I can test the new nightlies on a machine that never build widelands before, will close then.

**Comment by SirVer** [comment]
Build setup is healed and running again and I tested both nightlies on a machine that never built Widelands before successfully. So Mac OS nightlies are on track again.
