### ISSUE TITLE
In Map 'Long, long way v2.wmf', there is no space to build a mine at gold where from symmetry it seems that there should be.

### ISSUE THREAD

**Issue by dreirund** [widelands/widelands#4174]
### Describe the bug
In the map `Long, long way v2.wmf`, there is a place where there is gold, and symmetry of the maps make me assume that there should be space to build a mine. But there is no space (only space for flags).

### To Reproduce
1. Open the attached savefile `bug_ferry_stuck_at_lava_and_no_mine_building_place_at_gold.wgf.zip` of a gameplay of the map `Long, long way v2.wmf`,
2. go to the place in the attached screenshot `no_mine_place_at_gold.png`,
3. see that there is gold but no mine can be build. Forther north, there is a similar place and a mine can be built.

### Expected behaviour
A mine building place at the spot.

### Screenshots
Attached: `ferry_stuck_at_lava.png`.

### Version:
* OS: [Artix GNU/Linux](https://artixlinux.org/), 64 Bit
* Widelands Version (output of `widelands --version`): `1.0~git24817[73e7f04@master] (Release)`

---

#### Attached files:
* Savegame: [bug_ferry_stuck_at_lava_and_no_mine_building_place_at_gold.wgf.zip](https://github.com/widelands/widelands/files/5143342/bug_ferry_stuck_at_lava_and_no_mine_building_place_at_gold.wgf.zip "bug_ferry_stuck_at_lava_and_no_mine_building_place_at_gold.wgf.zip")
* Screenshot:
  ![no_mine_place_at_gold.zip](https://user-images.githubusercontent.com/1590519/91594943-ff72c580-e962-11ea-9a44-0127819cd2c0.png "no_mine_place_at_gold.zip")

**Comment by Noordfrees** [comment]
Sorry, side effect of #4033, will fix this quickly
