### ISSUE TITLE
Targeting Workers

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4184]
https://www.widelands.org/forum/topic/4930

***EITHER***

Allow moving the workarea of any building to a different spot (the worker should then prefer to work near the new centre).

***OR***

Allow marking immovables for removal using the fieldaction window (workers should then prefer ro work on those immovables).

Either way also should be adapted to allow the targeted removal of young trees.

**Comment by gunchleoc** [comment]
I'm in favor of option 1, as this will make it easier to clear forested mountains, for example.

I think the removal of young trees might be problematic. As discussed on the forum, it will go against deliberate blocking by trees on some maps.

**Comment by frankystone** [comment]
I agree with GunChleoc.

**Comment by Noordfrees** [comment]
Functional WIP branch for option 2: https://github.com/Noordfrees/widelands/tree/target_workers
I at first thought that this would be the better option but after some testing I'm not so sure. Will also make a branch for option 1 now.

**Comment by Noordfrees** [comment]
Functional branch for option 1: https://github.com/Noordfrees/widelands/tree/4184-move-workareas

IMHO this is a very powerful feature. It allows workers to reach immovables and other resources they could not reach otherwise. It also opens up lots of new ways of micromanaging, e.g. when your mine runs empty you just shift the workarea a bit further away.

Do we really want this? Please test both branches and tell me which one's better. I think option 2 (marking individual immovables for desired removal) is the better way to go.

**Comment by hessenfarmer** [comment]
we should have the movable workareas only for the workers not for buildings. This will exclude mines and wells.  
Furthermore I agree with GunChleoc and frankystone to not be able to remove young trees.

**Comment by Noordfrees** [comment]
The problem with that is that assuming we have a building that works by itself (like a mine) and can also send out a worker would then have one workarea for the building and another one with a different centre for the worker. We cannot differentiate this right now, and this would involve quite some tedious refactoring. 

I see that there's a majority for moveable workareas, and limiting this for workers only certainly makes sense. This is doable, but the complications implied are not worth the effort IMHO. Perhaps someone else will want to work on that (optionally building on the [branch](https://github.com/Noordfrees/widelands/tree/4184-move-workareas))

**Comment by frankystone** [comment]
I guess the problem is that the _worker_ programs are only defined by the _buildings_, __not__ the _workers_.  This has confused me quite a lot ;)

**Comment by hessenfarmer** [comment]
> 
> 
> I guess the problem is that the _worker_ programs are only defined by the _buildings_, **not** the _workers_. This has confused me quite a lot ;)    
   
This I don't understand. the worker program with all parameters is defined in the workers init.lua.

**Comment by Noordfrees** [comment]
In Lua, the definitions are separate. But in C++, the info we need is all mixed up together in `BuildingDescr.workarea_info`. It contains building actions (such as mining and conquer range), worker actions (like woodcutter), and also info about the building's enhancement's work areas. This would need to be split into something like this:
```
enum class WorkareaType { kBuilding, kWorker, kEnhancement };
using WorkareaInfo = std::multimap<uint32_t /* radius */, WorkareaType>;
```
(I think we can drop the descriptive strings, AFAIK they are unused.)
Then we could distinguish those in the workarea visualisation (which would also make #2145 much easier to implement). It's not really hard to implement, just very tedious as this info is used in many places.

**Comment by Niektory** [comment]
> IMHO this is a very powerful feature. It allows workers to reach immovables and other resources they could not reach otherwise. It also opens up lots of new ways of micromanaging, e.g. when your mine runs empty you just shift the workarea a bit further away.

How about instead of shifting the workarea one could select a location for the worker to focus on. Or a hard range limit so the new workarea is always a subset of the normal workarea.

**Comment by frankystone** [comment]
> > I guess the problem is that the _worker_ programs are only defined by the _buildings_, **not** the _workers_. This has confused me quite a lot ;)
> 
> This I don't understand. the worker program with all parameters is defined in the workers init.lua.

Maybe it's a misunderstanding from my side: For me a worker produces something, so if want to have look in the corresponding program, at first i search in the workers init.lua. But the programs to produce something are defined in the corresponding buildings init.lua.

Will test the branches soon.

**Comment by Noordfrees** [comment]
> How about instead of shifting the workarea one could select a location for the worker to focus on

+1

> Maybe it's a misunderstanding from my side: For me a worker produces something, so if want to have look in the corresponding program, at first i search in the workers init.lua. But the programs to produce something are defined in the corresponding buildings init.lua.

Most of the time wares are produced by *buildings*. The workers are only required to be *there* but they don't actually *do* anything. Only when workers are actively walking around in the field it is the worker that does something, though he only does it when the building tells him to.

**Comment by gunchleoc** [comment]
And I think a range limit is a good idea, as a property of the ProductionSiteDescr.

Trigger that shifting is allowed in the "callworker" productionsite program, this can set a flag in the ProductionSiteDescr if its range limit is > 0. Then all workareas for this building will be movable and all workareas always have the same center. Having multiple centers for the same building would be too much.

**Comment by Noordfrees** [comment]
> Having multiple centers for the same building would be too much.

True. But if we have a building that mines a resource *and* sends out a worker (could be easily created by a modder) then we would *have* to have multiple centres – one for the mining and one for the worker. 
I think this feature would have just too many complications…

**Comment by frankystone** [comment]
Both options has some ups and downs:

Option 1 (move workareas):
I like this very much, but i fear this implies some new balancing because the player do not need to build a new building to reach specific resources. Less buildings = less need for building materials which could be used for other things. In the end i think this option will make establishing a full working economy much faster. This can be partially compensated if the workareas of some buildings (woodcutter/quarry) get smaller. On the other side it is visually nice, because the playfield doesn't look geometrical anymore (farms/vineyard).
![shot0009](https://user-images.githubusercontent.com/6730556/91939537-4c092880-ecf6-11ea-8f30-06a0e926ae08.jpg)


Option 2 (mark individual resource for removing):
This is also nice, because _sometimes_ a player needs to wait until a woodcutter/quarry has removed a specific resource. With this option this time can be reduced. Currently one can mark a resource for removing if it is outside any workareas. This could lead into confusion if a player has marked one/two/three resources and wondering why they don't get removed first. But i think this can be solved somehow.

As a result i am unsure. Because i like widelands mainly because of the graphics and the visual representation option 1 is very nice. Option 2 is maybe easier to implement but i don't know if it is worth the work, because the underlying problem arises only sometimes, imho.

**Comment by gunchleoc** [comment]
If workareas have priority in the center, you can have the worker prioritize a certain immovable/resource, so that would be enough control.

> But if we have a building that mines a resource and sends out a worker (could be easily created by a modder) then we would have to have multiple centres – one for the mining and one for the worker.

No we wouldn't. We could just let the building mine where the worker goes and add this information to the scripting documentation so that modders will know what the behavior is.

**Comment by hessenfarmer** [comment]
well we already have buildings with differing workareas in the amazons branch (huntergatherer).    
I am still in great favor of the movable workareas. of course this would change somehow the current game as e.g. some rocks could be reached by a single quarry which couldn't be reached previous. however I don't see this as a big effect. Same for wood cutters as they get much more inefficient in terms of log per time the longer they have to walk. this would normally not compensate for having to spend some logs for a second one closer to the wood. 
in terms od radius we should limit the selection of the center to e.g. (ceil(radius*2/3) may be we could reduce some large radiuses by one to compensate for the greater range additionally (namely every radius bigger then 5 or 6.    
anyhow this should be limited to the workers workareas and not the building ones (while the only buildings having a radius currently which is not dependent on the worker are mines and wells ) 
Furthermore the moved workareas don't need to be reflected in the overlapping if we would use the maximum area for overlapping instead.

**Comment by Noordfrees** [comment]
> of course this would change somehow the current game as e.g. some rocks could be reached by a single quarry which couldn't be reached previous. however I don't see this as a big effect. Same for wood cutters as they get much more inefficient in terms of log per time the longer they have to walk. this would normally not compensate for having to spend some logs for a second one closer to the wood.

That's only true in cases where there are enough building spots around. But many official maps have much rough terrain where this would have quite a big effect. Being able to move workareas would introduce a new way of micromanaging which would penalize players who don't want to do that, especially if we "compensate" by reducing some radii. I wouldn't like that.
Using the maximum workarea to calculate overlaps will also get quite performance-hungry.

**Comment by gunchleoc** [comment]
It might still be balanced enough if we keep the allowed shift radius small.

For workarea overlap performance, the workarea centers could be recorded in the Map class.

**Comment by Noordfrees** [comment]
If we keep the radius (and the effect) small it's not really worth the effort imho…

Let's just go with option 2, I have a branch for that which only needs some minor tweaks to be ready for review

**Comment by gunchleoc** [comment]
OK, let's try this one out.
