### ISSUE TITLE
Windows build won't run

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4186]
I downloaded a development build from a GitHub action (x64, release) and got this:

![glew-dll](https://user-images.githubusercontent.com/4095570/91664734-03c8eb00-eae9-11ea-9a54-25e0005a6dbf.PNG)

Looks to me like the static linking doesn't work.

**Comment by hessenfarmer** [comment]
confirmed

**Comment by hessenfarmer** [comment]
I have identified a fix I believe. Will provide a branch tonight as this needs some cleanup and was not ready yet
