### ISSUE TITLE
Sigbart in defaultai.cc

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4187]
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/ai/defaultai.cc:1303: void DefaultAI::update_all_mineable_fields(uint32_t): Zusicherung »mine_fields_stat.has_critical_ore_fields()« nicht erfüllt.

1. Load attached savegame
2. Wait until the sentry in the east get filled with soldiers
3. As soon the first soldier walks in, the crash (assertion?) happens

[backtrace](https://github.com/widelands/widelands/files/5147200/bt.txt)

**Version:**
 - OS: archlinux
 - Widelands Version: [81633dd@master] (Debug)

[wl_autosave_00.wgf.zip](https://github.com/widelands/widelands/files/5147198/wl_autosave_00.wgf.zip)

**Comment by hessenfarmer** [comment]
well the AI Hints hadn't be renamed. I provided a branch that hopefully might fix this. However I can't check it as I can't get my debug builds to work
