### ISSUE TITLE
crash at start of debug build

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4190]
Starting any road placing or loading roads end with a crash in my debug build
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: C:\msys64\home\Stephan\debug\src\widelands.exe
File: D:/development/Widelands_Git/fork.../road_program.cc
Line: 92

Expression: *gl_texture == texture.blit_data().texture_id

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abbrechen   Wiederholen   Ignorieren   
---------------------------

**Comment by frankystone** [comment]
Here on archlinux it runs fine with version [c037065@master] (Debug).

Starting a new game and connected buildings with the headquarters, no problem.

**Comment by Noordfrees** [comment]
For me all works fine too (ubuntu). Which version? Self-compiled or downloaded from GitHub/Appveyor/…? Full log output?

**Comment by hessenfarmer** [comment]
self compiled version will check with appveyor / github as soon as it is possible again.

**Comment by hessenfarmer** [comment]
tried it with https://github.com/widelands/widelands/suites/1123111348/artifacts/15939188
same result

**Comment by gunchleoc** [comment]
I thought I had fixed this - problem is the same as in https://github.com/widelands/widelands/issues/4146

**Comment by hessenfarmer** [comment]
Probably related in normal games I saw my streets all suddenly changing to busy texture and some time later to norml texture. May be it is different between os how the textures are handled (i. e. which one is the first one)

**Comment by hessenfarmer** [comment]
I'd really appreciate some progress with this as currently I don't have any debug builds on my windows machine

**Comment by Niektory** [comment]
Tried the AppVeyor debug 64-bit build of bceb8dcd4537a442791dacaa55b7ec6634815004 on Windows 8.1, it crashes as described. I didn't try building it myself.
