### ISSUE TITLE
Check that detected datadir matches executable version

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#4194]
**Describe the bug**
When you start widelands, it crashes imidiatly.

**To Reproduce**
1. Freshly clone the repo
2. Run ./compile.sh -a -t -j 2
3. Wait to finish compiling
4. Run ./widelands

**Expected behavior**
Widelands should have started up.

**Version:**
 - OS: Arch Linux (5.4.60)
 - Widelands Version: 1.0~git1[c037065@master] (Debug)

**Error-Log**
his is Widelands Version 1.0~git1[c037065@master] (Debug)
INFO: Set home directory: /home/max/.widelands
INFO: Set configuration file: /home/max/.widelands/config
INFO: Widelands executable directory: /home/max/projects/widelands/
INFO: Adding directory: /usr/share/widelands
INFO: selected language: en
INFO: using locale en_US.utf-8
DEBUG: Byte order: little-endian
DEBUG: Graphics: Try to set Videomode 1280x720
DEBUG: Graphics: OpenGL: Version "4.6 (Compatibility Profile) Mesa 20.1.6"
DEBUG: Graphics: SDL_GL_RED_SIZE is 8
DEBUG: Graphics: SDL_GL_GREEN_SIZE is 8
DEBUG: Graphics: SDL_GL_BLUE_SIZE is 8
DEBUG: Graphics: SDL_GL_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_BUFFER_SIZE is 24
DEBUG: Graphics: SDL_GL_DOUBLEBUFFER is 1
DEBUG: Graphics: SDL_GL_DEPTH_SIZE is 24
DEBUG: Graphics: SDL_GL_STENCIL_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_STEREO is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
DEBUG: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
DEBUG: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
DEBUG: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
DEBUG: Graphics: SDL_GL_CONTEXT_FLAGS is 0
DEBUG: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
DEBUG: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
DEBUG: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
DEBUG: Graphics: OpenGL: Double buffering enabled
DEBUG: Graphics: OpenGL: Max texture size: 16384
DEBUG: Graphics: OpenGL: ShadingLanguage: "4.60"
DEBUG: **** GRAPHICS REPORT ****
DEBUG: VIDEO DRIVER GLVND x11
DEBUG: Display #0: 1366x768 @ 60hz SDL_PIXELFORMAT_RGB888
DEBUG: **** END GRAPHICS REPORT ****
terminate called after throwing an instance of 'LuaTableKeyError'
  what():  [../src/scripting/lua_errors.cc:22] window_border_focused is not a field in this table.
Aborted (core dumped)

**Comment by Noordfrees** [comment]
From the log it appears that an older installation of Widelands is around and causing trouble. You'll either need to specify the new data directory at startup with `--datadir=/home/max/projects/widelands/data` or remove the old installation at `/usr/share/widelands`. 

---

Not really a bug, but this problem is reported pretty often. Perhaps we should include a VERSION file in the data directory that is updated frequently (e.g. on every translations update, or autogenerated by CMake if possible) and only let Widelands accept a data directory with the matching hardcoded (and equally frequently updated) version.

**Comment by PinPhreek** [comment]
Thanks, that helped.

**Comment by Noordfrees** [comment]
Let's keep this issue open to remind us to implement some kind of version check while autodetecting the datadir

**Comment by PinPhreek** [comment]
ok
