### ISSUE TITLE
Fishers can't find any fish

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4198]
Fishers don't work at all now. Reported on the forum: https://www.widelands.org/forum/topic/4755/?page=12#post-34372

**To Reproduce**
1. Build a Fisher's House near a shore that should have fish.
2. You'll receive a "No Fish" message immediately.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24838[0107ae7@master] (Release)

**Comment by Noordfrees** [comment]
The fishers' program still says `"findspace=size:any radius:7 resource:fish"` but the resource has been renamed
