### ISSUE TITLE
New log output has too many lines

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4208]
**Is your feature request related to a problem? Please describe.**

The log output puts sometimes the time (" → took: xyz ms") in an extra line:

~~~~
INFO: ┃    → took 144ms
INFO: ┃    Frontiers, flags and roads: 
INFO: ┃    → took 5ms
INFO: ┃    Finalizing: 
INFO: ┃    → took 1ms
INFO: ┗━ took: 641ms
INFO: Game: Reading Player Info took 5477ms
INFO: Game: Calling read_complete()
INFO: Reading Elemental Data ... 
INFO:  → took 32ms
INFO: Reading Player Names And Tribe Data ... 
INFO:  → took 19ms
INFO: Reading Port Spaces Data ... 
INFO:  → took 0ms
INFO: Reading Heights Data ... 
INFO:  → took 3ms
INFO: Reading Terrain Data ... 
INFO:  → took 49ms
....
~~~~

This makes it hard to scroll up and the buffer on my system (1000 lines) get filled, so that i can't scroll to the first lines anymore after starting a game.

**Describe the solution you'd like**

If feasible all lines should be shown like the 7th line from the example above:
~~~~
...
INFO: Game: Reading Player Info took 5477ms
...
~~~~

**Comment by Noordfrees** [comment]
The alternative would be to print the whole string ("Reading xy data took 123ms") on one line that is only printed when the respective packet loading is complete. Downside: Warnings and error messages thrown up by a packet would not be prefixed with the packet name any more so one doesn't see as easily which packet they occurred in. Or alternatively print the duration only when --verbose is enabled.

**Comment by tibor95** [comment]
From design point of view this is not good approach. What if game crashes during these 5.4 seconds?
If the logs has the timestamp, it is not needed to say when it finished and how long it lasted, it can be deducted from (this and next) timestamp.

In fact I dont know if new logs has timestamps...

**Comment by Noordfrees** [comment]
It does have timestamps, but these refer to gametime and not realtime. They are only printed where applicable – as the gametime does not change during loading it is omitted there.
Should we additionally print realtime-stamps everywhere?

**Comment by tibor95** [comment]
Oh, I did not know. But two timestamps in one line would look like a mess. Maybe using real-time timestamps when gametime timestamps are not used... Just a braninstorming :)

**Comment by gunchleoc** [comment]
> Maybe using real-time timestamps when gametime timestamps are not used

This would certainly allow us to get rid of the "took..." lines.

We could prefix the timestamps with RT/GT or something equally short to distinguish real time from game time.

**Comment by Noordfrees** [comment]
We can either have second-precision with the real time
```
⌚ 12:41:04 DEBUG: Initializing economy serial
```
or have millisecond-precision relative to either the Widelands startup time
```
⌚ 0:00:00.000 DEBUG: Initializing economy serial
```
Which one do we want?

Also, the meaning of RT/GT is not intuitive in my opinion. I'm using a clock icon for absolute time and an hourglass for gametime for now, better suggestions welcome…

**Comment by tibor95** [comment]
those icons are shown also in linux teminals? And if I redirect the output to a file?

**Comment by Noordfrees** [comment]
Yes, they are :) 
![terminaloutput](https://user-images.githubusercontent.com/48293446/92106542-d465f700-ede4-11ea-9432-c162462d2201.png)
(those are characters taken from the system's character map actually)

**Comment by tibor95** [comment]
I am a minimalist in this regard, but if ok
BTW, what about better alignment if hours is single digit? I mean put a blank space or zero?

**Comment by frankystone** [comment]
Please use only ASCII characters. I fear problems with different operating systems ,character sets, fonts, language settings and so on.

Edit: Do we really need milliseconds?

**Comment by Noordfrees** [comment]
Milliseconds might be useful sometimes to debug race conditions. (edit: micro- and nanoseconds would be even nicer but that's overkill imho)
> Please use only ASCII characters. I fear problems with different operating systems ,character sets, fonts, language settings and so on.

okay, what strings should I use then to distinguish? `gametime`/`realtime` would be clear, but 8 chars is also pretty long…

**Comment by frankystone** [comment]
What about `hh:mm:ss.ms (Game) ......` equivalent `hh:mm:ss.ms (Real) .....`.  That should be clear?
