### ISSUE TITLE
Expedition Dock

### ISSUE THREAD

**Issue by josephomorrow** [widelands/widelands#4210]
In 1.0~git24821[f9830d8@master]:
(Using fedora 32)
3rd Empire campaign
Create port with new expedition. Allow ship to dock. Crash produces attached.
[20200903_DeadlySignal.txt](https://github.com/widelands/widelands/files/5168095/20200903_DeadlySignal.txt)

**Comment by Noordfrees** [comment]
I can reproduce. It happens when clicking on the "expedition ship is waiting" message in the messages menu.

**Comment by josephomorrow** [comment]
That is exactly what happens (still waking up after error occurring late last night).

**Comment by gunchleoc** [comment]
I can reproduce that too, with any game.

**Comment by Niektory** [comment]
Broken in 7f72ddfd870096f9d5e9dea44fc119fe21eeb3c1 (#4159)... I'll investigate.

**Comment by Niektory** [comment]
OK... It's *almost* working... :P

![funky screenshot](https://user-images.githubusercontent.com/4470900/92804953-01a03f80-f3b9-11ea-9cb5-8543c7dee230.png)

Turns out I changed the order of initialization which messed things up...
