### ISSUE TITLE
Editor categorized selection needs different focus highlighting

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4216]
In the attached screenshot, it's impossible to tell whether the Wisent has been selected or not without looking at the text on the bottom.

![animals_focus](https://user-images.githubusercontent.com/4095570/92299579-5708c680-ef4b-11ea-8cdb-cb152cd8328e.png)

For animals and immovables, we could add a fill rect, but that wouldn't work for the terrains, because they're square.

**Comment by Noordfrees** [comment]
This needs to be fixed in `UI::Checkbox` for all checkboxes with custom images. Perhaps draw the orange line with a thicker inner border and the focus rects somewhat thinner so both are visible at once?

**Comment by gunchleoc** [comment]
Sounds worth trying :)

Or draw the checkbox border on top of the focus border, so we have the checkbox line on the inside? This way, the thickness of the focus border could remain as it is.
