### ISSUE TITLE
Segfault opening wares statistics

### ISSUE THREAD

**Issue by pabordel** [widelands/widelands#4222]
A segfault happens each time I press "p" or use the menu  to see wares statistic 
os : ubuntu 20.04
saved game :
[en cours.wgf.zip](https://github.com/widelands/widelands/files/5178122/en.cours.wgf.zip)

widelands output :
[widelands.log.zip](https://github.com/widelands/widelands/files/5178125/widelands.log.zip)

**Comment by Noordfrees** [comment]
Duplicate of #4172
