### ISSUE TITLE
Add wares cheat to debug builds

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4230]
It would speed up playing through campaign missions if the players could cheat and give themselves some wares.

This would help translators to proofread the scenario dialog in context when the scenario is difficult or takes a long time to play.

This feature should be there for debug builds only.

Mockup:

![wares_cheat_mockup](https://user-images.githubusercontent.com/4095570/92329364-dfc45700-f05e-11ea-9613-e46e33fd3d2a.png)

**Comment by Noordfrees** [comment]
#3662 comes with a UI to change the actual ware quantity in warehouses and inputqueues for use in the editor which could be easily extended to be shown in debug builds for non-editor games as well

Edit: But perhaps it should only be shown if it is additionally enabled with a `--cheat` command line switch?
