### ISSUE TITLE
[Duplicate] Widelands::Bob::State& Widelands::Bob::top_state(): Assertion `stack_.size()' failed

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#4235]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
I played on the newest version of the master-branch (details below). And suddenly my game froze and crashed

**To Reproduce**
I have no Idea.

**Version:**
 - OS: Arch Linux 5.4.62-1-lts
 - Widelands Version: Widelands Build 1.0~git39[6307961@master](Debug)

**Error**
2:30:57.364 DEBUG: TW(1859): destination disappeared or economy mismatch -> fail
widelands: ../src/logic/map_objects/bob.h:301: Widelands::Bob::State& Widelands::Bob::top_state(): Assertion `stack_.size()' failed.
Aborted (core dumped)

[world_save.zip](https://github.com/widelands/widelands/files/5183805/world_save.zip)
(Save created in release-build 21)

**Comment by Noordfrees** [comment]
Duplicate of #3669

Do you have a replay?

**Comment by PinPhreek** [comment]
[replay.zip](https://github.com/widelands/widelands/files/5183930/replay.zip)

**Comment by Noordfrees** [comment]
Strangely enough I cannot reproduce with the same version and the replay :( 
Perhaps the bug is somewhere in rendering/ui-related code…

**Comment by PinPhreek** [comment]
I couldn't it reproduce neither :(
