### ISSUE TITLE
Player vision code is very slow

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4253]
And I mean **very** slow. Profiling shows it is the biggest CPU eater right now by far.

Here's the problem. Every time a bob moves, its entire view area from its old position is recalculated:
https://github.com/widelands/widelands/blob/ff36ede854ab98cab34e20d6b2c2a3002c38a27b/src/logic/map_objects/bob.cc#L929-L934
That means every field separately:
https://github.com/widelands/widelands/blob/ff36ede854ab98cab34e20d6b2c2a3002c38a27b/src/logic/player.cc#L1486-L1489
And for each of these fields, iterate through all of our+allied buildings+bobs, and calculate if this field is in their field of vision:
https://github.com/widelands/widelands/blob/ff36ede854ab98cab34e20d6b2c2a3002c38a27b/src/logic/player.cc#L1419-L1445

That gives us up to `(moving bobs) * (π * radius^2) * (bobs+buildings)` vision checks. Oops!

**Potential solutions:**

1. Cache the number of object that see each field so there's no need to calculate it all the time. Basically what was done before 02947d690dae1f87131a6db4e686c047939cbdab (#4046).
2. Reduce the number of checked fields by not checking the fields that are seen from the moving bob's new position.
3. When checking a group of nearby fields and finding that a seer sees one of them, check that seer first in subsequent iterations.

**ADDED:**

4. When evaluating an area, do an initial iteration calculating the distance of all seers to the center field and put the ones that are close into a list. Then for the other fields only check seers from that list.
5. Divide the map into sectors. When checking visibility, only consider seers from the same and adjacent sectors.
6. Iterate seers belonging to the field's owner first.

I think option 1 is the only real solution. The other options could give good gains in an average case but would still leave big lag spikes in some scenarios.

**Version:** ff36ede854

**Comment by Noordfrees** [comment]
It used to count only the number of map objects that see each field. This was very fragile so I removed it. I favour option 2. Option 3 also sounds good but a lot of effort. We could additionally tweak the iteration of player teams a bit so the seers belonging to the field's owner (if he's in the player's team) are iterated first.

**Comment by Niektory** [comment]
I've added some more ideas to the list in the initial post for discussion's sake, but my opinion doesn't change. Options 2-6 are band-aids. Even implementing all of them combined would still be significantly slower than option 1. If the old code was "fragile" (could you explain?) then it just needs to be rewritten in a non-fragile way. It's just a bunch of counters at its core, I'm sure we can do it. Well, I'm the one insisting on it, so the question will likely end up being can *I* do it? :-P

**Comment by Noordfrees** [comment]
Previously, the field's vision was a simple number where 0 meant "unexplored", 1 meant "previously seen" and 1+n meant "seen by n map objects". When a bob moved, the vision for all fields in its old vision range was decremented by 1 and the vision for all fields in the new vision range increased by 1. Similarly, buildings increased the vision of fields in their range by 1 when a worker entered a previously empty building, and it was decreased by 1 when the last worker left the building. Warehouses additionally increased the vision by 1 on creation and decreased it by 1 on cleanup so they always see. This caused such nice side effects as #744 and #3093. It especially did not work together with dynamic team changing during the game.
So if you are sure you want to do this, go ahead :) Just be aware that there are many places where this cache will need to be updated, and overlooking even one of them would regress some vision bugs; also if you want to implement this into `Player::Field` keep in mind that this struct is allocated in up to 512×512×16=4,194,304 instances in a large game so it needs to be memory-efficient.

**Comment by Niektory** [comment]
Some benchmarks to keep track of progress.
[Test savegame](https://github.com/widelands/widelands/files/5219868/406.wgf.zip)
CPU: Intel Core i5-2500K 3.7 GHz

Time spent in player vision code per 1 second gametime:
(The first second probably includes some initialization immediately after loading the game)

- build-21 release
gametime 51,163,247 - 51,164,252 took 100,838 µs
gametime 51,164,252 - 51,165,253 took 3,407 µs
gametime 51,165,253 - 51,166,255 took 3,170 µs
gametime 51,166,255 - 51,167,255 took 3,358 µs
gametime 51,167,255 - 51,168,256 took 2,940 µs

- build-21 debug
gametime 51,163,247 - 51,164,252 took 1,701,573 µs
gametime 51,164,252 - 51,165,253 took 23,353 µs
gametime 51,165,253 - 51,166,255 took 23,276 µs
gametime 51,166,255 - 51,167,255 took 25,725 µs
gametime 51,167,255 - 51,168,256 took 23,690 µs

- master release
gametime 51,163,247 - 51,164,252 took 13,343,304 µs
gametime 51,164,252 - 51,165,253 took 12,319,326 µs
gametime 51,165,253 - 51,166,255 took 13,096,185 µs
gametime 51,166,255 - 51,167,255 took 12,980,928 µs
gametime 51,167,255 - 51,168,256 took 13,386,293 µs

- master debug
gametime 51,163,247 - 51,164,252 took 37,526,002 µs
gametime 51,164,252 - 51,165,253 took 20,925,247 µs
gametime 51,165,253 - 51,166,255 took 21,633,846 µs
gametime 51,166,255 - 51,167,255 took 21,571,490 µs
gametime 51,167,255 - 51,168,256 took 22,534,888 µs

Tower dismantling test:

- build-21: didn't measure separately, appears to be less than 100 µs

- master release
remove_seer() at (37,235) took 3,200,100 µs
remove_seer() at (4,248) took 2,187,988 µs

- master debug
remove_seer() at (37,235) took 4,342,864 µs
remove_seer() at (4,248) took 2,852,231 µs

**Comment by Niektory** [comment]
I've got some questions about the intended behavior of the Lua functions `reveal_fields()` and `hide_fields()`.

1. `reveal_fields()` should make fields permanently visible until hidden again with `hide_fields()`.
`hide_fields()` should remove the "permanently visible" status set by `reveal_fields()`. Additionally, if `unexplore=true`, their "previously seen" status should be forgotten and set as unexplored. `hide_fields()` should have no permanent effect beyond that.
Is the above correct?
2. What should happen when `hide_fields()` is called on fields currently seen by the player's (or a teammate's) units?
3. What about team vision? Should `reveal_fields()` reveal fields for just the player it was called on or for the whole team?
4. When the players are then subsequently split into separate teams, should all the teams inherit the "permanently visible" fields or just the original player's team?
5. Does the "permanently visible" status need to be optimized for a large number of revealed fields or is it not necessary?

**Comment by Noordfrees** [comment]
1. Correct, with the exception that `hide_fields(..., true)` should also work on fields that are in the "normal" PreviouslySeen state.
2. Fields that are seen by an own or allied bob or building must be always visible.
3. Allied players share a vision, so every field that is visible for a player must also visible for all of his team mates.
4. The explicitly revealed fields only stay visible for the player for whom they were revealed. The other no-longer-allied players stop seeing those fields.
5. What kind of optimizing do you mean?

**Comment by Niektory** [comment]
Thanks, that clears things up.

> What kind of optimizing do you mean?

I don't have anything specific in mind, I'm just asking if it's a case I should be worrying about. For example storing a large number of them in a `std::set` might not be memory efficient (maybe, I haven't checked).

**Comment by Noordfrees** [comment]
If I remember correctly the endless_game_fogless win condition uses `reveal_fields` to remove the fog of war. So you could check how (in)efficient this is for an eight-player fogless game on a 512×512 map.

**Comment by Niektory** [comment]
Could this be done with `set_see_all()` instead?

**Comment by Noordfrees** [comment]
see_all mode additionally shows the player some stats info about other players' buildings, and makes it impossible to attack them
