### ISSUE TITLE
Trainingscamp window moves down by click on start/stop

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4255]
Clicking on the start/stop button of an empire trainingscamp let the window move down.

**To Reproduce**
1. Load attached save game
2. Make sure the trainingscamp is in upper third of the screen
3. Open the trainibgscamp window
4. Click on start/stop

On each click the window moves a bit down. This happens until the window bottom reaches the bottom of the screen.

[test.wgf.zip](https://github.com/widelands/widelands/files/5208050/test.wgf.zip)

**Expected behavior**
The window should stay at the same position.

**Version:**
 - OS: archlinux
 - Widelands Version: [7b55967@splashscreen] (Debug) but this happens also in master

**Comment by Noordfrees** [comment]
I cannot reproduce. What resolution does your Widelands window have?

**Comment by frankystone** [comment]
The window is 1920x1080 (windowed mode).

Maybe the 2. Point from the first post was wrong. You shouldn't move the window, just click on start/stop. Edit: Once it was moved with the mouse, the issue doesn't appear.

Recently the window moves to the right instead of down when hitting start/stop.

**Comment by Noordfrees** [comment]
Still no luck :(

**Comment by Niektory** [comment]
This way can be reproduced reliably:
1. Set your options like in the screenshot below.
2. Change the window size to the smallest possible (800x600).
3. Open the Training Camp window.
4. Click "Center view on this".
5. Close and reopen the Training Camp window.
6. Click Continue/Stop.

![options screenshot](https://user-images.githubusercontent.com/4470900/92974194-fb2bc980-f485-11ea-9516-0493240ee02f.png)

**Comment by Noordfrees** [comment]
Yes, now I can reproduce too. Looks like the buildingwindow docks to the bottom edge of the WL window (I cannot reproduce anymore after disabling that option).
