### ISSUE TITLE
Inconsistent placement of Save button in economy options

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4256]
Don't know if it is really a bug...

All Windows which have a "Save" or "OK" button has this this button either on the bottom of all other buttons or at right of all other buttons.

Except the "Save" button of the configure economy -> save own values. Here it is on the left of all buttons. Because i am used to click on the most right button to complete a task in widelands, recently i clicked the right button, which deletes my setting.

![save_economy](https://user-images.githubusercontent.com/6730556/92906852-17e3e500-f425-11ea-9f79-6701a67b46ba.jpg)

**Expected behavior**
Similar buttons should always be in the same order in each window.

**Version:**
 - OS: archlinux
 - Widelands Version: [7b55967@splashscreen] (Debug) but also in master

**Comment by gunchleoc** [comment]
I think the idea was to place the button next to the edit field.

How about using a new row for the buttons?

**Comment by Noordfrees** [comment]
> All Windows which have a "Save" or "OK" button has this this button either on the bottom of all other buttons or at right of all other buttons.

Except for the editor map options window

**Comment by frankystone** [comment]
> > All Windows which have a "Save" or "OK" button has this this button either on the bottom of all other buttons or at right of all other buttons.
> 
> Except for the editor map options window

Than those has to be changed also.
