### ISSUE TITLE
Starting a LAN game connects to the online lobby

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4265]
**To Reproduce**
1. Join the online lobby in Widelands (Multiplayer -> Online Game) or join #widelands on IRC.
2. Open another Widelands instance and start a LAN game (Multiplayer -> LAN / Direct IP).
3. You will see in the first client that the second one joined the lobby.

**Expected behavior**
Starting a LAN game does not connect to the online lobby.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: This behavior started in 1.0~git24883[c41b0b3@HEAD] (Debug)

**Comment by klaus-halfmann** [comment]
This is actually a privay issue as this will reveal a (under aged?) user that wanted to stay private.

**Comment by Noordfrees** [comment]
Ups, now what did I do there!? Will investigate… but I cannot reproduce, can you attach a screenshot?

Edit: Now I can reproduce – it only happens when using the dropdown, not with the hotkeys J+P. Will fix.

**Comment by gunchleoc** [comment]
@Noordfrees You added that to your fork

**Comment by Noordfrees** [comment]
I'm fixing this in the main menu redesign follow-up branch. It'll be ready for review quite soon…

**Comment by Niektory** [comment]
This is still happening.

**Comment by Noordfrees** [comment]
Argh, the fix was accidentally deleted during a merge
