### ISSUE TITLE
Incompatible b21 savegame

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4273]
- Open the savegame from https://bugs.launchpad.net/widelands/+bug/1799373/comments/20 with build 21. This will work without problem.
- Resave the savegame with b21.
- Try to load it in current master:
```
widelands: ../src/scripting/lua_map.h:800: const Widelands::TerrainDescription *LuaMaps::LuaTerrainDescription::get() const: Assertion `terraindescr_ != nullptr' failed.
```

**Comment by gunchleoc** [comment]
Here's the resaved savegame to ease testing:

[b21-incompatible.wgf.zip](https://github.com/widelands/widelands/files/5470436/b21-incompatible.wgf.zip)
