### ISSUE TITLE
atlantean scenario selection screen is layouted wrong

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4275]
![grafik](https://user-images.githubusercontent.com/43039887/93463053-7a3a5b00-f8e7-11ea-92f0-fe4e02282b33.png)

further more the text between choose a campaign and chosse a scenario jumps a bit down which does not look good
in the other tribes the distances between "choose a scenario" and the name of the campaign differs as well but is not overlapping

**Comment by Noordfrees** [comment]
Let's wait if this is still a problem when #4054 and #4274 are both in

**Comment by gunchleoc** [comment]
Same bug as https://github.com/widelands/widelands/issues/3985 ? The whole screen needs to be converted to `UI::Box`.
