### ISSUE TITLE
Neptune's Revenge is broken

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4279]
Reported on the forum: [artefacts not recognised after last upgrade](https://www.widelands.org/forum/topic/4954/)

When playing the Neptune's Revenge mission several bugs can be observed (probably all related):
1. Fog of war does not work normally. All explored fields become permanently visible, there is no "previously seen but now hidden" state.
2. Saving and loading the game results in unseen fields being replaced by grass: [Neptune2.wgf.zip](https://github.com/widelands/widelands/files/5251122/Neptune2.wgf.zip)
3. Loading some saves from this mission results in an error message: `view: invalid map_object_descr: artifact03`: [Neptune3.wgf.zip](https://github.com/widelands/widelands/files/5251124/Neptune3.wgf.zip) **(continued in #4359)**

**Screenshots**
![screenshot with unseen fields replaced by grass](https://user-images.githubusercontent.com/4470900/93694457-25c3f500-fb0c-11ea-8c4c-5b1c32cfbf5d.png)

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: Version 1.0~git24892[c3b1479@master] (Release)
If I tested correctly the first problem is there since 02947d690dae1f87131a6db4e686c047939cbdab, the second one since 8088aaa936eed9795921bae3bcfaf5b472c86778.

**Comment by frankystone** [comment]
Another observation: Load attached savegame and wait until the tower was built. The area which reveals if soldiers walks into the tower get revealed before the soldiers arrives at the tower.

[test.wgf_1.zip](https://github.com/widelands/widelands/files/5252262/test.wgf_1.zip)

**Comment by Noordfrees** [comment]
Seems like there are two bugs being mixed up in one thread: One about the artifacts, and one about several vision issues. I will try to have a look at the vision-related issues soonish

**Comment by hessenfarmer** [comment]
i just played the campaign with several reloads and it worked fine for the artifacts with current trunk. However we might have broken savegame compatibility with the object alive checks fix and its reversal (which is quite normal on a dev branch). So I can't confirm 1 and 3 for current trunk. However the grass issue is true although unrelated to this scenario. while it is not always grass nearly everytime the wrong teture is shown. for these fields after reloading. Even in a free game it is not working correctly. ( best to test with discovery or new world starting condition)

**Comment by josephomorrow** [comment]
Playing 1.0~git14[c3b1479@master] (debug):

Neptune's Revenge played fine from the beginning, but with same problems with sound effects as before. After saving, quitting, and reloading game, fog-of-war is broken and grass exists where much of the water should be.

**Comment by hessenfarmer** [comment]
@josephomorrow 
what do you mean with sound problems?   
Did you try the "grass" should be sailable where previously was water. So I believe iot is only a texture problem.   
Is there any other issue with fog of war then the "grass" problem.

**Comment by Noordfrees** [comment]
When all terrains are replaced with meadow1 this always indicates that it is a pure vision problem – a field is being made Visible for the interactive player without `rediscover_node` being called. The actual terrains should be set correctly internally.

**Comment by josephomorrow** [comment]
> @josephomorrow
> what do you mean with sound problems?
Saving game while sound effects are on (I never checked if music does the same), causes infinite console output of:
Partial readout from console after saving game:

[00:06:41.974 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 6 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 2 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 2 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!

(Turning all sounds off stops infinite errors.)

> Did you try the "grass" should be sailable where previously was water. So I believe iot is only a texture problem.
Water looks like "grass" but is sailable like water.

> Is there any other issue with fog of war then the "grass" problem.
Apparently, after reloading saved game, all previously fog-of-war (blacked-out) areas become visible as grass but with original behavior.

**Comment by frankystone** [comment]
@josephomorrow: This is a [different problem](https://github.com/widelands/widelands/issues/4258) and has nothing to do with the problems reported here.

I found that the exchange of terrains reverts if one builds a military building again, so the unseen visible area is the same as defined by the map. It looks to me like _grass_ is used for half visible areas. Anyway i can't get the amount of grass terrain shown like in the screenshot. For me the grass terrain is shown only at the border between visible and invisible areas.

**Comment by Noordfrees** [comment]
Starting emp03 with b21, saving it, and loading with current master works without issue for me.

I can confirm that the tower starts seeing immediately, will be an easy fix.

The interesting thing is that I cannot reproduce the grass issue by starting a new game on emp03, saving and reloading:
![shot0000](https://user-images.githubusercontent.com/48293446/94006022-7b640000-fd9f-11ea-9627-4a6f0f19b241.png)
The savegames attached in this thread were created with incorrect data which is being loaded correctly. To fix that I'd need steps how to create a savegame that will show this issue…
(edit: I can only reproduce that the edges between PreviouslySeen and Unseen areas are grass – I'd rather fix both issues in one go though)

**Comment by Niektory** [comment]
Here's a video: [That's a lot of seaweed.mkv.zip](https://github.com/widelands/widelands/files/5268228/That.s.a.lot.of.seaweed.mkv.zip)

**Comment by Noordfrees** [comment]
Thanks :)
One would think the compiler would complain about an implicit conversion from `const FCoords&` to `MapIndex`, but no, it silently performs the conversion and this is what we get :P 
The seaweed borders near unexplored areas are a bit more involved to fix because terrain (and edges) information is not being written to the savegame for those, will fix that too now

**Comment by Niektory** [comment]
> One would think the compiler would complain about an implicit conversion from const FCoords& to MapIndex, but no, it silently performs the conversion and this is what we get :P

https://github.com/widelands/widelands/blob/e5cb07646911fdd665222a9d4c1bfcf381705ae0/src/logic/widelands_geometry.h#L59

¯\\_(ツ)_/¯
