### ISSUE TITLE
Buildings are half translucent

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4291]
This image was made with the multithreading branch, but in master it's the same.

![multithr_half_visible_hq](https://user-images.githubusercontent.com/6730556/94429824-3b33c180-0193-11eb-8ce8-9086b521dc3c.png)

**To Reproduce**
Just start a new game.

**Version:**
 - OS: archlinux
 - Widelands Version: [4e9992f@master] (Debug)

**Comment by Noordfrees** [comment]
What checkboxes are checked under Options – New Games? It works fine for me

**Comment by frankystone** [comment]
Ahhh, there is a new option...

When i started widelands after compiling i didn't looked into the options with the result shown above. After uncheck/check the corresponding option the buildings are shown.

If i rename the config file and start widelands again, the buildings are translucent again. The corresponding option is marked. So to sum up:

1. Rename the config file
2. start widelands
3. look into options -> New Game: the option Show Buildings is checked. Click on Cancel
4. Start a new game

Result: Buildings are translucent here

**Comment by Noordfrees** [comment]
Can you try whether this fixes the issue:
```
diff --git a/src/wui/interactive_base.cc b/src/wui/interactive_base.cc
index 27e0e21c79..7d4813da4f 100644
--- a/src/wui/interactive_base.cc
+++ b/src/wui/interactive_base.cc
@@ -178,9 +178,9 @@ InteractiveBase::InteractiveBase(EditorGameBase& the_egbase, Section& global_s)
      workareas_cache_(nullptr),
      egbase_(the_egbase),
 #ifndef NDEBUG  //  not in releases
-     display_flags_(dfDebug | get_config_int("display_flags")),
+     display_flags_(dfDebug | get_config_int("display_flags", kDefaultDisplayFlags)),
 #else
-     display_flags_(get_config_int("display_flags")),
+     display_flags_(get_config_int("display_flags", kDefaultDisplayFlags)),
 #endif
      lastframe_(SDL_GetTicks()),
      frametime_(0),
```

**Comment by frankystone** [comment]
Yep, that seems to fix it :-)

Do you want me to create a pull request or do you apply this small change directly?
