### ISSUE TITLE
Editor player menu crashes on setting tribes

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4296]
**To Reproduce**
1. Create a new random map
2. Press 'p' to bring up the player menu
3. Try to change 'Random Tribe' with a tribe

Result:
~~~~
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/editor/ui_menus/player_menu.cc:301: void EditorPlayerMenu::player_tribe_clicked(size_t): Assertion `tribename.empty() || eia().egbase().tribes().tribe_exists(tribename)' failed.
Abgebrochen (Speicherabzug geschrieben)
~~~~

**Version:**
 - OS: archlinux
 - Widelands Version: [4e9992f@master] (Debug)

**Comment by Noordfrees** [comment]
This also happens when pressing P directly after starting the editor and choosing a tribe for a player.

@gunchleoc

**Comment by matthiakl** [comment]
Is it necessary to have the tribes loaded for the editor? Without the assert, everything seems to work, but I don't have much experience with the editor.

Otherwise, all tribes have to be loaded during editor startup. This was removed in PR #3693 .

```
--- a/src/editor/editorinteractive.cc
+++ b/src/editor/editorinteractive.cc
@@ -956,6 +956,7 @@ void EditorInteractive::run_editor(const std::string& filename, const std::strin
                egbase.create_loader_ui({"editor"}, true, kEditorSplashImage);
                eia.load_world_units();
                egbase.tribes();
+               egbase.load_all_tribes();
 
                {
                        if (filename.empty()) {

```

**Comment by gunchleoc** [comment]
We should use `TribeBasicInfo::tribe_exists(const std::string& tribename);` which loads just the basic info from Lua.

We do this in GameSettings somewhere too, where the info is stored in a variable so we don't have to rerun the Lua script for every check.
