### ISSUE TITLE
Minimap far too large

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4300]
When starting a game on a 64×512 map (low width, big height) at 1024×768 window resolution, the minimap is scaled up to many times the screen height. It should be small enough to fit on the screen completely.
![shot0003](https://user-images.githubusercontent.com/48293446/94602174-cfd21880-0294-11eb-849b-c8032037e56e.png)

**Comment by frankystone** [comment]
There was a similar issue when clicking on 2x in the minimap window with big maps and small screen resolution, but i can't find it anymore. Anyway this seems related to me.

**Comment by matthiakl** [comment]
Scaling the map only considers the width and not the height:
https://github.com/widelands/widelands/blob/9919ef5bf50f6873f36c594eb506d32e702d666d/src/graphic/minimap_renderer.cc#L273-L287
