### ISSUE TITLE
Map description in MP/SP setup screen does not scroll

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4309]
**Describe the bug**
The small map details textbox in both SP and MP does not scroll with the mouse wheel

**To Reproduce**
1a. Select a singleplayer map
or
1b. Start a multiplayer game and select a map
2. Move the cursor over the map description
3. Try scrolling using the mouse wheel

**Expected behavior**
The description should follow the mouse wheel.

**Version:**
 - OS: Arch Linux
 - Widelands Version: [`472f9102`@master] (Debug)

**Comment by Noordfrees** [comment]
will be fixed by #4301
