### ISSUE TITLE
Kicking a player causes a crash

### ISSUE THREAD

**Issue by MartinSchmidt123** [widelands/widelands#4318]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
When you host a game and kick a player before the game starts, the game will crash for the hosting player.

**To Reproduce**
1. Host a multiplayer game.
2. Open a second instance of widelands and join your game.
3. Do not start the game, but kick the joined player from the game using /kick <player> and /ack_kick <player>
4. The game will crash with error: 

`widelands: [..]/widelands/src/network/nethostproxy.cc:263: void NetHostProxy::receive_commands(): Assertion `clients_.count( id)' failed.`

**Expected behavior**
The game stays open and can be continued without the kicked player.

**Screenshots**
Not needed.

**Version:**
 - OS: Arch Linux
 - Widelands Version: Build 21 and current master 472f910242b8d23c51211ada5a42e6ed88ca5178

**Additional context**
* It seems that also the output of the commands /help, /kick <player> etc. are send to all players.
* The game crashes also while kicking a player during a game.

**Comment by Notabilis** [comment]
Thanks for reporting, should be fixed soon.
Small addition: This only happens when the metaserver is used but not for LAN games.
