### ISSUE TITLE
Window not maximized when hitting Apply or OK in options

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4322]
**Describe the bug**
Sorry, another window maximized issue:
The button OK and Apply do not work when one sets Window: Maximized in the options.

**To Reproduce**
1. Open Options window
2. Choose resolution 800x600
3. Click Apply -> The window get resized
4. Choose resolution: Window Maximized
5. Click either Apply or OK

Nothing happens. When Restarting widelands the resolution will be 800x600

**Version:**
 - OS: archlinux
 - Widelands Version: [152e1cb@master] (Debug)

**Comment by Niektory** [comment]
Works for me. Can you reproduce with this branch and post the log output? https://github.com/Niektory/widelands/tree/4322_debug_maximize

**Comment by frankystone** [comment]
[bug_4322.txt](https://github.com/widelands/widelands/files/5325439/bug_4322.txt)

Looks my statement 

> When Restarting widelands the resolution will be 800x600

Was wrong. May i have clicked 'Cancel' in the options. If i click OK and restart widelands the window get maximized.

**Comment by frankystone** [comment]
Here is a video of the issue created with your branch. You have to unzip it:

[bug_4322.zip](https://github.com/widelands/widelands/files/5325597/bug_4322.zip)

**Comment by Niektory** [comment]
`SDL_MaximizeWindow()` is called, and after that `SDL_GetWindowFlags()` reports that the `SDL_WINDOW_MAXIMIZED` flag is set. Yet the window is not actually maximized. What else am I supposed to do, call `pretty_please()`?

I'm afraid I'm out of ideas.

**Comment by frankystone** [comment]
Maybe its related to SDL and my window manager? There are some issues with the window manager right now, but i have noticed them as qml/qt bugs of kde plasma, not related to sdl.

SDL version: 1.2.15-14
Window Manager: kwin, version 5.19.5-2

**Comment by frankystone** [comment]
This is working again, at least with branch multithreading_new.
