### ISSUE TITLE
Tutorials: Automatic mouse move does not work with drop-up menu

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4341]
In the first tutorial the section to show/hide buildhelp does not work correctly. The mouse pointer moves to the bottom show/hide menu but not walks up the menu entries. The mouse pointer sticks at the bottom menu.

**To Reproduce**
1. Start first tutorial
2. Do the things the tutorial wants you to do
3. The message box to toggle the buildhelp appears
4. after clicking OK you will see

**Expected behavior**
The mouse pointer should go up the menu entries until it reaches the 'Show Buildhelp' menu entry and should make a click there.

**Version:**
 - OS: archlinux
 - Widelands Version: [7a3a5ab@master]

**Comment by flegmaatikko** [comment]
I can reproduce the bug. I think the incorrect behavior happens two times. The menu opens again after it was closed. But this may be the wanted behaviour.
There are also multiple clicking sounds when clicking the OK button of the  "Welcome the Widelands!" message box.

**Comment by gunchleoc** [comment]
The dropdown entries are selected by simulating a keyboard shortcut. I decided against using mouse clicks there, because if we redesign anything in those menus that changes the height of the entries, it will stop working.

If somebody wants to implement detection for dropdown menu list position, width and entry height for Lua, that will be fine and certainly an improvement for this scenario.

**Comment by frankystone** [comment]
I think for the menus we do not need such 'I'll show you how ...' with automatic mouse moves, maybe only 'I'll show where to find ...' and another message box describing the menu and the corresponding shortcuts. In this case the message box should request to press 'space' (or whatever one is wanted).

**Comment by flegmaatikko** [comment]
Sounds good. The tutorial continues after the player has practiced enough and has closed the message box.
It requires some kind of selective user input blocker where only the corresponding shortcuts are active.

**Comment by gunchleoc** [comment]
The tutorial continues when the player has done it, like for all other objectives. We use the actual state of the option for detection, so no problem there.

So, "I'll show you where the menu is" and click on the menu button, then let the user select the item from the dropdown or press the hotkeys as they see fit.

**Comment by frankystone** [comment]
I think this is fixed...
