### ISSUE TITLE
White border disturbs campaign message windows

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4343]
Message windows in campaigns and/or tutorials have a white border around the text. The text is too close to the border:
![white_border](https://user-images.githubusercontent.com/6730556/95679076-d0da4280-0bd0-11eb-9088-cae0fa8137b7.jpg)

The white rectangle has no meaning in this message boxes and is more disturbing than helpful.

**To Reproduce**
1. Start a tutorial

**Expected behavior**
Either the white border should be removed from those windows (preferable), or text should get more padding.

**Version:**
 - OS: archlinux
 - Widelands Version: [8f3fded@multithreading_new] (Debug)

**Additional context**

**Comment by Noordfrees** [comment]
This is the focus overlay that is drawn around the MultilineTextarea to indicate that any key presses (e.g. Up, Down) will be handled by the text area. *Not* having such an indicator would be a bug. 
Would it be enough for you to draw the silver overlay only around the scrollbar rather than the whole text area for MultilineTextareas?

**Comment by frankystone** [comment]
> This is the focus overlay that is drawn around the MultilineTextarea to indicate that any key presses (e.g. Up, Down) will be handled by the text area. _Not_ having such an indicator would be a bug.

Isn't the window itself marked to have the focus? Since such windows can only react on scrolling or closing (button click) it seems useless to me to have such an indicator.

> Would it be enough for you to draw the silver overlay only around the scrollbar rather than the whole text area for MultilineTextareas?

I am unsure. I don't like it all, maybe because of the coloring which is too disturbing, maybe because i had never trouble to find the things which have the focus, maybe because i am not familiar to have such an indicator, maybe because i am mostly use the mouse instead of the keyboard.

Another example: If you open the Tribal encyclopedia and open the wares tab, initially no Textarea has such a border. You can scroll with the mouse wheel. By a click the textarea gets suddenly this silver rectangle. For me it is quite disturbing because i have no idea why this rectangle suddenly appears and steels the focus from the things i want to read. Some ware details (the right part of the window) has no textarea, some have. Clicking on ware details which have the textarea switches the silver rectangle to the wares details, but for ware details which have no textarea, let the silver rectangle just disappear. It's just confusing me.

**Comment by Noordfrees** [comment]
The window has multiple child elements that can get focus: The textarea, the OK button and the three window titlebar buttons. So we do need a focus indicator.

Another option would be to put the focus on the OK button instead of the text area by default. 

> Another example: If you open the Tribal encyclopedia and open the wares tab, initially no Textarea has such a border. You can scroll with the mouse wheel. By a click the textarea gets suddenly this silver rectangle.

This is because the focus is first on the TabPanel because that's where you clicked first, and then you move it to the BaseListSelect by clicking on that.

---

So as I understand it, this issue is about the current focus overlay indicator being disturbing? Then we should consider alternatives to highlight the focused UI element in a less disturbing manner. But we always need to have a clear indicator for it, because not having one would be hostile to users who prefer to navigate with the keyboard.

**Comment by frankystone** [comment]
> So as I understand it, this issue is about the current focus overlay indicator being disturbing? 

Yes.

> Then we should consider alternatives to highlight the focused UI element in a less disturbing manner. But we always need to have a clear indicator for it, because not having one would be hostile to users who prefer to navigate with the keyboard.

I have to play and think of it a bit. Visually handicapped people might need such an focus overlay, whereas  other people find it annoying. In the end we may need a new option 'Use high contrast coloring'?

**Comment by gunchleoc** [comment]
How about putting the focus indicator around the scroll bar?

**Comment by Niektory** [comment]
I think the focus indicator doesn't need to be very prominent. One pixel thick might be enough, or maybe dotted lines. See here for example:

![shot0103](https://user-images.githubusercontent.com/4470900/96144382-642eb300-0f04-11eb-9124-2fb86f2a26f9.png)

The focus indicator is more prominent than the selection indicator, while the latter is more important.

It also overlaps the borders of buttons so they no longer look like buttons when focused (or pressed) – perhaps it could be drawn inside them, not at the very edge?

Perhaps one size does not fit all and some UI elements could use a customized indicators.

**Comment by Noordfrees** [comment]
Regarding the screenshot, those orange lines are not very prominent anyway. How about making them a pixel wider, and perhaps darkening the background when the statebox is selected?
Custom indicators are already implemented and used by e.g. tables, so it should be easy to move them further inside for buttons. I'll also make the focus indicator narrower; dotted lines are not trivial though.

**Comment by Niektory** [comment]
> Regarding the screenshot, those orange lines are not very prominent anyway. How about making them a pixel wider, and perhaps darkening the background when the statebox is selected?

Darkening the background sounds good, the lines could be a little brighter too. That should be enough. Thicker lines would obscure part of some icons (though that's not a major problem).
