### ISSUE TITLE
Rethink game window overlay strings

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4345]
The overlay strings in the game window corners can be a bit annoying. We have a clock in the upper left corner, the speed in the upper right, the coords in the lower right, autosave info messages in the lower left, the FPS in the middle of the upper screen border, and of course the toolbar in the bottom middle.

All these overlay strings are useful and important, but it is annoying when they are drawn on top of some edge-docked window and you effectively can read neither the info string nor the window content.

I propose to improve this by drawing an opaque panel the same height as the toolbar across the whole screen width both at the bottom and the top edge, and snapping windows to those panels rather than to the top/bottom screen border. All the info texts would then be drawn on this Wui-styled panel (perhaps as textareas) with no readability issues. 
In release builds, the top panel would have a lot of free space because no FPS is shown there – this could be filled up e.g. with a Widelands logo or some other nice decoration.

**Comment by frankystone** [comment]
Yes, i also think that it can be improved. But i would propose to have those (or part of those) strings in an optional window similar to the Info tool in the editor. Most of them are uninteresting in a normal game, imho. At least uninteresting most of the time. The Toolbar should stay where it is. May the new window can be opaque without borders to differenciate between game windows and this info window. Or make it like all other windows so it can be snapped to the other windows.

Currently the window border is a bit big. May we can make it some smaller?

What i would really like to see is that messages are popping up at the top middle, sliding down from the top. Messages shown there should be restricted to an amount of the last three messages, and clicking on this area will bring up the messages window. The saving game string should also go in there then.

To sum my idea up:
* leave Man menu (Toolbar) where it is
* Clock, FPS and Coords in a new (opaque?) window which can be opened on demand, e.g. with a shortcut 'i'
* Messages and autosave messages in a new section in the top middle. If new messages arrive, this section slide down to show the last three messages and vanish after some seconds again (slide up). Clicking on the slided down section will bring up the messages window.

**Comment by Noordfrees** [comment]
> Currently the window border is a bit big. May we can make it some smaller?

The top border needs to stay this big so the title fits, but +1 for shrinking the other borders

> What i would really like to see is that messages are popping up at the top middle, sliding down from the top. Messages shown there should be restricted to an amount of the last three messages, and clicking on this area will bring up the messages window. The saving game string should also go in there then.

Big +1 :) 

> Clock, FPS and Coords in a new (opaque?) window which can be opened on demand, e.g. with a shortcut 'i'

-1. IMHO, this info is important all the time. But how about reusing my idea about a top-bar panel where all this info should go, and adding a button to the panel's corner to toggle its visibility?

**Comment by Niektory** [comment]
> IMHO, this info is important all the time.

I don't think it is. But it doesn't hurt much to have it always on either.

How about integrating (some of) the strings in the toolbar, to not clutter the screen with other always visible elements?

**Comment by Noordfrees** [comment]
I was thinking about something like this:
![shot0001](https://user-images.githubusercontent.com/48293446/95761844-2b48d100-0cad-11eb-879c-8b1347fe716c.png)
Pressing the button in the top right corner toggles the panel's visibility

**Comment by Niektory** [comment]
It wastes space I think, most of it is unused. We already have the toolbar so I think any additional stuff should go in there if feasible.

**Comment by gunchleoc** [comment]
> I was thinking about something like this:
> ![shot0001](https://user-images.githubusercontent.com/48293446/95761844-2b48d100-0cad-11eb-879c-8b1347fe716c.png)
> Pressing the button in the top right corner toggles the panel's visibility

How about putting the new element on the bottom? We lose less screen space that way. The FPS could be moved right or left.

Also, have a look at the discussion in https://www.widelands.org/forum/topic/2769/ for a previous redesign attempt that ended up in our current bottom toolbar. Since some of the images are not visible in-line, I'll repost them here for reference.

![toolbar](https://user-images.githubusercontent.com/4095570/95768229-e8d3c400-0cad-11eb-9589-14dd9aca7a2b.png)
![toolbar3](https://user-images.githubusercontent.com/4095570/95768238-ea04f100-0cad-11eb-9b70-306ecca533fc.png)
![toolbar4](https://user-images.githubusercontent.com/4095570/95768240-eb361e00-0cad-11eb-983c-fe58500bdab0.png)
![toolbar-side2](https://user-images.githubusercontent.com/4095570/95768245-ec674b00-0cad-11eb-97ef-ce524ef6f203.png)

**Comment by frankystone** [comment]
I agree with Niektory. 

If playing in window mode, the window has two top 'menus' then: The one shown in the screenshot above and the one of the system.

The coords are only visible in debug builds, afaik. And FPS isn't much informational  to normal users, imho. So what is important in a release build are the time and the speed. May those can be assembled somehow in the main menu (toolbar), but i can not imagine how :-)

I believe having a window for those values will fit to all circumstances. One can open it, close it or minimize it. It's the players choice if he wants to have access to those information or not. In debug builds the other values (FPS, coords) can be added to this window. It will be very small anyway. Last but not least it fits with the widelands style and if this style ever get changed, it will be easier to do this (e.g. smaller borders)

I think the examples of GunChleoc are also too much space consuming, although nice...

**Comment by Noordfrees** [comment]
Maybe the toolbar icons could also be moved to the top panel then?
The message preview should drop out from the screen top, which would look better if there's a panel there, like this:
![shot0003](https://user-images.githubusercontent.com/48293446/95768826-3dc80800-0cb7-11eb-9b62-3094bb46e94c.png)

**Comment by Noordfrees** [comment]
WIP branch for testing: https://github.com/Noordfrees/widelands/tree/game_overlays_redesign

**Comment by frankystone** [comment]
I think we won't need a panel (mockups):

![screen_rework_1](https://user-images.githubusercontent.com/6730556/95777474-85a25b80-0cc6-11eb-9aec-79ed742e9dfd.png)
![screen_rework_2](https://user-images.githubusercontent.com/6730556/95777483-8b983c80-0cc6-11eb-995a-ccb0d9a39ea7.png)

Might be difficult with localized messages and string length.

**Comment by Noordfrees** [comment]
Not having some kind of panel would not solve the initial issue that the overlay texts are hard to read and clash with window content.

So let's have one panel as wide as the screen which contains the toolbar as well as all strings? We could
1. have it on the screen top, and let new messages drop down from it (my preferred), *or*
2. have it on the screen bottom (like the toolbar now) and have messages pop upwards, *or*
3. have the panel on the bottom, and messages drop in from the screen top with no connection to the panel.

Edit: I think the closed message scroll in your upper mockup image looks disturbing, because it makes it look as if there is something important there when there isn't. The message indicator should only be visible when there is a message.

**Comment by gunchleoc** [comment]
Before we make a big messages refactoring, we should improve the chat overlay (which also prints the Game Saved... messages) and see how that goes.

At the moment, we have an option of whether to draw a transparent darkened background behind chat messages. We could make that non-optional (because it's off by default I think) and work on that background to make the messages more readable.

I'm also in favour of left-aligning rather than center-aligning the messages, and right-aligning for RTL languages.

Once the chat overlay is working fine, we can then think about whether we want more messages there.

I agree that my mockups are space-consuming, if we go for any of those layouts, we should lose the window border.

Maybe something like this, only with centered toolbar?

![toolbar](https://user-images.githubusercontent.com/4095570/95768238-ea04f100-0cad-11eb-9b70-306ecca533fc.png)

**Comment by frankystone** [comment]
> Not having some kind of panel would not solve the initial issue that the overlay texts are hard to read and clash with window content.

The mockup does not reflect the idea of having overlay texts in a new window. Sorry if that was not clear.

> Edit: I think the closed message scroll in your upper mockup image looks disturbing, because it makes it look as if there is something important there when there isn't. The message indicator should only be visible when there is a message.

No :-) It indicates that there _can_ something happen. As soon the first message arrives it should be clear to player.

> Once the chat overlay is working fine, we can then think about whether we want more messages there.

So there will be a mix of chat messages and ingame messages?

If we go for a panel it should adjustable on which edge of the screen it should be displayed. Some like it at the bottom, some at the top and others on the left/right.

**Comment by gunchleoc** [comment]
We are actually discussion 3 things in this issue:

1. The game speed overlays etc, which was the original issue reported
2. The chat overlays, because they are also overlays
3. The discussion expanded to refactoring the message window too

**Comment by Noordfrees** [comment]
In my opinion we should not mess up chat and messages, nor refactor the message window. The new message dropping-in indicator should only be an addition to the message menu, because currently the arrival of a new message is not very conspicuous if you disabled that annoying sound effect, and it is much more convenient to know at once what the new message is about (and in my branch you can jump to the place of interest simply by clicking on the message indicator).
I have moved the autosave messages away from the chat to the message drop-in. 
The chat is fine as it is for me (I don't use it though…)

> I'm also in favour of left-aligning rather than center-aligning the messages, and right-aligning for RTL languages.

+1

> I agree that my mockups are space-consuming, if we go for any of those layouts, we should lose the window border.
> Maybe something like this, only with centered toolbar?

How do you mean exactly?

> If we go for a panel it should adjustable on which edge of the screen it should be displayed. Some like it at the bottom, some at the top and others on the left/right.

+1, though left/right would not work because the info strings would be too broad

**Comment by gunchleoc** [comment]
I thought you were suggesting a refactoring of the messages because of your mockup example where they show up in the top middle of the screen (https://github.com/widelands/widelands/issues/4345#issuecomment-707216708).

> How do you mean exactly?

The top bar from your mockup on the bottom, and maybe add some icons to the time strings. I had also suggested adding realtime so that one doesn't need to leave fullscreen to check what time it is, but that got a -1 from SirVer because it breaks immersion. So, if we should decide to add real time, it needs to be an option.

With a bar at the bottom, we lose less screen space, because some is lost anyway for the current toolbar buttons.

**Comment by Noordfrees** [comment]
More like this?
![shot0000](https://user-images.githubusercontent.com/48293446/95998639-5b22e080-0e35-11eb-9376-9ca98a18570d.png)
There is a new option whether the info panel and toolbar should be on the bottom (default) or top.
Its visibility can be switched between visible, hidden, and only visible on mouseover with the dropdown in the corner.
The realtime clock can also be en-/disabled in the options (I replaced the game_clock with this one because you can now disable the game clock simply by hiding the info panel).

**Comment by frankystone** [comment]
Hm... maybe make the panel as height as the menu buttons are. And remove the menu backgroundgraphics? And make the menu as wide as the width of the messages box.

But to be honest: I think there is too much information, and i think some this information is superfluous. At least in release builds, for a non-dev player. Is there a need to display the current time? And as previously said: The coords are only available in debug builds. Imagine this panel in a release build.

Looks my idea of a window containing all those information has no majority?

**Comment by Noordfrees** [comment]
Didn't I make this clear? FPS and coords are shown only in debug of course (coords also in the editor). And the realtime string is optional. Will try out increasing the height and removing the background graphics.

> And make the menu as wide as the width of the messages box.

Since SP, MP, Replay, MP spectator, and Editor all have differing amounts of buttons (and some are very narrow), this could only be done by either making the gaps size vary to fill the space, or having differing a message width. Which one is the lesser evil?

> Looks my idea of a window containing all those information has no majority?

A window would take away far more screen space than a narrow panel. And this panel can also be collapsed so it takes up no space at all, so it's almost like a top-docked unmovable window that can be easily minimized…

**Comment by Noordfrees** [comment]
Debug, realtime enabled, info panel on the bottom:
![shot0001](https://user-images.githubusercontent.com/48293446/96021815-3be57c80-0e50-11eb-85a2-b96f0edf42fe.png)
Release, realtime disabled, info panel on the top:
![shot0004](https://user-images.githubusercontent.com/48293446/96021837-4273f400-0e50-11eb-8a36-d3bf18f32e30.png)
I have changed the toolbar so the background graphics are only drawn if the info panel is hidden.
This is revision 5ded70f52a.

**Comment by gunchleoc** [comment]
I prefer the bottom layout.

What is the extra "Raadhus" etc? I thought we were not refactoring the messages window in this discussion? Or is it a placeholder for chat messages? In any case, having this centered below the menu when the bar is on top is not a good idea, since the menu would drop on top of it.

**Comment by frankystone** [comment]
> What is the extra "Raadhus" etc? 

The idea is to have game messages (not chat messages) popping up (sliding down) at the bottom screen and clicking on such an entry will open the normal message window.

I think the font there could be smaller and images shouldn't be shown there.

**Comment by Noordfrees** [comment]
> The idea is to have game messages (not chat messages) popping up (sliding down) at the bottom screen and clicking on such an entry will open the normal message window.
>
> I think the font there could be smaller and images shouldn't be shown there.

I have implemented that left-clicking a message preview will jump to the associated map location. This is more useful in my opinion because when you see e.g. that your quarry is out of stones or your sentinel under attack, you would usually do nothing except hit G when viewing that message in the message menu. (At least that's what I do…) 
And you can see the full message text when mousing over the message preview.

Right-clicking dismisses the preview. How about adding a row of small buttons (instead of the image, I don't like it much either) for Viewing the message, Marking as read, Marking as archived, Jumping to the location, Closing the preview?

The preview used to be about 2/3s of the current size but that made it a tiny click target in my opinion. Also the text might seem lost if it is made any smaller while keeping the size. Not sure what is best…

**Comment by frankystone** [comment]
> I have implemented that left-clicking a message preview will jump to the associated map location. This is more useful in my opinion because when you see e.g. that your quarry is out of stones or your sentinel under attack, you would usually do nothing except hit G when viewing that message in the message menu. 

Sounds logical to me. Bringing up the _real_ message window is also only one click away.

> And you can see the full message text when mousing over the message preview.
> 
> Right-clicking dismisses the preview. 

All fine, imho :-)

> How about adding a row of small buttons (instead of the image, I don't like it much either) for Viewing the message, Marking as read, Marking as archived, Jumping to the location, Closing the preview?

That should be only in the _real_ message window imho. Otherwise it will be some sort of useless.

> The preview used to be about 2/3s of the current size but that made it a tiny click target in my opinion. Also the text might seem lost if it is made any smaller while keeping the size. Not sure what is best…

I have to test it...

**Comment by frankystone** [comment]
Can you link a branch please?

**Comment by gunchleoc** [comment]
GitHub doesn't allow linking branches, only PRs. So, here's the link from above again: https://github.com/Noordfrees/widelands/tree/game_overlays_redesign

**Comment by frankystone** [comment]
Thanks, i have overlooked the link :-)

**Comment by frankystone** [comment]
Finally i had some time to test this branch, rev c22e05d@game_overlays_redesign.

Some thoughts:
- It took me some time to understand the option "Follow mouse" and found the functionality at random. But in general very nice :-) The panel menu (Pin/Follow Mouse/Hide) is somehow lost in the left corner. The only idea i had is to integrate this menu in the main menu but this would feels also not good to me. 
- The option to to show the bottom at top or bottom is also nice. Some of the (old) Menu background images do not fit if the menu is shown on top and the panel is hidden though.
![menu_panle](https://user-images.githubusercontent.com/6730556/99143561-b88d9580-265e-11eb-809b-390bdece0bcb.jpg)
- Very nice to have a 'time-progress-bar' which shows the balance time for a message.
- When loading a save game the last three messages appears. I think there should be no messages shown then.
- Currently the messages popup appear always at the top, although the main menu is at the bottom. I think it would be better if the messages popup would popup where the main menu is. So if it is at the bottom, the messages should also popup at the bottom.
- The wooden background of the messages is a bit hard. Can we have a semi transparent background? No wood, just a darkened area? And no images, imho. 

> Right-clicking dismisses the preview.

What about right clicking will bring up the messages inbox?

![shot0003](https://user-images.githubusercontent.com/6730556/99143685-bf68d800-265f-11eb-80d7-376f61f951a9.jpg)

**Comment by Noordfrees** [comment]
Thanks for testing and for the good suggestions :) 
All implemented except that I also don't know a better place for the displaymode dropdown. 
The mousebutton bindings for message previews are now
- Left: Center view
- Middle: Close message preview
- Right: Open message menu with this message selected

I decided to remove the position option again and instead added a "flip to top/bottom" button directly to the toolbar's dropdown; the last state of the dropdown (position and visibility mode) is now stored in the config file.
