### ISSUE TITLE
Minimap misses territory information

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4356]
The minimap's territory layer incorrectly displays the player's own territory as "unowned" near the player's roads, flags and buildings.
![shot0000](https://user-images.githubusercontent.com/48293446/95882153-a7104f80-0d79-11eb-9d2b-5cd95574707b.png)

**Comment by Niektory** [comment]
The minimap renderer reads the owner data from `Player::fields_`. On saveloading this data is preserved for `kPreviouslySeen` fields, but not for `kVisible` fields. The minimap renderer could just read it from `Map::fields_` for `kVisible` fields – this would be a trivial fix.

The question is, should the data for `kVisible` fields in `Player::fields_` be rediscovered after loading or is it not needed?

**Comment by Noordfrees** [comment]
We'd better rediscover it, there may be more places that read data from the Player::Field (now and in the future)
