### ISSUE TITLE
invalid map_object_descr in Neptune's Revenge

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4359]
Since I crammed too much into issue #4279 I'm making a separate one just for the artifact problem, which is still present in the current version.

Here are two savegames: [neptuneagain.zip](https://github.com/widelands/widelands/files/5376817/neptuneagain.zip)
`Autosave 03` is the last loadable one, `Neptune’s Revenge (Defeat the Barbarians)` is the first unloadable one. Loading the latter shows the error: `view: invalid map_object_descr: artifact02`

**To reproduce:**
Loading `Autosave 03` from [neptuneagain.zip](https://github.com/widelands/widelands/files/5376817/neptuneagain.zip), defeating the barbarians (they only have 1 warehouse left) and saving produces a broken savegame.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24934[93ec84d@master] (Release)

**Comment by gunchleoc** [comment]
I can reproduce this on https://github.com/widelands/widelands/commit/93ec84d3eba297c02e2f8cec79ba880f8a23447c but not on https://github.com/widelands/widelands/commit/404f2c475a4da604bd135adbdee3b1fd82800cde

So, the recent changes to the vision code fixed it.
