### ISSUE TITLE
Basic tutorial improvement suggestions

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4365]
Ideas to unclutter the first tutorial

https://www.widelands.org/forum/post/35041/

![1](https://user-images.githubusercontent.com/4095570/96083846-e774e800-0eb5-11eb-834b-1a434ca55f96.png)
![2](https://user-images.githubusercontent.com/4095570/96083850-e8a61500-0eb5-11eb-88b5-96ec05a63b48.png)
![3](https://user-images.githubusercontent.com/4095570/96083852-e93eab80-0eb5-11eb-9ffb-ca6586e627f1.png)
![4](https://user-images.githubusercontent.com/4095570/96083853-e9d74200-0eb5-11eb-934e-1d69fefaf93b.png)
![5](https://user-images.githubusercontent.com/4095570/96083854-ea6fd880-0eb5-11eb-94e6-64d411c58569.png)

**Comment by gunchleoc** [comment]
Tweaking the texts is a good first issue. Implementing the arrow is a bit more advanced and needs C++ changes.

**Comment by frankystone** [comment]
May i find time (and motivation) to work on this. It will take some time though...

**Comment by andy5995** [comment]
And what do you think about replacing some the text like

>There are five different tribes in Widelands: the Barbarians, the Empire, the Atlanteans, the Frisians and the Amazons. All tribes have different economies, strengths, and weaknesses, but the general gameplay is the same for all. We will play the Barbarians for now

with something like:

>For this tutorial, we will play the Barbarians tribe.

My thinking is that the tutorial should focus on game mechanics, rather than include info that is already in the general game documentation (to make the tutorial easier to maintain).

**Comment by hessenfarmer** [comment]
Well the Wiki is not well maintained. and the online encyclopedia lacks some coding changes to be in line with the ingame encyclopedia. 
Reason is that we decided to maintain only in game help and tutorials completely as this is the first hand information for new players.
So I am against deleting too much information. We already deleted some clutter while keeping all relevant information

**Comment by tothxa** [comment]
I've just realised that this issue is based on one user's comments, which also spawned the training wheels effort. I actually liked the verbose tutorials when I first tried Widelands.

I think we should close this, as superseded by #4396. The basic tutorial (as long as training wheels don't replace it ;) needs different modifications.
