### ISSUE TITLE
AI code bugs

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4368]
In AI code, there are at least two places where invalid function arguments are passed, and the AI relies on negative times and durations which needs to be refactored as these can no longer be negative. See #4325

_Originally posted by @gunchleoc in https://github.com/widelands/widelands/pull/4325#discussion_r506102102_

In `defaultai.cc`:

```
// this is set to negative number, otherwise the AI would wait 25 sec
// after game start not building anything
// TODO(Nordfriese): …but times can no longer be negative. Seems to be working fine though…
bo.construction_decision_time = Time(0);  // -60 * 60 * 1000;
```

```
// TODO(Nordfriese): Passing a PlayerNumber to a function that expects
// a Time is a very bad idea, no idea what was intended here…
inputs[26] = (player_statistics.get_modified_player_power(pn) >
              player_statistics.get_visible_enemies_power(Time(pn)));
inputs[27] = (player_statistics.get_modified_player_power(pn) <=
              player_statistics.get_visible_enemies_power(Time(pn)));
```

**Comment by tibor95** [comment]
What else in addition to that #4325 comment?

**Comment by hessenfarmer** [comment]
@tibor95 
the related branch identified the bug described in the 2nd code sniplet above where a player number is passed to a function that expects the actual gametime. This had no real bad effect so far but might mildly effect the weighting in the related part.  
Furthermore the branch of @Noordfrees resulted in time not allowed negative values anymore. Therefore I proposed "change the semantic of the construction_decision_time to be actual gametime +25 sec and check whether we have gametime bigger then construction_decision_time" where the 25 sec could be the currently used kBuildingMinInterval
this is to avoid the AI doing nothing for the first 25 seconds

**Comment by hessenfarmer** [comment]
Additionally I think we could improve the training and recruiting of soldiers within the AI. One of the keys might be to control the economy settings more explicit. Reason for this necessity in my eyes is the change in the soldier selection of trainingsites

**Comment by tibor95** [comment]
what about setting construction_decision_time  to kNever on the begining. If you are adding another check anyway, why not 

`if construction_decision_time  != kNever &&`

**Comment by hessenfarmer** [comment]
Well actually I intended to change the semantics of construction_decision_time like described above as it is cleaner imho then checking for a the startup condition each time it is used. 
Furthermore I am not sure if kNever still exists after the branch to make the time variables Typesafe.

**Comment by Noordfrees** [comment]
>  Furthermore I am not sure if kNever still exists after the branch to make the time variables Typesafe.

Just use a default-constructed `Time()` and its member function `construction_decision_time.is_valid()`/`construction_decision_time.is_invalid()`

**Comment by tibor95** [comment]
Looks interesting, but this still means additional checking every time if the time is valid... I must say I did not see the code of Time object

**Comment by Noordfrees** [comment]
> I must say I did not see the code of Time object

Link to header file: https://github.com/widelands/widelands/blob/refactor_time_and_duration/src/base/times.h

**Comment by tibor95** [comment]
Impressive. So we replace trivial(u)int32 with this object... OK

**Comment by hessenfarmer** [comment]
ok I fixed the wrong parameter given to visible_enemies_power function.  
I need to rethink about construction decision time as the AI now starts with only 2 lumberjacks which isn't too bad, as they get all materials delivered before any other building starts after 25 seconds. So I think we should not change this.

**Comment by gunchleoc** [comment]
Clang-tidy found this line in `defaultai_warfare.cc:348`:

`inputs[11] = (observer.second.mines_nearby == ExtendedBool::kTrue) ? 0 : 0;`

It's 0 in both cases.

**Comment by tibor95** [comment]
One of the zeros can be replaced by 1, or both by -1 and 1, depending on the context

**Comment by gunchleoc** [comment]
I have no idea how the scoring works, so can you make the decision, please?

https://github.com/widelands/widelands/blob/master/src/ai/defaultai_warfare.cc#L348

**Comment by hessenfarmer** [comment]
inputs[11] = (observer.second.mines_nearby == ExtendedBool::kTrue) ? 2 : 0;

should be safe to go imho

**Comment by tibor95** [comment]
I agree, theoretically some re-training would be done, but if there is only such tiny change it can wait. Maybe there will be more of them

**Comment by hessenfarmer** [comment]
I'll close this as all things mentioned herein have been fixed and for any other issue it is to unspecifc 
@Nordfrees I have reset the implementation version to 1.0 as all things mentioned herein have been introduced to 1.0
