### ISSUE TITLE
Running regression_test.py on VMware operated Ubuntu

### ISSUE THREAD

**Issue by Vipeltaja** [widelands/widelands#4378]
**Describe the bug**
Downloaded Source code (.zip) from the website, followed README.md instructions to compile the files into the game and tried running the regression_test.py. All of the processes were executed through Ubuntu's terminal with exact lines given in instructions. Game versions used were "build-21(Debug/Release)". All tests returned FAIL and end result looked like this:
Regression_Test (Widelands build-21 (Release)): 
Ran with: ./regression_test.py -b /widelands

Result:
	“SUMMARY: AddressSanitizer: 10231 byte(s) leaked in 273 allocation(s).
	Returned from Widelands, return code is 1
	
	Ran 45 tests in 681.195s
	FAILED (failures=45)”

Versions used:
- Ubuntu: 18.04.5 LTS
- VMware: 15.5.1

**To Reproduce**
1. Launch Ubuntu on VMware and continue the below steps there.
2. Download Source code (.zip) from https://www.widelands.org/wiki/Download/
3. Extract the files from the .zip
4. Open terminal from the "widelands-build21" -folder
5. Run "install_dependencies.sh"with "./install_dependencies.sh"
6. Run "compile.sh" with either "./compile.sh" or "./compile -r -w"
7. Once the compiler has finished use the command "./regression_test.py -b /widelands" to run the tests.
8. Watch the tests fail one after another. (Leave your PC, keyboard and mouse untouched for the process).

**Expected behavior**
I expected the tests to pass without any fails atleast for the "release"-build.

**Version:**
 - OS: Windows 10 - 10.0.19041
- Ubuntu: 18.04.5 LTS
- VMware: 15.5.1
- Widelands Version: [e.g. "Build 21"]

**Additional context**
Running the tests was a part of an University group project on a softwaretesting course. No idea if there were some files missing but achieved this result with exact same steps twice.

**Comment by Noordfrees** [comment]
Unfortunately compiling with ASan always results in Widelands exiting with an error code due to memory leaks in libraries which we use. That's something we cannot fix I believe. 
If you pass the `-a` switch to `compile.sh`, ASan will be disabled and everything should work fine.

**Comment by Niektory** [comment]
> If you pass the `-a` switch to `compile.sh`, ASan will be disabled and everything should work fine.

Clean the build directory before doing this, otherwise ASan might not be properly disabled.

**Comment by Vipeltaja** [comment]
That solved the problem. Thanks for the help!
