### ISSUE TITLE
Low Productivity editbox bugs

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4380]
1. Typing a letter in the Low Productivity editbox results in an error:
`terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'`
2. The box loses focus after a short moment.

**To Reproduce**
1. Start a game.
2. Build some buildings.
3. Open Statistics -> Buildings.
4. Click one of the building types you have.
5. Click on the percentage number next to "Low Productivity" so the editbox gains focus.
6. Type a letter (not a number). If you do it quickly you will get a bad_lexical_cast error (bug 1). If you're slow the box will lose focus (bug 2).

**Version:**
 - OS: Manjaro 20.1.1
 - Widelands Version: 1.0~git24947[870c1e1@master] (Debug)

**Comment by Noordfrees** [comment]
This editbox is awkward to use in my opinion even without those bugs. How about replacing the editbox with a spinner?

**Comment by gunchleoc** [comment]
For a spinner, we'll need to make the window wider, which I was trying to avoid.
Maybe put it in an additional row on the bottom?

**Comment by Noordfrees** [comment]
Another row on the button for the spinner would be fine.

By the way – are the labels meant to have different font sizes?
![shot0001](https://user-images.githubusercontent.com/48293446/96615885-282f8f80-1302-11eb-8f1c-a72c4859c07e.png)

**Comment by gunchleoc** [comment]
I don't remember - I did quite a lot of fiddling with the alignment for the editbox back then. Do feel free to change it, but it does need to stay small.
