### ISSUE TITLE
Windowed mode gets stuck in top left corner of the screen

### ISSUE THREAD

**Issue by Vipeltaja** [widelands/widelands#4382]
**Describe the bug**
When the game is opened and the resolution is set to be higher than or equal to the screen's resolution the game's titlebar goes beyond the top edge of the screen (even when fullscreen is unticked in the options menu). Changing the resolution still works but the gamewindow stays stuck in the top left corner of the screen.
No settings from the options-menu seemed make a difference (except restarting when lower resolution was selected).
Achieved the same result on three different devices and when changing the “Screen resolution” from Windows settings.

**To Reproduce**
1. Open Widelands
2. In the options menu change “window size” to be greater than or equal to the screen's resolution.
3. Untick the “Fullscreen” box
4. Click “OK” or “Apply”
5. The game should now be windowed and at least the same resolution as the screen.
6. Close Widelands
7. Open Widelands
8. The game should still be windowed and at least the same resolution as the screen but the “title bar” is beyond the top edge of the screen making the window unmovable
9. Try to lower the resolution
10. The window stays fixed to the top left corner of the screen

**Expected behavior**
When the game is set to be "windowed" the titlebar would be on the screen making the window movable.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/73128379/96583777-e85aaf00-12e5-11eb-8b31-7c362877f06b.png)

**Version:**
Game Version: Build-21(Release)
OS: Windows 10, 10.0.19041

**Additional context**
No idea whether this issue was already know or not. Restarting the game with lower resolution fixed the issue.
Could the default location be changed so that the titlebar stays on the screen when opened with those settings (Possible fix?).

**Comment by Niektory** [comment]
Could you test with the current development version? There have been changes since Build 21 that may have changed this behavior. You can build it yourself or see https://www.widelands.org/wiki/Download/ for pre-compiled builds.

**Comment by Vipeltaja** [comment]
Downloaded and installed the pre-compiled build (1.0~git24950[d4ceb37@HEAD] (Debug))
Setting resolution to 1920x1080 and restarting the game had the same result. (1920x1080 screen resolution)

Downloaded and installed the pre-compiled build (1.0~git24950[d4ceb37@HEAD] (Release))
Setting resolution to 1920x1080 and restarting the game had the same result. (1920x1080 screen resolution)

Build was from: (https://ci.appveyor.com/project/widelands-dev/widelands/build/job/1lijvyw5cijdnlvn/artifacts)

The "maximized" setting has similar functioning to the expected result.

Also would like to add that the current build looks way nicer already!

**Comment by Vipeltaja** [comment]
![Screenshot2](https://user-images.githubusercontent.com/73128379/96589982-222fb380-12ee-11eb-9b65-6b5cfac84806.png)

**Comment by Niektory** [comment]
I'm reluctant to add window-moving code to deal with this issue as it's OS-specific, easy to avoid and easy to work around. I'd rather discourage picking the biggest window size and recommend using Maximized or Fullscreen instead.

**Comment by Vipeltaja** [comment]
Maximized seems to work well for this specific use. As it has been implemented already.
