### ISSUE TITLE
wl.Game.Player:hide_fields() does not work anymore

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4422]
hide_fields() was previously used to hide fields of a headquarters or a ship and reveal the fields through [field_animations.lua](https://www.widelands.org/documentation/autogen_auxiliary_field_animations/), e.g. reveal_concentric(). This does not work anymore, because the fields revealed by a headquarters can't be hid.

**To Reproduce**
1. start attached scenario

Or use one of the campaigns, e.g. emp01.

One can also use the debug console within the attached scenario and try to run `pl:hide_fields(pl_sf:region(12), true)`

**Expected behavior**
The visible area shouldn't be visible until it get revealed again.

**Version:**
 - OS: archlinux
 - Widelands Version: [cf3f7f6@master]

[test_sleep.zip](https://github.com/widelands/widelands/files/5443654/test_sleep.zip)

**Comment by Noordfrees** [comment]
You cannot hide fields that are currently seen by a building or worker, not should this be possible

**Comment by gunchleoc** [comment]
I guess you'll need to hide the fields first ow, then place the headquarters, then reveal? Not quite as pretty, but should be OK.

**Comment by Niektory** [comment]
> You cannot hide fields that are currently seen by a building or worker, not should this be possible

Why not?

**Comment by Noordfrees** [comment]
> > You cannot hide fields that are currently seen by a building or worker, not should this be possible
> 
> Why not?

What *is* vision?
To me, the "logical" definition is that workers and buildings see fields in their vicinity and report their findings back to their chieftain (the player). That's why you can see *all* and *only* fields near a building or worker. Additionally scenario scripts may choose to grant you extra vision as a kind of "gift from the gods".
From this definition it follows that your HQ will always inform you what its vicinity looks like. After all your workers don't run around blindfolded, do they? If they did (or if the script's godlike interaction prevented them from communication somehow), they would logically be unable to work properly or do basically anything, in which case one might as well remove the HQ or the workers and be done with it.

We don't have an official definition, so I am curious what another definition of vision could be that makes the scripting all-powerful in a logically consistent way.

**Comment by frankystone** [comment]
> I guess you'll need to hide the fields first ow, then place the headquarters, then reveal? Not quite as pretty, but should be OK.

No, that doesn't work because placing a headquarters or ship does reveal the fields in any case. The only solution having a black screen before showing a headquarters is to place the headquarters after some time, e.g. after showing a message_box. 
Some of old LUA code does not work anymore as expected. As a result most campaigns which uses functions from  field_animations.lua in conjunction with any building must be reworked/removed. E.g. in the first empire campaign one can see moving the view to a ship now. To prevent noticing a player can see this move, this has to be changed that the view will be moved and then the ship has to be placed. Of course without revealing animations :-(

**Comment by frankystone** [comment]
> What _is_ vision?
> To me, the "logical" definition is that workers and buildings see fields in their vicinity and report their findings back to their chieftain (the player). That's why you can see _all_ and _only_ fields near a building or worker. Additionally scenario scripts may choose to grant you extra vision as a kind of "gift from the gods".

I agree from a players point of view.

> From this definition it follows that your HQ will always inform you what its vicinity looks like. After all your workers don't run around blindfolded, do they? 

Yes. Some workers walk in unseen areas, e.g. Hunters, Geolgists or Scouts.

> If they did (or if the script's godlike interaction prevented them from communication somehow), they would logically be unable to work properly or do basically anything, in which case one might as well remove the HQ or the workers and be done with it.
> 
> We don't have an official definition, so I am curious what another definition of vision could be that makes the scripting all-powerful in a logically consistent way.

Just because the author of a campaign is godlike. He can do many things what a player can't do, e.g restrict possible buildings, add workers or wares. why should a campaigns author should be able to do something like that, but not modify vision?

So far the possibility to hide and reveal fields wasn't used to restrict the vision for a player without reveling it afterwards. So i think it wouldn't be problem. In contrary i think this could be used to archive some interesting things, e.g. let a part of map ever unrevealed until a specific objective is solved.

**Comment by Noordfrees** [comment]
> > From this definition it follows that your HQ will always inform you what its vicinity looks like. After all your workers don't run around blindfolded, do they?
> 
> Yes. Some workers walk in unseen areas, e.g. Hunters, Geolgists or Scouts.

Yes they are blindfolded or yes they aren't blindfolded?
Hunters have a way of "knowing" where they may find animals in the far-away wilderness, but while they're there they still report what they see to you.

> > If they did (or if the script's godlike interaction prevented them from communication somehow), they would logically be unable to work properly or do basically anything, in which case one might as well remove the HQ or the workers and be done with it.
> > We don't have an official definition, so I am curious what another definition of vision could be that makes the scripting all-powerful in a logically consistent way.
> 
> Just because the author of a campaign is godlike. He can do many things what a player can't do, e.g restrict possible buildings, add workers or wares. why should a campaigns author should be able to do something like that, but not modify vision?

This does not necessarily make him a god though. Another interpretation: The players are dukes – they can build up and tear down stuff in their kingdom, give orders to their subjects, have feuds with each other. And above all there towers the absolutist king who issues edicts known as scripts by which he orders his dukes not to build a certain building type, informs them of important events, grants or fines them goods, and so on.

> So far the possibility to hide and reveal fields wasn't used to restrict the vision for a player without reveling it afterwards. So i think it wouldn't be problem. In contrary i think this could be used to archive some interesting things, e.g. let a part of map ever unrevealed until a specific objective is solved.

While it would allow interesting plots it seems illogical to me that workers would be unable to see things there – e.g. your scout would be able to go there – but the player would not be able to see the area even when he surrounds it with towers and sends in a dozen scouts.

**Comment by frankystone** [comment]
I have problems to understand your point. I can't express exactly why though. Maybe because i see no need to have a logical definition of the relation between a player and an author of campaign. All i know is: The more possibilities a campaigns author will have, the more interesting campaigns he can write. The __campaigns author is responsible for the logic__ in his campaign, also with regard to hide/reveal fields. 

In my opinion this has nothing to do with any definition of 'vision' or interpretation of the relation between an author of a campaign and the player. I can accept that some logical definitions are needed from a coding perspective though.

I do not know which commit causes this issue. But that commit prevents some nice visual effects, which is a bug in my eyes.

**Comment by hessenfarmer** [comment]
> 
> 
> I have problems to understand your point. I can't express exactly why though. Maybe because i see no need to have a logical definition of the relation between a player and an author of campaign. All i know is: The more possibilities a campaigns author will have, the more interesting campaigns he can write. The **campaigns author is responsible for the logic** in his campaign, also with regard to hide/reveal fields.
> 
> In my opinion this has nothing to do with any definition of 'vision' or interpretation of the relation between an author of a campaign and the player. I can accept that some logical definitions are needed from a coding perspective though.
> 
> I do not know which commit causes this issue. But that commit prevents some nice visual effects, which is a bug in my eyes.

Full agreement from my side. Need to retest the effect on the scenarion though. 
the problem is that especially empire03 uses a ship in the beginning to create the illusion of being in storms. this ship is later removed and we need to hide the fields seen by the ship completely as it was not meant that the place where the ship is in dangerous waters is even on this map.     
Hiding the fields would give the possibility to reveal them in certain way which creates atmosphere which is used for the HQ rather then having full view direct after placing it just looks nicer to reveal the view in concentric circles slowly until full view is reached.
next possible use might be to restrict the view of a building by hiding its original view and just reveal some part of it.    

creating foggy areas might be a possible use case as well. so We once had this functionality and not having it anymore is a step back.

**Comment by gunchleoc** [comment]
I'm in favor of getting this functionality back if the new vision code allows this.

**Comment by Niektory** [comment]
It should be possible, but we need to agree on the interface.

**Comment by frankystone** [comment]
What do you mean with 'interface'? Which possibilities do we have?

**Comment by Niektory** [comment]
I meant the meaning of the Lua functions – what each one is supposed to do precisely.

**Comment by frankystone** [comment]
The documentation of [hide_fields](https://www.widelands.org/documentation/autogen_wl_game/#wl.game.Player.hide_fields) says:

> Make these fields hidden for the current player if they are not seen by a military building.

I don't know why `hide_fields` shouldn't work for military buildings, but i am fine if it works as before: `hide_fields` should hide the given area of fields.

It would be nice if there were some explanation of 'unexplore'. What is the purpose to set this to true? When is this needed?
