### ISSUE TITLE
Corrupted scripting packet in all older savegames

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4426]
![image](https://user-images.githubusercontent.com/44526987/97306065-37f92780-185e-11eb-8412-c775c4f20628.png)

_Originally posted by @spirillen in https://github.com/widelands/widelands/issues/4384#issuecomment-717232984_

---

My older savegames (meaning: a few weeks to months old, created with master builds newer than b21) all show this behaviour.

**Comment by gunchleoc** [comment]
Probably related to training wheels, just like https://github.com/widelands/widelands/issues/4404

**Comment by spirillen** [comment]
Maybe not directly related, but the sound of training wheeeeeeeels...

Chose new game, Elven forest, Team up 1,3 & 2,4

![image](https://user-images.githubusercontent.com/44526987/97348170-16b02f80-188e-11eb-864a-ae57bc33daae.png)


After some playing in a new game this happens

![image](https://user-images.githubusercontent.com/44526987/97354623-f84e3200-1895-11eb-93a0-921cf6e3e029.png)

**Comment by gunchleoc** [comment]
The commit that broke it is https://github.com/widelands/widelands/commit/cf3f7f64c95247987b6b288b5d4785d3a081be15

Looks like we need to keep the LuaWorld and LuaTribes modules around for savegame compatibility.
