### ISSUE TITLE
Get rid of LuaWorld and LuaTribes

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#4438]
**Is your feature request related to a problem? Please describe.**

We must keep LuaWorld and LuaTribes around forever for fixing https://github.com/widelands/widelands/issues/4426

**Describe the solution you'd like**

Add versioning to only load these 2 modules when needed for compatibility, so that we can get rid of them eventually.

**Comment by Noordfrees** [comment]
Instead of adding versioning it would be easier to delete them when we next break savegame compatibility completely, together with `set_textdomain`. Not likely to happen before v1.0 though is it

**Comment by gunchleoc** [comment]
We might not even need to break savegame compatibility completely for v1.0, so I'd still like to look into whether we can avoid storing them with new savegames.

**Comment by gunchleoc** [comment]
The only viable solution would be to not persist those classes when saving. I don't want to dig further into that. We'll just have to keep the modules around until such a point when we should completely break savegame compatibility for all savegames.
