### ISSUE TITLE
Assert failure when trying to join online game

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4442]
I got an assert failure when trying to join an online game:
```../src/network/gameclient.cc:252: void GameClient::run(): Assertion `!d->settings.tribes.empty()' failed.```

Version: 1.0~git25070[9c06b77@HEAD] (Debug)

[multithreading_new_assert_9c06b77.txt](https://github.com/widelands/widelands/files/5460268/multithreading_new_assert_9c06b77.txt)

_Originally posted by @Niektory in https://github.com/widelands/widelands/pull/4319#issuecomment-718912385_

---

I can reproduce with the `multithreading_new`, `main-menu-redesign-3` and `4374-rewrite-inputqueuedisplay` branches, so this is apparently an issue in master.

**Comment by gunchleoc** [comment]
This assert was introduced with https://github.com/widelands/widelands/commit/334128853592eb02bc63edcd3206376b53a17587

My first guess is that the assert is in the wrong spot and needs to be shifted to a later place in the control flow.
