### ISSUE TITLE
Unexpected treetop sentry behavior

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4459]
* Treetop sentries cannot be placed on every tree (seems to be only possible on planted trees, not on generated ones). The problem was already mentioned in the forum (https://www.widelands.org/forum/topic/2897/?page=37#post-34333).
* Removing a treetop sentry constructionsite (with no materials) burns down the tree. Removing a normal constructionsite however leaves a clean field behind, so I think the tree should be preserved.

**Comment by hessenfarmer** [comment]
the first problem is not whether they have been planted or generated I believe. As you can build some in crater from the beginning. It is related to the fact that you only can use trees on a small building plot with no other tree on the flags place. Currently we don't have a user indication for this.  only solution would be to show the build help transparent under the trees (and other immovables ) probably. This would be a rather big change on game as together with the  remove immovable feature this would allow for precise removal to reach relevant build spaces (e.g. in forrest wall scenario). so this need to be evaluated carefully .

second one is not a bug in my eyes. just putting fire to a building to detroy it leaves a clean field so does the treetop sentry. If you put fire on such a building the tree can't be saved.

**Comment by matthiakl** [comment]
Thanks for the explanation.
> It is related to the fact that you only can use trees on a small building plot with no other tree on the flags place. Currently we don't have a user indication for this.

Ok, so I just misunderstood where it can be built. Some form of indicator would be nice for the future.

> just putting fire to a building to detroy it leaves a clean field so does the treetop sentry. If you put fire on such a building the tree can't be saved.

If the building is already partially constructed or some materials stocked up, it is totally fine to remove the tree, a normal construction site also burns for a short time in this case. Without any materials, there is only a flag, which has to be removed. A normal construction site does not burn at all in this case, while a treetop sentry does (together with the tree).

**Comment by hessenfarmer** [comment]
> > just putting fire to a building to detroy it leaves a clean field so does the treetop sentry. If you put fire on such a building the tree can't be saved.
> 
> If the building is already partially constructed or some materials stocked up, it is totally fine to remove the tree, a normal construction site also burns for a short time in this case. Without any materials, there is only a flag, which has to be removed. A normal construction site does not burn at all in this case, while a treetop sentry does (together with the tree).    

Seems I misunderstood that one. You are rigth this is a bit illogical. And it might be an effective method against any forrest wall made by another tribe, so yes I would consider it a bug
