### ISSUE TITLE
Missing encyclopedia ware/worker helptext translations

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4463]
The ware and worker helptexts are not localized in the encyclopedia in current master (dc1a860).

![grafik](https://user-images.githubusercontent.com/48293446/97882229-ab4dde00-1d23-11eb-9a5f-1cd542dafcd7.png)

**Comment by frankystone** [comment]
Can't confirm with [a9580f5@master] (Debug)

![lcalization](https://user-images.githubusercontent.com/6730556/105675448-6fbd4d00-5ee9-11eb-8d3b-ba90331210d8.jpg)

**Comment by Noordfrees** [comment]
I have debugged this in e9624ea@master and it seems that the text is not being localized while the tribe is being loaded – but I don't understand why.

`tribes/initialization/frisians/units.lua`:
```
         {
            name = "frisians_baker",
            helptexts = {
               -- TRANSLATORS: Helptext for a frisian worker: Baker
               purpose = pgettext("frisians_worker", "Bakes bread for miners and soldiers.")
            }
         },
```
```
During tribe loading:
(gdb) p helptexts 
$63 = std::map with 1 element = {["purpose"] = "Bakes bread for miners and soldiers."}
```
The textdomain is also set correctly:
```
(gdb) p LuaGlobals::textdomains
… [0x61b000178488] = std::vector of length 1, capacity 8 = {{first = "tribes_encyclopedia",  second = false}} …
```
I triple-checked that `po/tribes_encyclopedia/nds.po` contains the correct translation:
```
#. TRANSLATORS: Helptext for a frisian worker: Baker
#: ../../data/tribes/initialization/frisians/units.lua:768
msgctxt "frisians_worker"
msgid "Bakes bread for miners and soldiers."
msgstr "Backt Brood för de Soldaten un Bargwarkskeerls."
```
And the result is still:
![grafik](https://user-images.githubusercontent.com/48293446/105699515-c46fc080-5f07-11eb-8ddb-5fafd899092c.png)

I am out of ideas…

**Comment by matthiakl** [comment]
It looks like the textdomains are a bit scrambled. Sometimes it is translated, sometimes not. By specifying the textdomain in the lua gettext functions (possibly redundant?) it is fixed for me.
