### ISSUE TITLE
Assert fail in testsuite

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4468]
The testsuite occasionally report this assert:
```
widelands: /home/runner/work/widelands/widelands/src/logic/map_objects/tribes/production_program.cc:1818: virtual void Widelands::ProductionProgram::ActTrain::execute(Widelands::Game &, Widelands::ProductionSite &) const: Assertion `current_level < training_.level' failed.
```

**Comment by gunchleoc** [comment]
I changed the logging and we have a bit more info:

```
[00:05:00.562 game] DEBUG: MO(6808,empire_colosseum):   Training soldier's 3 (1 to 1)
widelands: /home/runner/work/widelands/widelands/src/logic/map_objects/tribes/production_program.cc:1818: virtual void Widelands::ProductionProgram::ActTrain::execute(Widelands::Game &, Widelands::ProductionSite &) const: Assertion `current_level < training_.level' failed.
```

**Comment by Noordfrees** [comment]
Another testsuite error, I don't see how it could be related to the branch with which it happened:
```
FAIL: test/maps/ship_transportation.wmf/scripting/test_rip_ship_before_picking_up_transporting_ware.lua

[00:00:14.301 game] ERROR: Error in Lua Coroutine
[00:00:14.301 game] ERROR: [/home/runner/work/widelands/widelands/src/scripting/lua_errors.cc:22] [string "test/maps/ship_transportation.wmf/scripting/t..."]:24: expected '1' but was '0'!
```
https://github.com/widelands/widelands/runs/1363370899?check_suite_focus=true

**Comment by Niektory** [comment]
See the upgrade program:
https://github.com/widelands/widelands/blob/e6f05045aa5af86285ef5d91649f6ac7a2a00d78/data/tribes/buildings/trainingsites/empire/colosseum/init.lua#L60-L62
If the game is saved after `checksoldier` but before `train`, loading that game will crash.

Saved before `checksoldier` (doesn't crash): [test_test_26.wgf.zip](https://github.com/widelands/widelands/files/5514527/test_test_26.wgf.zip)
Saved between `checksoldier` and `train` (crashes): [test_test_27.wgf.zip](https://github.com/widelands/widelands/files/5514528/test_test_27.wgf.zip)

You can use the non-crashing save to produce a crashing one. Run the game with `--verbose`, press PageDown during loading, then after loading press Shift+PageUp, PageDown in quick succession. If the log prints "Checking soldier" but not "Training soldier" you can save.
