### ISSUE TITLE
Unable to load savegame (vision packet)

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4480]
The attached two savegames were created with Version 1.0~git25021[fd4744c@master] (Release). They both fail to load with the same version:
```
[00:00:08.743 real] ERROR: Fehler mit de Speel-Daten
[00:00:08.743 real] ERROR: view: [../src/map_io/map_players_view_packet.cc:174] Read 183 unseen fields but detected 182 when the packet was written
```
```
[00:03:31.803 real] ERROR: Fehler mit de Speel-Daten
[00:03:31.803 real] ERROR: view: [../src/map_io/map_players_view_packet.cc:174] Read 1133 unseen fields but detected 1132 when the packet was written
```
[savegames.zip](https://github.com/widelands/widelands/files/5497565/savegames.zip)

**Comment by Niektory** [comment]
Do you have the replays?

**Comment by Niektory** [comment]
I'm pretty sure this partially seen weaving mill is where things went awry:

![shot0151](https://user-images.githubusercontent.com/4470900/98312160-66e76a00-1fd1-11eb-9969-549f1bf6e0b0.png)

There are other possibly related problems with partially seen buildings: Their info is only updated when a field is rediscovered, but that doesn't happen when the building is built, only on vision changes. A bigger overhaul might be needed...

**Comment by Niektory** [comment]
I don't know how to fix the bug, but I fixed your saves (for now) ;-)

[SnowBound_fixed.wgf.zip](https://github.com/widelands/widelands/files/5498697/SnowBound_fixed.wgf.zip)
[SnowBound_Battle_fixed.wgf.zip](https://github.com/widelands/widelands/files/5498696/SnowBound_Battle_fixed.wgf.zip)

**Comment by Noordfrees** [comment]
Thanks for the fixed saves! :)
Here is the replay (in two parts: How To Build A Pretty Good Economy and How To Get Very Nearly Taken Apart By The AI In A Poorly Planned Attack):
[SnowBoundReplays.zip](https://github.com/widelands/widelands/files/5500629/SnowBoundReplays.zip)

**Comment by Noordfrees** [comment]
Another savegame with this problem.
[Savegame](https://github.com/widelands/widelands/files/5553222/ColourCodedPlains.wgf.zip)
[Replay](https://github.com/widelands/widelands/files/5553225/ColourCodedPlains.zip)
Version 1.0~git25062[0a529da@master] (Release)
