### ISSUE TITLE
different translations for tribes of the same string is not possible anymore.  

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4490]
Previously it was possible to translate the same string diferently for different tribes.
e.g. soldiers was translated as "Soldaten" (soldiers) for atlanteans and empire but "Krieger" (Warriors) for barbarians and frisians.    

This seems to be not possible anymore e.g. for the miitary Buildings with the same name.

Do we need / want to change the source strings to be able to do that as well? or is there anaother way of achieving this.

**Comment by gunchleoc** [comment]
We can change the translation markups in `units.lua` and in the militarysites to use a tribe-specific pgettext context. Best grep for "soldier" so we won't miss anything.

What will remain as "Soldier(s)" when we do that are the census strings and statistics windows.

**Comment by hessenfarmer** [comment]
Census and statistics would be ok. Although census would be nice as well especially with amazons

**Comment by gunchleoc** [comment]
I had a look on Transifex. For C++ changes, we have the following categories:

- **Census** strings. Where do we define it in Lua? Could be at the soldier worker, at the military sites or in the units.lua. IAt militarysites sounds best to me, although this will generate some duplication. What do you think?
- **Production program** strings (would need to be defined via Trainingsite Lua
- **UI** strings (toolbar menu, attack box, building statistics menu, soldierlist) - can stay as they are

**Comment by hessenfarmer** [comment]
> 
> 
> I had a look on Transifex. For C++ changes, we have the following categories:
> 
>     * **Census** strings. Where do we define it in Lua? Could be at the soldier worker, at the military sites or in the units.lua. IAt militarysites sounds best to me, although this will generate some duplication. What do you think? 

Milsites should be ok

> 
>     * **Production program** strings (would need to be defined via Trainingsite Lua

ok 

> 
>     * **UI** strings (toolbar menu, attack box, building statistics menu, soldierlist) - can stay as they are

agreed

**Comment by hessenfarmer** [comment]
Unfortunately it isn't fixed
see
https://www.transifex.com/widelands/widelands/translate/#de/tribes/65218455

**Comment by hessenfarmer** [comment]
maybe we need to have an own TD for each tribe

**Comment by gunchleoc** [comment]
> Unfortunately it isn't fixed

Those are different strings, they just need a pgettext too

> maybe we need to have an own TD for each tribe

Not possible because of shared wares & immovables
