### ISSUE TITLE
Crash when removing many saved games

### ISSUE THREAD

**Issue by xorxsan** [widelands/widelands#4523]
**Describe the bug**
When you try to remove many saved games, Widelands crashes.

**To Reproduce**
1. Click on One player
2. Click on Load game
3. Try to select more than 23 saved games
4. Wait a little bit (less than 2 seconds) or click Remove, Back or any other button present in that UI
5. Widelands crashes

**Expected behavior**
You should be able to select many saved games, click on Remove and the files get removed.

**Version:**
 - OS: Windows 10 Version 1909
 - Widelands Version: "Build 21", "Release"

**Comment by Niektory** [comment]
That's in Build 21, right? For me it crashes in Build 21, but 1.0~git25064[405bd61@master] (Debug) works fine. So it seems to be fixed already.

**Comment by xorxsan** [comment]
Yes, sorry, it's Build 21 Release. I edited the comment to remove the [eg.].
If it's already fixed in master, I'll close this ticket.
Thanks!
