### ISSUE TITLE
Mac builds fail on Travis

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4535]
Since a couple of days (around 17.11.) the Travis build for Mac has a good chance of failing.
Comparing the logs of [this](https://travis-ci.org/github/widelands/widelands/jobs/745089920) and [that](https://travis-ci.org/github/widelands/widelands/jobs/745090537) build, the problem seems to be a new dependency, which requires a newer cmake version. Building this package takes just about the declared stall time of 10 min.

**Comment by Noordfrees** [comment]
Perhaps we should just get rid of travis entirely? – this is not the first time it's causing trouble and it won't be the last.
Travis tests compiling under MacOS 10.13.6; our build action compiles on MacOS 10.15.7. Do we need both?
