### ISSUE TITLE
Immovables do not restrict buildingspace on mountains

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4553]
Immovables wich have a size do restrict building space on arable terrains, but not on mineable terrains:

![immovables_mineable](https://user-images.githubusercontent.com/6730556/101829729-bde1e100-3b33-11eb-98f4-6640a4ba8106.png)

The standing stone on mineable terrain shows that only one  buildingspace is lost, whereas on arable terrain all surrounding buildingspace is lost.

**To Reproduce**
1. Start the editor
2. Place some mineable terrains
3. Enable buildhelp
4. Place some immovables on mineable and arable terrains

**Expected behavior**
Immovables placed on mineable terrains should restrict buildingspace for mines in the same way like with arable terrains. Since mines have only one size, every immovable wich have a size should mark all neighboring fields as unmineable if it get placed on mountains.

**Version:**
 - OS: archlinnux
 - Widelands Version: [7c074cf@master] (Debug)

**Comment by Noordfrees** [comment]
Faulty code: `logic/map.cc` `Map::calc_buildsize` lines 1725-1758 → if a mine can be built, the calculations regarding surrounding immovables are skipped
