### ISSUE TITLE
Inconsistent mouse behavior when placing flags on roads

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4555]
**Describe the bug**
Formerly one can just make a double click for placing flags on roads. For some reason this does not work anymore under some circumstances. I wasn't able to determine the circumstances.

**To Reproduce**
1. Start a game
2. Connect a building with a road without pressing STRG. This road should be long.
3. Try to place flags on the road 

Sometimes the mouse pointer moves to the place flag button (double click do work), sometimes the mouse pointer stays at the top tab panel.

**Expected behavior**
The mouse pointer should always be moved to the place flag button if the flag might be part of a road. Or it should stay always at the top tab panel.
At least the behavior should be consistent.

**Version:**
 - OS: archlinux
 - Widelands Version: [7c074cf@master] (Debug)

**Comment by Noordfrees** [comment]
Confirmed and very annoying. The 'Place Flag' button should always be the fastclick panel.

**Comment by matthiakl** [comment]
The 'sometimes' is, when the field underneath is capable of more buildings and not only flags.
