### ISSUE TITLE
Geologists put up empty signs only after save-reload

### ISSUE THREAD

**Issue by spth** [widelands/widelands#4566]
Yesterday, I started a multiplayer (LAN) game on the four castles map, using the current version from git as of yesterday.

Geologists then worked normally. Today, the game was loaded to continue playing.

However, geologists now put up empty signs only. Apparently, they find neither mountain resources, nor water.
However, the resources are there, and mines work normally (when I build a mine in a location where I remember a resource is located, the mine works, and no "exhausted" sign is being put up).

Both computers use AMD Ryzen APUs, and the OS is current Debian GNU/Linux testing.

P.S.: Savegame at http://www.colecovision.eu/stuff/widelands-no-resources-found/

**Comment by Noordfrees** [comment]
A missing postload() call somewhere, will investigate

**Comment by spth** [comment]
I checked that this bug is reproducible: I've started two other multiplayer games since, and each time, geologists work after the initial start, but not after loading a savegame.

**Comment by klaus-halfmann** [comment]
OK savegame in for Empire, playing in German.
I tried with Barabrians, using Crater and Englis, did not happen there.
Lets play around with Language/Tribe/Map, mmh.

**Comment by klaus-halfmann** [comment]
Ahh, the _existing_ flags will be loaded correctly, however the gelogist will not find the existing resources from the savegame. Ok now I can test that fix.
