### ISSUE TITLE
No "No Rocks" warning from Amazon Stone Carver

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#4580]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
The Amazone Stone Carver does not send news when it is running out of stones.

**To Reproduce**
1. Open Attached Savegame
2. Check Stonecarver next to HQ.
3. Stonecarver ist at 0% productivity

**Expected behavior**

Stonecarver  sends news "Ages of stones is over" :-) or such.

**Version:**
 - OS: [macOS 11.1 / BigSur ]
 - Widelands Version: [1.0~git25105[bccc375@master]

[NoStoneWarn.wgf.zip](https://github.com/widelands/widelands/files/5761497/NoStoneWarn.wgf.zip)

**Comment by Noordfrees** [comment]
No `productivity_threshold` is set for the `amazons_stonecutters_hut` @hessenfarmer
