### ISSUE TITLE
AI dont train soldier in any trainingssite if ration, snack and meal is used instead of meat and bread

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4589]
See also https://www.widelands.org/forum/topic/5111/

I suppose it has been hard coded somewhere that training soldiers require bread and meat / fish. The AI does not open the trainingssite to soldiers if you use a ration, snack or meal as a ware.

**Comment by hessenfarmer** [comment]
confirmed should be not too hard to do a quick fix as long as #3665 is not solved which is related

**Comment by hessenfarmer** [comment]
the linked branch should fix this.
@MarkMcWire can you confirm the fix?

**Comment by MarkMcWire** [comment]
It works, I have tested it in a new game.

**Comment by hessenfarmer** [comment]
> 
> 
> It works, I have tested it in a new game.

Would you like to provide a review on the branch? so it could get merged
