### ISSUE TITLE
Inform players about replay version mismatch

### ISSUE THREAD

**Issue by OIPUN** [widelands/widelands#4604]
**Describe the bug**
Unable to watch a reply of a game originaly played in build 21 release

**To Reproduce**
1. Go to 'Watch Replay'
2. Select the attached files
3. Error message occures

**Expected behavior**
I should be able to watch the replay

**Screenshots**
[2020-12-15T20.57.43_single_player.zip](https://github.com/widelands/widelands/files/5791363/2020-12-15T20.57.43_single_player.zip)

**Version:**
 - Widelands Version: originaly played in "Build 21 Release"; error in Widelands-Release-x64-1.0~git25107[fdadf54@HEAD]

**Additional context**
This is my first bug report. So please let me know if something is missing or not correct.

**Comment by Noordfrees** [comment]
Replays only work with exactly the same version they were created with, so this is expected.

This seems to be a common problem, perhaps we should show a warning if a replay was created with a different version. Keeping this issue open as a reminder to implement this.

**Comment by OIPUN** [comment]
Ok, I saw the message to report it so I did.
