### ISSUE TITLE
New World Staring condition not feasible for ATL

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#4607]
**Describe the bug**

Wehn using the "New World" Starting Condition with Atlanter it is impossible
(or veey difficult) to get the Economy going. 

We should add a normal- and a blackroot-farmer, a spider-breeder and a sawyer.
They could be distributed over the seven ships. A hint for the play that to he must
cancel the expedtions to unload the ships would help, too.

**To Reproduce**

1. Start a Naval game (e.g. Two lagoons) with ATL and stating condition "new world".
2. Play like a +/- novic Player might try
3. Fail to get you eceonomy going.
4.Search for hints how this could be avoided :-)

**Expected behavior**

An average player can get a econonmy running based on the  "New World" Starting Condition
and some hints found in the objectives

**Version:**
 - OS: should be any 
 - Widelands Version: 1.0~git25119[2c49e20@master]

**Additional context**

 Did not check the other tribes, yet

**Comment by Noordfrees** [comment]
I gave it a quick spin after not having played ATL for a while and got stuck with just 1 iron too few before I was able to get my iron mine operational. We could exchange a few spidercloth (there's way more than I needed) for a few more pieces of iron, then it should be doable without knowing how to puzzle it out.
