### ISSUE TITLE
Sound options wont close.

### ISSUE THREAD

**Issue by gituser823** [widelands/widelands#4610]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
There is no "close"-button to close the windows, it also does not work by pressing ESC.
Also the Music-configuration-windows can not be closed by this bug.

**To Reproduce**
1. Click on "Main Menu"
2. Click on 'Sound options'
They can only be closed, when clicking on Main-menu / Sound options again.

**Expected behavior**
Be able to close the window by pressing ESC or a "close"-Button.

**Screenshots**
-

**Version:**
 - OS: Linux Mint 20
 - Widelands Version: "Build 20"

**Additional context**

**Comment by klaus-halfmann** [comment]
Mhh, works for me on master and on Build20? but I use macOS.

Please attach a screenshot and tell us your screen resolution.

Maybe try opening widelands with
--xres=[...]         Width of the window in pixel.
--yres=[...]         Height of the window in pixel.

Anyone else with Linux Mint around?

**Comment by Noordfrees** [comment]
You can close every window by right-clicking into it. The Esc key to close a window is a bit buggy in Build 20 and older. 
In the last release (Build-21) this is improved, and every window now also has a Close button in the titlebar. So I think this is already fixed in the current dev version.
