### ISSUE TITLE
Update maps' "needs Widelands version after"

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4611]
Maps created with master are not backwards compatible with build21, so we need to increase the version number.

The change to the versioning scheme makes it necessary to introduce some change here. Currently we use a number: **20** means "needs a version **newer than build 20**" (= build21 or newer). 
Let's change this to a string with the **minimum** version, e.g. **"1.0"** would mean "needs v1.0 or newer".

The website code will probably also need updating to handle the change, while still being able to handle maps made with older builds as well. I hope this is feasible without too much change required? @frankystone

**Comment by frankystone** [comment]
See [bug](https://github.com/widelands/widelands-website/issues/343).

Currently i am not very motivated to work on this.

**Comment by frankystone** [comment]
It might get problematic if the new versioning schema will reach 19.0: Because 19 (old) == 19.0 (new).

At least in Python:
~~~~
>>> v1=19
>>> type(v1)
<class 'int'>
>>> v2=19.0
>>> type(v2)
<class 'float'>
>>> v1==v2
True
~~~~
Maybe this needs adding an additional value 'version_schema = [old,new]', or 'version_schema = [vs1, vs2]'?

**Comment by Noordfrees** [comment]
I don't think it likely we'll reach version 19.0, ever ;D 
Even if we make two releases a year and break compatibility after every build this would still be 9 years away – at the very least! I'm confident that in nine years everyone will be using the add-on system to share their maps and the homepage's map section will be superseded, and nobody will still 
be playing a WL version so old that they can't use add-ons.

In my opinion, it is safe to assume that values >= 19 refer to old-style builds and versions < 19 to new-style releases. 
Alternatively you could also check whether the version string contains a '.' character: if yes, it's a new-style version ("1.0"), otherwise it's an old-style version ("19").
