### ISSUE TITLE
use strip command on github artifacts

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4612]
From may perspective it makes sense to use the strip command before using innosetup on our windows artifacts on github as it decreases file size by a remarkable amount, this shortens downloadtimes and storage consumption

**Comment by Noordfrees** [comment]
Don't we do this already?
Actually we seem to run it *twice* before InnoSetup:
https://github.com/widelands/widelands/blob/f168f4a1b559279f3245a78d3e8368f5478d7a56/.github/workflows/build.yaml#L216
https://github.com/widelands/widelands/blob/f168f4a1b559279f3245a78d3e8368f5478d7a56/.github/workflows/build.yaml#L231-L232

**Comment by hessenfarmer** [comment]
forget it I was confused by the big filesize which is due to the background images,    

Maybe we could deliver them by another way (e.g. the addon server) reducing the filesize for dev builds, Howevever this is not urgent and has nothing to do with this issue so I am closing it
