### ISSUE TITLE
shipping_schedule.cc:1559: Zusicherung »!candidates.empty()« nicht erfüllt.

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4622]
Got this assertion.
[bt.txt](https://github.com/widelands/widelands/files/5810953/bt.txt)

This happens when the ship will arrive at the port.

Save game: 
[crash.zip](https://github.com/widelands/widelands/files/5810977/crash.zip)

**Version:**
 - OS: archlinux
 - Widelands Version: [5d04671@master] (Debug)

**Comment by MarkMcWire** [comment]
Game Crash:

[03:58:18.931 real] INFO: GameSaver::save() took 3094ms
widelands: ../src/economy/shipping_schedule.cc:1304: Duration Widelands::ShippingSchedule::update(Widelands::Game&): Zusicherung »index_of_end < 0« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

After restart the savegame:

[00:01:26.378 real] INFO: GameSaver::save() took 2910ms
widelands: ../src/economy/shipping_schedule.cc:570: void Widelands::ShippingSchedule::get_free_capacity_between(Widelands::Game&, const Widelands::Ship&, Widelands::ShipPlan&, Widelands::PortDock&, Widelands::PortDock&, bool&, bool&, bool&, bool&, Duration&, Duration&, uint32_t&): Zusicherung »ss.dock != &start« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)


Maybe related. 

See second savegame ans replays in https://www.widelands.org/forum/topic/5118/?page=1#post-35946

**Comment by Noordfrees** [comment]
https://www.widelands.org/forum/post/35979/
Another case of the same issue
