### ISSUE TITLE
Newest master doesn't complie

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#4626]
**Describe bug**
The newest master doesn't compile

**To Reproduce**
run $sh update.sh

You get the error-message:
`[ 77%] Generating translations for locale sr category scenario_tutorial04_economy.wmf
[ 77%] Generating translations for locale zh_CN category widelands
[ 77%] Generating translations for locale sr category texts
[ 77%] Generating translations for locale sr category training_wheels
/home/max/widelands/build/po/zh_CN_widelands.tmp.po:3089: 'msgid' and 'msgstr[0]' entries do not both end with '\n'
/home/max/widelands/build/po/zh_CN_widelands.tmp.po:3096: 'msgid' and 'msgstr' entries do not both begin with '\n'
/home/max/widelands/build/po/zh_CN_widelands.tmp.po:3437: 'msgid' and 'msgstr' entries do not both end with '\n'
/usr/bin/msgfmt: found 3 fatal errors
make[2]: *** [po/CMakeFiles/translang_zh_CN.dir/build.make:262: locale/zh_CN/LC_MESSAGES/widelands.mo] Error 1
make[2]: *** Deleting file 'locale/zh_CN/LC_MESSAGES/widelands.mo'
make[1]: *** [CMakeFiles/Makefile2:4565: po/CMakeFiles/translang_zh_CN.dir/all] Error 2
`

**Expected behavior**
Build should go through easy

**Version:**
 - OS: ArchLinux
 - Widelands Version: 1.0~git25130[1ed6652@master](Debug)

**Comment by Noordfrees** [comment]
Confirmed, I just ran into the same problem
```
[862/1459] Generating translations for locale zh_CN category widelands
FAILED: locale/zh_CN/LC_MESSAGES/widelands.mo 
cd /home/benedikt/wl/widelands/build/po && cmake -E make_directory /home/benedikt/wl/widelands/build/locale/zh_CN/LC_MESSAGES && /usr/bin/msgmerge -q --no-wrap /home/benedikt/wl/widelands/po/widelands/zh_CN.po /home/benedikt/wl/widelands/po/widelands/widelands.pot -o /home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po && /usr/bin/msgfmt -o /home/benedikt/wl/widelands/build/locale/zh_CN/LC_MESSAGES/widelands.mo /home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po && cmake -E remove /home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po
/home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po:3089: »msgid«- und »msgstr[0]«-Eintrag enden nicht jeweils mit »\n«
/home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po:3096: »msgid«- und »msgstr«-Eintrag beginnen nicht jeweils mit »\n«
/home/benedikt/wl/widelands/build/po/zh_CN_widelands.tmp.po:3437: »msgid«- und »msgstr«-Eintrag enden nicht jeweils mit »\n«
/usr/bin/msgfmt: es sind 3 fatale Fehler aufgetreten
[868/1459] Generating translations for locale ca category scenario_bar01.wmf
ninja: build stopped: subcommand failed.
```

**Comment by Noordfrees** [comment]
As a workaround you can do `rm po/widelands/zh_CN.po`
then it compiles

**Comment by Noordfrees** [comment]
I have added comments to the problematic strings on Transifex asking the zh_CN translator to resolve the issues. Transifex also flags them as errors.
