### ISSUE TITLE
Add information about attackability of ports to game FAq and encyclopedia

### ISSUE THREAD

**Issue by Ordoviz** [widelands/widelands#4638]
During Empire 3 some of my and the opponent’s buildings vanished into thin air. In particular, my port at the small island full of rocks vanished, leaving no place to build a new one. Consequently, I could not collect the last artifact.

My guess is that it has something to do with the buildings being unused or inefficient and on the border between the Empire and the Barbarians.

I am aware that this bug report is lacking steps to reproduce but I first want to know if someone knows more about this.

![Screenshot](https://user-images.githubusercontent.com/37733333/105359510-71d49280-5bef-11eb-9ef3-39ddfbfe5726.png)

As a "workaround" one can append `emp03.wmf="true"` to `save/campaigns.conf`.

 I used Widelands version 1.0~git25134[291c2e310ee4bb270b3a057353198afc04187e31@makepkg] on Arch Linux. Here is [my save file](https://github.com/widelands/widelands/files/5849757/port-vanished.zip). I changed the extension to zip because GitHub does not let me upload wgf files.

**Comment by klaus-halfmann** [comment]
@Noordfrees / @hessenfarmer we just yesterday merged some empie fixes to master:
https://github.com/widelands/widelands/pull/4625
Is this related or is this something totally different.

@Ordoviz you may have found some condition the underlying lua scripts could not cope with. Will take some time to fix this, but we are on the way to a RC-Freeze, so please keep on testing.

**Comment by frankystone** [comment]
> @Noordfrees / @hessenfarmer we just yesterday merged some empie fixes to master:
> #4625
> Is this related or is this something totally different.

That was for emp_04.

@Ordoviz : Do you have a save game before the port vanished?

**Comment by Ordoviz** [comment]
Yes, I have: [Save game before port vanished](https://github.com/widelands/widelands/files/5851253/port-exits.zip).

Interestingly, when I saved the game to give the file a new name, the port and the Barbarian buildings to the North became transparent but remained fully functional.
![Screenshot](https://user-images.githubusercontent.com/37733333/105393202-fcc78400-5c13-11eb-8bf2-ab9c014a6d1f.png)

The save game for the transparent port is [here](https://github.com/widelands/widelands/files/5851260/port-transparent.zip). I failed to reproduce the transparent port.

**Comment by Noordfrees** [comment]
The transparency can be toggled on/off with the hotkey 'U' or the button in the toolbar's showhide menu

**Comment by Noordfrees** [comment]
I built a quarry and let the game run for a while. Are you certain that this issue is not just about what this guy is doing:

![shot0003](https://user-images.githubusercontent.com/48293446/105396573-5c2b9100-5c20-11eb-8c10-0fd401fc5c81.png)

When the port is conquered and destroyed, the land may fall under control by the red player if he has built new military sites nearby in the meantime, making the port space inaccessible.

**Comment by Ordoviz** [comment]
> Are you certain that this issue is not just about what this guy is doing:

This seems like a good explanation. I did not know that enemies can attack non-military buildings and I did not get an “Attack!” notification.

I also lost two buildings on the island under the first island. This could have been an Barbarian as well. I thought there was something deeper going on because some of the Barbarian buildings also vanished. But maybe the AI controlling the barbarians just clicked the “Destroy” button and I came too late to see the ashes.

In any case, when the port vanished, I did not know yet that the mission became unfinishable. Later I hoped that I can reach the island from below after conquering the Barbarian territory.

**Comment by Noordfrees** [comment]
Any building that conquers land can be attacked: Militarysites, the HQ and ports. Also, if you dismantle military sites, the now-unguarded land can be conquered by other players, on which case any buildings you built are burnt down. No messages are sent about this.

The game is not yet lost now, you *can* still reach the artifact from the south. The red player's territory is all on one large island with several port spaces. But it's somewhat harder to win now of course…

It seems there is no real bug here so this issue can be closed.

**Comment by Ordoviz** [comment]
The port should not be attackable. It’s not the player’s fault that it got destroyed. How should they know that this is even possible? There is no visible threat on the island. If a player loses in a game and it’s not their fault, they will be frustrated.

And the fix seems quiet simple: Just disconnect the small island from the big island so that no Barbarian can reach the port. Remember: This is a medium difficulty campaign for newcomers.

**Comment by hessenfarmer** [comment]
Well. the island there was designed as a backdoor to the barbarians homeland, so I am against deleting the small landbridge. it might serve as a good source of marble in the beginning of the game leaving the opportunity to build a military building.
Ports are attackable as they can store soldiers. so not storing some of them in the building might be considered suboptimal. 

only valid complaint might be how should a player know that it can be attacked? Well. at least it is explained in the seafaring tutorial. , however we should probably add this to the game FAQ and /or the in game help

**Comment by Niektory** [comment]
Building a tower to the north across the strait lets you conquer the remaining scraps of enemy territory and enables an expedition to build another port:

![shot0162](https://user-images.githubusercontent.com/4470900/105410514-550d7e80-5c32-11eb-9028-124c14e00881.png)

I'd suggest modifying the map slightly by removing some building spaces so the red player can't block the port space from across the strait.

**Comment by hessenfarmer** [comment]
I am still against a modification as this spot was designed as valuable but vulnerable

**Comment by Ordoviz** [comment]
Maybe Amalea (the woman who gives you economy advice) can tell the player to leave some soldiers in the port?

**Comment by hessenfarmer** [comment]
> Maybe Amalea (the woman who gives you economy advice) can tell the player to leave some soldiers in the port? 
 
It sshould be Saledus as it is a military advice and it should be a general advice for all ports as we don't know the sequence a player build them but yes this would be doable together with the other measures

**Comment by hessenfarmer** [comment]
@Ordoviz 
I uploaded a branch to implement the advices. Maybe you could have a look into it. You may checkout the gaming FAQ on the homepage as well

**Comment by Ordoviz** [comment]
#4665 is a good addition. But if the player looses the port, they should be able to build a new port without any weird tricks. I like @Niektory’s idea:

> I'd suggest modifying the map slightly by removing some building spaces so the red player can't block the port space from across the strait.
