### ISSUE TITLE
Crash after save and Quit 

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4645]
I get some crashes after saving a game and afterwards quitting the game.

Don't know if the cause is always the same.

**To Reproduce**
1. Load a big save game
2. Play a bit
3. Save the game
4. Quit the game

Sometimes the main menu does not appear instead the whole game crashes. This time i get an ASAN report:
> SUMMARY: AddressSanitizer: SEGV /home/kaputtnik/Quellcode/widelands-repo/widelands/src/economy/supply_list.cc:42 in Widelands::SupplyList::remove_supply(Widelands::Supply&)

[bt.txt](https://github.com/widelands/widelands/files/5886782/bt.txt)

**Version:**
 - OS: archlinux
 - Widelands Version: [a846817@master] (Debug)

**Comment by frankystone** [comment]
A big save game for testing.

[test.zip](https://github.com/widelands/widelands/files/5886804/test.zip)

**Comment by Noordfrees** [comment]
Sounds related to https://github.com/widelands/widelands/issues/4533
