### ISSUE TITLE
Scenario The Green Plateau crashes

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4655]
There is a shipped map called "The Green Plateau". Trying to start it crashes the game.

**To Reproduce**
1. Start the map The Green Plateau

Result:
~~~~
[00:00:00.000 game] INFO: Forcing flag at (48, 14)
[00:00:00.000 game] INFO: Forcing flag at (42, 73)
[00:00:00.000 game] INFO: Forcing flag at (52, 27)
Speicherzugriffsfehler (Speicherabzug geschrieben)
~~~~

**Version:**
 - OS: archlinux
 - Widelands Version: [af82ca0@master] (Debug)

**Comment by matthiakl** [comment]
The atlanteans tribe isn't loaded, which is required for some prefilled buildings.
