### ISSUE TITLE
Choosing tribe in scenarios

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4661]
If you configure the scenario the green plateau you can change the tribes. But this has no effect, the tribe a aplayer plays is always barbarians.

**To Reproduce**
1. Configure the map the green plateau and change the tribe of player 1 from barbarians to another tribe.
2. Start the game 

You will play as barbarians although another tribe was chosen.

**Expected behavior**
Either prevent setting of a tribe in the game config screen for scenarios, or the game should set the chosen tribe for this player.

Maybe related: bug #2040

**Version:**
 - OS: archlinux
 - Widelands Version: [963b6b4@3849_win_conditions] (Debug)

**Comment by Noordfrees** [comment]
It's a UI bug. This scenario's tribes are defined as barbarians for all players so the dropdowns should be disabled.
