### ISSUE TITLE
expose win condition to lua

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4672]
Didn't found a way to examine the current win condition of a game in lua.

If the win condition is exposed to lua, an add-on can do different things depending on the win condition.

**Describe the solution you'd like**
Similar to [wl.Game.type](https://www.widelands.org/documentation/autogen_wl/#wl.Game.type) there should be a property `wl.Game.win_condition`

**Comment by Noordfrees** [comment]
Currently the C++ `Game` class only has a variable `win_condition_displayname_` which contains the win condition's (unlocalized) descname (e.g. `"Endless Game"`, `"Autocrat"`). For scenarios it is `"Scenario"`. Exposing this to Lua could be done easily also for v1.0. Would this be enough?

**Comment by frankystone** [comment]
Yes, i think it would be enough

But there is no need to hurry to get this in v1.0 :-)

**Comment by Noordfrees** [comment]
As I said this should be easy, so let's let add-on designers access this in 1.0 :)
