### ISSUE TITLE
macOS: libSDL2_image.dylib was built for newer macOS version (11.1) than being linked (11.0)

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#4679]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**

When compiling latest Version: e.g. e9ad8c0a8b258952ead573503af5de1a9d10c81b
I get ld: warning: dylib (/opt/local/lib/libSDL2_image.dylib) was built for newer macOS version (11.1) than being linked (11.0)

This may be reated to:
* lastest macOS 11.2.1
* Uprade of underlying macPorts System
* Update of Xcode to Version 12.4 (12D4e)

Relates Issue:
https://stackoverflow.com/questions/32270491/xcode-7-warning-was-built-for-newer-ios-version-5-1-1-than-being-linked-5-1#32697801

For now I found no Issues with the game itself, so see this as INFO only.

**Comment by matthiakl** [comment]
Have you tried cleaning up your build directory? This sounds like cmake needs to reevaluate the dependencies.

**Comment by klaus-halfmann** [comment]
This was a fresh build of https://github.com/widelands/widelands/pull/4677 
https://github.com/Notabilis/widelands/tree/3236-player-list but I had this this before. 
Lets kep this as a kind of tracking Issue for now.
