### ISSUE TITLE
HQ_Hunter does not destroy conquered military sites of other tribe

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4681]
Sorry, now i found a bug in hq_hunter:

If a player had conquered a military building wich belongs to a different tribe than the player plays, it get not destroyed if his headquarter was destroyed.

Difficult to reproduce... i have a replay but it does not work because [i used an addon which does not work for replays](https://github.com/widelands/wl_addons_server/issues/21)

Instead of a replay i try to explain:
Player A plays barbarians
Player B plays empire

1. Player A conquers a military site of player B, say 'empire_sentry'
2. Player B destroys A's headquarters

The conquered military site 'empire_sentry' from 1 will then not destroyed because it is not part of barbarians buildings.

I guess the culprit is in [check_player_defeated](https://github.com/widelands/widelands/blob/master/data/scripting/win_conditions/win_condition_functions.lua#L75)

where only buildings gathered a players tribe has.

**Comment by hessenfarmer** [comment]
yes i once used the allowed buildings per player and switched to the tribes buildings as they could be assessed more easy. switchingback should dot the trick
