### ISSUE TITLE
Watch window jumps to center of screen

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4689]
Related: #1232

If you open a watch window to watch an enemies military site and click on the military site inside the watch window, the watch windows jumps to the center of the screen.

**To Reproduce**
1. Open the watch window and move the content to see a foreign military building
2. Move the watch window to e.g. the upper left corner
3. Eventually wait until soldiers arrive at the watched military site
4. Click the military inside the watch window

**Expected behavior**
The watch window should stay where it is.

**Version:**
 - OS: archlinux
 - Widelands Version: [9d5409e@master] (Debug)

**Comment by Noordfrees** [comment]
This bug has been around for some time
