### ISSUE TITLE
Territorial time lua error after first player is defeated

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4699]
In the attached savegame, after the first player (empire) is defeated, the following error occured:
```
[03:00:48.100 game] ERROR: Error in Lua Coroutine
[03:00:48.100 game] ERROR: [/mnt/storage/Programme/widelands/src/scripting/lua_errors.cc:22] [string "scripting/win_conditions/territorial_function..."]:105: attempt to perform arithmetic on a table value (local 'fields')
[03:00:48.100 game] ERROR: Send message to all players and pause game
```
The save is a multiplayer pure AI game, so I'm not sure, whether this is related to multiplayer, ai or is a general bug.
[save.wgf.zip](https://github.com/widelands/widelands/files/6022915/save.wgf.zip)

**Comment by hessenfarmer** [comment]
confirmed. Strange thing is I got the error in line 69 instead of 105 will investigate.

**Comment by frankystone** [comment]
Those wincondition scripts are very complicated... at least for me.

The only place where `fields` will be a table is in https://github.com/widelands/widelands/blob/master/data/scripting/win_conditions/win_condition_functions.lua#L69

This should be `local fields = {}`, but i am totally unsure if this will fix it.

**Comment by Noordfrees** [comment]
Sounds like there might be two variables called `fields` which occasionally overwrite each other? All variable names should be globally unique…

> Those wincondition scripts are very complicated... at least for me.

You're not the only one :D

**Comment by hessenfarmer** [comment]
> 
> 
> Sounds like there might be two variables called `fields` which occasionally overwrite each other? All variable names should be globally unique…
> 
> > Those wincondition scripts are very complicated... at least for me.
> 
> You're not the only one :D

Yep I was not aware of the other variable, fix will be easy then

**Comment by matthiakl** [comment]
Should the fix be possible for the save directly? I renamed the table `fields`, but still get the error.

**Comment by frankystone** [comment]
> Should the fix be possible for the save directly?

No, afaik. One of the biggest drawbacks of lua scripts.

**Comment by Noordfrees** [comment]
Scripting data is stored as a binary dump file in savegames, so a savegame with broken scripting can not be fixed :( 

---

We should also add a warning note to the documentation that all variable names must be globally unique. It could also be good to rename all variables used by those scripts to names that are less likely to be used by modders, e.g. `__win_conditions_<variablename>` and `__starting_conditions_<variablename>`.

**Comment by hessenfarmer** [comment]
> We should also add a warning note to the documentation that all variable names must be globally unique. It could also be good to rename all variables used by those scripts to names that are less likely to be used by modders, e.g. `__win_conditions_<variablename>` and `__starting_conditions_<variablename>`.

Well this would be a big task and will gain only limited security. The hint to check for the variable name to be unique in scripting should be added to the scripting documentation though. Toghether with having as little global variables as reasonable. Sorry this is a perfect example of me doing 2 faults in one declaration.

**Comment by frankystone** [comment]
Normally defining variables as `local` is enough. Exceptions are global variables like 'pl', 'plr' or 'map'.

So +1 from my side to make global variables as unique as they can be. And to mention a rule for global variables in the documentation. A rule can be e.g. `scenario_name_<variablename>` or `addon_name_<variablename>`. For winconditions or other shipped scripts  we may can have a shortcut: `wincon_<variablename>` or `startcon_<variablename>`. At least they shouldn't be too complicated to write. Not all can touch typing :-D

Edit: But this should be a task for another release

**Comment by frankystone** [comment]
> Sorry this is a perfect example of me doing 2 faults in one declaration.

No need to say sorry :-)
