### ISSUE TITLE
Switch tundra/taiga terrains

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4732]
From a Transifex string issue:
>  I suggest renaming tundra as taiga and taiga as tundra. Taiga should be a forested biome. In tundra, there are no trees. 

Let's rename the terrains without changing the values:

<table>
<tr>
	<td> Old:
	<td> New:
	<td> Best tree growth:
<tr>
	<td>Tundra 1
	<td>Taiga 1
	<td> 88,3%
<tr>
	<td>Tundra 2
	<td>Taiga 2
	<td> 92,3%
<tr>
	<td>Tundra 3
	<td>Taiga 3
	<td> 89,4%
<tr>
	<td>Tundra Taiga
	<td>(unchanged)
	<td> 62,2%
<tr>
	<td>Taiga
	<td>Tundra
	<td> 36,9%
</table>

The four terrains to rename need to get a previously unused new internal name; by adding these mappings to the legacy lookup tables we can change the names without making existing winterland maps unplayable.

**Comment by hessenfarmer** [comment]
first we need to check the growth probabitlity of trees in the current terain definitions. Afterwards we should decide what to do.

**Comment by Noordfrees** [comment]
Added this info to the table above. Current tundra is very well suited for coniferous trees; nothing grows well on taiga; tundra taiga is in-between. In reality it should be the other way around.

**Comment by frankystone** [comment]
See also: #3154
