### ISSUE TITLE
Team vision bug regression

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4741]
![shot0000](https://user-images.githubusercontent.com/48293446/110141699-b5691180-7dd5-11eb-9a97-90cef6688163.png)

This is what happens when changing a player's team during the scenario. Before, player 1 was in team 1 and player 2 in no team (0); the scripting line is `p2.team = 1`. Apparently player1's vision is not updated. 

Version: `1.0~git25220[12de8e4@fri04] (Debug)` (code is equal to 83ac0475c7c03e07a1c2dac6c476a8a41cc2983f)

**Comment by hessenfarmer** [comment]
if player2 is red then it looks like player1 got the same vision as player 2. I can't see the problem in this screenshot

**Comment by Noordfrees** [comment]
The terrain and roads info has not been updated when the teams merged. That's why everything is coloured as meadow1 and player 2's roads are invisible. (The wintery landscape visible in the southern part of the image just goes on in the northern part.)

--- 

EDIT: This is what the map is meant to look like (the bug goes away after save-reloading because all visible fields are rediscovered on load)
![shot0001](https://user-images.githubusercontent.com/48293446/110203944-f2361680-7e70-11eb-9325-e86152f3bdbc.png)
