### ISSUE TITLE
No buttons anymore in Save game menu

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4750]
I have no buttons anymore in the save game menu:

![shot0006](https://user-images.githubusercontent.com/6730556/110248429-5c35e500-7f71-11eb-8393-d91fb640d697.jpg)

Don't know if this is important: This screenshot is taken with the normal theme, but previously i have played with my minimalistic theme. There i noticed the missing buttons so i turned on the normal theme. But the buttons are still missing. Restarting the game does also not help.

**Version:**
 - OS: archlinux
 - Widelands Version: [7243b3d@master] (Debug)

**Comment by Noordfrees** [comment]
Confirmed with 05232a8f6b572824f355dcc8aba8e2caa0c1db2b and default theme, perhaps related to #4742 @matthiakl?

**Comment by frankystone** [comment]
> ... perhaps related to #4742 @matthiakl?

Yes, definetly. The commit prior to this one shows the buttons.

**Comment by matthiakl** [comment]
Sorry, I overlooked this menu and did not test it. A fix is on its way.
However, I noticed a layouting bug in this menu (Maximize window, then resize again). This also happens on branches before my PR, so it seems to be unrelated:
![Bildschirmfoto vom 2021-03-07 23-05-50](https://user-images.githubusercontent.com/23122583/110256680-6d471c00-7f9a-11eb-9ca0-ce3b4a9abbb4.png)
