### ISSUE TITLE
new_game_template: Setting win_condition from Addon  does not work

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4757]
Trying to set a win_condition as Addon in the new_game_template crashes the game:

~~~~
[00:00:05.171 real] INFO: WidelandsMapLoader::load_map_complete() for 'Islands at War' took 766ms                                                  
terminate called after throwing an instance of 'LuaScriptNotExistingError'                                                                         
  what():  [/home/kaputtnik/Quellcode/widelands-repo/widelands/src/scripting/lua_errors.cc:22] The script 'scripting/win_conditions/First Hero Wins' was not found!                                                                                                                                   
Abgebrochen (Speicherabzug geschrieben)
~~~~~

I have tried to set the value from `wc_name` ( i guess this is the internal name), also the path, e.g. `'addons/first_hero_wins.wad/first_hero_wins.lua'` but it looks like the game searches only the path `scripting/win_conditions/` for win conditions. I have also tried to enable the addon in `mainmenu -> addons` prior starting it on the command line with the option `--new_game_from_template=`. Nothing worked.

**To Reproduce**
1. Copy the original  artifacts.lua to `addons/artifacts_1.wad/`, may rename the file to artifacts_1.lua, also change the value of `wc_name` to "Artifacts_1"
2. Create a file 'addons/artifacts.wad/addon'
3. Copy the new_game_template to a location where it should work and set `win_condition="Artifacts_1"
4. Try to start the game with the  option `--new_game_from_template=path_to/new_game_template`

**Version:**
 - OS: archlinux 
 - Widelands Version: [505c6c4@master] (Debug)

**Comment by Noordfrees** [comment]
You must use *only* the add-on's internal name: 
```
# The filename of the win condition script (without path), or the internal name of the add-on defining the win condition. Default: Endless Game.
win_condition="first_hero_wins.wad"
```

Whether the add-on is enabled doesn't matter, only the template's `addons` key is used to determine which add-ons are enabled in this game. But a win condition should work even if the add-on is not listed in this section.

**Comment by frankystone** [comment]
Ah, thanks. Please clarify this:

> .... or the __internal name__ of the add-on defining the win condition.

I have stumbled over this _internal_name_ and was not sure what this refers to. I wouldn't expect that this is just the name of the folder.

**Comment by Noordfrees** [comment]
Okay I just realized that I use internal add-on names all over the code everywhere where add-ons are used, but the doc only contains this tiny reference 
https://www.widelands.org/documentation/add-ons/#campaign
will adjust the documentation for add-ons and the shipped game template
