### ISSUE TITLE
Unknown map object type

### ISSUE THREAD

**Issue by spirillen** [widelands/widelands#4768]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
See screenshot

**To Reproduce**
1. Continue game

**Expected behavior**
:thinking: :thinking: :thinking: 

**Screenshots**
![image](https://user-images.githubusercontent.com/44526987/110866312-41db6e80-82c5-11eb-8db6-9365367c7d9f.png)

**Version:**
 - OS: [Ubuntu 20.04
 - Widelands Version: "Build 1", "`bzr9823~202103102232`"]

**Additional context**
Was looking for logs in /usr/share/games/widelands but could not find any

**Comment by matthiakl** [comment]
Some more information would be helpful: 

- Start widelands in a terminal to see and copy the log
- In which version did you save the game? 
Go to the load game window for this information.

**Comment by frankystone** [comment]
The `amazon_youth_gathering` was renamed to `initiation_site` recently. I guess the last save game was a made with a previous version, then you have updated widelands and the game can't find the old name anymore.

Such things can happen when using a development build...

**Comment by Noordfrees** [comment]
Yep, that's correct. You can repair the savegame manually though:
- Unpack the savegame (in case it is a zip file).
- Open the files `map/binary/building` and `map/binary/building_data` with a hex editor (e.g. GHex) and do a Replace All with `amazons_youth_gathering` → `amazons_initiation_site`.
- Replace the occurrence in `map/allowed_building_types` with a plain text editor as well.

I'll close this issue as wontfix.

**Comment by spirillen** [comment]
Yep, I notice as I started a new game, that it was cursed by a renaming of the youth center.

But I would like to suggest that, in the future of similar events, that there could be:

1. A message in the error, stating there was a renaming.
2. A builtin naming converter / Alias handling.

**Comment by Noordfrees** [comment]
When a unit is renamed between releases, it is added to the compatibility lookup table and the name is converted automatically when loading. But for development versions we don't usually bother with this as we don't guarantee stability here.
