### ISSUE TITLE
On win7 game crashes with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by another-m00** [widelands/widelands#4774]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
I'm not sure if this game is developed for win7, but I'll try to submit this bug report.
On Windows 7 enterprise, the program immediately crashes with the code 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)
(The error code is only aviable in the event log)

**To Reproduce**
1. Install the game.
2. Open either the game or the map editor
3. The app crashes without any error message

**Expected behavior**
Well, the app sould at least either throw an error, prevent installing or start normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/71275068/111817597-790dd900-88de-11eb-8501-83132c41bad8.png)

**Version:**
 - OS: Window 7 enterprise
 - Widelands Version: Build 21, offical Windows binary

**Additional context**
I could not find any bug report like this, so I created one.

![image](https://user-images.githubusercontent.com/71275068/111818110-1a952a80-88df-11eb-818f-03d0ce9b6393.png)
Translation:
Faulting application name: widelands.exe, version: 0.21.0.1, timestamp: 0x00000000
Faulting module name: unknown etc...
Exception code:0xc0000005
Fault offset: 0x00000000
Faulting prcess id: 0x1530
Faulting application start time: 0x01d71ce28cda3098
Faulting application path: C:\Users\Desktop\AppData\Local\Widelands\widelands.exe
Faulting module path: unknown
Report ID: cbef882a-88d5-11eb-bb9e-0025b329ee98

**Comment by frankystone** [comment]
Widelands does not support operating systems which are not maintained anymore. Sorry.

**Comment by another-m00** [comment]
Well, thats going to be a fork once I get some experience with C.

**Comment by Noordfrees** [comment]
Do you have the `stdout.txt` from the crash? It probably contains more information about what caused the crash. Good chance it might even be one of the crashes we fixed since build21.

**Comment by another-m00** [comment]
Oh, right, i forgot to incude that

```
This is Widelands Version build-21 (Release)
Set home directory: C:\Users\Desktop\.widelands
Set configuration file: C:\Users\Desktop\.widelands/config
Widelands executable directory: C:\Users\Desktop\AppData\Local\Widelands
Adding directory: C:\Users\Desktop\AppData\Local\Widelands\data
WARNING: No locale translations found in C:\Users\Desktop\AppData\Local\Widelands\data\locale
selected language: en
Byte order: little-endian
Graphics: Try to set Videomode 1024x768
Graphics: OpenGL: Version "2.1.0 - Build 8.15.10.2302"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 8
Graphics: SDL_GL_BUFFER_SIZE is 32
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 16
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 16
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 1
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 4096
Graphics: OpenGL: ShadingLanguage: "1.20  - Intel Build 8.15.10.2302"
**** GRAPHICS REPORT ****
 VIDEO DRIVER windows
 pixel fmt 370546692
 size 1024 768
**** END GRAPHICS REPORT ****
```

I can't find any note of error though :(

**Comment by Noordfrees** [comment]
Looks perfectly fine… The first step after the end of the graphics report is normally the loading of the style manager templates, which is prone to crash if something is wrong with the template file. There is no success message for this in the log. Does the file `C:\Users\Desktop\AppData\Local\Widelands\data\templates\init.lua` exist?

**Comment by another-m00** [comment]
Nope, only in the Default subdirectory, and it's hidden.
I'll check it out. _Which Lua version does it need?_... It seems any version

**Comment by Noordfrees** [comment]
My mistake that's the one I meant. So the datadir is also detected correctly and the template file is where it should be. I'm out of ideas now… :(

**Comment by another-m00** [comment]
I'll check the init function in the source to see what else come next

**Comment by Noordfrees** [comment]
The next ones are the mouse cursor and the sound handler. So you could try if one of the following commandline parameters would help:
```
--nosound
--sdl_cursor=false
```

**Comment by another-m00** [comment]
Iirc, the cursor didn't work on the 0.18 build either :(
with `--nosound` the window stayed alive for 2 more seconds, then crashed,
with `--sdl_cusor=false` inmediately crashed,
with both, inmediate crash again
So one of the errors might be with the sound module.
The stdout shows nothing new.
