### ISSUE TITLE
MP setup changes tribes of savegame players

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4778]
Select a savegame in the LaunchMPG setup. It is possible to share a saved slot with a different player, even if that player uses a different tribe, resulting in the shared slot to be assigned a different tribe. It is also possible to assign an AI to a player with New Tribe, in which case the tribe is changed to Amazons.

**Comment by matthiakl** [comment]
Is sharing a slot after a game has started even implemented? I tried sharing a savegame slot with a player with the same tribe, but don't get access it in game. So maybe we should just disable the "Shared in" option for savegames.
