### ISSUE TITLE
Help overlay menu is cut off

### ISSUE THREAD

**Issue by Borim7** [widelands/widelands#4781]
**Describe the bug**
When playing widelands in default resolution the menu for help overlays is cut off. An example is given as screenshot.

**To Reproduce**
1. Start widelands with default configuration, no changes after install
  * resolution: 800 x 600
2. Start any game
3. Click on overlay menu, where you can display building names etc.
4. The displayed menu is cut off

**Expected behavior**
Menu is completely visible

**Screenshots**
![overlay bug](https://user-images.githubusercontent.com/5786802/111917316-9928ce00-8a7f-11eb-81e9-a90e00144a29.png)

**Version:**
 - OS: Ubuntu 20.04
 - Widelands Version: PPA build 1.0~bzr9830

**Comment by klaus-halfmann** [comment]
OK, this happens in German (or some other "long String" Language) only.
Will test that fix now
