### ISSUE TITLE
Cannot get rid of maximized="true" via commandline or options menu

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#4783]
**Describe the bug**

Once the Option "Window Size" is set to "Maximized" (config: maximized="true" )
one cannot get persistently get rid of it by either setting a normal size or using command line opttions.

**To Reproduce**

1. Open the Options Menu and set "Window Size" to  "Maximized"
2. Click OK or Apply -> Size changes
3. Quit Widelands and reopen
4. Widelands starts with a maximized WIndow again.

Same applies for options like `widelands  --xres=800 --yres=600 --fullscreen=false`

Workarounds:
* scale the window by dragging the border or such
* Manually edit ~/.wideland/config

**Expected behavior**

* There is a commandline option --maximized=true|false
* Setting an option other than "Maxixmized" will reset the config flag maximized to false
* -fullscreen=true  should still override any size or the maximized flag.

**Version:**
 - OS: macOS
 - 1.0~git25245[0acf306@master]

**Additional context**
* Found this while checking #4781
* Not a big Issue but can be annoying in case you want a well defined, fixed size and you cannt find the workaround

**Comment by frankystone** [comment]
> **To Reproduce**
> 
> 1. Open the Options Menu and set "Window Size" to  "Maximized"
> 2. Click OK or Apply -> Size changes
> 3. Quit Widelands and reopen
> 4. Widelands starts with a maximized WIndow again.

Yes, it should so, imho. If you want another fixed size, just set it in the options. After restarting this new option is used.

Don't get the problem here.

**Comment by klaus-halfmann** [comment]
Hmm maybe this is an macOS only Issue?
Maybe its differnt as I have a dual Monitor setup?

Please check my Sccrencast here: https://www.magentacloud.de/share/ygwso1qmey
Anyone else with macOS around?

**Comment by frankystone** [comment]
Ah, that makes it more clear.

The problem is that command line options `--xres=` and `--yres=` doesn't apply once the window was maximized.

1. Start widelands and set resolution to maximized
2. close widelands
3. Try to start widelands with command line options like `./widelands --xres=800 --yres=600`

Result:
Windows is maximized although another resolution was given on the commandline

**Comment by frankystone** [comment]
I think in general command line options should preferred over settings from `config` file. If feasible without changing the config file.
