### ISSUE TITLE
[Duplicate] `SupplyList::remove_supply` crashes when leaving game

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#4792]
**Describe the bug**
The game crashed.

**To Reproduce**
While working on translation, I switched several times between Options and loaded singleplayer games, often pausing the game for a long time. The last game I loaded was originally an autosave after the host exited from a local multiplayer game. After running it at 8x speed for a while waiting for some buildings (with very low FPS - AIs not able to keep up according to stdout), I wanted to quit before memory runs out (happened a few times before, though on clean exits LeakSanitizer only reports a few hundred bytes leaked), so I saved the game (attached), and selected Exit Game. This caused the game to crash. End of stdout attached.

**Version:**
 - OS: antix / debian buster with some backports
 - Widelands Version: 1.0, 632406b9f6f00a977de9c7bd92316d0ee4784e39

[wl1_crashreport.txt](https://github.com/widelands/widelands/files/6232989/wl1_crashreport.txt)
[before_crash.wgf.gz](https://github.com/widelands/widelands/files/6232991/before_crash.wgf.gz)

**Comment by tothxa** [comment]
Maybe it's a case of #4645

**Comment by Noordfrees** [comment]
Yep, that's again the ominous `SupplyList::remove_supply` crash
