### ISSUE TITLE
Editor addons; create windows?

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4801]
The editor lacks some functionality which can be implemented as an add-on. E.g.:

* Change terrain from one type to another
* Copy some parts of the map

But this is currently not possible, because there is no possibility to ask for a terrain type, e.g. by a window.

**Describe the solution you'd like**
It would be nice if one can create windows inside the editor. Maybe also with a shortcut to open it. Very nice would be to have the possibility get the field a player has clicked on (this would be nice also for scenarios). I imagine a workflow like:

* Open window "Change terrain" with a sentence like "Click on the terrain on the map which you like to change"
* User clicks on the map and the script gets the field and thus the terrain type "xy"
* The window text changes, or a new window opens "Click on the terrain you would like the terrain xy to change to"

**Describe alternatives you've considered**
The only alternative i think is to use the debug console...

**Implementation steps**
- [ ] Add possibility to show a window in the editor. This should be simple, e.g. similar to [kdialog](https://develop.kde.org/deploy/kdialog/#kdialog-dialog-types), say `local w = ui.new_window("title", "message", inputbox)` where the third parameter is the type. Here it add's an input field to the box. Other types might be `[yes_no|combobox|...]`
- [ ] Add possibility to get a field a user has clicked on. This can also be used for scenarios, e.g. to determine if an immovable stands on this field. 
- [ ] ?

**Comment by Noordfrees** [comment]
+1
I see two ways to implement this:
- As a Script add-on. The only change needed in the backend is to allow running these in the editor (easy, probably); and for the Lua API we'd need to implement #2117 plus some additional features. 
    The user-clicked-field hooks will be the hardest part; I tried out a similar thing ("callback functions") a while ago and after a while scrapped my work and picked a different approach for whatever feature that was intended for.
- As a new add-on category "UI Extension" or such (which could also be used to enhance the in-game UI to allow automizing common tasks). We might not even need many Lua changes as we could let C++ autogenerate the UI according to some table in the init.lua, and invoke various Lua functions when the user clicks a button, the user clicks a field, to determine with what data to fill in the UI elements, etc. This approach is probably more difficult, but seems much more appealing to me.
