### ISSUE TITLE
Barracks missing in campaig

### ISSUE THREAD

**Issue by GoobScooper** [widelands/widelands#4804]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
The "barracks" building is missing in the campaign scenarios, making it impossible to produce new soliders.

**Version:**
 - OS: MacOS
 - Widelands Version: Build 21

**Comment by frankystone** [comment]
Which scenario exactly?

In some scenarios some of the buildings are not allowed to build, or some buildings are only allowed after specific objectives have been fulfilled.

**Comment by GoobScooper** [comment]
> Which scenario exactly?
> 
> In some scenarios some of the buildings are not allowed to build, or some buildings are only allowed after specific objectives have been fulfilled.

An Outpost for Exile (from the Empire campaign) is one example.  End of the mission the barracks is still not available.

**Comment by GoobScooper** [comment]
Worked out the issue - the last objective wasnt triggering.  Loaded from an earlier save, built the required buildings and it fixed the issue
