### ISSUE TITLE
UI: Mouse wheel issues

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4812]
**To Reproduce**
1. Open the tribal enccloypdia
2. Move mouse pointer to the right panel "About Widelands"
3. Use the mouse wheel scroll down
4. The next tab get activated and the left and right panel get updated
5. Use the mouse wheel again
6. Now the entry in the right panel moves up-down

**Expected behavior**
Exclude switching tabs when using the mousewheel. A tab is like a button, so it should work the same way, imho.

**Version:**
 - OS: archlinux
 - Widelands Version: [296b275@master] (Debug)

**Additional context**
In general the new handling of focus, mouse and shortcuts is sometimes very confusing for me. E.g. #4557 and there are some more issues with me and the new handling ;) For example i find also very annoying that the right panel of the tribal encyclopedia changes its content if i use the mouse wheel in the left panel.
Should we make a single bug for related things?

**Comment by Noordfrees** [comment]
How about letting tab panels handle the mousewheel only if the mouse is over the row of tab buttons?

> For example i find also very annoying that the right panel of the tribal encyclopedia changes its content if i use the mouse wheel in the left panel.

This is intentional – using the mousewheel over a list iterates through the list's entries. Simply point on the scrollbar on the right of the list instead to scroll the list without changing the selection.

>  Should we make a single bug for related things?

Let's discuss all related things in this issue

**Comment by frankystone** [comment]
> How about letting tab panels handle the mousewheel only if the mouse is over the row of tab buttons?

If scrolling through tabs is really needed this would be the better approach, imho.

> > For example i find also very annoying that the right panel of the tribal encyclopedia changes its content if i use the mouse wheel in the left panel.
> 
> This is intentional – using the mousewheel over a list iterates through the list's entries. 

When one is scrolling the left panel he probably searches an item. The flickering on the right side steals the focus of searching the item.

> Simply point on the scrollbar on the right of the list instead to scroll the list without changing the selection.

I would never assume this, and from my experience i don't know any program that behaves like this.

**Comment by Noordfrees** [comment]
> > Simply point on the scrollbar on the right of the list instead to scroll the list without changing the selection.
> 
> I would never assume this, and from my experience i don't know any program that behaves like this.

The MATE menus behave like this when they're too large to fit the screen: Point on the scrolling arrows while using the wheel and the selection stays the same; point at the list while scrolling and the selection moves along with the view.

---

If there are more points where the mousewheel or keypress behaviours are considered confusing/intrusive/unexpected by some, we could also add an option "Disable smart UI" or such that disables all of those.

**Comment by frankystone** [comment]
I have tried to find a video of the Mate desktop where this is shown but didn't found one. 

Maybe i am just too old school for such new things.
