### ISSUE TITLE
Editor: Add a history list of last used tools

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4813]
When working with the editor one does similar things close after each other. Say place summer terrain x, place wasteland terrain y. Every time one has to make several clicks to change from summer terrain x to wasteland terrain y.

**Describe the solution you'd like**
It would be nice to have a window which shows the last 10 'actions' a user has done. An 'action' consists of the used tool + the values used with this tool. Clicking on an entry in this list will activate the according tool with the assigned value(s). E.g. the List may have the following entries:

1. Terrain: "Summer meadow"
2. Terrain: "Wasteland ingneous rocks"
3. Height: "Increase 1, Set to 10"
4. Immovables: "Spruce, Alder, Rocks 1, Rocks 4"
5. Set Height: "Increase 2, Set to 10"
6. Resources: "Coal, Increase: 1, Set to: 64"
7. Resources: "Iron, Increase: 1, Set to: 10"
8. Terrain: "Summer mountain 1"
9. Set Height: "Increase 1, Set to 24"
10. Animals: Deer, Moose, Bear

Clicking on entry number 7 activates the Tool "Resources" with the given values (Iron, Increase by 1, Set to 10). Afterwards clicking on entry 4 activates the tool "Immovables" with the given values (Spruce, Alder, Rocks 1, Rocks 4). Clicking an entry will not change its position in the list, instead it will be highlighted, so a user knows which tool/value(s) he is actually working with.

A new entry will be added on top of the list if the chosen tool/value(s) is not already in the list.

**Implementation steps**
- [ ] 
- [ ] 
- [ ]

**Comment by Noordfrees** [comment]
It probably wouldn't work exactly like this. Technically, most tool windows have 2 or 3 separate tools associated with them, e.g. the Resources tool window has an "Increase Resources" tool, a "Decrease Resources" tool, and a "Set Resources" tool. The modifier key held down determines which of the three tools is used when clicking the map. So this history would contain entries like "Increase Resources: Coal, 1" or "Decrease Resources: Iron, 2". How should it be handled when clicking on a secondary or tertiary tool's record?

(Btw, the undo/redo history is implemented in a similar way: by keeping records of which tool to use with which parameters at which locations in which order. We could consider implementing this feature as an extension of that system, but then *every* new tool action would generate a new history entry regardless of whether it was already in the list.)

**Comment by frankystone** [comment]
Adding new tool actions if they aren't in the list would be just the final touch :-)

So i am fine with an extension of the _un/redo_ functionality.
