### ISSUE TITLE
Widelands installed blocks upgrade to Fedora 34

### ISSUE THREAD

**Issue by blu2lz** [widelands/widelands#4814]
Hi,

I want to let you know that the Widelands package blocks the Fedora upgrade from 33 to 34 because the upgrade that landed in 34 was obsoleted in 33 because of conflicts with the fonts. Could you please build an intermediate package for Fedora 33 that solves that conflict?

[Package for 34 in Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2021-08852b7ddd)
[Package for 33 in Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2021-b985d33aac)
[Bug Report in RedHat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1947182)

Thanks!

**Comment by Noordfrees** [comment]
The linked bug shows that it's a problem with the Culmus fonts bundled with Widelands. We last modified this shipped font over [6 years ago](https://github.com/widelands/widelands/tree/master/data/i18n/fonts/Culmus). To me this looks like it might be a problem with the Fedora packages rather than with Widelands itself?

**Comment by matthiakl** [comment]
The easiest way should be to uninstall Widelands, upgrade Fedora, install Widelands again.
The user data does not get deleted together with packages, so you won't loose anything.
To be safe, you can create a backup of your homedir (either `~/.widelands` or `~/.config/widelands` + `~/.local/share/widelands`)

**Comment by blu2lz** [comment]
> The linked bug shows that it's a problem with the Culmus fonts bundled with Widelands. We last modified this shipped font over [6 years ago](https://github.com/widelands/widelands/tree/master/data/i18n/fonts/Culmus). To me this looks like it might be a problem with the Fedora packages rather than with Widelands itself?

Yes. In the changelog it states “Unbundle Culmus fonts”, so I think that’s related. I hoped the package maintainer would read here to maybe react to the problems since there is no reaction in Bodhi oder Bugzilla. Maybe that is not the case, so feel free to close this issue if it does not fit here.

> The easiest way should be to uninstall Widelands, upgrade Fedora, install Widelands again.
> The user data does not get deleted together with packages, so you won't loose anything.
> To be safe, you can create a backup of your homedir (either `~/.widelands` or `~/.config/widelands` + `~/.local/share/widelands`)

Sure, that’s what ***I*** will do. I still think that it is unfortunate that the package is just built “fire and forget” and nobody seems to care about it getting negative karma on Bodhi because an upgrade of the package wasn’t even tested. An average user just sees the error message on upgrade and might not know what to do.

**Comment by blu2lz** [comment]
If the package maintainer looks at this issue here first:
https://bugzilla.redhat.com/show_bug.cgi?id=1947182#c1

**Comment by matthiakl** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1947182#c1

The linked bug report is marked as resolved, so I assume this is fixed.
