### ISSUE TITLE
update-script not working

### ISSUE THREAD

**Issue by PinPhreek** [widelands/widelands#4821]
**Describe the bug**
the updatescript errors out.

**To Reproduce**
run `sh update.sh`

it crashes with `sh update.sh: line 18: compile.sh: command not found`

**Expected behavior**
update and compile with no errors

**Version:**
 - OS: Arch Linux
 - Widelands Version: current master (5ba1114)

**Comment by Noordfrees** [comment]
Can you post the 18th line of your `update.sh`? (edit: and also the exact complete command with which you last compiled Widelands)
The script is autogenerated from the invocation of `compile.sh`. e.g. for me this line says `./compile.sh -r -c -j 2` which works fine.

**Comment by PinPhreek** [comment]
18th line: `complie.sh`. That's all.

**Comment by Noordfrees** [comment]
That's weird, it should not be possible to run the script without a path in the first place… 
can you try recompiling (by invoking `./compile.sh` again), and see whether the update script is still broken afterwards?

**Comment by PinPhreek** [comment]
Yup works now. Thanks for the help ^^. Shall I close this issue?
