### ISSUE TITLE
Addons manager 'Browse': Disable remaining 'type' entries if user clicks on one type

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4828]
It is a bit time consuming when one searches an addon of a specific type: One has to disable all other types to filter out the add-on's type he is not interested in.

**Describe the solution you'd like**
1. Opening  _"Addons -> Tab Browse"_: All types are enabled
2. Clicking on one of the types all other types get disabled (and not shown). E.g. Clicking on 'Scripts' the list should only show add-ons of type 'script'.

A player can easily distinguish between the types this way.

**Comment by Noordfrees** [comment]
You can use <kbd>Ctrl</kbd>+Click to enable a type and disable all others. But since filtering for 1 specific type is probably the most common usage, we could make that the default and use the modifier to allow selecting multiple types instead.
