### ISSUE TITLE
Dependency graphs for the Lua documentation

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4851]
I really miss a dependency graph for all the Lua classes in the documentation. This would make some things more easy to understand.

**Describe the solution you'd like**
Consider using the [graphviz extension](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html) and the [inherintance-diagram extension](https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html) to provide such graphs in our Sphinxdoc documentation.

**Describe alternatives you've considered**
One can do such a graph by hand, but changing this each time if something has changed, e.g. new classes get added, isn't useful.

**Comment by frankystone** [comment]
The inherintance_diagram extension works only for python, so it is not available for our documentation.

What i have for now is (thanks to Noordfrees for the ASCII-graph):
![class_graph](https://user-images.githubusercontent.com/6730556/117587132-b6435a00-b11c-11eb-83de-efd27c54c59f.png)

The `…` below `Building` is a clickable link which points to the class, which, ideally, shows  the inheritance graph for `Building`

The corresponding code is a bit big:
~~~~
   .. graphviz::
      :align: right
      :caption:
      
      graph dependency {
         bgcolor="transparent";
         node [shape=box, style=filled, fillcolor=white, fontsize=11];
         edge [color=white];
         MapObject [fillcolor=green, shape=oval]
         more [label="…", href="../autogen_wl_map.html#building", target="_parent"]
         
         MapObject -- {Bob BaseImmovable}
         Bob -- {Ship Critter Worker}
         Worker -- Carrier -- Ferry
         BaseImmovable -- {MapImmovable PlayerImmovable}
         PlayerImmovable -- {PortDock Flag "Road/Waterway" Building}
         Building -- more
      }
~~~~

Is it worth the work?

**Comment by frankystone** [comment]
Is this correct for Warehouse?

![class_graph_warehouse](https://user-images.githubusercontent.com/6730556/118100442-bd958c80-b3d6-11eb-85dd-bdfc9a574328.jpg)

The actual class (the chapter one is looking at) is marked with a green background. And show also the dependency-tree to the main class. The main class is always shown with a shape of a house. In between classes are shown inside a tooltip.

Since writing such RST-directives is a big task i am thinking about doing such things automatically. Either by adjusting extract_rst.py or by a new file.

**Comment by frankystone** [comment]
Can someone explain where the classes `HasWares`, `HasSoldiers`, `HasInputs` and `HasWorkers` are defined?

From my understanding they aren't classes at all. They are just some sort of a summary of methods which applies to the corresponding classes. E.g. a `Warehouse` and a `Flag` implements the methods defined by `HasWares`.

I think the current documentation is a bit confusing.

**Comment by Noordfrees** [comment]
These are abstract concepts, sort of like an [interface](https://docs.oracle.com/javase/tutorial/java/concepts/interface.html). They have no connections to the C++ backend and merely specify some functions that should be found in several classes that are only semantically related. So these interface "classes" are purely virtual and exist only in the documentation, not anywhere in code. Actually I don't really see the benefit of having this distinction at all.

**Comment by frankystone** [comment]
> Actually I don't really see the benefit of having this distinction at all.

Sorry, i fear to misunderstand this. Can you explain a bit more?

I am in favor to exchange the headings. Instead of marking as a class  

> `.. class:: HasWares` 

we can write 
~~~~
.. _has_wares:

Common functions for Objects implementing wares
-----------------------------------------------

 This is at the time of this writing
   :class:`~wl.map.Flag` and :class:`~wl.map.Warehouse`.
…
~~~~

And instead of linking like:
~~~~
   Child of: :class:`Building`, :class:`HasWares`, :class:`HasWorkers`,
   :class:`HasSoldiers`
~~~~
the links can be inside the the description.

I think this would be more 'truthful', and understandable,  than the current documentation.

--------------------

The reason why i stumbled over this: During trying to automate the creation of dependency-graphs i need to gather all main classes and derived classes. This class-gathering can be done by examining the rst-comments (find all lines containing `.. class:: xy` and `Child of: xy`), or by examining the `.h` files, e.g. `src/scripting/lua_map.h`. Examining rst-comments can be errorprone because it relies on the developers to write all needed things. So i thought examining the `.h`-files is more secure, but i couldn't find any definition of the class `HasWares` (and the other `HasXy`'s).

**Comment by Noordfrees** [comment]
+1 for changing the doc like this, and +1 for using the "real" classes from the .h files.

What I meant above is that we could also consider getting rid of the interface documentation completely and document the common functions in the implementing classes instead.

**Comment by frankystone** [comment]
Then we have duplicity...

I've put this in the [list](https://github.com/widelands/widelands/issues/4761#issuecomment-795883230) in the other bug

**Comment by frankystone** [comment]
I have a first working solution now, but again i have a question:

E.g. for [ConstructionSiteDescription](https://www.widelands.org/documentation/autogen_wl_map/#constructionsitedescription)  the text says it's a child of ImmovableDescription and BuildingDescription. But reading out `lua_map.h` ConstructioSiteDescription has no parent class ImmovableDescription. So the resulting graph of my current state is:

![constructionsitedescription](https://user-images.githubusercontent.com/6730556/122531751-1a144900-d020-11eb-9455-d6dc8ea38d95.jpg)

Parent of ConstructionSiteDescription is BuildingDescription... So what about ImmovableDescription? I couldn't find any connection between ConstructionSiteDescription and ImmovableDescription, either in `lua_map.cc` nor in `lua_map.h`.

Anyway here is the result of my current work as html. Highlight: Each class in each graph has a link to the corresponding class, which works also  across files. But there are also some things missing, e.g. limiting the number of child classes which make some graphs pretty big, but currently this is helpful.

[current.zip](https://github.com/widelands/widelands/files/6675743/current.zip)

**Comment by Noordfrees** [comment]
`ImmovableDescription` has no children so this is an error in the documentation. In C++, `ConstructionSiteDescr` is a child of `PartiallyFinishedBuildingDescr` which is a child of `BuildingDescr`. In Lua, the `PartiallyFinishedBuildingDescription` is omitted and `ConstructionSiteDescription` inherits directly from `BuildingDescription`.
