### ISSUE TITLE
fri03 error: Lua coroutine failed

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#4872]
**Describe the bug**
I got a lua error message in fri03, when I tried to reach the first new port:
[01:26:01.790 game] ERROR: […/widelands-master/src/scripting/lua_errors.cc:22] [string "scripting/mission_thread.lua"]:72: bad argument #-2 to 'get_distance' (Flag expected, got Road)

**To Reproduce**
After trying to understand the code, I think the cause may have been that I dismantled the original port and built the diker on the neighbouring spot. I only have the automatic save right after the error message.

**Screenshots**
![fri03_lua_error](https://user-images.githubusercontent.com/80712255/119282433-f38a0a80-bc39-11eb-9c76-ea969436f2d9.jpg)

**Version:**
 - OS: antix / Debian buster with some backports
 - Widelands Version: 3f3c18dea19ff2cfa449603398c4953ed8b59ecf

**Comment by klaus-halfmann** [comment]
Thanks for helping us testing widelands.
(I did not pay this scenario myself, thanks for reminding me ...)

We are currently in feature freeze fro the upcoming version 1.0 and
I think: this such an edge case that it is not worth hotfixing it for this
version. @Noordfrees  what do you think?

P.S  what language is this?

**Comment by tothxa** [comment]
I don't know if there is a lua call to prevent dismantling a building. If not, I thought of another simple quick semi-fix: Disallow warehouses until the first new port is built. (even I can make a PR for this if @Noordfrees agrees) Then noone would think of dismantling the original port, or if they do, they lose the game anyway.

(it's hungarian)

**Comment by Noordfrees** [comment]
Hey, you're not supposed to dike over the stream before claiming the eastern port space ;)
We have a C++ function to make individual buildings indestructible but it's not part of the Lua interface yet. IMHO the best short-term solution would be to replace the default frisians_port with a scenario-specific port building that is indestructible like an HQ.

… edit: But this would create new translatable strings. I'll instead expose the `destruction_blocked` property to Lua. This is also much simpler actually.
