### ISSUE TITLE
Addons: Clicking "Browse" takes too long

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4873]
When i click on "Browse" in the add-ons manager it take about 5 to 7 seconds until the UI reacts: The tab get activated and the add-ons are shown.

This is quite too long. And i guess the more add-ons will be available the longer the UI needs to react.

**To Reproduce**
1. Click on Add-Ons
2. Click on "Browse"

**Expected behavior**
The UI should react much faster.

**Version:**
 - OS: archlinux
 - Widelands Version: [d15ecd3@master] (Release)

**Comment by Noordfrees** [comment]
We cannot easily change this for v1.0 because curl needs this long time to download and parse the listfile. But when the webserver feature is implemented we can add a progressbar.

**Comment by frankystone** [comment]
Maybe there can be a sort of local cache: Dowloading the first time will take longer and fills the cache. Clicking the next time on "Browse" reads the cache first. Clicking on "Refresh"  will download only additional add-ons and update the local cache?

**Comment by Noordfrees** [comment]
In the addons-webserver branch all downloads are way faster than with curl in master. Let's first wait until the branch is ready and then see whether this is still an issue then.
Regarding a cache, see https://github.com/widelands/widelands/pull/4710
