### ISSUE TITLE
Addons mismatch closes (crashes) Game

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4882]
After confirming an addon mismatch in an online game the game gets closed (or crashes) rather than returning to the lobby

**Comment by klaus-halfmann** [comment]
I dont like having such chnages on the road to 1.0, lets better taraget a verison 1.1 or such?

**Comment by matthiakl** [comment]
This issue will likely be reported frequently, if it gets into 1.0. Crashes are always unpleasant and should not be in a stable version if possible. So 1.0 is the correct target.

**Comment by hessenfarmer** [comment]
@klaus-halfmann would you mind testing this branch tonight

**Comment by klaus-halfmann** [comment]
Its not about mind its about time :-)

**Comment by hessenfarmer** [comment]
Ok I will join the lobby tonight with this version anyway to see if it works

**Comment by klaus-halfmann** [comment]
Same here ... there is a +/- related issue when you join with a local version the addon is found in the config but not locall on disk, this leads to confusion when using addons. Woraround: uninstall and reinstall.
