### ISSUE TITLE
Rethinking terrains dither_layer

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4897]
Formerly the values for `dither_layer` were deliberately spread over 5 to 10 values. This was made to have some freedom for adding new terrains: If a new terrains dither_layer should be between e.g. 60 and 65 this was possible without having problems.

Since #4281 some values of dither_layer are just added by 1, which makes it impossible to easily add new terrains by just adding 1 to the value of a dither_layer.

Since add-ons can add new terrains there might be the possibility that using one "terrain add-on" might work, but using two "terrain add-ons" might do not work because the dither_layers of the two add-ons are conflicting.

I think the `dither_layer` should be reworked to prevent such things. But i have no really good idea for this issue. My first idea is to:

1. instead of values the `dither_layer` should be some kind of landscape description, a type: Say a terrain of type "beach" is between "water" and "arable land".
2. assigning values for `dither_layer` is then delegated to an algorithm which applies the values to the engine.

So this idea needs:
1. Specifying "landscape types" of terrains: E.g. (from bottom to top): "Water", "Beach" (or "Coast"), "Arable", "Unwalkable", "Dead", "Mountainious". Maybe there is a need of more types.
2. Give each "landscape type" a distinct range of values.
3. Create an algorithm which gathers all terrains and applies the computed values to `dither_layer`

Other ideas?

**Comment by hessenfarmer** [comment]
Basically the values do not matter as long as they are unique. they are just there to decide which terrain gets displayed of the other in our small blenfing area around a triangle. this results in the higher dither layer being displayed as a triangle which has bulges (Ausbauchung) and the lower one has a dint (Einbeulung) instead.

if 2 terrains from addons have the same dither layer a warning would be logged and the edge of the triangles would be a straight line instead of a curve if these 2 terrains are located next to each other.

**Comment by frankystone** [comment]
Yes, i know. I reworked the values some years ago. The dither_layer was implemented on purpose for such bulges and dints, because with some terrains it looks just better if one has a higher/lower value. E.g. terrains of type "beach" have always a lower value than water (beach is right). Which coastline looks better?
![dither_laeyr](https://user-images.githubusercontent.com/6730556/119937130-87d1d580-bf8a-11eb-9755-8df97295fb5b.jpg)

If we go for "it does not matter as long they are unique", we can omit the dither_layer from the lua files and compute them at runtime. For me the dither_layer does matter: Often when designing maps i want to have to have the dither layer of two adjacent terrains vice versa. So for me ideally the editor should give me the freedom to change the values. But such a feature isn't implemented easily so i try to find another solution for the problem if two add-ons define the same dither_layer's.

The background why i stumbled over this:
I want to create a real arid map where resources are very low. This was not possible because of the default_resources some terrains implement. So my idea was to create a new add-on which contain all terrains which define default_resources but make them having no default_resources. This would solve also #1381
![no_default_resources](https://user-images.githubusercontent.com/6730556/119939371-0d0ab980-bf8e-11eb-8d0c-7b8530f14ef9.jpg)
And now i want to give the terrains a dither_layer which is close to the dither_layer of the original terrains (containing default_resources) to make them visually even (having the same bulgs and dints) as the original terrains. This is possible (i think) but i have to check the values for dither_layer of all terrains in all add-on's :-(

**Comment by Noordfrees** [comment]
How about distributing the dither layers in a broader range? E.g. All the dither layers stated in the Lua files (both official and custom) would be internally multiplied with 10, and the layers for terrains belonging to the N-th enabled world add-on are then increased by N. This would allow up to 10 world add-ons without having conflicts. (We can also use any arbitrary larger number than 10.)

**Comment by frankystone** [comment]
Sounds ok for me. 
The only argument against this idea is: Adjusting things internally hides functionality to the user. I guess this can lead to unexpected results or questions in the forums.

Anyway in the [wiki sandbox](https://www.widelands.org/wiki/WikiSandbox/) is a list of all current dither_layer-values.

**Comment by hessenfarmer** [comment]
> 
> Sounds ok for me.
> The only argument against this idea is: Adjusting things internally hides functionality to the user. I guess this can lead to unexpected results or questions in the forums.      
    
Well, with the adon system we somewhat opened pandoras box, for having widelands in myriads of permutations. As we can't expect every user or addon designer to know as much as we do about internal mechanics. By this we need to put in some safeguards for this nice feature. So if there are complaints in the forum we need to rethink our safeguards to prevent such complaints. Implementing safeguards can't be 100% transparent to the user.        
   
I am sure this won't be the last issue of this kind.  

Thanks for pointing out and showing me the importance of the order which I wasn't that much aware of. Although I can't decide which beach looks better. ;-)

**Comment by frankystone** [comment]
BTW: The game should not through an error if two terrains have the same value for dither_layer, instead it should show just a warning and load the map anyway.

1. Same values do not harm
2. An add-on author can visually see what happens if two terrains have the same dither_layer
3. An add-ons author might want just hard edges
4. Without much effort one can't make images like in [Help Terrains](https://www.widelands.org/wiki/HelpTerrains/)

[The way i did reworked dither_layer some years ago](https://github.com/widelands/widelands/issues/1585#issuecomment-529443308)
