### ISSUE TITLE
Allow old maps to use new world Add-ons

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4899]
If one edits a map and want to modify it with a newly available add-on, this is currently not possible without editing the `elemental` file.

**To Reproduce**
1. Install an add-on providing new terrains
2. Start editor and load an "old" map
3. The new terrains are not available in _"Tools -> Terrains"_

**Expected behavior**
New terrains from add-ons should be ready to use for "old" maps.

**Version:**
 - OS: archlinux
 - Widelands Version: [e95de44@master] (Debug)

**Additional context**
It is also problematic that a map just stores the enabled add-ons without checking if the features an add-on provides are really used:

1. Install the addons "Foreign planet", "impassable water" and "no default resources"
2. Create a new map
3. Save it without using any of the terrains in the add-ons
4. Result 1: the file `elemantal` contains all enabled add-ons, although they aren't needed to load the map.
5. Uninstall one of previously installed add-ons
6. Quick-load the previously saved map by pressing "w" in the main menu, or try to load it via _"Load map"_ (ignoring the hint about conflicting add-ons)
7.  Result 2: The editor crashes due to not available add-ons, although this map does not really require this add-on:
    ~~~~
    terminate called after throwing an instance of 'Widelands::GameDataError'                       
       what():  Add-on 'foreign_planet.wad' (version 1.0.2) required but not installed               
    Abgebrochen (Speicherabzug geschrieben)
    ~~~~

**Comment by Noordfrees** [comment]
Well how would this be possible? There's no notion of "the features an add-on provides": Compare for example with the More Fish & Water add-on which modifies existing terrains. Some add-ons create new items, some modify existing ones, and others still may do both. How to decide which ones have to be fixed and which ones can be en-/disabled dynamically when loading?

A crash should not happen though, will fix this for 1.0.
