### ISSUE TITLE
Deprecated pictures parameter

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4906]
If --verbose output is turned on a lot of warnings like "animation contains deprecated Pictures Parameter" are logged.

**Comment by Noordfrees** [comment]
Ideally we should convert all these animations to spritesheets (except for single-image animations which only need to be converted to the new definition format). That's the third step of https://github.com/widelands/widelands/issues/3162. This is a simple job for someone with lots of spare time…

**Comment by hessenfarmer** [comment]
Ok I already started a branch where the things have been fixed for the world categories. hopefully I can fix some other instances tonight

**Comment by Noordfrees** [comment]
I had a look at your branch. Actually this syntax is also deprecated; the latest recommended structure is the one I used for the amazons units:
```
   animation_directory = dirname,
   animations = {
      unoccupied = {hotspot = {43, 44}},
      idle = {hotspot = {43, 44}},
   },
   spritesheets = {
      working = {
         hotspot = {43, 45},
         fps = 15,
         frames = 30,
         columns = 6,
         rows = 5
      }
   },
```

The `basename` can be omitted if it's identical to the animation's name (strongly recommended). The `directory` key for an animation is deprecated and should only be used if the unit has animation files in several directories (currently only the frisian soldier); please use `animation_directory` instead.

**Comment by hessenfarmer** [comment]
Ok I will redo all my work then, with this definitions.   
One question if there are playercolor mask does this work for them as well?

**Comment by Noordfrees** [comment]
Yes, existence of playercolor masks is always automatically detected, they're not stated in the animation table.

Thanks for taking on this task :)

**Comment by hessenfarmer** [comment]
ok changed world tribes wares and tribes immovables. Would be glad if you could have a look whether I am on the right way

**Comment by Noordfrees** [comment]
:+1: perfect :)

**Comment by hessenfarmer** [comment]
ok much to go then. At least I know what to do tonight

**Comment by hessenfarmer** [comment]
finished finally
