### ISSUE TITLE
AI bugs and glitches in v1.0

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4911]
1. this line

https://github.com/widelands/widelands/blob/0976a570055e43df6e7847c2831d08f6d09286e7/src/ai/defaultai.cc#L5628

should prevent the AI from building rangers if not at least one lumberjack was built.  With v1.0 we allowed multiple Lumberjacks to be designed in a tribe (e.g. amazons and europeans) so it is not necessarily the related lumberjack for the ranger in question. In fact for amazons and europeans an upgraded Lumberjack is considered.     
As it is not really stopping amazons, due to the upgraded Lumberjack built soon we might postpone this to v1.1. However Europeans will not work properly in AI without that fixed

2. detection of lumberjack is dependent on log used as build material. Should be detected by the immovables harvested.   

3. Detection of second carrier recruitment is not granular enough.     

4. Assertion in line defaultai.cc:3038 prevents rangers from being forced, which is against the concept of the forced_after parameter.    

5. genetic algorithm for determining Neededness of rangers is increasing the score if rangers are not allowed due to woodpolicy (e.g. defaultai.cc:5621). this should be the other way round.

**Comment by Noordfrees** [comment]
Don't know which of the several AI issues this best fits into or if I should open a new one…
I'm currently playing a game on Big Eden (which should be quite AI-friendly) and noticed that 5 of the 7 AIs are unable to develop a wood economy and run into a permanent no-logs-deadlock quickly. 
[Replay for the first 5 hours](https://github.com/widelands/widelands/files/6685437/replays.zip)
[Savegame after 15 hours](https://github.com/widelands/widelands/files/6685488/BigEden_BAR_PH.wgf.zip)
![grafik](https://user-images.githubusercontent.com/48293446/122737106-00be0780-d281-11eb-9b69-f3c9bdfb7000.png)

**Comment by hessenfarmer** [comment]
> 
> 
> Don't know which of the several AI issues this best fits into or if I should open a new one… I'm currently playing a game on Big Eden (which should be quite AI-friendly) and noticed that 5 of the 7 AIs are unable to develop a wood economy and run into a permanent no-logs-deadlock quickly. [Replay for the first 5 hours](https://github.com/widelands/widelands/files/6685437/replays.zip) [Savegame after 15 hours](https://github.com/widelands/widelands/files/6685488/BigEden_BAR_PH.wgf.zip) ![grafik](https://user-images.githubusercontent.com/48293446/122737106-00be0780-d281-11eb-9b69-f3c9bdfb7000.png


I couldn't reproduce this. Saving from replay and continue from save did show completely different behaviour. Furthermore the replay desyncs although I compiled the git tag mentioned in the replay files. Ai built not as many buildings as they should normally build, so only guess is that the time was set to very fast resulting in AI code getting skipped.
