### ISSUE TITLE
Can't get WL_create_spritesheet to run on a Windows System

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4919]
see titlle. I ahve compiled this succesfully however it doe not run.   
Do I have to run it from a special directory?   
Does it need to be installed registered in some path?     

I usually use a buildfolder different from the sourcefolder does this matter?   
do I need to use -- for the options like in the normal game?

**Comment by Noordfrees** [comment]
The program takes no optional arguments unlike the main game, and the mandatory options are positional and unnamed (not prefixed with `--xyz=`). There's also no way to specify a custom datadir, it always defaults to `INSTALL_DATADIR` which in turn defaults to `./data`. So one thing you could try is to recompile while passing `-DWL_INSTALL_DATADIR=C:/absolute/path/to/widelands/data` to CMake. If this also doesn't help please paste the full commands you use to compile & run and their output (if any).

**Comment by hessenfarmer** [comment]
I am not getting this to work. Windows logs just tell me it is crashing with error code 0xc0000005. When I try to run it in msys it tells me segmentation fault.

**Comment by matthiakl** [comment]
Did any of the website tools work in the past on windows? Every time I test compilation on windows the website tools were disabled. Now I compiled them in my Visual Studio setup and get
```
Assertion failed: logger != nullptr, file W:\widelands\src\base\log.cc, line 177
```
It looks like the logger is not initialized for these binaries.
Try adding this to the `wl_create_spritesheet` and see, if it helps:
```
#ifdef _WIN32
	set_logging_dir();
#endif
```

**Comment by hessenfarmer** [comment]
@matthiakl   thanks a lot that did the trick

I just added it to the main routine and the spritesheet was created. However I had to run it from the base directory of a widelands installation or source folder to find the proper data path. I need to get the output of the lua code be redirected to stdout.txt but that should not be the problem and then I can start to convert animations to spritesheets. That will be a big improvement.

**Comment by hessenfarmer** [comment]
Ok i started a branch to work on the graphics
https://github.com/widelands/widelands/tree/create_spritesheets

it is dependent on the deprecated pictures branch though.   
one last question: is it normal that the hotspot is recalculated for the spritesheets sometimes?

**Comment by Noordfrees** [comment]
Great that it's working now. The animation is automatically cropped during converting and the hotspot adjusted accordingly.

**Comment by hessenfarmer** [comment]
Ok so I continue to do this.    
btw the linked branch will fix this issue as well as it contains the code changes in create_spritesheets.cc to work in windows.   
@MarkMcWire you might use my work in the branch instead of doing it yourself of course.
