### ISSUE TITLE
Tipps: German localization of Game speed messed up

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4922]
The localized string regarding the game speed is not completely centered and extends the scroll:

![game_speed](https://user-images.githubusercontent.com/6730556/120890027-8e9ebf00-c600-11eb-8085-63b53c073248.png)

Maybe rephrasing like:

"Speed up or slow down the game with PageUp/PageDown. Using this keys in combination with  Ctrl for rapid change, with Shift for smooth change."

BTW: PageUp/PageDown is not localized.

**Comment by Noordfrees** [comment]
Will be fixed by #4784

Edit: The overlong strings are probably because there's no way to break them up currently, see #1077
