### ISSUE TITLE
Seafaring comes to a complete halt when a single port is destroyed.

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4929]
As soon as a port is destroyed, all ships with the status "delivering wares" gather at the other ports and do not continue to work. 
Wares contained in the ship are not unloaded.

Apparently there seems to be a problem with the determination of the destination of the flow of wares as soon as a port is deleted from the game.

Errors can be traced on every map with seafaring. It doesn't matter whether it is one of my ports or that of an AI.

Restarting the game save solves the problem. But it is not a permanent solution.

**Comment by klaus-halfmann** [comment]
Hello Markus, thanks for joining us here on GitHub,

I can confirm your findings, but it happend with some older version.
The Europe Map is a good candiate to run nto this Issue.
Can you support us with a savegame with perhaps 2 players where
you provoke this (rare) situation? Please save the game some time before
the port is destroyed, so the ShipEconomy can rebuild itself
to a status where the Bug may hit us.

Thanks for helping us hunting down such bugs.

**Comment by frankystone** [comment]
This is current master Version 1.1~git25536[a1c3ba9@master] (Release)

Here is a savegame, map Europe 1.2.. If you start the game you will see the port i just built and two construction sites which needs some wares.  Just dismantle or destroy another port, e.g. the one shown in the bottom right window. After my ships arrive at a port, they get stuck.

[destroy_a_Port.zip](https://github.com/widelands/widelands/files/7614163/destroy_a_Port.zip)

**Comment by Noordfrees** [comment]
I cannot reproduce this with b4c1560 – I loaded your savegame and dismantled the port in the bottom-right watchwindow, but all ships continued to carry wares and workers around normally, e.g. between the port in the top-right watchwindow and the colony in the main view. The constructionsites are completed and occupied after a while.

**Comment by MarkMcWire** [comment]
@Noordfrees 
I can confirm the issue. Happened to me sometimes in the current master build, too. As soon as a port that is currently being approached by a ship has been destroyed, the entire seafaring of the corresponding player comes to a standstill. As soon as the game saves and reloads, it continues as normal. I suspect that has something to do with the broken chain of routes for the transported wares.

**Comment by frankystone** [comment]
ok, next try...

Load attached savegame. Look where the ship called Alexandria (top right window) is sailing to (its in the north of Spain). Then destroy or dismantle this port (on Spain). Alexandria's destination now changes to the port  in the north of France. As soon it arrives at this port the ship get some wares and the destination changes to the port on England, but the ship stuck at the port of France.

[destroy_a_Port_1.zip](https://github.com/widelands/widelands/files/7616367/destroy_a_Port_1.zip)

**Comment by Noordfrees** [comment]
Still cannot reproduce… after arriving at the French port, *Alexandria* receives a shipment of marble for England and promptly delivers it there. The ship then continues sailing to the Mediterranean port in the bay between Italy and Spain (South of France? Spain? My geography is not that great ;P )

**Comment by frankystone** [comment]
hm, strange. Can anyone else reproduce? Beside the different versions of widelands, can Debug vs. Release builds make a difference?

During this game i got this issue several times. As Mark said: It disappears after saving and reloading.

**Comment by frankystone** [comment]
Another try: one player game on map Fellowships

If i load the attached savegame and dismantle/destroy the seen port, the ship Amolius is turning and sailing to another port. Looking at the new destination of Amolius and waiting for Amolius to arrive this happens here reproducible:

1. Amolius arrives and get stuck
2. Every ship which arrives at this port get stuck also (next ship is Saturn, then Siena and so on)

Playing a debug with `--verbose` gives me this output close after Amolius arrived at the pot where it get stuck:
~~~~
[03:52:40.962 game] DEBUG: ShippingSchedule::ship_arrived(Amolius at 657)
[03:52:40.962 game] DEBUG: [Shipping Schedule] Loaded cargo and sending to 1044
[03:52:40.982 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[03:52:40.982 game] DEBUG: MO(882,empire_ship): ship_update: Have lastdock 657
[03:52:40.982 game] DEBUG: MO(882,empire_ship): Follow pre-computed path from (88,53)  [idx = 70]
[03:52:41.002 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[and many more of this]
[00:02:11.791 real] DEBUG: MO(1950,log): cancel_moving
[03:52:41.442 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[03:52:41.442 game] DEBUG: MO(882,empire_ship): ship_update: Have lastdock 657
[03:52:41.442 game] DEBUG: MO(882,empire_ship): Follow pre-computed path from (88,53)  [idx = 70]
[03:52:41.462 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[03:52:41.462 game] DEBUG: MO(882,empire_ship): ship_update: Have lastdock 657
[03:52:41.462 game] DEBUG: MO(882,empire_ship): Follow pre-computed path from (88,53)  [idx = 70]
[03:52:41.482 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[03:52:41.482 game] DEBUG: MO(882,empire_ship): ship_update: Have lastdock 657
[03:52:41.482 game] DEBUG: MO(882,empire_ship): Follow pre-computed path from (88,53)  [idx = 70]
[03:52:41.502 game] DEBUG: MO(882,empire_ship): ship_update: Go to dock 1044
[03:52:41.502 game] DEBUG: MO(882,empire_ship): ship_update: Have lastdock 657
[03:52:41.502 game] DEBUG: MO(882,empire_ship): Follow pre-computed path from (88,53)  [idx = 70]
[and many more]
~~~~
[test_ports.zip](https://github.com/widelands/widelands/files/7628404/test_ports.zip)

**Comment by Noordfrees** [comment]
Arrrgh… It looks like a bug where the start and end of a path are inverted again. I thought I had squashed that one *ages* ago, it used to appear all the time in the testsuite and was gone after one of the shipping algorithm refactorings. Those are near-impossible to chase down because they're hard to trigger and they always go away after reloading. 

What appears to be happening, judged solely from the log output you posted and a look at the savegame (which works fine for me) is that the ShipFleet, when asked for the route from port A to port B, returns a route from B to A. The ShipFleet caches the route only for one direction and inverts it when asked for the route in the other direction. 

From memory, the last time I fixed it, the bug was caused by the ship fleet not cleaning up stale port paths when a port was deleted. So the mappings for the no-longer-existing port still existed. But when the port was later re-added, there was a 50-50-chance that the new port was inserted with a different index, resulting in all cached paths to/from that port now being the wrong way around regarding the new port order. 

The relevant code is in https://github.com/widelands/widelands/blob/master/src/economy/ship_fleet.cc, especially `add_port`, `remove_port`, and `connect_port`. Perhaps there's some special index for which the ~obscure magic~very intuitive code below does not work or some such…

https://github.com/widelands/widelands/blob/2c4e78b9a0e0176bb873d8e816d7716f85938f68/src/economy/ship_fleet.cc#L589-L600

**Comment by frankystone** [comment]
> But when the port was later re-added

Yes in this game i dismantled and re-added a port. But in the game mentioned earlier this wasn't the case.

> The ShipFleet caches the route only for one direction and inverts it when asked for the route in the other direction.

A check if the route is still valid doesn't work? Maybe it's too much calculating?

**Comment by Noordfrees** [comment]
> A check if the route is still valid doesn't work? Maybe it's too much calculating?

This would only address the symptom but not the actual problem. A route should not become invalid in the first place, ever. And when a bug is addressed symptomatically it might just cause other, possibly worse, follow-up bugs elsewhere.

This evening I'll do what proved so successful for #5052 – I'll make a branch with lots of debug output and hope that you can reproduce the bug there so the logs may reveal more details.

**Comment by klaus-halfmann** [comment]
I found the same Issue here 
[EuroCrash.wgf.zip](https://github.com/widelands/widelands/files/7660413/EuroCrash.wgf.zip)

**Comment by Noordfrees** [comment]
I can't even get any meaningful log output out of this tangled paths and ports storage concept… I'll leave this bug for someone who enjoys jungle exploration ;)

**Comment by frankystone** [comment]
Another one...
This is Widelands Version 1.1~git25546[42089b9@master] (Debug)

Load the game and wait for the ship called 'Remus' get full of wares. Then destroy the port in the watch window on the top. 'Remus' turns back and get stuck at the port where it got the wares.
Here i can reproduce it on every load of the save game.

The destroyed port was the first port i built in this game (just to mention it).

No port was destroyed and readded throughout the game.

[test.zip](https://github.com/widelands/widelands/files/7697287/test.zip)

**Comment by Noordfrees** [comment]
This time I can reproduce the bug :) 
Will have a go at it with a debugger now…

---

It's a mess. The three remaining ports are
```
[0] at 10×100
[1] at 23× 88
[2] at 61× 60
```
But the new cached portpaths are
```
0→1 : 61× 60 → 10×100
0→2 : 61× 60 → 27× 90
1×2 : 10×100 → 23× 88
```
But I can now try to fix or refactor the remapping (emphasis on *try*)…
