### ISSUE TITLE
No upgrade of trainingssites, if there are only 3 or lower count of mines. (AI)

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4932]
I don't know if this is a bug or not. The AI only upgrades trainingsites if there are more than 3 mines. Since the Europeans never build more than 3 mines* (1 coal, 1 iron, 1 gold), since there is no granite mine, the trainingssites are never upgraded.
I have to force the construction of a fourth mine using a Lua script for the expansion to take place. Can also be easily reproduced.

(* btw: Thats another bug, which had to investigated.)

In the case of the official tribes, this behavior only affects the empire.  Only the Arena can be expanded into the Colosseum, there are no other upgradable trainingssites. Neither the Arena nor the Colosseum require weapons or armor from smithies, as both buildings only train "Evade". Seen in this way, it is unnecessary somewhere for the AI to check before the expansion whether 3 or more mines have been built there.

**Comment by Noordfrees** [comment]
What's the difference to #4669?

**Comment by MarkMcWire** [comment]
I totally forgot that I mentioned that on, sorry.
