### ISSUE TITLE
Add a check for developers.json

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4933]
Every time a comma is missing, or a table entry ends with a comma, the website throws lots of server errors.

So a check for validity for this file would be fine.

The website code fails e.g. here https://github.com/widelands/widelands-website/blob/master/mainpage/views.py#L104

**Comment by Noordfrees** [comment]
Is there a commandline utility or script that does these checks? If yes adding it to the build suite should be easy

**Comment by frankystone** [comment]
Something like this should work in python:

~~~~
import json

try:        
    with open('data/txts/developers.json', 'r') as f:
            json_data = json.load(f)['developers']
except JSONDecodeError as err:
    print("Invalid file: {}".format(err))
~~~~

**Comment by frankystone** [comment]
Oh, and sorry for changing the file directly on master. But creating a pull request seemed a bit overkill to me.

**Comment by Noordfrees** [comment]
Doing such small fixes on master is fine :) 

I added this to #4735, one catch-all PR for three pieces of actions magic

**Comment by frankystone** [comment]
Thanks :-)

**Comment by gunchleoc** [comment]
Drive-by comment:

Run `python3 utils/update_authors.py`. This will not only create the Lua file for Widelands, but also valiate the JSON.

This script is also triggered by `utils/merge_and_push_translations.sh`.

There is also a `utils/validate_json.py' script
