### ISSUE TITLE
Some tooltips are too sticky

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#4941]
While building a road, the road length tooltip is visible. However, it is not replaced if another tooltip is shown, resulting in something like this:
![Bildschirmfoto vom 2021-05-25 19-17-42](https://user-images.githubusercontent.com/23122583/121752302-25dba900-cb10-11eb-9e49-a9e9f8a63759.png)

A tooltip also stays active, when a message box opens, no matter where the mouse is moved:
![Bildschirmfoto vom 2021-06-11 23-47-34](https://user-images.githubusercontent.com/23122583/121752285-1d836e00-cb10-11eb-85ec-505496d07b7e.png)

Edit: And another one when clicking on "Continue" in the main menu:
![Bildschirmfoto vom 2021-06-13 12-04-45](https://user-images.githubusercontent.com/23122583/121803105-2d9a6b00-cc40-11eb-8ecc-33e90537aaaf.png)

Maybe related to #4673

**Comment by frankystone** [comment]
Really annoying.

The mouse reacts very slow during loading a game anyway and the tooltip (from Continue) is wandering along the stuttering mouse moves.

**Comment by Noordfrees** [comment]
I can look into at as soon as some of my 18 open PRs have been reviewed :wink:
