### ISSUE TITLE
Add "all" option to player:get_buildings

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#4946]
I need for a script the possibility to iterate over all buildings the player has.

In the current version you have to add the name of one or more buildings to "get_buildings". When I use player.tribes.buildings for this handover, captured military buildings are not displayed. So I cannot generate a list of occupied buildings from other tribes.  Or I have to iterate over all the tribes available in the game every time, which is very time consuming.

**Comment by Noordfrees** [comment]
`do_get_buildings` internally uses `parse_building_list` which already supports the `"all"` argument. `do_get_buildings` has code that disables this though:
https://github.com/widelands/widelands/blob/2bc7c3b986b289c35e677bb4c72d4f3170d25852/src/scripting/lua_game.cc#L1166-L1177
So extending this should not be too hard. (*extending*, not *replacing*, for backwards compatibility.)

Additionally a `building_descriptions` equivalent of https://www.widelands.org/documentation/autogen_wl/#wl.Descriptions.immovable_descriptions and its siblings would also solve the issue. Best to add both.

**Comment by SimonHeimberg** [comment]
Trying to implement `player:get_buildings("all")` and `player:get_constructionsites("all")`. Tests are running :eyes: .

**Not** working on `wl.Descriptions().building_descriptions`.
