### ISSUE TITLE
Delete Inbox message when the site is muted

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#4957]
When a site creates an Inbox message, that message is automatically removed when the building is dismantled/upgraded. This is a great help to reducing the manual steps needed to keep the Inbox tidy. If a site generates an out of resources message, and is then muted, it would be helpful if the Inbox message is removed in the same manner.

**Comment by jmoerschbach** [comment]
can this be closed because of  #5109? :)

**Comment by Noordfrees** [comment]
IMHO, muting all buildings of a type should also remove inbox messages
