### ISSUE TITLE
Problems with Korean Translations

### ISSUE THREAD

**Issue by SirVer** [widelands/widelands#4959]
A Korean Translator of Widelands has contacted me on my email:

> Hello
I've been in touch with you before. 
I am a translator at Transifex. 
I still can't play the game.
I think there must be a problem with the game. 
I can't figure out what the problem is even if I check the LOG file. 
However, I found that the problem only occurred when I changed to Korean. 
If I can know which string in which file is the problem, it will help me to fix the problematic part.
Therefore, my requirement is that the error string and file name should be recorded in the log. 
If you can't improve the imported files and strings to be logged as LOG,
 please change the settings to Korean and play,
 and let me know where the problematic file is.
I can't figure out where the problem is coming from.

I have not yet tried to reproduce, but I assume setting language to Korean crashes the game. It seems hard to figure out where the offending string is, because there is no useful error message on crash.

**Comment by SirVer** [comment]
I am reporting here, since I will not be able to look into this myself.

**Comment by Noordfrees** [comment]
There's a known printf placeholder mismatch in a korean main menu string which I guess is responsible. I wrote a comment to the translator on Transifex which got no reply. In v1.0 I had removed the faulty translation. I'll delete the translation on Transifex now.
Edit: Done. String is Widelands Main 864

**Comment by SirVer** [comment]
Do you mind pasting your comment here. I can relay to the translator

**Comment by Noordfrees** [comment]
---
> @kmshts The printf placeholders in this string are missing in the Korean translation. Please fix, otherwise Widelands will crash when this string is displayed. 
Edit: I deleted the translation now 
---

The string in question is
```
(C) %1%-%2% by the Widelands Development Team · Licensed under the GNU General Public License V2.0
(C) 2010 - 2022년 와이드랜드 개발 팀에 의해 GNU 일반 공중 사용 허가서 V2.0에 따라 사용허가가 부여되었습니다
```

**Comment by SirVer** [comment]
@Noordfrees I think the main ask here is that if a gettext problem happens, it is more clearly tracable for the translators, so they can fix it themselves, i.e. a crash should print the problematic string (or the english original) onto the commandline.
