### ISSUE TITLE
#4935 broke savegame compatibility for sceanrios using scenario specific buildings

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4985]
As the Lua files in the savegame are still refering to animations that aren't there anymore (they used the animation files of the normal buildings) of the   savegame compatibility is broken for Empire 4, Frisians 2 and 3

**Comment by Noordfrees** [comment]
To prevent this in the future it would probably be best to copy the PNGs to each scenario map that uses them. Keeping them in separate directories like now is fragile.
To reinstate backwards compatibility we could re-add the old image files for the affected units and keep them around until 1.1.

**Comment by hessenfarmer** [comment]
Will try this and test how it works
