### ISSUE TITLE
NullPointer in Carrier::transport_update(Widelands::Game&, Widelands::Bob::State&) carrier.cc:171

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#4988]
**Describe the bug**

Played a nice network game against some player called "No" on "The Thaw".
after about 2:30 of Gametime the was a nasty congestion around
36,85 - 33,87 - 31,87 (Flag, Woodcutter, Fisher)
I noticed this at around 3:20 and tried to optimze the local Road-Network.

**To Reproduce**
1. Open Attached Replay [Crash2021-07-03.zip](https://github.com/widelands/widelands/files/6759790/Crash2021-07-03.zip)
2. Run it to the very end while checking the coordinates  36,85 - 33,87 - 31,87
3. Check console output.

**Expected behavior**

* Carrier ist not lost at Null wen road is removed under its feet :-)
* Game should continue to run wtihout Errors

**Version:**
 - OS: macOS Big SUre Verison 11.4 (20F71)
 - Widelands Version: 1.0 

**Additional context**

Was not abel to reproduce using a savegame from some minutes before the crash.

**Comment by klaus-halfmann** [comment]
Created a branch https://github.com/widelands/widelands/tree/npe4988 based on relase-1.0 to hunt this down, not sure how sucessfull I will be

**Comment by klaus-halfmann** [comment]
Changed the code starting at carrier.cc:171  as follows
```
  MapObject* location = get_location(game);
  // Maybe null in rare cases (locaton.m.serial == 0)
  RoadBase& road = dynamic_cast<RoadBase&>(*location);
```
Indeed the location is null as locaton.m.serial is null.

I will now just return; here. Assuming the carrier is kind of invalid

**Comment by klaus-halfmann** [comment]
Now I get this in the logs:
[00:32:21.892 real] WARNING: Economy still has flags left on destruction
[00:32:21.892 real] WARNING: Economy still has flags left on destruction
[00:32:21.894 real] WARNING: ObjectManager: ouch! remaining objects

And some Exception like "Failed to act" but this is only in a dialog box and does not make it into a logmessage?

**Comment by klaus-halfmann** [comment]
And now: do I have to merge something from master, first?
Run failed: Formatting your code - npe4988

**Comment by hessenfarmer** [comment]
hi Klaus,
unfortunately I have no understanding of this parts of the code

**Comment by matthiakl** [comment]
> And now: do I have to merge something from master, first?
Run failed: Formatting your code - npe4988

You can continue without merging master for now. The run failure is just that the code would be formatted, which might result from a version mismatch of clang-format (master uses 12, v1.0 uses 10).

From the action log:
> Branch npe4988 in repository widelands/widelands does not have an open pull request, so no changes will be pushed. Please note however that your code is not properly formatted

**Comment by klaus-halfmann** [comment]
Sorry fogort the crash log
[Crash.txt](https://github.com/widelands/widelands/files/6909279/Crash.txt)
