### ISSUE TITLE
Amazon graphics size is to big

### ISSUE THREAD

**Issue by pabordel** [widelands/widelands#4994]
Since the creation of the amazon tribe the size of wideland has grown up  by a half. 
the explanation is the size of amazons graphics files : 
for example with workers : 
9,6M atlanteans
12M	empire
37M	barbarians
62M	frisians
174M amazons

please considers enabling better compression for those files.

Thanks for that  great game !

**Comment by Noordfrees** [comment]
Related: #3162

**Comment by hessenfarmer** [comment]
I think one of the reasons is that especially atlanteans and empire lack a lot of animations and they are lacking zoomable graphics, whilst amzons having them so I would believe it to be better to have more animationfiles for them resulting in even bigger graphicssize, to support 4k and to have more animated screens

**Comment by tothxa** [comment]
Can we consider this fixed by #5204?

**Comment by hessenfarmer** [comment]
I think so.
