### ISSUE TITLE
DejaVuSans-Bold build-20(Release)

### ISSUE THREAD

**Issue by spirillen** [widelands/widelands#5004]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Unable to load the game at all

**To Reproduce**
1. Install from PPA daily
2. Try to launch game
3. See error

**Expected behavior**
Play a game

**Screenshots**
Not needed

**Version:**
 - OS: Ubuntu 20.04
 - Widelands Version: "Build 20", "`?`"]

**Additional context**
<details><summary>Log from terminal</summary>

$ widelands 
This is Widelands Version build-20 (Release)
Set home directory: /home/joakim/.widelands
Adding directory: /usr/share/games/widelands/data
selected language: en
using locale en_US.utf-8
Graphics: Try to set Videomode 1920x1080
Graphics: OpenGL: Version "4.6.0 NVIDIA 390.144"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 16
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 2
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384
Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
**** GRAPHICS REPORT ****
 VIDEO DRIVER GLVND x11
 pixel fmt 370546692
 size 1920 1080
**** END GRAPHICS REPORT ****
Style Manager: Loading templates/default/init.lua ... took 1ms
Style Manager: Reading button styles ... took 4ms
Style Manager: Reading slider styles ... took 0ms
Style Manager: Reading tabpanel styles ... took 0ms
Style Manager: Reading editbox styles ... took 0ms
Style Manager: Reading dropdown styles ... took 0ms
Style Manager: Reading scrollbar styles ... took 0ms
Style Manager: Reading style templates took 5ms
**** SOUND REPORT ****
SDL version: 2.0.10
SDL_mixer version: 2.0.4
**** END SOUND REPORT ****
SoundHandler: loaded song "music/intro_00.ogg"
Font file not found. Falling back to sans: DejaVu/DejaVuSans-Bold.ttf
LayeredFileSystem: Could not load file: could not find file or directory: i18n/fonts/DejaVu/DejaVuSans-Bold.ttf
I have tried the following path(s):
    /home/$USER/.widelands/i18n/fonts/DejaVu/DejaVuSans-Bold.ttf
    /usr/share/games/widelands/data/i18n/fonts/DejaVu/DejaVuSans-Bold.ttf

Caught exception (of type '17FileNotFoundError') in outermost handler!
The exception said: LayeredFileSystem: Could not load file: could not find file or directory: i18n/fonts/DejaVu/DejaVuSans.ttf
I have tried the following path(s):
    /home/$USER/.widelands/i18n/fonts/DejaVu/DejaVuSans.ttf
    /usr/share/games/widelands/data/i18n/fonts/DejaVu/DejaVuSans.ttf

This should not happen. Please file a bug report on version build-20(Release).
and remember to specify your operating system.

SoundHandler closing times 1, freq 22050, format 32784, chan 2
SDL_AUDIODRIVER pulseaudio

</details>

2 related issues: https://github.com/widelands/widelands/issues/1386, https://github.com/widelands/widelands/issues/514

**Comment by Noordfrees** [comment]
> Install from PPA daily

That cannot be correct, because the daily PPA never contained the (ancient, outdated) version build-20. It should give you version `1.1~bzr9968-202107250301~ubuntu20.04.1`. Perhaps there are multiple Widelands versions installed; current daily builds will select the correct data directory but older versions tend to be confused by it.

Which Widelands PPA(s) are added on your system? What is the output of `apt show widelands` and `apt list --all-versions widelands`?

Did you try un- and reinstalling:
```
sudo apt remove widelands widelands-data
sudo apt update
sudo apt install widelands
```

**Comment by spirillen** [comment]
A first reply as I'm currently on a different PC, I did uninstall (purge) the stable PPA version, then installed the daily PPA, only the stable can be executed successfully.

About the info about the $data-dir I will take a look at that when I come to the other machine :)

**Comment by spirillen** [comment]
```shell
sudo apt remove widelands widelands-data -y && sudo apt autoremove -y

ll /home/$USER/.widelands
total 60
drwxrwxr-x 10 $USER $USER  4096 Feb 19 02:10 ./
drwxrwxrwx 69 $USER $USER  4096 Aug  1 10:25 ../
drwxrwxr-x  6 $USER $USER  4096 Feb 19 04:28 addons/
drwxrwxr-x  6 $USER $USER  4096 Feb 19 02:10 addons_i18n/
-rw-rw-r--  1 $USER $USER   228 Feb 19 02:14 addons_i18n_versions
drwxrwxr-x  2 $USER $USER  4096 Mar 18  2020 ai/
-rw-rw-r--  1 $USER $USER  1099 Jul 29 16:55 config
drwxrwxr-x  4 $USER $USER  4096 Nov 23  2020 maps/
drwxrwxr-x  2 $USER $USER 16384 Jul 29 15:41 replays/
drwxrwxr-x  2 $USER $USER  4096 Jul 29 16:31 save/
drwxrwxr-x  7 $USER $USER  4096 Jul 19 11:59 temp/
drwxrwxr-x  3 $USER $USER  4096 Sep 21  2020 tribes/
```

```shell
sudo apt purge widelands widelands-data -y && sudo apt autoremove -y

ll /home/$USER/.widelands
total 60
drwxrwxr-x 10 $USER $USER  4096 Feb 19 02:10 ./
drwxrwxrwx 69 $USER $USER  4096 Aug  1 10:25 ../
drwxrwxr-x  6 $USER $USER  4096 Feb 19 04:28 addons/
drwxrwxr-x  6 $USER $USER  4096 Feb 19 02:10 addons_i18n/
-rw-rw-r--  1 $USER $USER   228 Feb 19 02:14 addons_i18n_versions
drwxrwxr-x  2 $USER $USER  4096 Mar 18  2020 ai/
-rw-rw-r--  1 $USER $USER  1099 Jul 29 16:55 config
drwxrwxr-x  4 $USER $USER  4096 Nov 23  2020 maps/
drwxrwxr-x  2 $USER $USER 16384 Jul 29 15:41 replays/
drwxrwxr-x  2 $USER $USER  4096 Jul 29 16:31 save/
drwxrwxr-x  7 $USER $USER  4096 Jul 19 11:59 temp/
drwxrwxr-x  3 $USER $USER  4096 Sep 21  2020 tribes/
```

This means `purge` isn't removing the conf dir

```bash
/etc/apt/sources.list.d/widelands-dev-ubuntu-widelands-focal.list
# deb http://ppa.launchpad.net/widelands-dev/widelands/ubuntu focal main
# deb-src http://ppa.launchpad.net/widelands-dev/widelands/ubuntu focal main
```

```bash
/etc/apt/sources.list.d/widelands-dev-ubuntu-widelands-daily-focal.list
deb http://ppa.launchpad.net/widelands-dev/widelands-daily/ubuntu focal main
# deb-src http://ppa.launchpad.net/widelands-dev/widelands-daily/ubuntu focal main
```

```shell
apt show widelands
Package: widelands
Version: 2:1.1~bzr9971-202107311016~ubuntu20.04.1
Priority: optional
Section: games
Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Installed-Size: 40.5 MB
Depends: widelands-data (= 2:1.1~bzr9971-202107311016~ubuntu20.04.1), libc6 (>= 2.29), libcurl3-gnutls (>= 7.16.2), libgcc-s1 (>= 3.0), libgl1, libglew2.1 (>= 1.12.0), libicu66 (>= 66.1-1~), libpng16-16 (>= 1.6.2-1), libsdl2-2.0-0 (>= 2.0.10), libsdl2-image-2.0-0 (>= 2.0.2), libsdl2-mixer-2.0-0 (>= 2.0.2), libsdl2-ttf-2.0-0 (>= 2.0.14), libstdc++6 (>= 9), zlib1g (>= 1:1.1.4)
Download-Size: 11.1 MB
APT-Sources: http://ppa.launchpad.net/widelands-dev/widelands-daily/ubuntu focal/main amd64 Packages
```

apt list --all-versions widelands

```
Listing... Done
widelands/focal 2:1.1~bzr9971-202107311016~ubuntu20.04.1 amd64
widelands/focal 1:20-2build2 amd64
```

> Did you try un- and reinstalling:

Yes twice


sudo apt install -y widelands


This time it worked :+1:

**Comment by klaus-halfmann** [comment]
We try not to touch the .widelands directory, so savegames sellmade maps and replays are not lost.
We partially cleanup autosaves and replays on startup of the game.

Hope to see you in the internet lobby then,
