### ISSUE TITLE
Too many open files in link step of build

### ISSUE THREAD

**Issue by michaelbaeuerle** [widelands/widelands#5005]
Link step of build fails because the OS limit for open files is too low.

Example how the error messages look like:
```
...
[100%] Linking CXX executable wl_create_spritesheet
ld: cannot find ../graphic/animation/libgraphic_animation.a: Too many open files in system
ld: cannot find ../graphic/libgraphic_image_io.a: Too many open files in system
ld: cannot find ../graphic/libgraphic_surface.a: Too many open files in system
ld: cannot find ../io/filesystem/libio_filesystem.a: Too many open files in system
ld: cannot find ../logic/liblogic.a: Too many open files in system
ld: cannot find ../logic/map_objects/liblogic_map_objects.a: Too many open files in system
ld: cannot find ../base/libbase_times.a: Too many open files in system
ld: cannot find ../base/libbase_i18n.a: Too many open files in system
...
```

Versions:
 - OS: NetBSD 9
 - Widelands Version: 1.0

OS limits:
```
$ ulimit -S -n
1024
$ ulimit -H -n
3404
```
I have tested again with the hard limit (3404), but this is still too low.
Is there a possibility to reduce the required number of open files for the build process?

**Comment by klaus-halfmann** [comment]
Hello michael. By default the compile script will use mutiple cores via the -j parameter.
So maybe try -j 1 and then slowly increase. 

This is not per se a bug of widelands, but a problem of the buildenvironment. 
Can you increas that file limit? (Like here: https://codingshell.com/linux-limit-number-of-open-files)

Which compiler (gcc / clang) and version did you use?

**Comment by michaelbaeuerle** [comment]
> Hello michael. By default the compile script will use mutiple cores via the -j parameter.
> So maybe try -j 1 and then slowly increase.

A build without parallel jobs is currently running (at 10% now, I will report the outcome later).
But I don't think this will help, because the problem is the number of open files **per process**.
 
> This is not per se a bug of widelands, but a problem of the buildenvironment.
> Can you increas that file limit? (Like here: https://codingshell.com/linux-limit-number-of-open-files)

This works differently in NetBSD, but is possible via sysctl(8).
I have tested larger values and 4096 seems to be sufficient.

But increasing the kernel limit requires root permissions and our package building infrastructure (pkgsrc) has no support for it.
Therefore the question whether the Widelands build system can be convinced to use a smaller number of files per process.

> Which compiler (gcc / clang) and version did you use?

GCC 7.4.0

**Comment by michaelbaeuerle** [comment]
> > Hello michael. By default the compile script will use mutiple cores via the -j parameter.
> > So maybe try -j 1 and then slowly increase.
> 
> A build without parallel jobs is currently running (at 10% now, I will report the outcome later).
> But I don't think this will help, because the problem is the number of open files **per process**.

The build without parallel jobs was successful.
Looks like my assumption was wrong and the per process limit was not the problem.

Thank you for the quick response. The program can now at least be started.
The splash screen pops up and the menu can be activated.
Later it fails with FATAL EXCEPTION, but this is a different problem. I think this issue can be closed.
