### ISSUE TITLE
Setting Atlantan tower to 0 soldiers

### ISSUE THREAD

**Issue by spth** [widelands/widelands#5006]
I noticed that most of the time I can set the Atlantan tower (and its upgraded version) to 0 soldiers. I noticed this in a LAN multiplayer game, 2 players, widelands from git from a few days ago; didn't try in singleplayer yet.

If it build a tower (or upgrade it from the tower construction site), and I then quickly click the down buttons, I can set the number of soldiers all the way down to 0. I I then set it back to a higher number, I cannot set it down to 0 again. Since the tower ebhaves differently than other buildings, and since I cannot set it back to 0 after increasing the number, this is incosistent, so I suppose it is a bug.

**Comment by klaus-halfmann** [comment]
I asssume this is related to multihreadig: The command to reduce the soldiers is on its way 
in some other thread while the GUI still allows further clicks based on the actual value...

In a network game I now got 
`Assertion failed: (ms->max_capacity >= capacity), function execute, file ../src/logic/playercommand.cc, line 1640.`
which would incifate more soldiers then expected ...

**Comment by klaus-halfmann** [comment]
Got it, already while building the tower (local network game, client) <img width="540" alt="Tower at 0" src="https://user-images.githubusercontent.com/16598373/127636588-101c4e31-4bae-4c9e-b9e9-389407dfdd79.png">

Once the tower is complete I get:
`Assertion failed: (ms->desired_capacity >= b.soldier_control()->min_soldier_capacity()), function cleanup, file ../src/logic/map_objects/tribes/constructionsite.cc, line 352.`

**Comment by klaus-halfmann** [comment]
@Noordfrees I dont think we need a savegame or such any longer?

**Comment by Noordfrees** [comment]
No need for a savegame here. I'm trying to reproduce now, should be an easy fix
