### ISSUE TITLE
v1.0 crashes when replay from development version is highlighted in replay chooser

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5017]
**Describe the bug**
Version 1.0 crashes when the selection in the "Choose Replay" window is moved to a replay from a newer development version. If the latest replay is a new one, then it crashes immediately when the choose replay window is opened.

**To Reproduce**
1. Create a replay in a current development build.
2. Start version 1.0
3. Choose "Watch Replay"
4. a. Program crashes if new replay is first in list
b. Move selection to new replay
5. b. Program crashes

**Expected behavior**
It should be possible to safely browse replays, even if unloadable replays are present.

**Error message on stdout**
```
Caught exception (of type 'N9Widelands13GameDataErrorE') in outermost handler!
The exception said: terrain: DescriptionManager::load_description: Object 'winter_taiga1' was not registered

This should not happen. Please file a bug report on version 1.0(Release).
and remember to specify your operating system.
```

**Version:**
 - OS: antix / debian buster with backports
 - Widelands Version: version 1.0 (Release)
(both native build and flatpak)

**Comment by Noordfrees** [comment]
Happens in current master too when you rename a terrain in the Lua files
