### ISSUE TITLE
Crached after updating

### ISSUE THREAD

**Issue by Nick222** [widelands/widelands#5018]
Xubuntu 21.04
Widelands crashed on start - after addons updating

> This is Widelands Version 1.0 (Release)
> [00:00:00.000 real] INFO: Set home directory: /home/nick/.widelands
> [00:00:00.000 real] INFO: Set configuration file: /home/nick/.widelands/config
> [00:00:00.000 real] INFO: Adding directory: /usr/share/games/widelands/data
> [00:00:00.001 real] INFO: selected language: (system language)
> [00:00:00.001 real] INFO: using locale ru_RU.UTF-8
> [00:00:00.006 real] INFO: Byte order: little-endian
> [00:00:00.097 real] INFO: Graphics: Try to set Videomode 1600x1024
> [00:00:00.153 real] INFO: Graphics: OpenGL: Version "4.3 (Compatibility Profile) Mesa 21.0.3"
> [00:00:00.154 real] INFO: Graphics: SDL_GL_RED_SIZE is 8
> [00:00:00.154 real] INFO: Graphics: SDL_GL_GREEN_SIZE is 8
> [00:00:00.154 real] INFO: Graphics: SDL_GL_BLUE_SIZE is 8
> [00:00:00.154 real] INFO: Graphics: SDL_GL_ALPHA_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_BUFFER_SIZE is 24
> [00:00:00.154 real] INFO: Graphics: SDL_GL_DOUBLEBUFFER is 1
> [00:00:00.154 real] INFO: Graphics: SDL_GL_DEPTH_SIZE is 24
> [00:00:00.154 real] INFO: Graphics: SDL_GL_STENCIL_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
> [00:00:00.154 real] INFO: Graphics: SDL_GL_STEREO is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
> [00:00:00.155 real] INFO: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
> [00:00:00.155 real] INFO: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
> [00:00:00.155 real] INFO: Graphics: SDL_GL_CONTEXT_FLAGS is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
> [00:00:00.155 real] INFO: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
> [00:00:00.155 real] INFO: Graphics: OpenGL: Double buffering enabled
> [00:00:00.155 real] INFO: Graphics: OpenGL: Max texture size: 16384
> [00:00:00.155 real] INFO: Graphics: OpenGL: ShadingLanguage: "4.30"
> [00:00:00.156 real] INFO: **** GRAPHICS REPORT ****
> [00:00:00.156 real] INFO: VIDEO DRIVER GLVND x11
> [00:00:00.156 real] INFO: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
> [00:00:00.178 real] WARNING: Ignoring unreadable add-ons profile addons/intelligent_teamplay_maps.wad/addon: [./src/io/profile.cc:560] [addons/intelligent_teamplay_maps.wad/addon] addons/intelligent_teamplay_maps.wad/addon:10: [./src/io/profile.cc:725] runaway multiline string
> [00:00:00.555 real] INFO: **** SOUND REPORT ****
> [00:00:00.555 real] INFO: SDL version: 2.0.14
> [00:00:00.555 real] INFO: SDL_mixer version: 2.0.4
> [00:00:00.555 real] INFO: **** END SOUND REPORT ****
> [00:00:00.648 real] WARNING: Not loading add-on 'intelligent_teamplay_maps.wad' ([./src/io/profile.cc:560] [] addon:10: [./src/io/profile.cc:725] runaway multiline string)
> 
> Caught exception (of type 'N9Widelands13GameDataErrorE') in outermost handler!
> The exception said: reading basic info for tribe "europeans": [./src/scripting/lua_errors.cc:22] [./src/scripting/lua_errors.cc:22] The script 'addons/enhanced_debug_scripts.wad/debug.lua' was not found!
> stack traceback:
> 	[string "addons/europeans_tribe.wad/scripting/starting..."]:6: in main chunk
> 
> This should not happen. Please file a bug report on version 1.0(Release).
> and remember to specify your operating system.
> 
> [00:00:00.713 real] INFO: SoundHandler: Closing 1 time, 22050 Hz, format 32784, 2 channels
> [00:00:00.713 real] INFO: SoundHandler: SDL_AUDIODRIVER pulseaudio

**Comment by Noordfrees** [comment]
Thank you for your bug report. Which add-ons do you have installed and in which order?
(You can find this info in `/home/nick/.widelands/config` in the line that starts with `addons=`)

**Comment by Nick222** [comment]
> addons="foreign_planet.wad:true,fishy.wad:true,Tournament_2021_maps.wad:true,Tournament_2021_win_condition.wad:true,challenge-map-set.wad:true,europeans_tribe.wad:true,first_heroes_win.wad:true,formerly_official_maps.wad:true,frisians-economy-ultra.wad:true,higher-experience.wad:true,impassable_water.wad:true,more-fish-and-water.wad:true,mostly_balanced_maps.wad:true,pioneer-post.wad:true,royal.wad:true,stronger-trading-outpost.wad:true,the-x-mod.wad:true,tropics.wad:true,wells-running-out.wad:true,white_summer.wad:true,white_summer_maps.wad:true,no_default_resources.wad:true,legacy_ui.wad:true,minimalistic_theme.wad:true,1v1_high_level_map_pool.wad:true,fast_1v1_maps.wad:true,europeans_map_modified.wad:true"

**Comment by Noordfrees** [comment]
Okay, this is a bug in the `Europeans Tribe` add-on. It depends on the `enhanced_debug_scripts.wad` add-on since the last update, which is not installed, and this requirement is not mentioned in the add-on config @MarkMcWire. In the current development version the error is caught so this no longer results in a crash. Please try deleting the directory `/home/nick/.widelands/addons/europeans_tribe.wad`, then Widelands should work again.


@widelands/developers Since this kind of problem prevents Widelands from starting until one manually deletes the causing add-on(s), should we consider backporting add-on related crash-fixes to 1.0?

**Comment by MarkMcWire** [comment]
@Noordfrees  Sorry. There was a file in the add-on that shouldn't be become public. Please delete the hq_debug.lua in europeans_tribe.wad/scripting/starting_conditions.  This condition is only for developement.

**Comment by Noordfrees** [comment]
Should no longer relevant with versions newer than v1.0
