### ISSUE TITLE
Automatic check test_ai fails for windows x86 Builds

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5022]
See e.g.: https://github.com/widelands/widelands/pull/4823/checks?check_run_id=3304557612

Error:
~~~~
undefined reference to `_imp__lerc_encodeForVersion'
~~~~

Full error:
~~~~
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../lib\libtiff.a(tif_lerc.o):tif_lerc.c:(.text+0x852): undefined reference to `_imp__lerc_encodeForVersion'
~~~~

**Comment by hessenfarmer** [comment]
will have a look seems that libtiff has a new dependency

**Comment by Noordfrees** [comment]
Would it be possible to detect those dependencies in CMake automatically instead of editing the list manually every time a 3rd-party library is updated?

**Comment by hessenfarmer** [comment]
Can't tell. I still struggle with CMake. Maybe @matthiakl has more Knowledge

**Comment by matthiakl** [comment]
> Would it be possible to detect those dependencies in CMake automatically instead of editing the list manually every time a 3rd-party library is updated?

Short answer: No.
Long answer: Static libraries don't contain any information about dependencies. Therefore they can't resolve them automatically (in contrast to shared libraries). The only possibility would be to check whether the package dependencies have changed, but this would require some scripting and I don't think it is possible with pure CMake.

MingW libraries are built with maximum features:
```
  ../tiff-${pkgver}/configure \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --target=${MINGW_CHOST} \
    --enable-static \
    --enable-shared \
    --enable-cxx \
    --enable-jbig \
    --enable-lerc \
    --enable-libdeflate \
    --enable-webp \
    --without-x
```
([mingw-w64-libtiff/PKGBUILD#L45](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libtiff/PKGBUILD#L45))

vcpkg libraries on the other hand are built with minimal features:
```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        ${EXTRA_OPTIONS}
        -DBUILD_DOCS=OFF
        -DBUILD_CONTRIB=OFF
        -DBUILD_TESTS=OFF
        -DCMAKE_DEBUG_POSTFIX=d # tiff sets "d" for MSVC only.
        -Dlibdeflate=OFF
        -Djbig=OFF # This is disabled by default due to GPL/Proprietary licensing.
        -Djpeg12=OFF
        -Dlerc=OFF
        -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_GLUT=ON
)
```
([vcpkg/ports/tiff/portfile.cmake#L42](https://github.com/microsoft/vcpkg/blob/master/ports/tiff/portfile.cmake#L42))

That's the reason why the mingw builds need permanent adjustments, when a library introduces a new feature while MSVC build  still work as before.

**Comment by hessenfarmer** [comment]
as Lerc is not provided with a static library, we may be at a decision point. For our github CI checks we could eventually drop the static builds and use dynamic linking instead. This should be sufficient enough for checking if it builds and whether the 5 tests run fine on windows.  but if we still want to provide static development builds to the community we would have to maintain 2 different MSYS buiold environments. Which isn't desirable as well. 
So I see the following options:
1. Continue using bloody hacks to use MSYS2 environment (in this case overwrite the lib with a working one) top provide static builds. 
2. Switch the whole Windows Builds CI Systems to MSVC (In this case we definitly need to check for licensing issues, maybe the builds might be bigger too)
3.  drop the static builds again and switch back to collect all needed dll in the installer again. 

for the moment being 2. seems to be the way to go for me if we can be sure we are not running into licensing issues either with MS or with our CI providers.  
I will try a solution according 1. for the moment to buy us some time on this issue.

**Comment by hessenfarmer** [comment]
@matthiakl       
for the moment being this had been workarounded a while. However I'd like to ask if you could elaborate whether solution 2 would be feasible. (i.e. make a github action to build a static build in msvc.)

**Comment by matthiakl** [comment]
I already checked, that the tools are available. So using MSVC in the CI should be possible. 
Regarding the licensing, I posted a question on the Github community/support forum (https://github.community/t/github-action-visual-studio-licensing/213190/1)
I will try to put together a build script.

**Comment by matthiakl** [comment]
> I will try to put together a build script.

Ready for testing in #5132
