### ISSUE TITLE
Widelands crashing after loading huge savegame from widelands 21

### ISSUE THREAD

**Issue by cliffalbert** [widelands/widelands#5026]
**Describe the bug**
Widelands crashes after loading my huge savegame from widelands 21. Savegame is included.

[widelands-21-save.zip](https://github.com/widelands/widelands/files/6993065/widelands-21-save.zip)

**To Reproduce**
- Start widelands
- Open savegame

**Expected behavior**
- The game running with the loaded savegame

**Screenshots**
[crashdump.txt](https://github.com/widelands/widelands/files/6993074/crashdump.txt)

**Version:**
 - OS: Xubuntu 21.04
 - Widelands Version: Version 1.1~git25428[4a9cb01@master] (Debug)

**Comment by Noordfrees** [comment]
gdb shows that the ship whose removal crashes was present in the fleet twice. This seems to be due to the bug that was fixed by #4027. Unfortunately there's no way to recover an already broken b21 savegame; it seems to load fine in a release build of current master though

**Comment by hessenfarmer** [comment]
@Noordfrees 
as you explained that this was already fixed in current master , shall we close this issue then?
