### ISSUE TITLE
Zipped non-installer version for windows.

### ISSUE THREAD

**Issue by ZehCastro** [widelands/widelands#5027]
Is there a zip/non-installer version for windows?
If not, could you add one?

Thanks.

**Comment by matthiakl** [comment]
The installer does not require elevated privileges. So there is no real reason for a separate package. If you want a portable version, just install it to your device Widelands does not require a fixed absolute path.

**Comment by hessenfarmer** [comment]
As there was no response from the author of the issue I'll Propose this for closing 
Opinions @widelands/developers

**Comment by matthiakl** [comment]
Closed for inactivity
