### ISSUE TITLE
Typo in options menu: plantng

### ISSUE THREAD

**Issue by ZehCastro** [widelands/widelands#5028]
https://github.com/widelands/widelands/blob/1317dd9c8817e5954bbaff31a759568f9a9bcf3b/po/widelands/en_GB.po#L5411

![image](https://user-images.githubusercontent.com/1457644/129657628-487571cb-b02b-4bbd-982a-805a2729ed31.png)

**Comment by Noordfrees** [comment]
Thanks, I corrected the translation on transifex. 

Fix will be in master at the next automated translations sync (in two days or so)
