### ISSUE TITLE
Cannot make expedition in Twin Lagoons as Atlanteans

### ISSUE THREAD

**Issue by burger-drip** [widelands/widelands#5036]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Single player. 1v1 Normal AI. Twin Lagoons
Can built a dock
Can click start expedition
Even with the materials, nothing seems to happen. 
Even building a different dock location, there is no effect.

**To Reproduce**
Single player. 1v1 Normal AI. Twin Lagoons
Build dock. 
Click Start expedition.

**Expected behavior**
Can start expedition

**Screenshots**
![image](https://user-images.githubusercontent.com/6712779/130349178-37611779-ccd0-4c68-a1fe-6f900857245a.png)

![Screenshot_2021-08-22_19-07-34](https://user-images.githubusercontent.com/6712779/130349420-bae7c462-416d-4788-a70e-07cccdd0c6be.png)

![Screenshot_2021-08-22_19-06-13](https://user-images.githubusercontent.com/6712779/130349423-aba31d38-1a66-470f-8935-3e4f83c6aa97.png)
![Screenshot_2021-08-22_19-05-34](https://user-images.githubusercontent.com/6712779/130349424-ff2087ae-dbd6-4254-b683-6de416316cf2.png)
[no-expedition.wgf.zip](https://github.com/widelands/widelands/files/7026932/no-expedition.wgf.zip)

**Version:**
 - OS: 5.8.0-41-generic #46~20.04.1-Ubuntu SMP
 - Widelands Version: This is Widelands Build 1.0(Release)

Cancelling/starting has no effect.
Adding unnecessary items to expedition is possible, but still cannot begin the expedition[](url)

attached are screens of loading stock, and nothing happening
save game attached as well

Thank you

**Comment by Noordfrees** [comment]
You built a ferry yard but did you also build a shipyard? Expeditions can only be loaded on full-size ships; ferries are only for servicing minor waterways. (this is also explained in the third tutorial)

**Comment by burger-drip** [comment]
Yes, I am a fool...
