### ISSUE TITLE
Capitalisation of Tribe names

### ISSUE THREAD

**Issue by alasiax** [widelands/widelands#5041]
Tribe names are not capitalised within the game consistently. I noticed this with the Amazons, but hessenfarmer mentioned it should be the case for all tribes (see [comment 37928 in the forum](https://www.widelands.org/forum/topic/2897/?page=40#post-37928)).

I'll start with Amazons and then go through the other tribes.

**Comment by alasiax** [comment]
I tried to label and self-assign this, but I can't figure out how, or perhaps I don't have permissions?

**Comment by aummishra** [comment]
I would like to contribute to this issue

**Comment by alasiax** [comment]
Hi Aummishra, the more the merrier! Did you have a preferred tribe to start on?

**Comment by Vamsikrishnapac** [comment]
Can I take this.

**Comment by hessenfarmer** [comment]
anybody's help is welcome. But if 2 persons will do the same this might be a waste.  So it would be good if you agree on which tribe is done by whom.

**Comment by aummishra** [comment]
I'm currently working on another issue, I'd not be able to work on this issue. You can assign it to anyone else. Thank you!

**Comment by alasiax** [comment]
Thanks for letting us know Aummishra.

I'm happy to start with Amazons, since I'm working with those files anyway.

**Comment by alasiax** [comment]
@hessenfarmer : we should create a new branch here for this one, right? Call it 5041_Caps_fixes ?

**Comment by hessenfarmer** [comment]
> 
> 
> @hessenfarmer : we should create a new branch here for this one, right? Call it 5041_Caps_fixes ?

yes it is recomended to create a new branch in your fork and create a pul request from this branch. don't forget to pull in master frequently to stay in sync with it.  
the name of the branch is your free choice. however mentioning the bugnumber which should be fixed is good practise. What is more important then the branch name is the title of the PR. Cause this title is what appears in the changelog in the end.

**Comment by jgsogo** [comment]
I've went through the code and I think this issue has already been fixed.

**Comment by hessenfarmer** [comment]
you need to go through the data folder as well, and search for translatable texts ( they are denoted by a leading un derscore like _"text" or inside a format function. in a quick check for barabarians I found some not capitalised Instances in fri02 campaign in the texts.lua for example
