### ISSUE TITLE
Improve Error Message when loading saved game from an old version

### ISSUE THREAD

**Issue by markusd112** [widelands/widelands#5051]
**Describe the bug**
Error message "UnhandledVersionError" This game was saved with an incompatible widlenad version and cannot be load.

Saved version: 3
Current version: 5

**Screenshots**
![Screenshot_Widelands_01](https://user-images.githubusercontent.com/14372683/131257704-4f257219-b138-4896-ac78-c2691c290c4d.PNG)

**Version:**
 - OS: Windows 10
 - Widelands Version: 1.0 (Release)

**Comment by markusd112** [comment]
[stdout.txt](https://github.com/widelands/widelands/files/7072855/stdout.txt)

**Comment by hessenfarmer** [comment]
well actually the error is handled. 
as the savegame is 2 versions behind there is not much we could do about. 
With which version was the save created

**Comment by Noordfrees** [comment]
Savegame compatibility is guaranteed only from one Widelands release to the next. This save was probably created with build-20, so it needs to be loaded and resaved with build-21 before the resaved game can then be loaded in v1.0. 

If this is indeed a b20 savegame then I propose closing this issue as wontfix

**Comment by hessenfarmer** [comment]
> 
> If this is indeed a b20 savegame then I propose closing this issue as wontfix

exactly what I thought

**Comment by markusd112** [comment]
That's ok. I wanted only to help, because the text says, to report this bug, Thanks. :-)

**Comment by hessenfarmer** [comment]
> 
> 
> That's ok. I wanted only to help, because the text says, to report this bug, Thanks. :-)
 
Well this is a valid point, maybe we should think about editing this error message to state what @Nordfrees mentioned above, to avoid false alarms. 
thanks for reporting it anyway
