### ISSUE TITLE
Unused keys in LuaTable

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#5055]
Widelands Version 1.1~git25442[4faef54@master] (Release). I believe I was just watching the builders build and the other player removed a road from a forester build site and was about to replace it.

Started a multiplayer game and was only a few minutes in when the game segfaulted with:
[00:06:27.246 real] WARNING: Unused key "descname" in LuaTable. Please report as a bug.
[00:06:27.246 real] WARNING: Unused key "tooltip" in LuaTable. Please report as a bug.
181354 Segmentation fault      (core dumped)

[Attached map, replays, output and syncstream](https://github.com/widelands/widelands/files/7080744/luatable-crash.zip), the replay plays back without crashing.

**Comment by simply-peachy** [comment]
Just re-tried the same map and I noticed the same two Lua errors but no crash yet.

**Comment by hessenfarmer** [comment]
which tribe did you choose. were any addons activated?

**Comment by alasiax** [comment]
We were Atlanteans in both games, no addons as far as I know on server side (although apparently client side had the mostly balanced maps add-on enabled), shared in.

In the first game there were duplicate tribes (random picks). In the second game, we chose different 
tribes for the AI players (2 with HQ, 2 with Trade Posts). The game did not crash or return a visible error on the client end, but hung as it does when our connection drops out. Client is Version 1.1~git25441[d355de6@HEAD] (Debug)

[spider_lake.zip - Client side replay](https://github.com/widelands/widelands/files/7084282/spider_lake.zip)

**Comment by hessenfarmer** [comment]
Another question is: it seems that @simply-peachy used the datadir option. Was this the datadir of the same Git version as the game?

**Comment by simply-peachy** [comment]
> Another question is: it seems that @simply-peachy used the datadir option. Was this the datadir of the same Git version as the game?

It looks like there were differences between the source `data` and game `datadir`, but only in locale files (my copy script didn't take into account symlinks).

To clarify the tribes: Player 1 and player 6 were shared in as Atlantean. Player 2 was Amazon (AI), 3 and 4 were Frisians (AI), player 5 was Atlantean (AI).

We've tried to recreate the crash (incl. with the same tribes and positions) but to no avail.

**Comment by hessenfarmer** [comment]
well, I started the replay and I did not get the lua errors, so I beleive they are due to some leftovers in the used datadir. 
I believe furthermore that the crash might be due to another not yet detected race condition implied by the multithreading change.

**Comment by hessenfarmer** [comment]
@simply-peachy @alasiax 
As I beleive the lua errors are due to leftovers in the used datadir and the crash is not reproducable, should we consider this to be closed?
