### ISSUE TITLE
Focused dropdown consumes `Enter` key even when closed

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5058]
1. Open the single player game setup menu
2. Choose a map, click OK
3. Click on the win condition dropdown
4. Click on a win condition. The dropdown closes and is still focused (which is correct).
5. Press <kbd>Enter</kbd> to start the game → nothing happens (bug)
6. Press <kbd>Tab</kbd> and then try <kbd>Enter</kbd> again → now it works

Version 1.1~git25451[f598487@master] (Release)
Perhaps related to 7c1250da9cb0589303e9f6d133e21e80405913d4

**Comment by Noordfrees** [comment]
Partly regressed in 1.1~git25571[c898083@master] (Release):
1. Open the single player game setup menu
2. Choose a map, click OK
3. Click on any player's **tribe** dropdown, then click on any entry. (Other dropdowns don't seem to be affected.)
4. Press <kbd>Enter</kbd> → nothing happens

**Comment by jmoerschbach** [comment]
fixed with #5237
@Noordfrees  please confirm and close :)
