### ISSUE TITLE
MacOS CI Failure

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5082]
Since the `macos-latest` image was updated from  10.15.7 to   11.6 yesterday, all MacOS CI builds are now failing with a CXX compiler selftest error:
```

   Source:      ../
   Version:     1.1~git1[4374f79@HEAD]
   Destination: WidelandsRelease
   Type:        Debug
   macOS:       11.6
   Target:      10.7
   Compiler:    Apple clang version 12.0.5 (clang-1205.0.22.11)

-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/opt/ccache/libexec/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/local/opt/ccache/libexec/clang++
-- Check for working CXX compiler: /usr/local/opt/ccache/libexec/clang++ - broken
CMake Error at /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:62 (message):
-- Configuring incomplete, errors occurred!
  The C++ compiler
See also "/Users/runner/work/widelands/widelands/build_wl/CMakeFiles/CMakeOutput.log".

See also "/Users/runner/work/widelands/widelands/build_wl/CMakeFiles/CMakeError.log".
    "/usr/local/opt/ccache/libexec/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/runner/work/widelands/widelands/build_wl/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_80b5c && [1/2] Building CXX object CMakeFiles/cmTC_80b5c.dir/testCXXCompiler.cxx.o
    clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    [2/2] Linking CXX executable cmTC_80b5c
    FAILED: cmTC_80b5c 
    : && /usr/local/opt/ccache/libexec/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_80b5c.dir/testCXXCompiler.cxx.o -o cmTC_80b5c   && :
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


Error: Process completed with exit code 1.
```

**Comment by hessenfarmer** [comment]
@SirVer  @stonerl @klaus-halfmann 
any ideas?

**Comment by klaus-halfmann** [comment]
Works for me, but I use the clang provived by MacPorts not from XCode 
$ which clang
`/opt/local/bin/clang`
$ clang --version
```
clang version 9.0.1 
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-9.0/bin
```

This is an Image based on Big Sure ad (propably) XCode Version 13.0 (13A233)

Will need some time to check this, but I am currently quite stressed by my Job

**Comment by klaus-halfmann** [comment]
I Upgraded macports to clang/llvm-12 but found that widelands compiles with

-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake version 3.21.3

Where does this `/usr/local/opt/ccache/libexec/clang++` come from?
The image seem so use and slightly older XCode version

@Noordfrees please provide a link to an example of a broken build
Do we already have a branch to fix this?
Can I test this Image (in Docker?) locally?

Sorry cant do much more for now

**Comment by klaus-halfmann** [comment]
@Noordfrees please move from your Noordfrees:buildsys-update branch to a public one, So I (and others) may commit something there. (I will not clone this right now)

**Comment by Noordfrees** [comment]
> @Noordfrees please move from your Noordfrees:buildsys-update branch to a public one, So I (and others) may commit something there. (I will not clone this right now)

Done: #5085 / https://github.com/widelands/widelands/tree/buildsys-update
No branch for this issue exists yet but you're welcome to add a fix to the buildsys-update branch

> @Noordfrees please provide a link to an example of a broken build
Do we already have a branch to fix this?
Can I test this Image (in Docker?) locally?

Broken build: https://github.com/widelands/widelands/runs/3878335125?check_suite_focus=true
They seem to publish their images [here](https://github.visualstudio.com/virtual-environments/_build/results?buildId=117812&view=artifacts&pathAsName=false&type=publishedArtifacts), no idea how to use those though

**Comment by klaus-halfmann** [comment]
systeminfo.md  from Built_VM_Artifacts.zip 
tells us where to find a clang from brew, maybe we can use that one?

**Comment by klaus-halfmann** [comment]
OK maybe the fix is just to use the X-Code clang (and forget about brew) will try along this path

**Comment by klaus-halfmann** [comment]
Will try to fix this using my [m1arm](https://github.com/widelands/widelands/tree/m1arm) branch.
