### ISSUE TITLE
Compiling widelands for Apple Silicon / M1 ARM

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5103]
**Is your feature request related to a problem? Please describe.**

I  got a brand new M1 MacBook Pro and tried to compile widelands.

```
$ uname
Darwin <hostname> Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
```
I switched from macports to brew. All the libs should be there but it now fails me at:
```
CMake Error at /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_LIBRARY) (found version
  "68.2")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindICU.cmake:335 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:146 (find_package)
```
**Describe the solution you'd like**

* I assume the OS / CPU detection from CMake needs to be adopted.
 * I will try to install some other sdl based games via brew or installer and maybe get some ideas there.

**Describe alternatives you've considered**

* As of the Rosetta Emulation Widelands runs emulated, so there is no hurry to get this done..
* Crosscompiling on M1 for Intel might be possible, but makes no sense.
* Crosscompiling vice versa, makes even less sense :-)

**Additional context**

This might actually help porting widelands to other ARM based Computers, e.g. the Rapberry

**Implementation steps**

- Create a new branch m1arm or such.
- Fix Issues with CMake detection 
- Fix potentially other Issue / Errors playing the game

**Comment by Noordfrees** [comment]
This looks like a problem specifically with locating the ICU library, rather than a platform-related error. I'm not familiar with MacOS but can you try the solutions [described here](https://stackoverflow.com/questions/52510499/the-following-icu-libraries-were-not-found-i18n-required) and see if any of them fixes it?

**Comment by klaus-halfmann** [comment]
So info that may be usefull:
https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by klaus-halfmann** [comment]
Looks like this is needed
```
brewprefix="`brew --prefix`"
export CMAKE_PREFIX_PATH="${brewprefix}/opt/icu4c"
```
Basically found at https://miktex.org/howto/build-mac

Thanks @Noordfrees you where almost on the right track

**Comment by klaus-halfmann** [comment]
Compiling  was **fast** 2m13.580s And head no fan (like on my Intel Mac) even though the Cores went to ~90 °C

**Comment by klaus-halfmann** [comment]
Looks like it is running fine (and fast!) 
I added that snippet to fix the icu4c issue in [Building_Widelands_on_macOS]( https://www.widelands.org/wiki/Building_Widelands_on_macOS/)
Could we include this in some other place?

Next question should we now make Release 1 a universal binary?

**Comment by klaus-halfmann** [comment]
I try to build the complete MacOS app as described here: https://www.widelands.org/wiki/Building_Widelands_on_macOS/

But .`/build_app.sh clang release ../release-1.0` does not work as described there.
I checked here:  https://github.com/widelands/widelands/runs/4089997323?check_suite_focus=true
../utils/macos/build_app.sh clang release ../

It fails me with

```
    "/opt/homebrew/opt/ccache/libexec/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/klaus/develop/widelands/release-1.0/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/opt/homebrew/bin/ninja cmTC_33a96 && [1/2] Building CXX object CMakeFiles/cmTC_33a96.dir/testCXXCompiler.cxx.o
    clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    [2/2] Linking CXX executable cmTC_33a96
    FAILED: cmTC_33a96 
    : && /opt/homebrew/opt/ccache/libexec/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_33a96.dir/testCXXCompiler.cxx.o -o cmTC_33a96   && :
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

But the normal ./compile.sh works fine?

**Comment by Noordfrees** [comment]
That's the same error as in #5082

**Comment by klaus-halfmann** [comment]
OK, I checked this `/utils/macos/build_app.sh`

* Looks like same handcrafted magic from @SirVer that got broken with macOS 12.x Moterey -> Used compile.sh for the build part for now.
* Some other magic found in ` utils/macos/fix_dependencies.py` is broken ad gave me some ugly crash. But it looks like the orginal tool [macdylibbundler](https://github.com/auriamg/macdylibbundler) may do the trick.
* Basically all dynamic libraries must be copied into the .app Bundle ,and the main binary patched to use the correct path
* There is some nice one-liner bash tick to find the location of the ASAN library, respect!
* The info.plist does not know about the architecture ad needs no modifications
* A 'fat' binay is actually a file containig the x86 and arm cod in one file
* This would need al Libraies as binary Files, too 
* -> Will not try to build a fat binary any longer
So far for today

**Comment by klaus-halfmann** [comment]
* I switched `utils/macos/build_app.sh` to use ./compile.sh so we need to change the
automated buildscript to call it as `../utils/macos/build_app.sh -r`
* This currently only works for a release build , fo debug / ASAN I need to fix some Issue
* I will push this change to https://github.com/widelands/widelands/tree/m1arm
* BUT on startup I get  `EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid)) `.

@Noordfrees can we change the setup for the macOS Build for this branch only?
we will nee to install https://github.com/auriamg/macdylibbundler for this

**Comment by Noordfrees** [comment]
> @Noordfrees can we change the setup for the macOS Build for this branch only?

I assume you mean the CI builds?
Just edit the section `macos` in https://github.com/widelands/widelands/blob/m1arm/.github/workflows/build.yaml#L246-L282. 
You may additionally want to add the branch name to line 6 and comment out line 247 to ensure you get a mac CI build for every push to the branch.

**Comment by klaus-halfmann** [comment]
@Noordfrees thanks for your hints:

A of the modifications the shard libs lost there signature, e.g.
```
$ codesign --verify  libFLAC.8.dylib 
libFLAC.8.dylib: invalid signature (code or signature have been modified)
In architecture: arm64
```

Look like with Monterey code signing is played as hard as on iOS :-/

**Comment by klaus-halfmann** [comment]
Looks like
`codesign --sign - --force` * in `Widelands.app/Contents/libs` 
does the trick

**Comment by klaus-halfmann** [comment]
OK, puzzled it all together, hold thumbs. Will check tomorrow

**Comment by klaus-halfmann** [comment]
OK the build does not know about macOS 12, yet, goig back to macOS 11
Here is a 1.0 build  https://www.magentacloud.de/share/ygwso1qmey.
Shall I just add it to https://www.widelands.org/wiki/Download ? Or do we have a better place?

**Comment by Noordfrees** [comment]
>  Here is a 1.0 build [magentacloud.de/share/ygwso1qmey](https://www.magentacloud.de/share/ygwso1qmey).
> Shall I just add it to [widelands.org/wiki/Download](https://www.widelands.org/wiki/Download) ? Or do we have a better place?

Great :) 
Please upload it to both the GitHub release at https://github.com/widelands/widelands/releases/tag/v1.0 and to the launchpad release at https://launchpad.net/widelands/1.x/1.0 . Let me know in case you don't have permissions for one of them. The download page can then link to one of these downloads.

**Comment by klaus-halfmann** [comment]
Uploading to the release page now, the name is not _that_ good (there never was an m1 Mac before  mac0S 11)
Would widelands_m1Arm_1.0.dmg be OK.

I did not login to launchpad since ages, do we really need it there?

Next thing I will try is to get that debug build going.

**Comment by Noordfrees** [comment]
> I did not login to launchpad since ages, do we really need it there?

Yes, please do upload it there as well. LP downloads are way more reliable than those from GitHub for whatever reason, so the Download page should preferably link to the LP files. Also you can there add a signature to the file in case you have a GPG key.

**Comment by klaus-halfmann** [comment]
Never had a PGPG key on Launchpad, will try now

**Comment by klaus-halfmann** [comment]
Uhh, I tried to upload twice, but failed.
Maybw I need more badwidth

**Comment by Noordfrees** [comment]
Happens to me a lot as well… I'll download the file and try pushing it to LP

**Comment by klaus-halfmann** [comment]
Thats Odd, in my ARM Version I cannot switch to German, but to e.g. polish, even switching to German via the intel version leaves the language settings as "not-selected", indeed the "de" locale is missing. Will try to fix this later.
(Pushing to LP failed me again this morning)

**Comment by klaus-halfmann** [comment]
OK fixed the debug build, now we have a decision to make:
* This change will most probably break @SirVer daily build for the old macOS Version, so do we want to keep them.
* I will investigate if github allows compiling for Apple Silicon and maybe add this. @Noordfrees / @hessenfarmer  any idea?

**Comment by klaus-halfmann** [comment]
Added topica macos-app and apple-siicon so we now appear on https://github.com/topics/apple-silicon

**Comment by Noordfrees** [comment]
Only these environments are supported by GitHub's CI: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners

---

Pushing to LP failed for me yesterday and overnight, now trying one last time…

**Comment by klaus-halfmann** [comment]
https://github.com/actions/virtual-environments/issues/2187 and we are not the only ones waiting for this :-)

**Comment by klaus-halfmann** [comment]
Oh, the binaries build by github actions have only a (broken) symlink for the locale.

**Comment by klaus-halfmann** [comment]
@Noordfrees I think I fixed the locale Issue so is is ready to merge, but I am sure we must rever some parts
of that .github/workflows/build.yaml
