### ISSUE TITLE
Random Number Generator is Never Seeded

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5123]
The random number generator (`RNG`) that deterministically generates all pseudo-random events in a game is never actually seeded, so that all games always use the exact same sequence of random numbers.

The RNG must be seeded with a truly random number (e.g. `SDL_GetTicks()` or `clock()`) exactly once at the start of every game.
In MP matches, the seed value must also be distributed from the host to the clients. 
Replays already have code to preserve the RNG state which should not require adaption.

Question for discussion: Should the state of the RNG be dumped to savegames as well, so that reloading will not alter the sequence of events, of should it be reinitialized with a new truly-random seed on load like for new games?

**Comment by klaus-halfmann** [comment]
To reproduce bugs it should be possible (in Debug builds only) to set this value.
So we are able to reproduce the exact startconditions etc.

**Comment by spth** [comment]
Reinitalizing on savegame load would make it much harder to reproduce bugs. So I'd be opposed to that (no matter if debug or release build).
