### ISSUE TITLE
Update of macdylibbundler may have broken arm and eventually x86 MacOS build

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5148]
Macdylibbundler has been updated to add the missing codesigning: https://github.com/auriamg/macdylibbundler/pull/71

I tried to build an m1Arm build but starting the App fails with an obscure message like
```
Error Formulating Crash Report:
_dyld_process_info_create failed with 6
dyld_process_snapshot_get_shared_cache failed
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
```

Where can I find the latest .dmg build to verify this. meanwhile I have created a local branch "ma1rm2" to check this.
May I will push this once I got an idea how to fix this.

**Comment by Noordfrees** [comment]
You can always find the latest builds under this link: https://github.com/widelands/widelands/releases/tag/latest

The DMGs are compiling and building fine, though there's no automated testing whether they actually work.

**Comment by klaus-halfmann** [comment]
Lets close this one now
