### ISSUE TITLE
tag creation triggers superfluous appveyor built

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5152]
the autoamted updated tag introduced with #5143 triggers an additional appveyor build. 

any way to circumvent this would be welcome. maybe we could add the tag before buolding everything

**Comment by Noordfrees** [comment]
I have disabled building tags in the appveyor settings now, let's see if this fixes it next time the tag is updated

**Comment by hessenfarmer** [comment]
just had a look in the settings again and the flag to not build tags was not set. I have added this setting again however appveyor settings in the webcenter are widely ignored if an appveyor.yml is provided . if it does not work in the next run we need to include this setting in the appveyor.yml

**Comment by hessenfarmer** [comment]
Worked with the latest commit so I am closing this

**Comment by hessenfarmer** [comment]
I was to quick. tried another solution directly in master.

https://github.com/widelands/widelands/commit/0b25706e056c1a540197df4d8cb2c1be49bcd8df

**Comment by hessenfarmer** [comment]
using the appveyor.yml did the trick
