### ISSUE TITLE
Expedition can't find port space although it is shown in buildhelp

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5155]
After destroying/dismantling a port, an expedition ship doesn't find the port space anymore. After some Roads/Buildings around the port space are destroyed the expedition ship finds the port space.

**To Reproduce**
1. Load attached save game
2. Let the expedition ship try to find the open port space -> It can't find it
3. Destroy roads around the port space
4. Let the expedition ship try to find the open port space -> It can't find it
5. Destroy the Armor smithy
6. Let the expedition ship try to find the open port space -> Now it finds the port space and the port can be built

I had a similar situation where destroying roads was enough to let the expedition ship find the port space.

**Expected behavior**
If the buildhelp shows a spot for a port space, an expedition should find it.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25551[3d01188@4929-portpaths-ordering] (Debug)
 
[no_port_space_found.zip](https://github.com/widelands/widelands/files/7698577/no_port_space_found.zip)

**Comment by Noordfrees** [comment]
This is where the availability of an expedition port space is checked. It assumes that you won't build a port in a place where you already have flags and roads and buildings in certain nearby spaces:
https://github.com/widelands/widelands/blob/7f3312646a24853e8353c543a260bd43ba9a62a0/src/logic/map_objects/tribes/ship.cc#L56-L100

**Comment by frankystone** [comment]
So initially this was meant to not bother a player with 'Port space found' messages for already owned land...

Can there be a check for warehouses/ports in the corresponding economy? 
If economy has_not warehouse then find port_space... or so :-D

Or implement #4574 and remove some of the checks?

**Comment by tothxa** [comment]
Here's a savegame to reproduce the bug with v1.1 and 1.2~devel: [bug5155_test.zip](https://github.com/widelands/widelands/files/9965012/bug5155_test.zip)
