### ISSUE TITLE
Can't build source code, because asio.hpp doesn't exist

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5181]
```
FAILED: src/network/CMakeFiles/network.dir/bufferedconnection.cc.o 
/usr/bin/c++ -DUSE_XDG -DWL_USE_GLVND -I/home/solus/Git/widelands/src -I/home/solus/Git/widelands/build/src -isystem /usr/include/SDL2 -g  -std=c++11  -g -DDEBUG -fsanitize=address -fno-omit-frame-pointer -Wredundant-decls -Wall -Wpedantic -Wdeprecated-declarations -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winit-self -Winvalid-pch -Wlogical-op -Wmissing-include-dirs -Wno-undef -Wold-style-cast -Woverlength-strings -Wpacked -Wpointer-arith -Wsign-promo -Wsync-nand -Wtrampolines -Wundef -Wunused -Wunused-macros -fno-elide-constructors -Werror -MD -MT src/network/CMakeFiles/network.dir/bufferedconnection.cc.o -MF src/network/CMakeFiles/network.dir/bufferedconnection.cc.o.d -o src/network/CMakeFiles/network.dir/bufferedconnection.cc.o -c /home/solus/Git/widelands/src/network/bufferedconnection.cc
In Datei, eingebunden von /home/solus/Git/widelands/src/network/bufferedconnection.h:28,
                 von /home/solus/Git/widelands/src/network/bufferedconnection.cc:1:
/home/solus/Git/widelands/src/network/network.h:25:10: schwerwiegender Fehler: asio.hpp: Datei oder Verzeichnis nicht gefunden
   25 | #include <asio.hpp>
      |          ^~~~~~~~~~
Kompilierung beendet.
[211/765] Building CXX object src/netw...Files/network.dir/internet_gaming.cc.o
FAILED: src/network/CMakeFiles/network.dir/internet_gaming.cc.o 
/usr/bin/c++ -DUSE_XDG -DWL_USE_GLVND -I/home/solus/Git/widelands/src -I/home/solus/Git/widelands/build/src -isystem /usr/include/SDL2 -g  -std=c++11  -g -DDEBUG -fsanitize=address -fno-omit-frame-pointer -Wredundant-decls -Wall -Wpedantic -Wdeprecated-declarations -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winit-self -Winvalid-pch -Wlogical-op -Wmissing-include-dirs -Wno-undef -Wold-style-cast -Woverlength-strings -Wpacked -Wpointer-arith -Wsign-promo -Wsync-nand -Wtrampolines -Wundef -Wunused -Wunused-macros -fno-elide-constructors -Werror -MD -MT src/network/CMakeFiles/network.dir/internet_gaming.cc.o -MF src/network/CMakeFiles/network.dir/internet_gaming.cc.o.d -o src/network/CMakeFiles/network.dir/internet_gaming.cc.o -c /home/solus/Git/widelands/src/network/internet_gaming.cc
In Datei, eingebunden von /home/solus/Git/widelands/src/network/bufferedconnection.h:28,
                 von /home/solus/Git/widelands/src/network/netclient.h:25,
                 von /home/solus/Git/widelands/src/network/internet_gaming.h:26,
                 von /home/solus/Git/widelands/src/network/internet_gaming.cc:20:
/home/solus/Git/widelands/src/network/network.h:25:10: schwerwiegender Fehler: asio.hpp: Datei oder Verzeichnis nicht gefunden
   25 | #include <asio.hpp>
      |          ^~~~~~~~~~
Kompilierung beendet.
[212/765] Building CXX object src/CMakeFiles/build_info.dir/build_info.cc.o
ninja: build stopped: subcommand failed.


```

**Comment by Noordfrees** [comment]
The [Asio](https://think-async.com/Asio/) library is a new dependency (replacing boost), please install it

Edit: We don't yet have a CMake check if it's installed, but I happen to be working on writing such a check just now :P

**Comment by klaus-halfmann** [comment]
Same here, installed asio via homebrew, all fine.

We should however check the homepage for the build instructions to mention this.

**Comment by Noordfrees** [comment]
I updated https://www.widelands.org/wiki/Building%20Widelands/ yesterday to point to the script 
```sh
./install-dependencies.sh
```
which will install all dependencies (including asio) on most supported systems, including homebrew.

**Comment by MarkMcWire** [comment]
> I updated https://www.widelands.org/wiki/Building%20Widelands/ yesterday to point to the script
> 
> ```shell
> ./install-dependencies.sh
> ```
> 
> which will install all dependencies (including asio) on most supported systems, including homebrew.

Autodetecting operating system...
ERROR. Unable to detect your operating system.

I use Solus 4.3

**Comment by Noordfrees** [comment]
Solus is not supported yet, presumably because no developer ever used this system ;) If you could provide the command-line to install all dependencies needed to compile Widelands under Solus we can add it to the list of systems supported there

EDIT Ah this was on the wiki already so no need…

**Comment by MarkMcWire** [comment]
There exists no libasio for Solus. 
The manual compilation doesn't work either, I've tried. :-(

**Comment by Noordfrees** [comment]
Hm :(
I'm going to build a Solus VM and have a look…

**Comment by tothxa** [comment]
> There exists no libasio for Solus. The manual compilation doesn't work either, I've tried. :-(

The Asio documentation is indeed not clear at all. You don't have to compile anything to use it, but the release includes examples, which are compiled by default (and need boost). I figured out from the FreeBSD sources that you can use the `install-data` target, ie. `./configure && make install-data`. (Actually all this does is copy `asio.hpp` and the `asio` subdirectory from the `include` directory to your systemwide include directory and set ownership and permissions.)

**Comment by MarkMcWire** [comment]
I've installed a second OS (LinuxMint 20.2) on my PC on another SSD I put in today. I'll try to use widelands there.

**Comment by MarkMcWire** [comment]
Now, it works. :+1: @Noordfrees @tothxa
