### ISSUE TITLE
formatting workflow should be run on PR

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5221]
**Describe the bug**
Currently the format.yaml workflow is only run on push, so it is possible to create a pull request with unformatted code if the PR branch comes from a fork where format.yaml can't push changes. 

**To Reproduce**
E.g. see history of #5215

**Expected behavior**
The formatting workflow should run for all new PRs, not just for new commits to a PR.

**Comment by Noordfrees** [comment]
Would be great but I'm not sure this is possible currently:

> For pull requests from a forked repository to the base repository, GitHub sends the […] events to the base repository. No pull request events occur on the forked repository.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories

and
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository. The GITHUB_TOKEN has read-only permissions in forked repositories
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories


master is always formatted by the action, so if unformatted code is merged it will just be taken care of a few minutes later…

**Comment by Noordfrees** [comment]
When the Codeberg mirror is set up, how about removing the formatting action and letting bunnybot take care of formatting automatically while mirroring the branches?

**Comment by Noordfrees** [comment]
Now implemented in the GH/Codeberg mirror with the add-ons server a proven testcase. So this will be fixed when we deploy it live.
