### ISSUE TITLE
appveyor Artifact upload failing due to invalid filename

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5222]
Since some builds our appveyor builds are failing as the upload of the final artifact is not working. I have created a support ticket which resulted in the following answer:   

<html><body>

From: Feodor Fitsner (Support staff)                      Well, nope, the issue is not in artifact storage size. Apparently, the new storage we are adopting right now does not like []  square brackets in a file name. Remove square brackets from file name  or wrap it into zip (which is even more recommended considering the size  of that .exe) and upload should be working again. PS: Consider uploading artifact in some builds only, like tag builds to reduce storage consumption.                        
On Fri, Jan 28 at 08:13 AM PST, Feodor Fitsner wrote:                            widelands-dev account has reached a  monthly allowance of 50 GB for artifacts storage. We've increased it to  75 GB, so you should be unblocked now.

</body>
</html>

So if we want to keep appveyor for distribution of dev builds we need to remove the square brackets from our filename.
Furthermore we should merge the PNGQuant branch soon to reduce file size and not exceeding our quota.

**Comment by matthiakl** [comment]
As we now have all daily builds on GitHub we may disable Appveyor build for every commit.

**Comment by hessenfarmer** [comment]
> As we now have all daily builds on GitHub we may disable Appveyor build for every commit.

the only reason to keep it was that from appveyor the artifacts could be downloaded by everyone and on github you need to register. So we did not want to enforce registry for just downloading a dev build. 
if we skip this policy we might skip appveyor. 

my vote would be to keep appveyor for the reason above and alter the filename.

**Comment by Noordfrees** [comment]
But now we upload the GitHub Actions CI artifacts to the `latest` pre-release, where they can be downloaded publicly without signing in. +1 from me for dropping AppVeyor altogether.

**Comment by hessenfarmer** [comment]
in this case lets drop it. But we should keep a copy of the appveyor.yml somwehere to be able to reuse it just in case we might need it sometimes

**Comment by Noordfrees** [comment]
The file will be part of the git history forever, it's impossible to permanently lose [any file](https://github.com/widelands/widelands/blob/08d590c990ad437e6ff91707ac3e96587f2920eb/tribes/barbarians/stronghold/stronghold_i_00.png) · [no matter](https://github.com/widelands/widelands/blob/08d590c990ad437e6ff91707ac3e96587f2920eb/worlds/blackland/pics/loading_01.jpg) · [how old](https://github.com/widelands/widelands/blob/69a3282eda4e067a81c6a55736850927430df1a2/tribes/romans/workers/butcher/conf) with git :)

**Comment by hessenfarmer** [comment]
As I don't like throwing things away (for reason that you never know if you might need them again) I made a fix without interfering anything else.
