### ISSUE TITLE
could not create png struct

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5239]
After building the game successfully with cmake and ninja option the game's GUI and music worked fine but then whenever I start any kind of game, a pop up error window comes with the massage "widelands/src/graphic/image_io.cc:87 save_to_png : could not create png struct" 
alle dependencies are installed via homebrew.

1. build the game with ninja macOS Monterey version 12.2
2. run the game
3. start a new single game

**Version:**
 - OS: macOS Monterey version 12.2
 - Widelands Version: build 1.1~git25630[e9f047d@master]

I only have libpng1.6.37 installed ,but still cmake during building is somehow using libpng1.4.12 and i can’t install libpng1.4.12 since this version is not supported anymore.
<img width="1193" alt="Screenshot 2022-02-10 at 17 01 32" src="https://user-images.githubusercontent.com/57096392/153451247-0ea45146-1ce2-48ac-843e-9829ab0b752b.png">
<img width="982" alt="Screenshot 2022-02-10 at 17 01 52" src="https://user-images.githubusercontent.com/57096392/153451270-0a68bc63-ff5b-4baa-a213-d18b8630713e.png">

**Comment by klaus-halfmann** [comment]
Is this an x86 or arm (Apple Silicon) Mac?

**Comment by Ahmad-fadl** [comment]
Its Intel 6-core i7

**Comment by klaus-halfmann** [comment]
Please compare with my installation
```
% brew search libpng 
==> Formulae
libpng ✔      liboping      libbpg        libwpg        libupnp       libming       libgnt        libpst        libpcl        libmnl        libagg        libgig
libspng       libpgm        libmng        libpano       libtrng       libpq         libpsl        libp11        zlib-ng       libsvg        libvnc        libogg ✔

% brew info libpng  
libpng: stable 1.6.37 (bottled), HEAD
Library for manipulating PNG images
http://www.libpng.org/pub/png/libpng.html
/opt/homebrew/Cellar/libpng/1.6.37 (27 files, 1.3MB) *
  Poured from bottle on 2021-10-29 at 19:49:59
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libpng.rb
License: libpng-2.0
```

(If you are running Apple Silicon you may have a mixed installation wit old x86 libpng).
please try to find out where this libpng 1.4.12 comes from.

you may need to `rm -Rf build` to recompile the code once you fixed that.
(please add the logs as text, too)

**Comment by klaus-halfmann** [comment]
I will be online at https://meet.ffmuc.net/WidelandsChat for about an hour now.

**Comment by Ahmad-fadl** [comment]
<img width="982" alt="Screenshot 2022-02-10 at 18 35 36" src="https://user-images.githubusercontent.com/57096392/153464212-9d73270d-3464-4da9-8f9a-7bc6a11a7b9c.png">

I only have libpng 1.6.37 installed i already tried building otherwise using this ./compile script.
That also didn’t work.
i even tried to specify the version of libpng in the "find_package" function in cmakelists.txt that didn’t work as well and of Course i deleted the build folder every time

**Comment by klaus-halfmann** [comment]
Compiling I get 
`Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.37") `

Please check also

```
brew --prefix
/opt/homebrew
```

**Comment by klaus-halfmann** [comment]
My $PATH  is
`/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/klaus/bin`

**Comment by Ahmad-fadl** [comment]
I deleted "/Library/Frameworks/Mono.framework/Versions/Current/Commands" from my path so my path now is "/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/ccache/libexec:/Library/Apple/usr/bin:/Applications/Privileges.app/Contents/Resources:/usr/local/opt/unzip/bin:/usr/local/anaconda3/bin:/usr/local/anaconda3/condabin"
and the error is still there

**Comment by klaus-halfmann** [comment]
Try to reduce the path to an absolute minimum. There are some extras there widelands will not need.
Hint: contact can be done in German, too.

**Comment by Ahmad-fadl** [comment]
I jsut reduced it to the minimum "/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin" 
still the same error

**Comment by Ahmad-fadl** [comment]
I took a look at the generated make files and saw that the included png library was taken from the mono.framework.
The issue has been solved By Deleting mono.framework. Otherwise Cmake wouldn’t include libpng from the right directory no matter if mono.framework in the PATH or not.
