### ISSUE TITLE
Tutorial basic control

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5243]
After compiling with ./compile.sh.
I started the tutorial basic control.
The tutorial started teaching me about "show building spaces" and then automatically highlighted show/Hide options one after another but when the highlighter came to show building spaces (as in the screenshot) the whole game crushed  and the massage ("Illegal instruction: 4") appeared on the terminal

1. build the game with ninja macOS Monterey version 12.2
2.  run the game
3. start the tutorial basic control
4. wait until the part with "building_spaces"
5. See error

**Version:**
 - OS: macOS Monterey version 12.2
 -  Intel processor 
 - This is Widelands 1.1~git25635[ca5ad8e@master]

I assume the error is in [this line](https://github.com/widelands/widelands/blob/b0d4511f32772934bcff8432e2c73a46ae7c7205/data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua#L57) .
I tried to remove the parameter "obj_initial_toggle_building_spaces" and ran the game again.
A pop up window with cam with error in the "campaign_message_with_objective" function but the game **didn't crush**.
<img width="299" alt="Screenshot 2022-02-12 at 18 10 11" src="https://user-images.githubusercontent.com/57096392/153721529-f5709082-5114-4e05-ae4e-0e2a689ed60a.png">

**Comment by klaus-halfmann** [comment]
Hello Ahmand, thanks for digging into the tutorials. I think such Errors happens as we introduced multithreading. Such functions kind of violate the idea of gui vs. control threads and needs special
treatments. I will try to reproduce this tomorrow.

**Comment by Ahmad-fadl** [comment]
Thanks for taking a look at it.
after more testing the error is for sure here in [this line](https://github.com/widelands/widelands/blob/b0d4511f32772934bcff8432e2c73a46ae7c7205/data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua#L56) so that you know where to start and to save you sometime.

**Comment by frankystone** [comment]
Here on archlinux using version 1.1~git25633[b0d4511@master] (Debug) no error appears.

**Comment by hessenfarmer** [comment]
i couldn't reproduce this neither on current master on windows

**Comment by Ahmad-fadl** [comment]
I already merged [this](https://github.com/widelands/widelands/commit/504858c9a6f565c06e622b04edfda0de0fce3075) with [this](https://github.com/widelands/widelands/commit/97d6f701322bdc32f822391aeb6e510f435f9360) fix on my fork .
but just a minute i'll try with the newest version of the upstream master

**Comment by Ahmad-fadl** [comment]
My mistake sorry..
