### ISSUE TITLE
AI don't build enough wells and upgrade no buildings.

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5244]
As already mentioned in the other thread, the Europeans in the current build of Widelands don't build the required 5 wells (basic amount) and thus somehow get stuck in the basic economy. No battle arenas, warehouses, or building upgrades are constructed even after 10 hours of gameplay.

-> https://drive.google.com/file/d/13Ppm8BqTTDdeqCTcOaAMC4rJf1NGVpBY/view?usp=sharing

Use as addons only europeans_map, europeans tribe (2.2.6) and enhanced_debug_scripts.

**Comment by tibor95** [comment]
I will look into this. I must check the code.
I presume the problem is general - in all tribes

**Comment by tibor95** [comment]
First thing that comes into mind is if the well building is properly identified by AI:
https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L962
But I presume this is OK on your side

**Comment by tibor95** [comment]
But actual problem is here:

https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L5542

We do not even consider basic_amount for these three types of buildings..

EDIT:
It is interesting that nobody complained so far.
Also, there can be problem with changing this and AI training. If all current 4 tribes has this amount set to 1...

I will wait till that other branch will be in master and branch new one and play with this.

**Comment by hessenfarmer** [comment]
I agree we shuld go over the code to see whether it could be improved.   
However basic_amount was meant to be used to prevent an AI deadlock by prefering some essential buildings in the start of the game . So normally we should have only basic_amount = 1 as this would prevent a deadlock.  sometimes we used basic_amount = 2 on special occasions but carefully. Specifying basic_amount = 5 could easily result in a deadlock itself, for reason the AI not reaching basic economy or creating a build material shortage or having to many constructionsites.         
So I believe the AI would do better if specifiying basic_amount = 1

**Comment by hessenfarmer** [comment]
> But actual problem is here:
> 
> https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L5542
> 
> We do not even consider basic_amount for these three types of buildings..
> 

we do in this line 
https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L5597

so adding a higher value then 4 might help here

**Comment by tibor95** [comment]
This is what I just found in one init.lua:
   aihints = {
      very_weak_ai_limit = 1,
      weak_ai_limit = 2,
      basic_amount = 2,
   },
How can basic_amount be above *_ai_limit?

Similarly Building Observer's cnt_target should be always at least equal basic _amount. So one of changes could be force cnt_target >= basic_amount - at least for the well and other two sites.

However I agree that basic_amount should be total bare minimum to avoid deadlock on the early stage of game. So in 99,99% of cases 1 well should be enough for this purpose.

**Comment by MarkMcWire** [comment]
I've reduced all my basic_amounts to 1 or 2, with the exception of the reed_yards, which is still 4, because Europeans need lot of reed as build material for basic buildings and reed_yards needs some time to reach the optimum work output, because reed grows not as fast as the consumption.

But only 2 wells are actually not enough to start an economy, because most of my buildings have water as input.
Reed yards, farms and ranger's huts all need water to plant plants,  clay pit and lime kiln need it to produce clay, bricks and grout. Not to mention breweries and taverns to produce beer and rations and spider farms and sheep farms to produce silk and wool.

In terms of dependency on water, I may have made them too realistic.

**Comment by tibor95** [comment]
Yes, I am trying to improve the code here.
How this what you describe is not a  "deadlock" - deadlock can be no lumberjack and no wood to build one. Or no wood hardener and no planks to build one.

The problem here is with AI training. We do not have a 'stable' tribe that is so heavy dependent on water, so training might not be very effective

But as I say - I work and investigate this..

**Comment by tibor95** [comment]
Another idea - we make the wells count kind of depend on productionsites - not bad concept, but what if we counted actual water-consumers? I do not think AI is doing something like that in any such case

**Comment by hessenfarmer** [comment]
> Another idea - we make the wells count kind of depend on productionsites - not bad concept, but what if we counted actual water-consumers? I do not think AI is doing something like that in any such case

1. for solving the basic_economy we might apply the same bonus as shown after this line for the wells as well (which is basically what suggested above.  
https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L6194

2. rather basing them on a new value to be calculated I'd prefer using the mechanisms.  like in line 
https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L6147
maybe just comment the wells out in line 5540 and see how they would be handled in the code after 
https://github.com/widelands/widelands/blob/df614fd8e76f79084d3d35cd3bfbd5efcbc29d1f/src/ai/defaultai.cc#L5947

**Comment by hessenfarmer** [comment]
> This is what I just found in one init.lua: aihints = { very_weak_ai_limit = 1, weak_ai_limit = 2, basic_amount = 2, }, How can basic_amount be above *_ai_limit?

good question which Building was this
edit found it. there are other files like this.    
this is definitly a bug and should be fixed, I think it never arose as problem as nobody used weak AI

**Comment by tibor95** [comment]
> good question which Building was this edit found it. there are other files like this. this is definitly a bug and should be fixed, I think it never arose as problem as nobody used weak AI

It is rather bug in logic in AI, or corner case that is not handled properly. The code of AI is simply too complex :(

**Comment by tibor95** [comment]
I already created a branch and some code there, definitelly this need improvement, I want to use stocklevel in decision making.

However if productionsites can have very different water needs, their number is not good enough predictor of needed wells count. I will let you know if some code will be ready at least for draft pull request

**Comment by hessenfarmer** [comment]
> > good question which Building was this edit found it. there are other files like this. this is definitly a bug and should be fixed, I think it never arose as problem as nobody used weak AI
> 
> It is rather bug in logic in AI, or corner case that is not handled properly. The code of AI is simply too complex :(    
    
well having a lua definition like the described is a definition error. Only thing AI should  do codewise is to safeguard this by throwing a warning in the logs.

**Comment by hessenfarmer** [comment]
What we should do imho is handle wells separatly (means duplicating the current weighing section and adjusting it) or handle them like all other productionsites (which means just let them fall through to line 5947.    
I would first go for the second solution and only afterwards for the first one.      
Maybe we could add a little more weight on stocklevel for the  handling of all normal sites as well.

**Comment by tibor95** [comment]
> well having a lua definition like the described is a definition error. Only thing AI should do codewise is to safeguard this by throwing a warning in the logs.

I agree. But who reads logs :) This is basically to preserve status quo

**Comment by tibor95** [comment]
I would not mix them with other buildings

My suggested logic would be:

- basic_amout => forced withing building basic economy
- cnt_count => relevant after achieving basic economy
- cnt_count is minimal number of such sites and when dismantling sites, never go under this

However we can go up to 2*cnt_count, but above cnt_count we can go only if stockcount < 10 (or some other number)

This will allow us some freedom for tribes that are more dependant on water.

EDIT: So I mean to preserve current group of fishers, wells and hunters.

**Comment by hessenfarmer** [comment]
> I would not mix them with other buildings.     
    
well, currently they are mixed with fishers and hunters ;-). to be honest we need to think of what ios driving the necessity of these buildings most. In my eyes it is Low stock for their outputs. we can add some other factors like size of productionsites or expansion modus but in the end it remains needednes of the ware should be the main factor. Therefore we could try to skip the logic for them all and let them be handled like every other productionsite. Probably by giving some bonus for the first one.     
  
> 
> My suggested logic would be:
> 
>     * basic_amout => forced withing building basic economy      
    
that would be completely different from what is implemented now for all basic buildings. they are encouraged by a bonus or discouraged  but not forced.     
    
> 
>     * cnt_count => relevant after achieving basic economy       
   
agreed but basically we would only need this value if we calculate it from economy size.     
    
> 
>     * cnt_count is minimal number of such sites and when dismantling sites, never go under this      
    
dismantling is already based on stocklevel mostly which is ok.

> 
> However we can go up to 2*cnt_count, but above cnt_count we can go only if stockcount < 10 (or some other number)    
   
rather thenm experimenting with numbers here, I suggest to rethink the weights calcualted in inputs to determine neededness. target_cnt is only used in 4 out of 32 inputs. 

> 
> This will allow us some freedom for tribes that are more dependant on water.      
   
be mainly dependent on stocklevel of a ware would be the most flexible way as this would always show whther we need a building or not.
> 
> EDIT: So I mean to preserve current group of fishers, wells and hunters.

**Comment by tibor95** [comment]
Even now we do not dismantle wells below cnt_target:
https://github.com/widelands/widelands/blob/6e1c91828294e26343dd340f4f39eb8648d0ecf0/src/ai/defaultai.cc#L4839

Maybe I used wrong words:

- basic_amount => do not exceed while building basic economy
- cnt_count => minimal count of sites once basic economy is achieved, regardless of stock level, never dismantle below this level
- above cnt_count and up to 2*cnt_count - build/dismantle based on stocklevel

These sites are quite specific: cheap, no inputs, single output, unique produces. What other "normal" productionsites are like that? Yes, quarry can be similar (BuildingAttribute::kNeedsRocks). But we build quarry regardless of if we need stones - to clean up the space

Also normal productionsites do not deduct needed count from size of economy

It feels safer to me to modify small piece of code than end up with some wild changes...

**Comment by tibor95** [comment]
Also I do not see good way how to calculate cnt_target from stocklevel. If we were trying to come up with such number

**Comment by hessenfarmer** [comment]
> Even now we do not dismantle wells below cnt_target:
> 
> https://github.com/widelands/widelands/blob/6e1c91828294e26343dd340f4f39eb8648d0ecf0/src/ai/defaultai.cc#L4839
> 

ok so I agree that cnt_target should be a safeguard for dismantling.    

> Maybe I used wrong words:
> These sites are quite specific: cheap, no inputs, single output, unique produces. What other "normal" productionsites are like that? Yes, quarry can be similar (BuildingAttribute::kNeedsRocks). But we build quarry regardless of if we need stones - to clean up the space

quarry is different of course. However the reason why these 3 kinds of building may be grouped together is that they are all important for the food economy. so in theory they should be of equal importance unless one tribe needs much more from one ware then the other. this is where stock dependency is kicking in.      
to cure for the basic economy issue (which isn't a real issue as basic_amount = 5 is rather a misuse of it) we should increase the bonus if the building is part of it in line 5598 to something similar to line 6194 ff. or we might use the same code as in line 5803ff.

> 
> Also normal productionsites do not deduct needed count from size of economy      
    
that is why I wanted to try to let wells be handled by this code as well as size of economy is not as good a measure as is stocklevel. 

> 
> It feels safer to me to modify small piece of code than end up with some wild changes...       
    
I understand, but I will do the experiment myself tonight and see how it works.

**Comment by hessenfarmer** [comment]
> Also I do not see good way how to calculate cnt_target from stocklevel. If we were trying to come up with such number.

easiest way would be to do something like a stepped if:
if stocklevel  == economy target then cnt_target++
if stocklevel < 0.8 # economy target then cnt_target++

or something similar

**Comment by tibor95** [comment]
Of course, do some experiments. But I do not believe you comment a block of code and it will work automagically.

Current code allows to exceed cnt_target - if AI indeed does it - I have no idea, but it would be nice to have this block of code more readable and more explicit.

**Comment by tibor95** [comment]
> > Also I do not see good way how to calculate cnt_target from stocklevel. If we were trying to come up with such number.
> 
> easiest way would be to do something like a stepped if: if stocklevel == economy target then cnt_target++ if stocklevel < 0.8 # economy target then cnt_target++
> 
> or something similar

But a time aspect should be there, so that it does not increase every 10 seconds or so.
Basically this is what I propose, only I do not define target as a concrete number. Just I would allow next building if:

- no other building of the type is being in construction (unoccupied??)
- total_count() < cnt_count * 2

EDIT: third condition of course

- stocklevel < some_target

**Comment by hessenfarmer** [comment]
> > > Also I do not see good way how to calculate cnt_target from stocklevel. If we were trying to come up with such number.
> > 
> > 
> > easiest way would be to do something like a stepped if: if stocklevel == economy target then cnt_target++ if stocklevel < 0.8 # economy target then cnt_target++
> > or something similar
> 
> But a time aspect should be there, so that it does not increase every 10 seconds or so. Basically this is what I propose, only I do not define target as a concrete number. Just I would allow next building if:
> 
>     * no other building of the type is being in construction (unoccupied??)
> 
>     * total_count() < cnt_count * 2
> 
> 
> EDIT: third condition of course
> 
>     * stocklevel < some_target

All valid factors, some of them are already considered probably. Only thing is that in my code example I assumed that cnt_target is always initialized at the beginning according to the current formula and only increased if stocklevel is low.

**Comment by hessenfarmer** [comment]
I did some experimentation.    
1. @MarkMcWire already reduced basic_amount of the wells in his addon to 2
2. master can't handle this.
3. commenting out the whole block works, but not pretty well.
4. copying the bigger (and somewhat generic algorithm modified) bonus for basic buildings from line 6246 to line 5649 works to cope for basic building issues later on the AI build enough wells from my perspective, but we may add some dependency of stocklevel to neededness. 
5. in my code analysis i identified an error which I probably made while not being that familiar with the Ai code. 
6. in evaluating suitability of a building field for a needed building I mixed in some dependencies on stocklevel which are not related to the field and should not be considered there but rather in the determination whether we need a building. so after line 3208 there are 3 blocks defining and using the variable "current_stocklevel" these need to be deleted there nad moved to the corresponding sections in the neededness determination section (i.e. the following function https://github.com/widelands/widelands/blob/6e1c91828294e26343dd340f4f39eb8648d0ecf0/src/ai/defaultai.cc#L5340) 
7. while applying bonus and malus depending on warehouse distance we somewhat tampered the scores of kNeedsBerry sites (i.e. frisian fruit collector and probably beekeper) so they get built less often due to other buildings having more score. so we either need to give them the same bonus as the spaceconsumers, or we need to increase their priority if there are supporting buildings nearby with a factor to keep them close to them.  The latter might be better.

**Comment by tibor95** [comment]
OK, this is quite a lot of findings. So I presume that you are overtaking this.

If you want and will have a branch ready, I can do some AI training to see how things settle down...

**Comment by hessenfarmer** [comment]
originally that was not my plan. However As I introduced the main error it should be my obligation to do so.      
I assume I might ask for a review if I am ready?
Edit:
if you already had a branch for this you might just push it to either upstream or to your fork and point me there to see what I could use from it.

**Comment by tibor95** [comment]
You already have some working code on your PC, everything in your head so it is logical for you to continue...

Yes, of course I will review the pull request.

One comment generally - we/you should not overthink scoring, bonuses and so on, just provide the room for AI to find out own weights and scoring...

**Comment by tibor95** [comment]
I had a branch, but really no use for you to use it, your changes are much broader....

**Comment by hessenfarmer** [comment]
> You already have some working code on your PC, everything in your head so it is logical for you to continue...

I only had it for the original problem regarding the AI handliung of basic_amount with wells. But yes it is logical I will take this as I introduced the wrong code some time ago and I have some solution in mind already.   

> 
> Yes, of course I will review the pull request.

I am glad you have more time for discussing things lately as it is errorprone to do things alone as I just have proven.     

> 
> One comment generally - we/you should not overthink scoring, bonuses and so on, just provide the room for AI to find out own weights and scoring...          
   
that is what I always try when changing things: make the AI consider some topic in evaluation but leave room finding proper values. However in some cases the basis for evaluation was not complete or like now we forgot to apply some evaluations in a specific part. such things can't be cured by training as there isn't any check or variable to train. So my basic working / analysis method is to ask are we asking the right questions for a specific evaluation topic and not are we giving the right answers.
