### ISSUE TITLE
Ships are not shown on minimap

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5264]
Whereas roads, buildings and other things are shown immediately on the minimap if they change, ships aren't shown on the minimap at all.

![missing_ships](https://user-images.githubusercontent.com/6730556/154495117-0c776f85-ac33-4132-b31a-a982d5abedd8.jpg)

It would be very helpful if sailing ships are shown on the minimap.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25639[6e1c918@master] (Release)

**Comment by jmoerschbach** [comment]
Should there also a new map layer for that? I believe ships do not fit in any of the existing buttons/layers.
