### ISSUE TITLE
widelands_m1Arm_1.0.dmg damaged

### ISSUE THREAD

**Issue by bkmystim** [widelands/widelands#5265]
Hi guys,
I've downloaded the widelands apple silicon version now a few times, but I just can't get it to run on my M1 OSX 12.2.
After opening the dmg and copying widelands to my Apliccations folder
I always get the following message: "Widelands is damaged and cannot be opened." The dialog then suggests to move it to Trash.

Any ideas?

**Version:**
 - OS: Mac OSX Monterey 12.2 on Apple M1
 - Widelands Version: widelands_m1Arm_1.0.dmg

**Comment by hessenfarmer** [comment]
duplicate to #5202

**Comment by klaus-halfmann** [comment]
As far as I know this some Apple quarantine kicking in 
I will comment in https://github.com/widelands/widelands/issues/5202
