### ISSUE TITLE
Game crash if two different workers can became same kind of another worker.

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5274]
I did an experiment a while ago. In my tribe there are several levels for each worker, so that the basic can become normal and the normal can become advanced. Each with different experience points.

Since the development from basic_stonemason via normal_stonemason to advanced_stonemason took too long and the AI ​​constantly had empty stonemason_houses, I also entered the option for advanced_stonecutter (from the quarry) to become advanced_stonemason via experience points, too. Since the quarry is built early in the game, you have an advanced_stonecutter available pretty early on, given the time it takes to create an advanced_stonemason from a basic_stonemason.

This has led to several crashes. The stonemason house requires at least one normal_stonemason and one advanced_stonemason. Obviously normal_stonemason can be substituted with advanced_stonemason, so that two advanced_stonemason can occupy the house.

But if instead of an advanced_stonemason created by the normal_stonemason, an advanced_stonemason created by an advanced_stonecutter should occupy the house instead of the normal_stonemason, the game crashes.

btw: In the current state of development of the Europeans, the case no longer exists. Now the advanced_stonecutter can be "built" directly in the warehouse into an advanced_stonemason.

**Comment by tibor95** [comment]
I am not very familiar with that workers upgrading stuff, but general question - do you have DEBUG build, can you run with -verbose parameter and get command line output? Probably there will be nothing useful, but still

I wonder if this can be related to AI code or something else

**Comment by hessenfarmer** [comment]
I dont't believe this is AI related neither do I think this is a bug.     
I need to check whether this might be related to wrong definitions in lua instead. But this is not possible anymore as @MarkMcWire found another solution.     
if it is really not possible it isn't a bug neither as in this case it is a feature request. 

Edit: @MarkMcWire could you provide the crashing definitions

**Comment by MarkMcWire** [comment]
@hessenfarmer 

`
push_textdomain("europeans_tribe.wad", true)

dirname = path.dirname(__file__)

descriptions:new_worker_type {
    name = "europeans_stonemason_normal",
    -- TRANSLATORS: This is a worker name used in lists of workers
    descname = pgettext("europeans_worker", "Normal Stonemason"),
    animation_directory = dirname,
    icon = dirname .. "menu.png",
    vision_range = 2,
    
    experience = 24,
    becomes = "europeans_stonemason_advanced",

    programs = {
        check_rocks = {
            "findobject=attrib:rocks radius:12",
        },
        check_stone = {
            "findspace=size:any radius:12 resource:resource_stones",
        },
        cut_granite = {
            "findobject=attrib:rocks radius:12",
            "walk=object",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "callobject=shrink",
            "createware=granite",
            "return"
        },
        cut_marble = {
            "findobject=attrib:rocks radius:12",
            "walk=object",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "callobject=shrink",
            "createware=marble",
            "return"
        },
        mine_granite = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=granite",
            "return"
        },
        mine_marble = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=marble",
            "return"
        },
        mine_quartz = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=quartz",
            "return"
        },
        mine_diamond = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=diamond",
            "return"
        }
    },
    animations = {
        idle = {
            hotspot = { 7, 20 }
        },
    },
    spritesheets = {
        hacking = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            hotspot = { 10, 19 }
        },
        walk = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            directional = true,
            hotspot = { 10, 21 }
        },
        walkload = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            directional = true,
            hotspot = { 10, 23 }
        },
    }
}

pop_textdomain()


push_textdomain("europeans_tribe.wad", true)

dirname = path.dirname(__file__)

descriptions:new_worker_type {
    name = "europeans_stonecutter_advanced",
    -- TRANSLATORS: This is a worker name used in lists of workers
    descname = pgettext("europeans_worker", "Advanced Stonecutter"),
    animation_directory = dirname,
    icon = dirname .. "menu.png",
    vision_range = 2,

    experience = 12,
    becomes = "europeans_stonemason_advanced",
        
    programs = {
        check_rocks = {
            "findobject=attrib:rocks radius:12",
        },
        check_stone = {
            "findspace=size:any radius:12 resource:resource_stones",
        },
        cut_granite = {
            "findobject=attrib:rocks radius:12",
            "walk=object",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "callobject=shrink",
            "createware=granite",
            "return"
        },
        cut_marble = {
            "findobject=attrib:rocks radius:12",
            "walk=object",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "callobject=shrink",
            "createware=marble",
            "return"
        },
        mine_granite = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=granite",
            "return"
        },
        mine_marble = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=marble",
            "return"
        },
        mine_quartz = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=quartz",
            "return"
        },
        mine_diamond = {
            "findspace=size:any radius:12 resource:resource_stones",
            "walk=coords",
            "playsound=sound/stonecutting/stonecutter priority:50% allow_multiple",
            "animate=hacking duration:12s",
            "mine=resource_stones radius:1",
            "createware=diamond",
            "return"
        }
    },

    spritesheets = {
        idle = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            hotspot = { 9, 23 }
        },
        hacking = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            hotspot = { 8, 23 }
        },
        walk = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            directional = true,
            hotspot = { 9, 22 }
        },
        walkload = {
            fps = 10,
            frames = 10,
            rows = 4,
            columns = 3,
            directional = true,
            hotspot = { 8, 25 }
        },
    }
}

pop_textdomain()

`

**Comment by hessenfarmer** [comment]
I successfully used 2 advanced stonemason created by 2 different careers in the same stonemasons house so I would close this bug
