### ISSUE TITLE
AI does not expand properly - problem with basic economy

### ISSUE THREAD

**Issue by tibor95** [widelands/widelands#5283]
**Describe the bug**
AI players does not grow properly, f.e. wood hardeners are not build, logs shows something like that:

`[00:00:03.943 game] INFO: AI  1: Player has not all buildings for basic economy yet (12 missing), but enemy is nearby, so quitting the mode at 000:00:03`

What is a nonsense,

**To Reproduce**
1. Run game with --verbose mode
2. Start the game with AI players, be sure that they are far from each other
3. Watch logs for above log
4. Watch the expansion of players

**Expected behavior**
Such log should not be there

**Version:**
 - current master

**Additional context**

**Comment by tibor95** [comment]
I think it goes to last_time_seen in EnemySiteObserver. It seems it is now set to 0, that is evaluated as we just seen the enemy. Should be invalid or very big number. I think there were changes few commits in this regard...

**Comment by hessenfarmer** [comment]
good catch we removed the overriding of the default init value in the constructor of the object for satisfying clang tidy so we now need to properly define the init value in the class definition, as you already did.
