### ISSUE TITLE
Does not install with NLS disabled

### ISSUE THREAD

**Issue by AMDmi3** [widelands/widelands#5298]
**Describe the bug**
When configured with `-DOPTION_BUILD_TRANSLATIONS=OFF`, install target fails:

```
CMake Error at cmake_install.cmake:151 (file):
  file INSTALL cannot find
  "/wrkdirs/usr/ports/games/widelands/work/.build/locale": No such file or
  directory.
```
while with the enabled option it's:
```
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale/el
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale/el/LC_MESSAGES
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale/el/LC_MESSAGES/maps.mo
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale/el/LC_MESSAGES/scenario_tutorial03_seafaring.wmf.mo
-- Installing: /wrkdirs/usr/ports/games/widelands/work/stage/usr/local/share/widelands/locale/el/LC_MESSAGES/world.mo
```
it looks like it tries to install files which are not generated.

Additionally, it seems to require Gettext regardless of the option setting.

**Expected behavior**
Installation should pass.

**Version:**
 - OS: FreeBSD 13.0
 - Widelands Version: 1.0

**Comment by Noordfrees** [comment]
This could be fixed by surrounding the respective `install` command with an `if(OPTION_BUILD_TRANSLATIONS)`, but I wonder if having an option to build translations even makes sense. Building them takes so little time compared to compiling the source code that skipping them doesn't offer any benefits in my opinion. Would anyone miss this option if it's removed and translations are always built?

**Comment by AMDmi3** [comment]
Well i18n files take noticeable amount of disk space, which can be gigabytes overall for an average desktop system, while providing no or almost no benefit since a person usually needs no more than one translation, and not all of them. That's why `localepurge` was invented. So I'd prefer this option to work properly, e.g. toggle both dependency on gettext and translation files building/installation. If the option is removed, I'd prefer translation files to be installed into standard location, e.g. `PREFIX/share/locale`, where they can be handled by systemwide mechanisms like the mentioned localepurge.

**Comment by AMDmi3** [comment]
Works for me, thank you!
