### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5303]
Hi, this is not a bug but rather a question to the developers.
I'm trying to save some data from the game for my scientific project (Building's inputs outputs wares logistic data etc..).
Can someone please tell me how to map "descriptionindex" to the actual ware name ? 
It should be done somewhere in the source code but i can’t find it.
Sorry for putting this here but i didn’t know where else to ask such a question.

**Comment by Noordfrees** [comment]
```c++
egbase.descriptions().get_ware_descr(index)->name()
```
- `egbase`: Many functions get a `Game` or `EditorGameBase` reference as parameter. if not, many map object or Player instances and other objects also have an `egbase()` or `game()` function that returns it.  So it should nearly always be possible to get this reference though the exact way depends on which function you're working in.
- `get_ware_descr`: Depending on what type of object you're looking at, this may also be `get_worker_descr`, `get_building_descr` etc
- `index`: the `DescriptionIndex` to look up

The best place for questions is the [forum](https://www.widelands.org/forum/forum/16/) or alternatievly the [discussions](https://github.com/widelands/widelands/discussions/categories/q-a) page, but we're happy to help anywhere :)

**Comment by Ahmad-fadl** [comment]
this egbase.descriptions().get_ware_descr(index)->name() worked. Thanks
