### ISSUE TITLE
Screen is flickering green after startup

### ISSUE THREAD

**Issue by bgruschko** [widelands/widelands#5322]
After startup the GUI is flickering with green stripes. 

**Steps to reproduce the behavior:**
1. Start the game

**Screenshot:**
![screen](https://user-images.githubusercontent.com/7606982/159666177-a9aa4049-6492-43c6-b0b6-fc67eec9a5fb.png)

**Version:**
 - OS: Windos 10 with latest Nvidia driver pack
 - Widelands Version: ["Release 1.0", "master branch"]

**Comment by frankystone** [comment]
Can you please provide the `stdout.txt` which should be in the same folder where widelands is installed?

**Comment by bgruschko** [comment]
I couldn't find an stdout.txt in the installation directory. Starting from console and properly exiting widelands (tooks me a couple of tries with the flickering) also didn't generate one:
![screen2](https://user-images.githubusercontent.com/7606982/159874708-fe3740bb-560e-4db0-a7c7-5388f52014a9.png)

**Comment by frankystone** [comment]
Can you try: `widelands.exe > log.txt` when starting from a console?

That should generate the file `log.txt`. I am not a  Windows user so i just follow https://www.widelands.org/wiki/Technical%20Faq/#how-do-i-get-log-output-in-windows-for-debugging See also the next chapter there.

**Comment by bgruschko** [comment]
I found a stdout.txt in ~/.widelands:

[stdout.txt](https://github.com/widelands/widelands/files/8340016/stdout.txt)

**Comment by frankystone** [comment]
For comparison with my video:

Your output | My output
------------------ | --------------
Graphics: Try to set Videomode 800x600 |                           Graphics: Try to set Videomode 1600x900
Graphics: OpenGL: Version "4.6.0 - Build 27.20.100.8280" |         Graphics: OpenGL: Version "4.6.0 NVIDIA 510.54"
Graphics: SDL_GL_RED_SIZE is 10 |                                  Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 10 |                                Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 10 |                                 Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 2 |                                 Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 32 |                               Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1 |                               Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 24 |                                Graphics: SDL_GL_DEPTH_SIZE is 24
Graphics: SDL_GL_STENCIL_SIZE is 8 |                               Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 0 |                             Graphics: SDL_GL_ACCUM_RED_SIZE is 16
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0 |                           Graphics: SDL_GL_ACCUM_GREEN_SIZE is 16
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0 |                            Graphics: SDL_GL_ACCUM_BLUE_SIZE is 16
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0 |                           Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 16
Graphics: SDL_GL_STEREO is 0 |                                     Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0 |                         Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0 |                         Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1 |                         Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2 |                      Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1 |                      Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0 |                              Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0 |                       Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0 |                 Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0 |                   Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled |                       Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 16384 |                        Graphics: OpenGL: Max texture size: 32768
Graphics: OpenGL: ShadingLanguage: "4.60 - Build 27.20.100.8280" | Graphics: OpenGL: ShadingLanguage: "4.60 NVIDIA"
**** GRAPHICS REPORT **** |                                        **** GRAPHICS REPORT ****
VIDEO DRIVER windows |                                             VIDEO DRIVER GLVND x11
Display #0: 1536x960 @ 59hz SDL_PIXELFORMAT_RGB888 |               Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888 

The suspicious ones are the `SDL_GL_ACCUM_*_SIZE` or the `Max texture size: 16384` but i am no graphics expert. You may have to adjust the nvidia settings or wait for someone with more knowledge :-(

**Comment by hessenfarmer** [comment]
I believe this issue is not a Widelands issue but a driver issue.       
With my Geforce GTX70 it works well in windows. Maybe deinstalling and reinstalling the driver from Windows might help. 
I installed the driver from windows and it has a version beginning with 27.21....... this corresponds to 510.64 I believe.  So may be the driver is outdated or corrupted. 
In any case I don't think this to be a widelands issue.

**Comment by hessenfarmer** [comment]
@bgruschko have you been able to solve the issue, so we can close this?

**Comment by bgruschko** [comment]
@hessenfarmer: No I couldn't, but I strongly suspect that it has something to do with opengl drivers. I'll close the bug since it is not really a widelands bug. If I'll find a a solution I'll post it here in case someone else should happen to have the same problem.

**Comment by hessenfarmer** [comment]
Well if I / we might be of any help let us know. your suspection is reasonable. BTW which graphics card are you using?

**Comment by TheRaven500** [comment]
Same problem here! Windows 11 with hybrid graphic (Intel UHD and Nvidia GF GTX 1650 Ti).
My Solution: Looks like the Intel UHD has problems with Widelands. So switch the graphic to the Nvidia and it works in my case. Open the windows menu, search for "graphic" and open it. Add widelands as a new "Desktop-App" and set in the options nvidia as preferred graphic card.
