### ISSUE TITLE
Friends in Need - cannot load game - Unknown worker 'frisians_diker'

### ISSUE THREAD

**Issue by rwblyth** [widelands/widelands#5346]
Hi, I am part way through Friends in Need and cannot load my game after updating Widelands. The error message says, "Unknown worker 'frisians_diker'". 

**Steps to reproduce**
1. With any saved game from Friends in Need (even one saved at the very start of the level), saved before updating Widelands today 2nd April
2. Load the scenario
3. Game tries to load but fails with the error message in the attached screenshot.

**Expected behavior**
Game should be loaded

**Screenshots**
![Screenshot from 2022-04-02 17-52-24](https://user-images.githubusercontent.com/2817741/161390967-7ba20876-e797-4993-829b-03eaf555757c.png)

**Version:**
 - OS: Ubuntu 20.04.4 LTS
 - Widelands Version: 1.1~bzr10232-202204020331 (Release)

**Additional context**
Happy to provide the saved file if that is useful (although I can't find the saved game - no ~/.widelands directory - please advise where they go)

**Comment by hessenfarmer** [comment]
the savegame really would help. to find it maybe just search for files of type .wgf.   
Furthermore it would help to know with which version the save had been saved.

**Comment by rwblyth** [comment]
The search worked - they are saved to `~/.local/share/widelands/save` - attached the first save from this scenario ("new-land.wgf") and the most recent ("new-port.wgf") in the attached zip. Both of them get the same error on loading.

Looking at the update log I think I was running 1.1~bzr10206-202203182002 for both of these.

[widelands-5346-saved-games.zip](https://github.com/widelands/widelands/files/8405358/widelands-5346-saved-games.zip)

**Comment by Noordfrees** [comment]
Yet another load order bug, will investigate…
