### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5368]
Hi,
This is just a question to the developers or to someone who understands the logic of the game.
A Productionsite has the attribute "inputqueu" and an inputqueu has (1- get_max_size()  2- get_max_fill() 3- get_filled())  where :
get_max_size() returns the capacity of the building regarding this ware.
get_filled() the currently existing amount of this ware.
get_max_fill() returns the maximum amount of wares or workers which SHOULD be stored here.
so can I consider this as a ware order? if not is there any attribute that refers to wares that has been ordered by this building? (because when playing the game there are always resources that are currently in the building and resources that have been ordered).
there is actually an attribute "[working_positions] " in a productionsite but it only holds worker_orders but not ware_orders.
I would be glad if anyone has any idea where these wares' orders are saved.

**Comment by Noordfrees** [comment]
An "order" for a ware or worker is represented by the **`Request`** class. An `InputQueue` has a `request_` attribute which it frequently updates with information about how many more items the queue wants. The `Request` instance tracks how many items have been sent and how many are lacking, and an `Economy` instance regularly tries to satisfy open requests and handles assignment of available supplies to requests.

**Comment by Ahmad-fadl** [comment]
Ah ok i see.
I'll write a getter function to access The request from inside the building.
Thanks.
