### ISSUE TITLE
Rev-Detects broken and game crash with line 'findspace=size:any radius:6 avoid:field saplingsearches:7':

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5379]
I've cloned a fresh copy of this repo and compiled it. Regardless for release or debug, i get this info

`This is Widelands Version 1.1~error-REVDETECT-BROKEN-PLEASE-REPORT-THIS (Release)`

I cannot start a game, because of:

`[00:00:05.251 real] ERROR: ##############################
[00:00:05.251 real] ERROR:   FATAL EXCEPTION: game class: Error while loading tribe 'amazons': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] tribe amazons: Failed adding worker 'amazons_jungle_preserver': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] amazons_jungle_master: Error in worker program plant: Error reading line 'findspace=size:any radius:6 avoid:field saplingsearches:7': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] [string "add
[00:00:05.251 real] ERROR: ##############################
`

**Comment by Noordfrees** [comment]
Those are two completely unrelated errors. 
- Regarding the second one (unable to start the game), please disable the Europeans add-on and try if it still happens.
- Regarding the revdetect, please paste the output of `./utils/detect_revision.py`

**Comment by MarkMcWire** [comment]
> Those are two completely unrelated errors.
> 
> * Regarding the second one (unable to start the game), please disable the Europeans add-on and try if it still happens.
> * Regarding the revdetect, please paste the output of `./utils/detect_revision.py`

2.) Error occurs also without any addon
1.)

`python detect_revision.py
1.1~git25737[518bb83@master]
`

**Comment by Noordfrees** [comment]
Just to be sure, by disabling add-ons I mean you have to untick the add-ons' checkboxes in the add-ons manager – if the Europeans tribe is available in the game setup screen and you just don't use it for any player, then the add-on itself is still enabled.

Regarding the rev detect, please delete the build dir and paste the complete output of a fresh compilation. Maybe the CMake status messages contain a hint why the script fails when invoked from CMake but succeeds when run directly.

**Comment by MarkMcWire** [comment]
I disabled the checkboxes, but error occurs regardless. If I delete the entire addons folder, than a new game starts.

If I reinstall and activate the addon from repository, the error occurs again. But with reference to amazon_jungle_preserver.

If I start entire new game with only barbarians tribe, error references to barbarians_ranger. 

> [00:11:29.427 real] ERROR: ##############################
> [00:11:29.427 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'barbarians': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] tribe barbarians: Failed adding worker 'barbarians_ranger': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] barbarians_ranger: Error in worker program plant: Error reading line 'findspace=size:any radius:5 avoid:field saplingsearches:5': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] [string "addons/europeans_tribe.wad/immovables/ryefiel..."]:5: attempt to index a nil value 
> [00:11:29.427 real] ERROR: ##############################

If I start entire new game with only empire tribe, error references to empire_forester. 

> [00:12:33.459 real] ERROR: ##############################
> [00:12:33.459 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'empire': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] tribe empire: Failed adding worker 'empire_forester': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] empire_forester: Error in worker program plant: Error reading line 'findspace=size:any radius:5 avoid:field saplingsearches:8': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] [string "addons/europeans_tribe.wad/immovables/ryefiel..."]:5: attempt to index a nil value (global 'des
> [00:12:33.459 real] ERROR: ##############################

And if I start entire new game with only atlanteans tribe, error references to atlantean_forester.

> [00:00:18.210 real] ERROR: ##############################
> [00:00:18.210 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'atlanteans': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] tribe atlanteans: Failed adding worker 'atlanteans_forester': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] atlanteans_forester: Error in worker program plant: Error reading line 'findspace=size:any radius:5 avoid:field saplingsearches:12': [/home/linuxmint/Git/widelands/src/scripting/lua_errors.cc:21] [string "addons/europeans_tribe.wad/immovables/ryefiel..."]:5: attempt to index a nil v
> [00:00:18.210 real] ERROR: ##############################

Thanks to the longer error description, it seems my rye field causes the problem.

**Comment by MarkMcWire** [comment]
Problem #2 solved. I replaced 'descriptions:' with 'wl.Descriptions():' in rye field init.lua.

**Comment by hessenfarmer** [comment]
> Problem #2 solved. I replaced 'descriptions:' with 'wl.Descriptions():' in rye field init.lua.

you need to do this in all of the init.lua files of your addon to avoid such errors.

**Comment by MarkMcWire** [comment]
> wl.Descriptions()

Done with Update 2.4.9.

**Comment by MarkMcWire** [comment]
> Regarding the rev detect, please delete the build dir and paste the complete output of a fresh compilation. Maybe the CMake status messages contain a hint why the script fails when invoked from CMake but succeeds when run directly.

```
linuxmint@linuxmint-NHx0ERQ-EPS:~/Git/widelands$ sudo ./compile.sh
 
###########################################################
#     Script to simplify the compilation of Widelands     #
###########################################################
 
Using 15 core(s).

Using compiler: system default
 
Using cross compile unit optimization if available.
 
A complete build will be created.
You can use -w or --no-website to omit building and
linking website-related executables.
 
Translations will be built.
You can use -t or --no-translations to omit building them.
 
Tests will be built.
You can use -s or --skip-tests to omit building them.
 
###########################################################
 
Creating a Debug build. Use -r to create a Release build.
 
Will build with AddressSanitizer.
https://clang.llvm.org/docs/AddressSanitizer.html
You can use -a or --no-asan to switch it off.
Will build without ThreadSanitizer.
You can use +m or --with-tsan to switch it on.
 
Basic XDG Base Directory Specification will be used on Linux
if no existing $HOME/.widelands folder is found.
The widelands user data can be found in $XDG_DATA_HOME/widelands
and defaults to $HOME/.local/share/widelands.
The widelands user configuration can be found in $XDG_CONFIG_HOME/widelands
and defaults to $HOME/.config/widelands.
See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
for more information.
 
 
###########################################################
 
Call 'compile.sh -h' or 'compile.sh --help' for help.

For instructions on how to adjust options and build with
CMake, please take a look at
https://www.widelands.org/wiki/BuildingWidelands/.
 
###########################################################
 
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake version 3.16.3
-- Building with XDG support
-- Picking up default CXX flags:
    - CMAKE_CXX_FLAGS=''
    - CMAKE_CXX_FLAGS_RELEASE='-O3 -DNDEBUG'
    - CMAKE_CXX_FLAGS_DEBUG='-g'
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2.so (found version "2.0.10") 
-- Found SDL2main: /usr/lib/x86_64-linux-gnu/libSDL2main.a (found version "2.0.10") 
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.5") 
-- Found SDL2_mixer: /usr/lib/x86_64-linux-gnu/libSDL2_mixer.so (found version "2.0.4") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.15") 
-- Found the following ICU libraries:
--   uc (required)
--   dt (required)
-- Found ICU: /usr/include (found version "66.1") 
-- Found GLEW: /usr/include (found version "2.1.0") 
-- Found Asio in '/usr/include'.
-- Not using ThreadSanitizer.
-- Using AddressSanitizer https://clang.llvm.org/docs/AddressSanitizer.html
-- Adding linker flags for GLVND.
fatal: unsafe repository ('/home/linuxmint/Git/widelands' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/linuxmint/Git/widelands
-- Version of Widelands Build is 1.1~error-REVDETECT-BROKEN-PLEASE-REPORT-THIS(Debug)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen not found, disabling 'make doc'
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'minizip'
--   No package 'minizip' found
-- Using embedded minizip libraries
-- Link io_filesystem with third_party_minizip
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linuxmint/Git/widelands/build
```

**Comment by matthiakl** [comment]
```
fatal: unsafe repository ('/home/linuxmint/Git/widelands' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/linuxmint/Git/widelands
```
I guess `linuxmint` is not your current username? You should login as this user, clone the repo into your own home directory or use the provided git command.

**Comment by MarkMcWire** [comment]
> ```
> fatal: unsafe repository ('/home/linuxmint/Git/widelands' is owned by someone else)
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /home/linuxmint/Git/widelands
> ```
> 
> I guess `linuxmint` is not your current username? You should login as this user, clone the repo into your own home directory or use the provided git command.

Your guess is wrong. Its my current username. However, the folder has been restored from a backup after my old pc was gone and I buyed a new one. And obviously the access rights are set incorrectly.

**Comment by Noordfrees** [comment]
> And obviously the access rights are set incorrectly.

Then that's probably the cause of the problem. The compile script should never (need to) be invoked with `sudo`! 
Please call 
```bash
sudo chown -R linuxmint /path/to/folder
```
on the folder with the wrong rights to adjust ownership, then try to compile again (**without** `sudo`).

**Comment by hessenfarmer** [comment]
can this be closed?
