### ISSUE TITLE
Daily PPA Failing to Build

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5387]
Re https://github.com/widelands/widelands/pull/5359#issuecomment-1114222800 & https://github.com/widelands/widelands/pull/5383

As of 0ce5fb604e9bf884b0c4956500b61282cf6ae869 the [daily PPA](https://code.launchpad.net/~widelands-dev/+recipe/widelands-daily) is still failing. The build logs seem to be unavailable currently.

@matthiakl @andy5995 

---

By the way, the PPA also doesn't use Debian's minizip library yet:
https://github.com/widelands/widelands/blob/0ce5fb604e9bf884b0c4956500b61282cf6ae869/debian/control#L12-L14
(oldest we now support is 16.04)

**Comment by matthiakl** [comment]
[amd64 build of widelands 2:1.1~bzr10260-202205040401\~ubuntu18.04.1 in ubuntu bionic RELEASE](https://code.launchpad.net/~widelands-dev/+archive/ubuntu/widelands-daily/+build/23607664) succeeded, so I am not sure if this is really another bug in the code or something related to launchpad. Also the missing logfiles look like the builds did not properly started. 
Do you have the possibility to retry a build?

**Comment by Noordfrees** [comment]
Yes but it usually takes some time until it starts. I triggered just one new build for now: https://code.launchpad.net/~widelands-dev/+archive/ubuntu/widelands-daily/+build/23607678

**Comment by matthiakl** [comment]
Same again: now kinetic builts successfully. Could it be a problem that the repo is too full with old packages? (20GB/8GB) Maybe launchpad only allows to store a single package per build matrix in this case.

> (oldest we now support is 16.04)

The PPA description still lists trusty as published platform. Is this outdated?

**Comment by Noordfrees** [comment]
Okay, seems to have just been a transient LP error then. 
The repo size limit has been exceeded since about forever :wink: we never had any problems with it though.
We'll know for certain after the next build…

Trusty is listed – along with a lot of other EOL releases – because the PPA contains a package that installs there, but they're no longer kept up to date. The official description text says "Packages are available for all currently supported Ubuntu releases."

**Comment by Noordfrees** [comment]
Failing again:
```
CMake Error at cmake/WlFunctions.cmake:81 (target_compile_options):
  target_compile_options called with invalid arguments
Call Stack (most recent call first):
  cmake/WlFunctions.cmake:232 (_common_compile_tasks)
  src/base/CMakeLists.txt:3 (wl_library)
```
(many more similar traces…)
https://launchpadlibrarian.net/600067122/buildlog_ubuntu-impish-amd64.widelands_2%3A1.1~bzr10261-202205060716~ubuntu21.10.1_BUILDING.txt.gz
Perhaps related to system-wide minizip?

**Comment by andy5995** [comment]
One unrelated and probably minor thing I noticed from that log is that the buildtype is specified twice in the cmake args. Set to 'None' in one place and 'Release' in the other.


>dh_auto_configure: error: cd obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DWL_INSTALL_BASEDIR=/usr/share/games/widelands -DWL_INSTALL_DATADIR=/usr/share/games/widelands/data -DCMAKE_INSTALL_PREFIX=/usr -DOPTION_USE_GLBINDING:BOOL=OFF -DOPTION_ASAN=OFF -DCMAKE_BUILD_TYPE=Release .. returned exit code 1

But to (hopefully) fix the actual problem with the errors, I opened https://github.com/widelands/widelands/pull/5396
