### ISSUE TITLE
cmake failure with system wide minizip

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5397]
**Describe the bug**
cmake fails if libminizip-dev is installed on my system. Not sure if caused by some customisation quirk or version dependent…

**To Reproduce**

0. Make sure compiling Widelands works
1. Install libminizip-dev
2. Create and enter new build directory
3. Call `cmake <widelands-srcdir>`

**Expected behavior**
cmake should generate build files without error.

**Version:**
 - OS: antix/Debian buster with some backports
 - Widelands Version: 1.1~git25742[7ab454f@master]

**Additional context**
Minizip version reported by cmake is 1.2.8, but dpkg version is 1.1-8

[cmake_stdout_stderr.txt](https://github.com/widelands/widelands/files/8638826/cmake_stdout_stderr.txt)
[CMakeOutput.log.txt](https://github.com/widelands/widelands/files/8638825/CMakeOutput.log.txt)
[CMakeError.log.txt](https://github.com/widelands/widelands/files/8638824/CMakeError.log.txt)

**Comment by matthiakl** [comment]
This should have been fixed by #5396. Can you please check again?

**Comment by tothxa** [comment]
Indeed, it works now. Sorry, it wasn't clear to me from the other bug and the PR discussion that it was the same problem. Thank you.
