### ISSUE TITLE
`NOCOM` Comments in AI Code

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5405]
Current master has two `NOCOM` annotations in it:
https://github.com/widelands/widelands/blob/b8bea72df4348cea4c8ee6bccb0bdbb107759434/src/ai/defaultai.h#L189
https://github.com/widelands/widelands/blob/b8bea72df4348cea4c8ee6bccb0bdbb107759434/src/ai/ai_help_structs.h#L417

The keyword `NOCOM` is used to annotate development debugging statements that are really, really not meant to belong in master. 

Since it here refers to some commented-out lines, all related code should probably be removed. 
(If this is meant to signify "we don't need this right now but maybe again in the future", don't forget the code will remain in the Git history forever so that it can be safely deleted.)

**Comment by tibor95** [comment]
Yes, should be OK to remove
