### ISSUE TITLE
testsuite frequently failing with Make install / uninstall task

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5412]
for some latest builds our ubuntu 20 debug builds are failing in the make instal uninstall task

**Comment by matthiakl** [comment]
I guess this is caused by using parallel make during uninstall (@andy5995 added it in https://github.com/widelands/widelands/pull/5358/commits/9b9cd8ced7c1d601cf3c26b128a6f52394c415f7 (#5358)). Then multiple processes might try to remove a child and a parent directory at the same time or cause other race conditions.

**Comment by hessenfarmer** [comment]
I have no glue what is causing this. However it worked some days ago and now it doesn't master is failing since https://github.com/widelands/widelands/commit/b714bc04c2a479173c80c0bcc702380fe102b901 while the Ci was green before this merge. So my best gues would be something might have changed in the CI environment meanwhile. 
Anyhow guessing around here might not be the correct method, so I propose to just revert the changes that introduced the Install / uninstall until the root cause has been detected. to get a working CI again for our prerelease dev jobs

**Comment by andy5995** [comment]
> I propose to just revert the changes that introduced the Install / uninstall until the root cause has been detected. to get a working CI again for our prerelease dev jobs

I agree. I've pushed a change to https://github.com/widelands/widelands/pull/5413

It only disables the uninstall; the install should be fine.

**Comment by hessenfarmer** [comment]
well going through the logs it seems that in debug configuration it is trying to remove the local/./ directory which it doesn not in release config and which it previously did not for the debug build as well. 
correctly it would delete local instead directly
