### ISSUE TITLE
Are the WARNINGS about barrack, well and hunters hut really necessary?

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5420]
```
[00:04:26.694 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of barracks building. This is the building that produces the tribe's 'soldier' worker.
[00:04:26.694 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of well at the most. This is the building that produces the ware 'water', has no inputs and mines the 'resource_water'.
[00:04:26.694 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of hunter's building at the most. Hunters are buildings that collect any bob from the map.

```
Are these warnings even needed or can't we just turn them off to make the debug text a bit clearer and point to real errors?

Especially since the warnings for buildings belonging to fishermen, stonecutters, lumberjacks or foresters are obviously not necessary.

The background is also that I would like to remove my hunters from the tribe and instead want to use the piggery as a meat producer.

**Comment by tibor95** [comment]
They indicate that AI might not work properly. At the end they are just warnings, not errors.
AI is trying to regulate stocks of meat and water via regulating particular types of buildings. There is dedicated code and logic for this. If particular types of buildings does not exist - this code and logic will not have any effect. I do not say it will lead to disaster, but AI is built on presumption that these building are so specific that they need this dedicated logic
Barracks is the same...

It is about three lines of log - they do not repeat so I do not see big problem here

**Comment by hessenfarmer** [comment]
well, the warnings are already different.      
and as Tibor commented they indicate that the AI might not work properly.       
For the barracks it is essential that there exists exactly one building, that recruits new soldiers.     
for hunters and wells the warning states " .. one building at the most" which means we can have 0 or 1 but not more of them, cause the AI can't handle more then 1 building.

**Comment by hessenfarmer** [comment]
@MarkMcWire if this answers the question please close the issue
