### ISSUE TITLE
hiding priority slider crashes game

### ISSUE THREAD

**Issue by jopewe** [widelands/widelands#5425]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Upgrading a building and changing building material priorities. Trying to use Ctrl + click to increase priority crashes the game.

**To Reproduce**
1. Upgrade a building
2. Click on the building again
3. hold ctrl and click on the arrow to increase the priority
4. Game crashes
5. Error: src/wui/inputqueuedisplay.cc:563: void InputQueueDisplay::set_collapsed(bool): Zusicherung »collapsed_ != c« nicht erfüllt.

**Expected behavior**
Not crash.

**Screenshots**

**Version:**
 - OS: Devuan GNU/Linux
 - Widelands Version: commit b2addfc83a51e1f0d27a5a33831e8a439a077b20 (master as of 20220515

**Additional context**

**Comment by Noordfrees** [comment]
Thanks for reporting :) 
I opened a PR to fix this: #5426

**Comment by jopewe** [comment]
I'm testing the PR.

**Comment by jopewe** [comment]
Fix was successful from my point of view - can I approve the PR, or do I have to be a proper project member?
