### ISSUE TITLE
Minimum distance between warehouses

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/widelands#5427]
The AI often has a habit of building warehouses next to each other when there is space. I noticed this in 3 out of 5 test games with the Europeans (version 2.8.x).

Maybe some kind of distance penalty should be built in the AI Code to prevent the AI from building one warehouse too close to another. Because that reduces the benefit and produces traffic jams. The minimum distance should be 1/3 or better 1/2 of the biggest distance from headquarter to the border of the currently available (conquered) area.

And if we want to make the code particularly good, a warehouse should always be covered by at least two military buildings, so that it won't be destroyed if one of the two buildings is captured by the enemy.

#AI

**Comment by hessenfarmer** [comment]
should have been fixed / addressed by #5229 
which version did you use?

**Comment by MarkMcWire** [comment]
> should have been fixed / addressed by #5229 which version did you use?

I use latest master from this repository. The problem occurs not everytime. Sometimes the AI build warehouses next to each other without a reason.

**Comment by hessenfarmer** [comment]
Well, currently we have a distance_malus value which is a measure for distance of a field to the nearest warehouse. It is used to increase the priority of a warehouse on more distant fields.  However regions near the border are discouraged, which might lead to little spots left to build a needed warehouse.      
can't tell without replays or at least a savegame. As you made the observation with your addon a confirmation with replay of this behaviour with a genuine tribeand the addon disabled  would be helpful.

**Comment by tibor95** [comment]
Also do not forget - when second warehouse is built (construction starts) the territory is as is. After some time when you look at the map and conclude that it was not well placed...

**Comment by MarkMcWire** [comment]
The problem is destinct to my European tribe addons. So I close this topic and maybe I can make a solution myself.
