### ISSUE TITLE
Mysterious SIGSEGV

### ISSUE THREAD

**Issue by epixinvites** [widelands/widelands#5431]
**Describe the bug**
Program SIGSEGVs without warning

**To Reproduce**
I was playing the economy tutorial until the point where I was supposed to check the encyclopedia and see which wares I need to produce a soldier.

**Version:**
 - OS: Arch Linux (5.17.9-zen1-1-zen)
 - Widelands Version: Commit `7c7565278d858656f0807b1599eff665f6367d84`

**Additional context**
Backtrace retrieved via coredumpctl: https://termbin.com/nj1a (<- This paste expires after a month, [this](https://0bin.net/paste/qZSnR9Qt#NiFn07rBsMUUV64dgKA7LjYsau15tLlzPUQPQzEcyY1) does not expire)

**Comment by Noordfrees** [comment]
Judged from the backtrace, I believe this is actually another aspect of #5474 and was fixed by #5475
