### ISSUE TITLE
mysterious segfault in notifications_test

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5433]
In the Appveyor CI the Notifications test is failing for x64 builds.  
I can reproduce this in my own MSYS installation. but only on a clean build if I build a delta the test is working. 
Furthermore it is not failing in the Github CI using MSYS.

**Comment by matthiakl** [comment]
Interestingly I cannot reproduce it on a local setup. My guess now is, that some cmake/gcc internals are slightly different on the systems. I currently don't have much time, but trying some things on [5433-appveyor_segfault](https://github.com/widelands/widelands/tree/5433-appveyor_segfault) branch.

**Comment by matthiakl** [comment]
> In the Appveyor CI the Notifications test is failing for x64 builds.

Since the latest update, all configurations fail with the same error...

**Comment by hessenfarmer** [comment]
This is hard to track down as it is only happening sometimes in my own Msys2 environment. and never in the github environment

**Comment by Noordfrees** [comment]
Can you try to run the tests in a debugger and get a backtrace for the segfault?

**Comment by matthiakl** [comment]
The problem:
```
Reading symbols from notifications_test.exe...
Starting program: C:\projects\widelands\build\src\notifications\test\notifications_test.exe 
Adding testcase SimpleTest
Log output will be written to: C:\projects\widelands\build\src\notifications\test\stdout.txt
Program received signal SIGSEGV, Segmentation fault.
0x00007ff726577295 in std::ostream::flush() ()
#0  0x00007ff726577295 in std::ostream::flush() ()
#1  0x00007ff7265ba5fc in std::ios_base::Init::~Init() ()
#2  0x00007ffe5100a8cb in msvcrt!_initterm_e ()
   from C:\Windows\System32\msvcrt.dll
#3  0x00007ff7263c14ad in __tmainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:332
#4  0x00007ff7263c14c6 in WinMainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
A debugging session is active.
	Inferior 1 [process 3904] will be killed.
```
The solution:
```
-TEST_EXECUTABLE(notifications, true)
+TEST_EXECUTABLE(notifications, false)
```
Something in this test causes the windows runtime to screw up the std::cout redirection used for logging. When someone finds this cause, we can re-enable the logging.

**Comment by matthiakl** [comment]
Just for reference the method I used to obtain the trace:
- Install gdb (mingw-w64-%MINGWSUFFIX%-gdb)
- Add to CMakeLists.txt where the problematic binary is defined (src/notifications/test/CMakeLists.txt)
```
add_custom_target(notifications_test_gdb
    COMMAND gdb -ex r -ex bt -ex q notifications_test.exe
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    DEPENDS notifications_test
    USES_TERMINAL
  )
# Run it before the normal testsuite
add_dependencies(wl_tests notifications_test_gdb)
```
