### ISSUE TITLE
Crash after returning to game / campaign announcement has been displayed for several minutes

### ISSUE THREAD

**Issue by jopewe** [widelands/widelands#5434]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
After an announcement (campaign information / next tasks) pops up and the game is ignored for a while, the game crashed when closing (click "ok") the announcement.
It was present in the last few builds as well, I was not sure of how often this actually happens - now I feel quite confident it is mostly reproducible.

**To Reproduce**
1. Start a campaign
2. so stuff
3. Announcement pops up
4. wait a few 10s of minutes (like maybe 20 or so)
5. dismiss announcement, click ok
6. game crashes: widelands: ./src/graphic/texture.cc:161: virtual Texture::~Texture(): assertion »is_initializer_thread()« not fulfilled

**Expected behavior**
not crash.

**Screenshots**

**Version:**
 - OS: Devuan Daedalus (current, 2022-05-27)
 - Widelands Version: 20b0953a10742f5cab5d35cd98412f385a4e8bbf

**Comment by Noordfrees** [comment]
Looks like #5403

**Comment by jopewe** [comment]
Yes, duplicate. Somehow I missed the other one.
