### ISSUE TITLE
Stuck at "Game ending - please wait" when loading a game from inside a game

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5453]
**Describe the bug**
Since #5421, loading a game directly from a game is broken. When the game to load is selected and OK is clicked the Widelands window is grayed out and the "Game ending - please wait" message is shown, but it never goes away. The controls of the game loading dialog underneath the graying out still respond to mouse clicks and key presses. If cancel is clicked, the loading dialog goes away, and the stopped game is visible under the graying out, but it does not respond to the mouse and the keyboard. If the window is closed by the window manager, then the previous game finally ends, the new one is loaded, then it exits immediately (with a segfault, if the dialog was closed).

**To Reproduce**
1. Start a game
2. Select "Load Game" (ctrl-L) from the main menu
3. Select a game to load
4. Click OK
5. See error

**Expected behavior**
The old game should end and the new game should be loaded.

**Version:**
 - OS: antix / Debian buster + backports
 - Widelands Version: 1.1~git25790 (3b6997d@master) ­– 92a5e0c works / 45e168b is broken

**Comment by Noordfrees** [comment]
Confirmed. Does #5419 change the behaviour?

**Comment by tothxa** [comment]
> Does #5419 change the behaviour?

It doesn't. Sorry, I forgot to mention it in the OP.
