### ISSUE TITLE
Neptune's revenge, campaign objective unclear

### ISSUE THREAD

**Issue by aggro80** [widelands/widelands#5478]
Neptune's revenge, campaign objective unclear. Tested with nightly build.

Objective text asks to convert wheat into 50 wool, but does not give any help in how that is done. The text should indicate that player needs to build a sheep farm to do so. This is especially misleading because the scenario does not show sheep farm in building menu at the start and there is only one location on the map where sheep farm can be build and there is enough wool in the warehouse to make cloth for the ship even without sheep farm, so player can end up building a ship thus finishing the main objective, but still fail to trigger even, because 50 wool is missing.

Another objective is to go into expedition with a ship. It is unclear to a new player how this is done. The text should advice to select "port" building and click "start an expedition" button.

**Comment by Noordfrees** [comment]
The sheep farm is explained at large in the campaign dialogue:
> So, let’s think this over. To weave cloth we need some wool from a sheep farm. The sheep farm itself needs wheat and water to work. So, let’s find a space for a big building and build a farm first.
>
> After the production of enough wheat, we can dismantle the farm and build a sheep farm to produce wool. When the sheep farm starts working, we could find or free up space for a medium building to build a weaving mill to use our wool for weaving cloth. But for the moment being, let’s start by producing a reasonable amount of wheat.
> 
> I think a stock of 50 sheaves of wheat would be enough for starters. We do not have a target quantity for wheat, because the farmer does not need other wares to produce it. All we have to do is watch our stock of wheat grow.

Later:
> Well done so far. We have produced enough wheat. Now dismantle the farm and build the next building in the production chain.
>
> Don’t forget to check the target quantity of wool and cloth in the economy settings. We need to turn all the wheat into wool and then the all the wool into cloth.
>
> Perhaps it would be a good idea to stop the shipyard’s production until we have some cloth available in order to not waste any logs or planks.

How to launch an expedition is explained in detail in the 3rd tutorial. One shouldn't play the campaigns before they've completed those.

**Comment by aggro80** [comment]
I don't read the dialogue because I assume the important stuff is in the objectives. I think that just adding "sheep farm" to the objective text would fix the issue I experienced.

I also skipped the tutorials, because I have rough understanding how the game works, but I did not expect the expedition to be in the game.

I agree with you that if the player follows the correct order and protocol, no problems will occur. But I think it is quite common for people to rush into action without tutorials and reading. I'm not asking to write full tutorial there again. Just adding a few key words to give them hint where to look. I also understand if adding such words will ruin the visual impression of the game. 

Either way, these changes make difference only for those who play for the first time and it is not impossible to solve it (I googled for how to produce wool in the game and after some searching found the button and figured out how the ship operates).

**Comment by hessenfarmer** [comment]
Not reading the dialogues will resut in missing important hints. in other scenarios as well as in neptunes Revenge we put some good hints for the player in the dialogues to make reading them a benefit. I took us some effort to write them so we wanted them to be read. 
Furthermore the info how to get cloth from wool, and wool from wheat is in the tribes encyclopedia as well. Lokking in the wares tab will show you which buildings are producing the ware.   

What I will do with the scenario though is: 
1. adding the sheep farm to objective text.
2. reduce the start amount of cloth to make it impossible to build a ship without a cloth production.
3. add a sentence to send the expeditin from your own port

**Comment by aggro80** [comment]
Thank you, that sounds good to me.
