### ISSUE TITLE
Master fails to save File in multiplayer mode with unclear focus

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5485]
**To Reproduce**

* Open attached File from the Muliplayer Menu and try to save it, after playing a few seconds.
* Notice: that it still still possible to select something during the attempted save.
* Notice that Network connection is lost after a while.
* After pressing Escape Game seems to continue in the Background
* Debug Output does not indicate any real attempt to save.
* Notice that Autosave works as expected.

**Expected behavior**

* Game is stopped during the save.
* No interaction with background possible during save.
* Game is saved in the End.

**Attachements**

[Save File and debug log](https://github.com/widelands/widelands/files/9248779/SaveGameBug.zip)
A Screencast can be found here: https://magentacloud.de/s/e7BHdHH2tgNLXLJ 

**Version:**
 - OS: macOS Monterey 12.5 (21G72)
 - CPU:  M1 ARM
 - Widelands Version: 1.1~git25829 (c58a8c6@master)

**Additional context**

* Is this a focus issue from the GUI? or is this just some side effect?
* I this a racecondition related to Multithreading?
* I case I should debug something please give me a hint where to start

**Comment by hessenfarmer** [comment]
the debug shows that the europeans addon is activated, which changes the tribes immovables of the tribes. Just for sorting things out is this reproducible with the addon disabled? was the savegame created without the addon?

**Comment by hessenfarmer** [comment]
bug confirmed. not relate to addons. tried it with different other multiplayer savegames. 
edit: in windows the game freezes after rightclicking in the background.

**Comment by Noordfrees** [comment]
Looks like a multithreading race condition bug. Could you check whether reverting 5750147a3445bbaeea7dfa8b07ecca0031642460 changes the behaviour?

**Comment by hessenfarmer** [comment]
> Looks like a multithreading race condition bug. Could you check whether reverting [5750147](https://github.com/widelands/widelands/commit/5750147a3445bbaeea7dfa8b07ecca0031642460) changes the behaviour?

unfortunately not

**Comment by klaus-halfmann** [comment]
@hessenfarmer so you can reproduce this?

I disables all addons but still get the error. 
Could we add some debug info when we are waiting for a Mutex for more then a second or such?
Where could I start debugging this? (The X-Code Debugger can cope well with multiple Threads)

**Comment by Noordfrees** [comment]
> Where could I start debugging this?

Wait until you get the hang, then get a full backtrace of all Widelands threads. That should contain all the relevant info.

>  Could we add some debug info when we are waiting for a Mutex for more then a second or such?

+1 should be doable in the `MutexLock` constructor (`base/multithreading.cc`)

**Comment by Noordfrees** [comment]
I tried catching this in GDB now but I can no longer reproduce. In a release build, I get the bug, in a debug build + GDB, it works fine.

**Comment by klaus-halfmann** [comment]
Giving XCode a try ....
I see the code is haging around in "Thread1" at `game_main_menu_save_game.cc#292`:
   `MutexLock m(MutexLock::ID::kLogicFrame, [this]() { stay_responsive(); });`

The only other active Thread is `Thread10` stuck at: `gamehost.cc#618 `
```
void GameHost::think() {
	NoteThreadSafeFunction::instantiate([this]() { handle_network(); }, true);
```

From hat I see this is the "initailalizerThread" but the Mutex is waiting for the "kLogicFrame"?

Maybe a common debug Session would help?

As the programm does not rally crash I dont get the usual Thread Dump from the Appe Crash anaylzer

**Comment by Noordfrees** [comment]
Please post the full backtraces of both threads, so we can see via which pathways they got there and which mutexes they acquired along the way…

**Comment by klaus-halfmann** [comment]
Sorry needed to find out how to extract the stack from XCode: [Threads.txt](https://github.com/widelands/widelands/files/9270300/Threads.txt)

**Comment by Noordfrees** [comment]
Aaaaaah…

The save game dialog has been made "fake"-modal some time ago to fix focus issues. It pretends to be a modal dialog but is not really. The stay_responsive code that is supposed to break the race condition assumes that the save game dialog is modal and tells it to handle responsiveness. The save game dialog however assumes that since it is *not* modal the underlying modal panel is responsible for that. Solution is that the save game dialog must be refactored to be genuinely modal and not just fake it.

**Comment by hessenfarmer** [comment]
by testing I found out, that #5421 introduced the bug
