### ISSUE TITLE
Coding question

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5498]
Hi All,
This is a question and not a bug.
I'm trying to get the route between tow building without the flags in between.
For example if there is a route between a production site and a head quarter without any other building in between but only flags then i want to save only these tow buildings.
I was trying something like :
`if ((transfer->route_.route_[0].get(game)->get_building() != nullptr)&&(transfer->route_.route_[transfer-> route_.route_.size()-1].get(game)->get_building() != nullptr)) `
and then 
` transfer->route_.route_[0].get(game)->get_building()`
 and 
 `transfer->route_.route_[transfer->route_.route_.size()-1].get(game)->get_building()`
 
 i'm getting READ memory access error at runtime already at the if condition line where i'm only trying to check if the flag has a building.
 is there another way to check if a flag has a building without facing this nullpointer issue?

**Comment by Ahmad-fadl** [comment]
I made the route_ attribute public that is why I could access it from inside the Request class. as in the code above

**Comment by Noordfrees** [comment]
Did you first check that `transfer->route_.route_` is not empty, and that `transfer->route_.route_[...].get(game)` is not `nullptr`?
If either assumption does not hold then you dereference invalid memory. If you obtain a valid non-null `Flag*` then `get_building()` should tell you safely whether the flag has a building or not.

**Comment by Ahmad-fadl** [comment]
This worked thanks a lot.
