### ISSUE TITLE
Add an upgrade option for Ferry Yard to produce larger ferries that workers can be transported across the water

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5507]
Per issue https://github.com/widelands/widelands/issues/5505

feature request: Add an upgrade option for Ferry Yard to produce larger ferries that workers can be transported across the water.

In some cases, the shortest path between two locations is by water, or even in some cases maybe only by water. I haven't played enough yet to know, but I think that islands that are not connected by roads/bridges, that workers are not able to get onto that island. With an upgraded ferry yard transport vessel that can carry workers, it should then be possible to have workers either reach the island, or in case of shortest path by water, get to the location by water possibly quicker than by land (depending on distance and speed of travel by water versus walking)

**Comment by Noordfrees** [comment]
Ferries can carry no workers on purpose because this would break a lot of existing map designs. It would make currently unreachable areas easily reachable. So -1 to allowing ferries to carry workers.

**Comment by hessenfarmer** [comment]
-1 from me as well for exactly the same reason

**Comment by frankystone** [comment]
Noordfrees summarized the reasons why this feature might not be implemented, and personally i agree with him.

For a full discussion why ferrys don't carry workers, see e.g. https://www.widelands.org/forum/post/25405/ and the following posts.
Ferries must be different from ships, not only by the amount of transported wares. 

But i think this discussion may arise then and then in the future, probably by people who don't want to play the tutorials or by people who get confused with the term "Ferry". So what about some renaming:

* Ferry → Freight [Ferry|Boat]/Cargo [Ferry|Boat]
* Ferryyard → Boatbuilder (in case of "Boat")

**Comment by tothxa** [comment]
Can we close this as `wontfix`?

I don't think renaming is needed. Players should play the tutorials first, or be ready for surprises.
