### ISSUE TITLE
[Feature Request] Repeat build action when holding CTRL or SHIFT or some other keyboard shortcut

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5508]
When building the same building types (e.g. Lumberjack's Hut) consecutively, allow for something like:

- Press and hold on keyboard the CTRL or SHIFT key before clicking on the build action
- click on the build action normally, action dialog window closes normally, build action proceeds normally
- still holding down CTRL or SHIFT, continue clicking on small, medium, or big building icons on the map, and rather than showing the build action dialog each time, repeat the last action since the CTRL or SHIFT key has been held down

This is just one idea for such an implementation, but other shortcut procedures are okay too.

**Comment by Noordfrees** [comment]
This seems very similar to the building fastplace feature added in the current development version. It allows you to assign keyboard shortcuts to any building, and then in the game you can press the shortcut and the associated building is constructed at the node you're pointing the mouse over. Does this meet your needs?

**Comment by jasonkhanlar** [comment]
Ah nice! I haven't seen that as I'm using latest stable release, but it seems good enough! Thanks!
