### ISSUE TITLE
MSVC CI builds failing

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5511]
since a couple of days the MSVC release build is failing due to some linking errors.

**Comment by matthiakl** [comment]
This is a problem with the Windows runner and will be fixed with the next deployment (probably monday). 
See https://github.com/actions/runner-images/issues/6107

**Comment by matthiakl** [comment]
Resolved with new runner image: https://github.com/widelands/widelands/actions/runs/2901254154
