### ISSUE TITLE
can't connect to the Addon server

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5514]
With latest master I don't get a connection to the addon server.     
tried it with version 1.0 and it works. So I assume it is a problem in the client at current master

**Comment by hessenfarmer** [comment]
maybe it is a server issue instead as the automated server sync seems to be stale as well

**Comment by Noordfrees** [comment]
The server had crashed again. Restarted it, now it works.

v1.0 does not connect to the server, it reads from the GitHub repo instead.
