### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5523]
**Describe the bug**
The Widelands user interface glitches slightly where the coordinates to click became displaced from what the visual screen looks like, both during gameplay as well as at the menu screen, in the following condition:

**To Reproduce**
1. Use i3 window manager [ https://i3wm.org/ ] and in a workspace screen where other windows are tiled (e.g. above or below Widelands), and widelands in window mode (without CTRL+F keyboard shortcut enabling fullscreen)
2. Push CTRL+F to turn on/enable Widelands native fullscreen mode (otherwise there is no issue)
3. Push i3wm keybinding Mod1+f to toggle i3's fullscreen mode. (this should undo Widelands fullscreen to revert back into a window)
4. Move the cursor around to see coordinate glitches

**Expected behavior**
Window manager toggling of fullscreen should be detected by Widelands in addition to Widelands's internal keyboard shortcut.

**Comment by matthiakl** [comment]
This sounds like a problem with SDL. Do you experience this issue with other SDL applications as well? (e.g. https://www.supertux.org/)

**Comment by jasonkhanlar** [comment]
@matthiakl I just installed Supertux to test. Supertux in a window, Options -> Fullscreen (enabled), then pushing Mod1+F (i3wm fullscreen toggle) to go back into a window. Yep, same issue. The game thinks it is still in fullscreen mode and does not appear correctly, does not appear like it does when in windowed mode.

**Comment by matthiakl** [comment]
Then please report this issue to [SDL](https://github.com/libsdl-org/SDL/issues) since we can't do anything in the Widelands code about it.
