### ISSUE TITLE
Random number: Select all text when double clicking

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5530]
**Describe the solution you'd like**
In Single Player... -> New Random Game dialog, when double clicking on the Random number: text input field, select all of the text. Clicking and dragging selects the text. CTRL+A selects all of the text. Double clicking should select all of the text too.

- Note that even when pushing CTRL+A or clicking and dragging to select all (or part of) the text, when typing a number expecting to replace/overwrite the value, instead it doesn't overwrite, and merely inserts the character where the cursor appears to be. However, when pushing the backspace or delete keys, apparently all of the selected text gets removed. This seems like the backspace/delete keys are treated differently than other keypresses.
- Also suggestion: CTRL+Backspace should get rid of all the text to the left of the cursor, and CTRL+Delete all text to the right.

**Additional context**
See https://github.com/widelands/widelands/issues/5522

**Comment by jasonkhanlar** [comment]
- [Feature Request] Random number: Prevent nonnumbers from showing up in the text input field

- [Feature Request] Map ID: Disable editing this value
    - In the New Random Game dialog, changing this value appears to have no effect.
    - In the Editor mode, changing this value appears to disable the "Generate Map" button if the value of the field is not the correct hash ID value, and renables the button when it is edited to be correct, even though the value is automatically generated for each change to other input fields.

I'm posting these two here as a comment instead of yet another separate issue.

**Comment by Noordfrees** [comment]
The point of the Map ID is that you can paste an ID there to recreate a "random" map exactly. So -1 to making it unchangeable. 

Preventing non-numeric characters from being entered in an editbox might be doable but tricky.

The opening post applies to all editboxes in general, not specific to random maps.
