### ISSUE TITLE
[Question] Is there a way to kill/destroy workers/soldiers?

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5531]
Is there a way to kill/destroy workers/soldiers? I have a saved game from edits to lua files with 50,000 soldiers and I want to remove 40,000 of them. There is a situation in the saved game that I cannot easily reproduce. Apparently the saved game does not load in the debug build, but if I can prepare the saved game to a state that is able to be loaded in the debug build, such as by killing off existing workers/soldiers, then I'd like to be able to do that so that I can prepare the saved game to be loadable in the debug build without errors causing it to crash.

Also minor issue I notice the military building action dialogs tend to break, and not show important/key user interface elements when max_soldiers = 40000. For example, the Prefer heroes/rookies and Capacity up/down buttons do not appear. I thought I could send the soldiers into a building, and then destroy the building, killing all of the soldiers inside, but I guess that doesn't work, and they survive.

Also see https://github.com/widelands/widelands/issues/5517#issuecomment-1221264362

I just realized I should have probably just asked commenting in there instead.

However also, just like destroying buildings, there should be a way to destroy workers. So consider this a feature request if it doesn't already exist.

**Comment by Noordfrees** [comment]
> However also, just like destroying buildings, there should be a way to destroy workers. So consider this a feature request if it doesn't already exist.

Why would you need to do this? Workers in warehouses don't take up any resources, you wouldn't gain anything by deleting them. Situations like the nice problem you got yourself into by pushing scripting to its limits don't arise in normal games ;)

---

To answer the question, although you can't access the scripting console in release builds, you *can* write a lua script and have the game run it after loading.

1. Create in your Widelands home directory `remove_soldiers.lua`:
```lua
   local p = wl.Game().players[wl.Game().interactive_player]
   local whs = array_combine(
      p:get_buildings(p.tribe_name .. "_headquarters"),
      p:get_buildings(p.tribe_name .. "_port"),
      p:get_buildings(p.tribe_name .. "_warehouse"))
   for idx,wh in ipairs(whs) do
      wh:set_soldiers({})
   end
```
  (not tested, may need a bit of tweaking before it works)

2. Start Widelands with the command line parameters `--loadgame=save/FILENAME.wgf --script=remove_soldiers.lua`
3. Save the game under a new name. The resulting savegame *might* be loadable in debug builds and work correctly.

**Comment by hessenfarmer** [comment]
-1 for a feature to destroy workers or soldiers, as there is no logical cause in the game to do so. 
such features which are useless in normal gameplay would just increase code complexity and maintenance for no real benefit.

**Comment by hessenfarmer** [comment]
@jasonkhanlar can we close this

**Comment by jasonkhanlar** [comment]
Yep!
