### ISSUE TITLE
Segfault in flatpak build with runtime version 22.08

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5540]
**Describe the bug**
Flatpak built with version 22.08 of the freedesktop.org runtime crashes when a game is started.
Not sure whether it's a host problem (see below), bug in the runtime, or an actual Widelands bug.

**To Reproduce**
1. Build Widelands for flatpak with runtime 22.08 from https://github.com/tothxa/org.widelands.Widelands/tree/beta-freeze-8 or install the test build from https://buildbot.flathub.org/#/builders/32/builds/107434 (will be deleted in a few days)
2. Run it
3. Try to start a game or the editor

**Expected behavior**
Should not crash. :smiley: 

**Version:**
 - OS: freedesktop SDK and runtime 22.08
 - host: Debian buster/bullseye (partially upgraded test environment running as a chroot on buster) – this may also cause the problem, if someone could test it on some up to date host system and it works, then the bug can be closed
 - Widelands Version: 1.1~git25862 (cdb5ccf@master)

**Additional context**
[flatpak_debug_log.txt](https://github.com/widelands/widelands/files/9478080/flatpak_debug_log.txt)

**Comment by Noordfrees** [comment]
The line in the log is known as a bit of a troublemaker: Terrain textures are required to be indexed PNGs, and this line accesses the image's palette. So I guess there's something going wrong there – either a terrain image has been modified so it's RGB instead of indexed, or the SDL/PNG lib version used doesn't load the palette correctly.

I can't reproduce with a self-compiled build on Ubuntu Jammy. Perhaps you could add some logging output to see which input file causes the problem, to determine whether the problem comes from the file or the library.

**Comment by tothxa** [comment]
Nothing is printed on stdout after the main menu is loaded without `--verbose`. Here's the log with `--verbose`:
[flatpak_stdout.txt](https://github.com/widelands/widelands/files/9478682/flatpak_stdout.txt)

With gdb, the window stays open after the crash, so the last message in the status bar when loading a savegame is:
```
Loading map: Terrains (3/23)
```

When the editor is started (with either menu option), the last message is:
```
Loading world…
```

SDL-image was updated in the runtime to 2.6.2 (from 2.6.0 with the unknown pixel format bug) in the last days due to my bug report.

---

As it works with a newer host, you may close this. OTOH I can't understand from the backtrace how the host comes to play here…

**Comment by tothxa** [comment]
I've upgraded my test environment to bullseye, but I still get the crash. Kernel versions: 5.1.11 (antix/buster chroot) and 5.10.136

**Comment by tothxa** [comment]
Tested on 2 more host systems with 2 more laptops and both segfault.

* Endless OS 3.7.8 (yes, I'm not quite keen on system upgrades…), kernel version: 5.3.13
* Void Linux live 20210930 (this one's the latest though), kernel version: 5.13.19

**Comment by tothxa** [comment]
> I can't reproduce with a self-compiled build on Ubuntu Jammy.

I tried the linked autobuild on a Lubuntu Jammy live host system, and it crashes there too.

**Comment by Noordfrees** [comment]
Tried again and now it segfaults for me too. Probably I was just doing something wrong earlier…

**Comment by Noordfrees** [comment]
If I run my normal Widelands with the flatpak installation as datadir it works fine. This suggests a problem with a library with which the flatpak version is built, most likely either `SDL_image` or `libpng`.

**Comment by tothxa** [comment]
I'm trying to debug it as much as I can…

As I expected, it crashes on the first image. (summer/meadow1/idle.png, which is indexed of course)

The sdl_surface's palette is `null`:
```
(gdb) print sdl_surface->format->palette 
$9 = (SDL_Palette *) 0x0
``` 
so I guess the `…palette->colors` nullptr dereference causes the segfault.

This should have been set up by `load_image_as_sdl_surface()`, shouldn't it? Is that SDL (2.24.0) or SDL-image (2.6.2)? We don't have problem with these versions on other systems, do we?

libpng is version 16.37

One thing I don't understand:
```
(gdb) print top_left_pixel_color 
$6 = <optimized out>
```
The SDK has GCC 12.1.0, which we know is icky… (I wonder why they rushed it…) Could this be also part of the problem?
In my native build with GCC 8.3.0 `top_left_pixel_color` is properly defined.

**Comment by Noordfrees** [comment]
https://github.com/libsdl-org/SDL_image/issues/298

**Comment by tothxa** [comment]
> [libsdl-org/SDL_image#298](https://github.com/libsdl-org/SDL_image/issues/298)

Indeed. I [tested with clang](https://github.com/flathub/org.widelands.Widelands/pull/44) and it crashes too.

So I guess that means we'll have to release v1.1 flatpak with 21.08, and adapt to new SDL-image in v1.2?

**Comment by Noordfrees** [comment]
We only access the palette of indexed images for this one line of not exactly critical importance. It would not be bad to change it to sample an average colour from the whole image instead and thus permit normal RGB images for terrain textures. This would make the SDL_image bug a non-issue for us. I'd not be opposed to having that for v1.1 if the codechange is not too involved.

**Comment by tothxa** [comment]
> We only access the palette of indexed images for this one line of not exactly critical importance. It would not be bad to change it to sample an average colour from the whole image instead and thus permit normal RGB images for terrain textures. This would make the SDL_image bug a non-issue for us. I'd not be opposed to having that for v1.1 if the codechange is not too involved.

OK, I've already started working on it anyway out of curiosity. But the SDL API is horrible, and every time I have to deal with it I keep discovering newer depths of its horribility…

As for mixing it down to a single colour, I was wondering whether the single pixel access was for speed. We have 69 terrains (plus addons?), and game init takes too long already.

**Comment by Noordfrees** [comment]
Since I spent the last week porting another open source game I work on from SDL software rendering to OpenGL this type of code doesn't shock me as much just now ;)

Could you try if this quickly written and briefly tested patch works with the buggy SDL_image version:
[patch.txt](https://github.com/widelands/widelands/files/9488623/patch.txt)

**Comment by tothxa** [comment]
> Could you try if this quickly written and briefly tested patch works with the buggy SDL_image version: [patch.txt](https://github.com/widelands/widelands/files/9488623/patch.txt)

It works. But do you mind if I clean it up?

Meanwhile I tried to use `SDL_BlitScale()` to get it down to 1x1 with a known pixelformat, but I'm doing it or `SDL_GetRGB()` wrong, because I get all black. I'm not sure though whether it's offloaded to the GPU, but at least this would be more universal.

**Comment by tothxa** [comment]
OK, `SDL_BlitScale()` doesn't handle pixelformat conversion, which is OK, but it also doesn't blend the colours, so it is equivalent to just picking the first pixel. So I dropped it, and just use SDL's pixelformat conversion to get the colour: 
[firstpixel_convert_simple.patch.txt](https://github.com/widelands/widelands/files/9490806/firstpixel_convert_simple.patch.txt)

I have a paranoid version as well that checks SDL return values too: 
[firstpixel_convert.patch.txt](https://github.com/widelands/widelands/files/9490844/firstpixel_convert.patch.txt)

Maybe 8 and 16 bit could be handled by conditional casts, but 24 bit is more problematic. At least I'm afraid to do bit shifting because of possible endianness problems. That's also a problem with your patch, because you assume fixed order of colours within the pixel representation.

**Comment by Noordfrees** [comment]
Looks good to me :) 
Checking the return values is good practice, we should use that one.
