### ISSUE TITLE
Daily PPA is Failing on Xenial

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5546]
#5545 breaks on old SDL versions

[Sample Buildlog](https://launchpadlibrarian.net/622054583/buildlog_ubuntu-xenial-amd64.widelands_2%3A1.1~bzr10377-202209061446~ubuntu16.04.1_BUILDING.txt.gz)

```
/<<PKGBUILDDIR>>/src/logic/map_objects/world/terrain_description.cc: In member function ‘void Widelands::TerrainDescription::replace_textures(const LuaTable&)’:
/<<PKGBUILDDIR>>/src/logic/map_objects/world/terrain_description.cc:194:67: error: ‘SDL_PIXELFORMAT_RGBA32’ was not declared in this scope
    SDL_Surface* converted = SDL_ConvertSurfaceFormat(sdl_surface, SDL_PIXELFORMAT_RGBA32, 0);
                                                                   ^
```

**Comment by tothxa** [comment]
It seems RGBA8888 is the old style name present (at least) since 2.0.0, of which RGBA32 is an alias.

**Comment by tothxa** [comment]
BTW (mostly off-topic) if anyone is actually using it (isn't it EOL? packages.ubuntu.com doesn't list it), could they please test [horizontal scrolling](https://github.com/widelands/widelands/discussions/5367)? I still wonder whether it has always been wrong, or there was some change in input handling on linux that broke it.

**Comment by Noordfrees** [comment]
Our policy is to support the latest EOL LTS distro, so Xenial keeps getting PPA builds until Bionic goes EOL in April (something I'm looking forward to because it will allow us to switch to C++17). And after that for as long as it still works. I doubt such an ancient distro is still widely used though.
