### ISSUE TITLE
Translation update script should push updated templates before pulling translations

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5549]
**Describe the bug**
It takes  2 rounds of `utils/merge_and_push_translations.sh` runs to properly propagate source string changes to `.po` files. `.pot` and `*.po` are inconsistent between the 2 runs.

**To Reproduce**
1. Check diff of `po/widelands/widelands.pot` in 9a4ed5d (4 Sep): strings `src/ui_fsmenu/addons/packager_box.cc:372`, and `:373` are removed, but still present in `po/widelands/<any lang>.po`.
2. Check diff of `po/widelands/<any lang>.po` in a1e798f (7 Sep): the above strings are only removed by this commit

**Expected behavior**
`.po` files should be updated at the same time as the `.pot`.

**Additional context**
I think the reason is that local updates of both `.pot` and `.po` files are handled by `utils/buildcat.py`, so solving this will need heavy refactoring (ideally merging?) of the 2 scripts.

**Comment by SimonHeimberg** [comment]
If I read correctly, utils/buildcat.py only updates the *pot* files (see also https://github.com/widelands/widelands/actions/runs/5538564887/jobs/10108629088#step:5:5502, it only lists pot files)
As I see it, *po* files are updated by transifex only. (See my understanding of utils/merge_and_push_translations.sh below.)
But we first download (the po files) from transifex and later upload the new templates (the pot files). This results in a roundtrip (see below).

So we should adapt utils/merge_and_push_translations.sh to
- first generate the translation templates
- then push the template to transifex (maybe only if it has changed, not date only)
- wait for transifex to update the translation files
  (no idea how long this takes, either wait in the script or start a job later)
- download the translations from transifex
- generate all other files
- commit the templates, the translations and the other generated files

There are other strategies to avoid a round trip.
(v2: downloading the template files from transifex as well (`tx -fas`), update the other files and committing them all, and finally updateing the template files from source and push them to transifex without committing to git)
(v3: ??)

***more details***

****I understand utils/merge_and_push_translations.sh like this****
- [tx pull -fa](https://github.com/widelands/widelands/blob/70f49b9/utils/merge_and_push_translations.sh#L63) # pull **a**ll translation files (*.po) from transifex
- python3 utils/update_authors.py # update authors in data/i18n/locales/*
- python3 utils/update_appdata.py # update appdata in xdg/
- [python3 utils/buildcat.py](https://github.com/widelands/widelands/blob/70f49b9/utils/merge_and_push_translations.sh#L84) # create *.pot file from source files (.cc, .lua, ...)
- python3 utils/update_translation_stats.py # write data/i18n/translation_stats.conf.
- [echo "Skipping changes to $entry"](https://github.com/widelands/widelands/blob/70f49b9/utils/merge_and_push_translations.sh#L104) # undo changes of only the date
- git add ... # add files to staging area
- [if [ -z "$(git status -s)" ]; then](https://github.com/widelands/widelands/blob/70f49b9/utils/merge_and_push_translations.sh#L122C1-L122C35) # abort if nothing has changed
- git commit -m "Fetched translations and updated catalogs." # commit staged changes
- git push "$push_target" master # push (to github)
- [tx push -s](https://github.com/widelands/widelands/blob/70f49b9/utils/merge_and_push_translations.sh#L132) # push (**s**ource) catalogs to transifex (*.po)

Maybe I could add some comments to the script.

****Resulting roundtrip:****
- Translation is removed in the source file.
- run utils/merge_and_push_translations.sh
  - Old translation (fr.po, ...) is downloaded from transifex.
  - New translation template is generated from source file (xxx.pot)
  - all (old) translations (.po) and (new) template translations (.pot) included in a commit and pushed (9a4ed5d4deec47c2fa9f1d0026f0bd94df9f7d2d)
  - New translation template is pushed to transifex
- next run of utils/merge_and_push_translations.sh
  - New translation (fr.po, ...) is downloaded from transifex.
  - ...
  - all (new) translations (.po) and (newer) template translations (.pot) included in a commit and pushed (a1e798f7d8c68b67d723292c8822ef5b484e6605)
  - Newer translation template is pushed to transifex
