### ISSUE TITLE
Too much churn in translation templates

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5550]
**Describe the bug**
Most changes in translation updates are just reordering translator comments (IIRC also back references). This not only pollutes the commit history, but it often makes it very hard to see the actual translation updates.

**To Reproduce**
1. See the diff of almost any translation update. (eg. a1e798f `po/tribes_encyclopedia/<any lang>.po`)

**Expected behavior**
Ordering of comments for a string should not change when there is no actual change.

**Additional context**
Probably a gettext bug, but can we find or write a workaround?

**Comment by Noordfrees** [comment]
buildcats.py does not pass the files to xgettext in any particular order. Some alphabetical sorting on the filenames might do the trick.
```diff
diff --git a/utils/buildcat.py b/utils/buildcat.py
index 51be558393..0156f613fe 100755
--- a/utils/buildcat.py
+++ b/utils/buildcat.py
@@ -242,7 +242,8 @@ def run_xgettext(infiles, outfile, opts):
     xgettext = subprocess.Popen("xgettext %s --files-from=- --output=\"%s\"" %
                                 (opts, outfile), shell=True, stdin=subprocess.PIPE, universal_newlines=True)
     try:
-        for fname in infiles:
+        for fname in sorted(infiles):
             xgettext.stdin.write(os.path.normpath(fname) + '\n')
         xgettext.stdin.close()
     except IOError as err_msg:
```

**Comment by tothxa** [comment]
Oh, I thought xgettext was supposed to order them. Will try to test this.

**Comment by tothxa** [comment]
I tested it and it works.

I was able to reliably reproduce the problem by running the script with python3 in different branches, but with the patch I get the same order in all of them.

With python2 (default on my Debian oldstable system) there was no problem (running it in different branches resulted in the same order), however the python2 stable order is different from the python3 sorted order.

**Comment by tothxa** [comment]
@Noordfrees Can we have this before the next translation update? I don't see any risk, and it would be most useful during the freeze period. (it'll still require 2 runs after merging to settle down, due to #5549)

**Comment by tothxa** [comment]
Thank you!
