### ISSUE TITLE
Should be able to load another replay when in replay mode

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5551]
**Is your feature request related to a problem? Please describe.**
In v1.0 the ability was added to games and the editor to load another game or map respectively without going back to the main menu. This should be added to replays as well.

**Describe the solution you'd like**
Add a "Load Replay" button to the "Main Menu" for replays.

**Comment by fernandezmatthew** [comment]
Hello, I'm interested in solving this issue. Could I be assigned to this?

**Comment by fernandezmatthew** [comment]
Hey, do you know where I could find the current file(s) defining the main menu that is pulled up while in a replay? I noticed that the main menu for the editor seems to be defined across several files in "../src/editor/ui_menus," but I cant find an equivalent for replays

**Comment by Noordfrees** [comment]
Hi, have a look at `src/ui_fsmenu/loadgame.*`, which is the wrapper around a game or replay loading display, and `src/wui/load_or_save_game.*`, which implements the generic UI for saving and loading all kinds of savegames and replays.

**Comment by tothxa** [comment]
I think the main menu is defined in `wui/interactive_gamebase.{cc,h}`.

**Comment by fernandezmatthew** [comment]
Hey, unfortunately I won't be able to fix this issue. There's a bit too much here that I don't quite understand. I apologize for the inconvenience, but I hope you can find somebody else who can solve this.
