### ISSUE TITLE
Crash in LAN game

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5555]
**Describe the bug**
While playing a LAN game, Widelands crashed at the same time on the host and the client after about 27 minutes. The client had a segfault, probably the host too, but I don't have the console log for it.

**Version:**
 - OS: host: Endless OS 3.7, client: antix/Debian buster + backports
 - Widelands Version: 1.1~git25864 (b301eaa@master) host: flatpak, client: native build (Debian libasio-dev 1:1.12.2-1)

**Additional context**
[crash.log](https://github.com/widelands/widelands/files/9538627/crash.log)

**Comment by Noordfrees** [comment]
Is it reproducible with the replays?

**Comment by tothxa** [comment]
We continued today from the last autosave past the time of the crash, but there was no crash.

**Comment by tothxa** [comment]
With the new crashlog code any such crashes should become better debuggable. There's no point in keeping this around.
