### ISSUE TITLE
Allow player to pin notes to map locations

### ISSUE THREAD

**Issue by RHolton** [widelands/widelands#5558]
Currently, the results of geological surveys (water, gold, iron, etc.) only remain visible for a limited time. I suspect this is to limit clutter. But there are times when, as a player, you'd like to keep track of some of the survey results.

My suggestion is to implement a way for the player to pin notes to the map. The visibility of such pins could be toggled (similar build help), and the player could later delete any note.

Players will likely find other uses aside from saving useful survey results.

The UI should probably be something like:
1. Player selects "pin note" via menu or key.
2. Player then uses a mouse button to select the pin location. 
    - If an existing pin is clicked, the pin text is displayed until the player dismisses it.
    - If a new location is clicked, display a dialog for the player to enter note text.
3. Right mouse button or screen button to exit from "pin note" mode. 

Also, need to add Show/Hide pin notes to the Show/Hide menu.

One possible alternative is to make survey results permanent, with a visibility toggle. However, there are often survey results that aren't useful, such as water found outside the range of any possible well location.

**Comment by tothxa** [comment]
> One possible alternative is to make survey results permanent,

We actually have an addon that does this. :) (Permanent Resource Indicators in tribes category)

> with a visibility toggle. However, there are often survey results that aren't useful, such as water found outside the range of any possible well location.

Well, not this. But you can remove them by building (then removing) a road through them.
