### ISSUE TITLE
Howto begin

### ISSUE THREAD

**Issue by Ygarr** [widelands/widelands#5559]
Maybe add some interactive tutorial or tips because with 0ad experience there is lack of understanding what to do?
No way to produce workers, develop settlement etc. Even how to finish command for road build. Or it is feature - deep threshold of entry.

**Comment by tothxa** [comment]
We have tutorials starting with the very basics: Main Menu -> Single Player -> Tutorials.

**Comment by hessenfarmer** [comment]
@Ygarr can we close this or do you need further information
