### ISSUE TITLE
The editor should get a bigger load screen

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5570]
**Is your feature request related to a problem? Please describe.**
The editor still has a 800x600 loadscreen only, and it isn't even scaled for bigger screens.

**Describe the solution you'd like**
It should get a higher resolution loadscreen, that looks good at various scales, and it should be scaled to the window.

**Additional context**
Current editor loadscreen in a high resolution window:
![editor_load](https://user-images.githubusercontent.com/80712255/190257625-049af18a-2e00-4c65-bde0-74be4d0a16a8.png)

**Comment by matthiakl** [comment]
We can do it like the splashscreen (#5183). Here is an example from bigjpg.com scaled up to 2592x1944 with fuzzy borders:

![editor](https://user-images.githubusercontent.com/23122583/190272089-f4a50d1c-394f-48bd-adc9-ea2f0878a3af.jpg)
