### ISSUE TITLE
Have a way to move the map back to focus on an unfinished road.

### ISSUE THREAD

**Issue by RHolton** [widelands/widelands#5572]
Too many times i"ve just ordered the construction of a building when a message comes in that I respond to. In doing so, the needed road for the new building is left incomplete. I shift the map to check on the message and may move the map more as a result. Only when I go to do some more construction or add to a different road do I realize that the first road needs to be finished. 

It would be very helpful to hit a key to jump back to where the road is needed. Depending on what happened before I ordered the original construction, the "jump to recent location" key may not be helpful.

**Comment by klaus-halfmann** [comment]
Did you try the ',' and '.' shortcuts? maybe that will already be what you need...

**Comment by RHolton** [comment]
That's what I meant when I talked about the "jump to recent location". It is not always helpful. It depends on how you reached the location where you started the build.

**Comment by klaus-halfmann** [comment]
So maybe we could push the current location to that stack when you jump to the latest news?
(I actually need to check that ,/. implemenation, have not seen that code for a while)

**Comment by RHolton** [comment]
Or maybe push the current location when you start construction on a new building?

**Comment by klaus-halfmann** [comment]
@RHolton please download the Binaries based on the branch Noordfrees has opened and do some testing, I will do likewise e.g. https://github.com/widelands/widelands/suites/10129614389/artifacts/494617444

I think the implementation is not what you intended ?
