### ISSUE TITLE
Cut folder names in replay listbox

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5591]
I noticed this today while trying to open the replay from Seefahrer vs Niektory: https://www.widelands.org/forum/post/39491/

The folder name in the listbox is cutted, the part ". Niektory" is missing.

**To Reproduce**
1. Download replay
2. unpack it into the replay folder, be sure to use the same name for the folder as the zip file has.
3. Open the Replay screen of widelands

As you can see in the screenshot the folder name in the listbox  is cutted directly after the dot, on the right the whole name is shown. Other entries are much longer so i think it is not a matter of the string length.

**Expected behavior**
Show the correct folder name.

**Screenshots**

![cut_folder_name](https://user-images.githubusercontent.com/6730556/193532573-cfaaf351-a86a-4fc5-aeb5-84b4f17b7347.jpg)

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25864 (b301eaa@HEAD) Debug

**Comment by Noordfrees** [comment]
I think this is because everything after the last '.' is treated as a filename extension. Solution: Don't hide extensions for directory entries.
