### ISSUE TITLE
Expedition can build port on port space blocked by rocks

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5594]
**Describe the bug**
An expedition reports port space even if it is blocked by rocks. It is then possible to build a port, in which case the blocking rocks are instantly removed.

**To Reproduce**
1. See attached savegame: [port_space.zip](https://github.com/widelands/widelands/files/9719614/port_space.zip)

**Expected behavior**
Blocked portspaces shouldn't be found by expeditions.

**Screenshots**
![blocked port space found](https://user-images.githubusercontent.com/80712255/194183792-78c9dee6-cbfe-46d2-99dc-0349a1e4fc80.png)

**Version:**
 - OS: Debian buster
 - Widelands Version: 1.1~git25864 (b301eaa@master)

**Comment by frankystone** [comment]
As far i remember this was implemented because of trees are seeded automatically and can therefore block port spaces. I remember this was a problem with an Empire campaign. In result code was implemented to remove all immovables if one builds a port at this spot.

In case of the screenshot you provided i see no problem with this behavior. Moreover i think this can make maps more interesting: Should i build  a port or should i keep the rocks to get some resources?

**Comment by frankystone** [comment]
After some research it turned out that removing trees on port spaces was implemented first and removing rocks was implemented afterwards. I found the  [commit](https://github.com/widelands/widelands/commit/883877bde945c7b4525fb8a271c53e779eda4f88) but not the underlying bugreport.

**Comment by tothxa** [comment]
So it's intentional, but I still find it strange. I understand the issue with trees, but I can't understand why rocks, which can only be placed by the map designer, should be cleared.

OTOH if it's intentional, maybe they should be removed one-by-one with short delays and the materials added to the new port? Even better, but quite big change: have a separate concept for such blocked port spaces, and to clear them require a lumberjack/stonemason (as appropriate) in the expedition to allow clearing them with their standard animations.

**Comment by tothxa** [comment]
So the current behaviour seems to handle blocked portspaces as bugs in the map design. If it stays so, then #5556 needs to be changed accordingly.

**Comment by frankystone** [comment]
Some of your ideas were already discussed. Just gathering some related bug reports:

- https://github.com/widelands/widelands/issues/1981
- https://github.com/widelands/widelands/issues/1033 (possibly introduced clearing of rocks)
- https://github.com/widelands/widelands/issues/430 (initital problem)

I am fine with removing the code parts which removes rocks. So it's a map designers choice to block a portspace with rocks nearby for whatever reason.

**Comment by tothxa** [comment]
> Some of your ideas were already discussed. Just gathering some related bug reports:

Oh, sorry. I've only checked open bug reports. There were too many closed ones with ports.

**Comment by frankystone** [comment]
No need to say sorry :-)

The question is: What had the maps author in mind by placing the rock at this place?

**Comment by tothxa** [comment]
> The question is: What had the maps author in mind by placing the rock at this place?

Speaking of the map in the attached save, I don't know what the [original](https://www.widelands.org/maps/forest-valley/) author's intention was, but when I [modified](https://www.widelands.org/maps/forest-valley-tournament-version/) it, I expected that the blocked spots would only become available when cleared from land.

**Comment by frankystone** [comment]
hm, looking at the original map and the modified one in the editor i can't find this post space. Do you have another version?

Original:
![shot0002](https://user-images.githubusercontent.com/6730556/194496719-8d1ef6a9-c73f-4c27-a9c9-4bc6fa0b2ae1.jpg)

Modified:
![shot0003](https://user-images.githubusercontent.com/6730556/194496760-a00dc9db-5696-40e8-961e-49189cd94aaa.jpg)

**Comment by tothxa** [comment]
> hm, looking at the original map and the modified one in the editor i can't find this post space. Do you have another version?

You have to turn on maximum building spaces to see it. That's kind of the point of this bug report.

**Comment by frankystone** [comment]
Oh yes, i forgot (lost in new features ;) ).

**Comment by hessenfarmer** [comment]
Well currently the search for port spaces looks for max_buildcaps.    
https://github.com/widelands/widelands/blob/174b63af14ce928df5cbb82595412721702eaa2d/src/logic/map_objects/tribes/ship.cc#L414   
  We could easily use buildcaps, but this would regress the issue with random trees blocking the space.      
We might introduce a port_buildcaps and use this for detection though.
