### ISSUE TITLE
`utils/dump_economy.lua` fails on portdocks

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5595]
**Describe the bug**
When I try to use `utils/dump_economy.lua` with an economy with ports, I get an assertion failure.

**To Reproduce**
1. Start a debug build of Widelands
2. Start local multiplayer game with e.g. this save: [5t.zip](https://github.com/widelands/widelands/files/9737330/5t.zip)
3. Enter the debug console
4. Load the dump economy script with `dofile()` (as described in the script file)
5. Try to dump either tribe (as described in the script file)
6. See error

**Expected behavior**
The economy should be dumped without an error message.

**Version:**
 - OS: Debian buster
 - Widelands Version: 1.1~git25864 (b301eaa@master)

**Additional context**
Error message on stdout:
```
UNKNOWN immovable type: 	nil
[00:12:15.495 real] DEBUG: *** [../src/scripting/lua_errors.cc:21] src/widelands-master/utils/dump_economy.lua:130: assertion failed!
```

The error printing line has a bug too, it uses `immovable.type` instead of `immovable.descr.type_name`. The following patch makes the script run, but just ignores portdocks (haven't tested whether the dump can be loaded this way): 
[dump_economy.patch.txt](https://github.com/widelands/widelands/files/9737369/dump_economy.patch.txt)

BTW the usage help assumes that Widelands is started from the top level of a Widelands source directory. It should mention that the argument to `dofile()` is relative to the directory from where Widelands is started.

**Comment by hessenfarmer** [comment]
I believe portdocks can be ignored as they are (hopefully automatically set by placing the port. so the patch is fine (but could explain that fact in the comment. Feel free to make a PR with it.

**Comment by tothxa** [comment]
> I believe portdocks can be ignored as they are (hopefully automatically set by placing the port.

I thought they store some wares, don't they? But indeed, that's not very important for dump economy.

Actually, do we really need the assert, can't we just ignore all unknown immovables?

> so the patch is fine (but could explain that fact in the comment. Feel free to make a PR with it.

OK. I'm mostly ready, but I want to test – and if I can, fix – some more issues with dump/restore.
