### ISSUE TITLE
Garbled soldier level indicators on freedesktop runtime 22.08

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5602]
**Describe the bug**
See https://www.widelands.org/forum/post/39525/

**Version:**
 - OS: Debian bullseye (host)
 - Widelands Version: 1.1~git25877 (40450cc@master) from flathub-beta

**Additional context**
@Noordfrees Please help identify which libraries may be involved, so that we can check whether it affects other systems with the same library versions. May be another SDL related bug, but I wonder why it affects only the level indicators.

Possible workaround is to make the release flatpak with last year's runtime.

**Comment by Noordfrees** [comment]
Possible libraries at fault are SDL_image and libpng. Which versions of these are used in the runtime?

**Comment by tothxa** [comment]
libSDL_image-2.6.2 and libpng-1.6.37.0

Hmmm, libpng is to be updated to 1.6.38? https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/22.08/elements/components/libpng.bst
They also have some apng [patch](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/22.08/patches/libpng/libpng-1.6.37-apng.patch) for it.

**Comment by Noordfrees** [comment]
I would guess it's most likely another regression of libSDL_image 2.6.2. That version has lots of them.

I installed the latest flatpak beta build and tried converting the images from indexed to RGB, and adding some coloured blobs, and it *still* fails:
![image](https://user-images.githubusercontent.com/48293446/194754164-cef59612-afb8-4b58-bfe0-654eeea4297a.png) ![image](https://user-images.githubusercontent.com/48293446/194754200-704f221f-911e-4e75-8ca6-d1395c030397.png) ![image](https://user-images.githubusercontent.com/48293446/194754171-ef3ac707-a4f7-4163-9a32-fed265fdcd01.png)

Best long-term solution might be to get rid of SDL_image and use libPNG directly. It should not be that much effort (we only use one SDL_image function call) and that library had too many major regressions for my liking recently. But for v1.1 I guess it would be safer to revert to the older flatpak runtime instead.

**Comment by tothxa** [comment]
OK.

**Comment by tothxa** [comment]
Thank you for the help.
