### ISSUE TITLE
Ware priority section get widened on start stop

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5605]
I guess once a player has a specific situation reached during a game, he would likely have the window of the Training camp constantly open to start/stop the training camp depending on the stored wares. But this window covers some of the maps area, especially if the priority sliders are visible. Fortunately those sliders can be hidden so the window is much smaller and does not cover so many parts of the map. But unfortunately if one starts/stop the training camp the priority slider section of the window get widened again.

On big screens one may do not use the possibility to hide the priority sliders but since i am on my laptop with a screen resolution of 1280x800 i use this feature a lot to see more of the map. But the current behavior of widen the window on start/stopping the training camp becomes really annoying. After every click on stop and every click on start i have to make an additionally click to hide the sliders again. Since i have this window in the top right corner the window will move to the left if the priority sliders get widened (start/stop). So i additionally i have to move the window to the right again.
The reason to have this window on the top right might be that the inventory window is opened at the top left of the screen.

**Describe the solution you'd like**
Once the sliders got hidden they should only be widened again if the corresponding button is clicked.

**Describe alternatives you've considered**
Maybe there could also be a configuration option which applies to all buildings which have priority sliders. Something like: "Hide priority sliders on startup"?

**Comment by tothxa** [comment]
This is actually not so trivial.

1. Why is the building window reinstantiated on status change? (`BuildingWindow::on_building_note()` / `wui/buildingwindow.cc:92`)
2. If we want the setting to be remembered, I think it has to be added to the `Building` class in `logic/map_objects/tribes/building.h`, but I don't think it belongs there logically.
3. If it is remembered, should it also be saved in savegames? That needs loading compatibility code.

@Noordfrees Could you please advise how to handle it?

**Comment by Noordfrees** [comment]
I think the only reason why it's completely rebuilt is to update the start/stop button and possibly other buttons correctly. If those were handled by making `on_building_note` `virtual` then that could be cleaned up without having to work around any of those side-effects.

+1 for adding it to savegames.

-1 for storing it in the `Building` class, but we could add it to the registry for each unique window (similar to how the minimap remembers which layers are selected).

**Comment by tothxa** [comment]
Thank you. I'll still try to look into it, but then it's certainly not for #5668.
