### ISSUE TITLE
utils/macos/build_app.sh fails in OSX 12.6 with Apple Silicon

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5610]
**Describe the bug**

Running `utils/macos/build_app.sh` fails with
```
WidelandsRelease/Widelands.app/Contents/MacOS/widelands: replacing existing signature
WidelandsRelease/Widelands.app/Contents/MacOS/widelands: bundle format unrecognized, invalid, or unsuitable
In subcomponent: .../v1.1-rc1/WidelandsRelease/Widelands.app/Contents/MacOS/data/maps/Finnish_Lakes.wmf
  * Error : An error occurred while applying ad-hoc signature to WidelandsRelease/Widelands.app/Contents/MacOS/widelands. Attempting workaround
    cp -p "WidelandsRelease/Widelands.app/Contents/MacOS/widelands" "/var/folders/sq/gy2m486j4nggs6j6w_z658440000gn/T/dylibbundler.NXz3pOjx/widelands"
    mv -f "/var/folders/sq/gy2m486j4nggs6j6w_z658440000gn/T/dylibbundler.NXz3pOjx/widelands" "WidelandsRelease/Widelands.app/Contents/MacOS/widelands"
    rm -rf "/var/folders/sq/gy2m486j4nggs6j6w_z658440000gn/T/dylibbundler.NXz3pOjx"
    codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - "WidelandsRelease/Widelands.app/Contents/MacOS/widelands"
WidelandsRelease/Widelands.app/Contents/MacOS/widelands: replacing existing signature
WidelandsRelease/Widelands.app/Contents/MacOS/widelands: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Users/klaus/develop/widelands/v1.1-rc1/WidelandsRelease/Widelands.app/Contents/MacOS/data/maps/Finnish_Lakes.wmf
  * Error : An error occurred while applying ad-hoc signature to WidelandsRelease/Widelands.app/Contents/MacOS/widelands
```

**Version:**
 - OS: OSX 12.6
 - Widelands Version: v1.1-rc1

**Ideas what could be done**

* Need to dig into that script what command actually fails
* The resulting .app is actually running (So a workaround might be to ignore that error)
* The .dmg (Volume image) is not created and files like README are missing
* Need to compare with "normal" OSX build which seem to not have Issues?

**Comment by klaus-halfmann** [comment]
might be related to #5148

**Comment by klaus-halfmann** [comment]
* It is not a Problem with the Finnish_Lakes.wmf map - removing it just results in some other File 
* Need to use .`/utils/macos/build_app.sh --release `
* Removing data/campaigns and data/maps will do the trick so maybe I need to ignore them
* copying the files after signing makes the app fails to start :-(

igrnorig the result of dylibbundler did the trick, but I do not like it :-(

**Comment by klaus-halfmann** [comment]
Created https://github.com/auriamg/macdylibbundler/issues/79 based on this one.

**Comment by klaus-halfmann** [comment]
OK for release 1.1 need to review this for 1.2 again.
@Noordfrees shall we close this now or leave it open for 1.2?

**Comment by Noordfrees** [comment]
Since the fix is not applied to master this will still be an issue during the release of 1.2 until the upstream bug is fixed. So let's leave it open.
