### ISSUE TITLE
widelands 1.1-rc1: compilation error: use of undeclared identifier 'PATH_MAX'

### ISSUE THREAD

**Issue by AngryPenguinPL** [widelands/widelands#5614]
**Describe the bug**
When compiling widelands 1.1-rc1 on OpenMandriva Cooker I see build error:

```
/builddir/build/BUILD/widelands-1.1-rc1/src/io/filesystem/filesystem.cc:183:11: error: use of undeclared identifier 'PATH_MAX'
DEBUG util.py:446:          char cwd[PATH_MAX + 1];
DEBUG util.py:446:                   ^
DEBUG util.py:446:  /builddir/build/BUILD/widelands-1.1-rc1/src/io/filesystem/filesystem.cc:188:35: error: use of undeclared identifier 'PATH_MAX'
DEBUG util.py:446:          char* const result = getcwd(cwd, PATH_MAX);
DEBUG util.py:446:                                           ^
DEBUG util.py:446:  2 errors generated.
```

Same error on Clang 15.0.2 and GCC compiler.

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/9e9dcb617964e9d37469c17b9007b6fb930fab0d.log?show=true

**To Reproduce**
1. Compile from source widelands 1.1-rc1
2. See error

**Expected behavior**
Compilation ends without errors

**Version:**
 - OS: [e.g. OpenMandriva Cooker]
 - Widelands Version: 1.1-rc1]

**Comment by Noordfrees** [comment]
Fixed in the release branch, and I copied the fix to master as well in 0137d92798011509d8c0869c82357b53ad1bab47
