### ISSUE TITLE
New release of zlib -- bugfix

### ISSUE THREAD

**Issue by RHolton** [widelands/widelands#5620]
I just noticed that zlib has a new release as of October 13. It's a bugfix for a "critical" bug that's listed in the US National Vulnerability Database (run by NIST).

See [the zlib hompage](https://zlib.net/)

I'm not sure if our code is impacted. It may make sense to update the zlib libraries used for the next release.

**Comment by Noordfrees** [comment]
The CVE entry description says "only applications that call inflateGetHeader are affected" and we (neither our embedded minizip version) don't seem to call that function. 

ZLib is an external dependency, the version we use is whichever the CI environment provides. That's not something we can control.

**Comment by klaus-halfmann** [comment]
@Noordfrees all of sudden I get an error when trying to compile Release 1.1:
`ld: library not found for -lminizip`
since when do we depend of this library?

**Comment by Noordfrees** [comment]
We try to detect whether minizip is installed; if so, use the system library; otherwise, use the embedded one we ship as 3rd party code. 
Does the error still happen when deleting the build dir and compiling it fresh? If not, `-DOPTION_FORCE_EMBEDDED_MINIZIP=ON` should help.

**Comment by klaus-halfmann** [comment]
Indeed I installed minizip via brew and yes `-DOPTION_FORCE_EMBEDDED_MINIZIP=ON` did the trick.
Shall I create (and then try to fix) a bug about using the locally installed minizip on macOS?
This could fix #5567 in the end ...

**Comment by andy5995** [comment]
I was looking at the workflow output and noticed a message saying that [minizip would be installed](https://github.com/widelands/widelands/actions/runs/3866930584/jobs/6592102109#step:3:51) but I didn't see that it was (I used the search function in the upper-right).

Lower down, the cmake configuration output said that minizip wasn't found and that it would use the embedded.
https://github.com/widelands/widelands/actions/runs/3866930584/jobs/6592102109#step:4:117

That's running in [macOS 11.7.2](https://github.com/widelands/widelands/actions/runs/3866930584/jobs/6592102109#step:1:4)

**Comment by klaus-halfmann** [comment]
Hello @andy5995 

I am Running macOS 13.1 on a M1 Chip and I tried/found the same but had no time to check/fix this by now. Any help on this issue would be appreciated. Either adapt the existing sources for widelands and/or help CMake to locate Minizip as installed by brew.

**Comment by andy5995** [comment]
@klaus-halfmann When minizip is installed via brew, what's the path to 'minizip.pc'?

**Comment by klaus-halfmann** [comment]
@andy5995 
```
brew   --prefix
/opt/homebrew

brew instal minizip
...
==> Fetching minizip
==> Downloading https://ghcr.io/v2/homebrew/core/minizip/manifests/1.2.13
...
==> Pouring minizip--1.2.13.arm64_ventura.bottle.tar.gz
==> Caveats
Minizip headers installed in 'minizip' subdirectory, since they conflict
with the venerable 'unzip' library.
==> Summary
🍺  /opt/homebrew/Cellar/minizip/1.2.13: 14 files, 382.9KB
...
->  /opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig/minizip.pc
```

**Comment by andy5995** [comment]
Could you try this and see if it works?

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig

Then run cmake and see if it finds the library installed by brew...

**Comment by andy5995** [comment]
If that works, we should be able to add that into the [CMake file (between L79 and L80)](https://github.com/widelands/widelands/blob/89142315a8d5a7e5f56b9727638475bfda495d6b/src/CMakeLists.txt#L79), with an implementation like what's shown here:

https://stackoverflow.com/a/44487317/6838037

Though I'm not sure the best way to implement that. I have no idea why the minizip version is hard-coded into the path. Who's the cmake guy here? @Noordfrees @tothxa @hessenfarmer ?

**Comment by klaus-halfmann** [comment]
Installed minizip via brew
./compile.sh
-> ld: library not found for -lminizip
clang: error: linker command failed with exit code 1 (use -v to see invocation)
export PKG_CONFIG_PATH=/opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig # PKG_CONFIG_PATH was empty
./compile.sh
-> Still ld: library not found for -lminizip :-(

./compile.sh however shows 
```
- Checking for module 'minizip'
--   Found minizip, version 1.2.13

ls /opt/homebrew/Cellar/minizip/1.2.13/lib/
libminizip.1.dylib	libminizip.a		libminizip.dylib	pkgconfig
```

So maybe  -lminizip.a or -llibminizip.dylib is needed?

cat /opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig/minizip.pc 

```
prefix=/opt/homebrew/Cellar/minizip/1.2.13
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/minizip

Name: minizip
Description: Minizip zip file manipulation library
Requires:
Version: 1.2.13
Libs: -L${libdir} -lminizip
Libs.private: -lz
Cflags: -I${includedir}
```

**Comment by andy5995** [comment]
@klaus-halfmann I wasn't very clear before. But this is meant to be entered at the command line.

`export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig`

And then in the same terminal, run cmake or compile.sh. is that what you did?

>So maybe -lminizip.a or -llibminizip.dylib is needed?

According to the .pc file, the correct flag should be '-lminizip'. You can kind of see what cmake is doing by running at the command line

    pkg-config --libs minizip

Cmake should be calling `pkg-config` and adding the output to the build https://github.com/widelands/widelands/blob/89142315a8d5a7e5f56b9727638475bfda495d6b/src/CMakeLists.txt#L79-L80

If you already used `export` the way I explained (and it didn't work), then you could try adding this between L79 and L80, with the same indentation as L80 (src/CMakeLists.txt)

`set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/opt/homebrew/Cellar/minizip/1.2.13/lib/pkgconfig")`

**Comment by andy5995** [comment]
>- Checking for module 'minizip'
--   Found minizip, version 1.2.13

If you get that output but the build still fails, I'd strongly recommend completely removing the build directory and trying again.

**Comment by hessenfarmer** [comment]
this issue is a perfect example of a complete mess due to unrelated discussions. 
From my side the original issue can be closed as zlib is an external dependency.  
If there is still a problem with minizip detection on MacOS we should open a new issue. 
Closing this one as wont fix
