### ISSUE TITLE
Coding question

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5624]
Hi,
This is again a coding question:
In the productionprograms of a productionsite-description there is the attribute `[produced_wares_]` that should hold all wares that could be produced in this productionsite.
this works for almost all productionsites except for a few buildings like "woodcutters_hut" , "hunter_gatherers_hut" or "fishers_house" is there a logical reason ,why that so is?
I looked into the lua-data-tables and the only connection I could find is action to call a worker so I assume the only way to know what these buildings can produce , is throw the workingpositins and the workers there, but not throw the building-desc itself right?
Is there a way to get these produced wares only once? Without having to do it in each iteration of the game? Because at the initialisation the workers are not there yet and the building description doesn’t have These Informations.
I could write an encyclopedia entry into the lua-tables of these buildings if this is desirable and try to merge it.
thanks in advance .

**Comment by Noordfrees** [comment]
The information which wares can be produced by a *productionsite* is stored in the `ProductionSiteDescr`, sorted into *produced* (by a `ProductionProgram`) and *collected* (by a `WorkerProgram`):

https://github.com/widelands/widelands/blob/4ce5025ac8c0dd8e6ab787f21e3df67f768d3200/src/logic/map_objects/tribes/productionsite.h#L282-L295

Each of the sub-programs only stores the wares produced by that particular program.

**Comment by Ahmad-fadl** [comment]
Thanks
