### ISSUE TITLE
Widelands not working on OSX 13

### ISSUE THREAD

**Issue by dante11235** [widelands/widelands#5627]
Hello guys,

24. October OS X 13 was released and when I try to run in, it said that "Widelands is damaged and can't be opened. You should move it to the bin". I try to run latest release (1.1).  I understand that this release is for OS X 12. I just wanted to let you know about this issue. 

When I try to run the daily release(1.2~git1 3fe8e88@master), the game starts, but when i try to start single player game, I get error "/Users/runner/work/widelands/src/graphic/image_io.cc: save_to_png: could not create png struct"

I have MBP 13 M1 with OSX 13.0

Keep up the good work

**Comment by hessenfarmer** [comment]
if you downloaded the new release with a browser a quarantine flag is set for it due to missing signatures. You may try the hints from our download sections.    
https://www.widelands.org/wiki/Download/#arm-apple-silicon-builds

**Comment by dante11235** [comment]
@hessenfarmer great... thank you very much for info. It works flawlessly. I believe we can close this.
