### ISSUE TITLE
Please don't activate ASan nor TSan in RelWithDebInfo cmake mode, to support the official Debian packaging guidelines

### ISSUE THREAD

**Issue by mquinson** [widelands/widelands#5628]
Hello,

I'm part of the official packaging team for Debian, and I would like to drop one of the patches that we have locally:
https://salsa.debian.org/games-team/widelands/-/blob/master/debian/patches/dbg_symbols

This patch simply adds `-g` to the build args in Cmake in Release mode, because Debian wants to retain the debug symbols in the release. These symbols are then automatically stripped and moved to a widelands-dbg package, that can be installed separately by people wanting to get an informative backtrace of their segfault when reporting a bug (or other similar usecases).

 In my opinion, Debian would like to use [intend of the RelWithDebInfo](https://stackoverflow.com/a/59314670/1756334), but I seem to understand that this build type also activates AddressSanitizer or ThreadSanitizer, which is probably not something we would like to do in production, I guess.

Would it be possible to make RelWithDebInfo more in line with Debian expectations? I guess that not setting the sanitizers in this case would be enough. Alternatively, a new cmake configuration dedicated for that would be very nice.

Thanks in advance, Mt

**Comment by tothxa** [comment]
For the Debian package, why can't you just use `-DOPTION_ASAN=OFF` in `debian/rules` instead of patching `CMakeLists.txt`?

But +1 for disabling ASAN with build type `RelWithDebInfo`[^1] anyway.

[^1]: why isn't that DbgInfo BTW? Deb had been mentally reserved for Debian way before cmake was written, hadn't it?
