### ISSUE TITLE
Make additional wares for expeditions more convenient

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5638]
Since [this bug or feature](https://www.widelands.org/forum/post/38414/) does not work anymore (Version 1.2~git25912 (03c78da@master) Debug), the management of additional wares should be more convenient.

**Describe the solution you'd like**
One possible solution was mentioned by [Solstice_s_Return](https://www.widelands.org/forum/post/38417/): Just like the possibility to have predefined economy settings it might be a good idea to have predefined settings for additional expedition items (wares and workers). The possibility to change each entry should remain though.

**Describe alternatives you've considered**
Bring back the [bug or feature](https://www.widelands.org/forum/post/38414/) :-D

**Comment by tothxa** [comment]
Just a rough idea, but maybe adding extra items should get a new window which looks and works similar to the economy target window, but has a counter at the bottom that shows the available empty places, and does not allow more if it's full.

**Comment by frankystone** [comment]
Hm i have known there is already a bug report open for this: #4842

And it covers also your idea, tothxa :)

Closing here as duplicate.
