### ISSUE TITLE
Consider another storing mechanism for replays

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5644]
Replays are stored in two files and one folder. After some games the `replays` folder is full of files. Beside #5643 it should considered to have another mechanism to store those files. This should also prevent to explain what and where those replays are saved for new players.

**Describe the solution you'd like**
One solution might be to zip the files into one file.

**Describe alternatives you've considered**
An alternative would be to store the replay files below a subfolder, e.g.:

`replays/DATE_HOSTNAME/`replay-files

**Implementation steps**
- [ ] 
- [ ] 
- [ ]

**Comment by tothxa** [comment]
I thought this was about more ambitious changes. :) Like coming up with a smart way to store deltas between autosaves, so all autosaves could be included in the replay, which would make it possible to [step back](https://www.widelands.org/forum/post/39559/), and make replays more useful between incompatible versions.

**Comment by frankystone** [comment]
@tothxa I think your idea is worth for another feature request :)
