### ISSUE TITLE
Thinke of SoldierPanel results in heap-buffer-overflow

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5652]
**Describe the bug**

I was playing on master using my snprintf bug fix,
The new feature to show the coming soldiers is nice but seems to have a bug.

**To Reproduce**

1. Load Attached Savegame
2. Check Soldiers at the Bordes
3. Eventually tear down an occupied enemy Building

**Version:**
 - OS: MacOS Ventura 13.0
 - Widelands Version: 1.2~git25924 (aeb9ae2@fix_sprintf)

**Additional context**
I do not think this is related to my branch.

[Crash.zip](https://github.com/widelands/widelands/files/9981047/Crash.zip)

**Comment by klaus-halfmann** [comment]
Just got another one will an extra Savegame / Replay help?

**Comment by klaus-halfmann** [comment]
OK now got it 100% reproducible:
* Open [Crash.wgf.zip](https://github.com/widelands/widelands/files/9990889/Crash.wgf.zip)
* Click on the Castle at 54,25
* Click "Prefer Rookies"
* If game was paused run it
@Noordfrees can you reproduce this, too?
I will now check for a Workaround

**Comment by Noordfrees** [comment]
Yes, that's reproducible for me

**Comment by Noordfrees** [comment]
I think this is related to #5437: The soldier list now wants to show the 12 soldiers stationed in the building plus the 1 soldier assigned to come to the building, totalling 13 soldiers to display. But the display has only 2 rows with 6 columns each, so there isn't enough space. 
So the display must expand to show an extra row in this case.

**Comment by klaus-halfmann** [comment]
Also happens in the second tutorial
