### ISSUE TITLE
macOS: tutorial results in crash "nextEventMatchingMask should only be called from the Main Thread!'"

### ISSUE THREAD

**Issue by Spectrik** [widelands/widelands#5655]
**Describe the bug**
Hello team,

every time I start a game of tutorial, it crashes after clicking OK in the following window (see below)

**To Reproduce**
1. Download game via curl mentioned here https://www.widelands.org/wiki/Download/ (for Arm / Apple Silicon Builds)
2. Mount image, move game to the applications folder
3. Run the game from applications folder
4. Start tutorial
5. Click OK in the window shown below
6. See error

**Expected behavior**
No error.

**Screenshots**

![bugwindow](https://user-images.githubusercontent.com/7544328/201518068-3efc6229-a066-44ab-b19f-cfeaf8bfc5f6.jpg)

**Version:**

> Version: 1.1 Release  
> Operating System: macOS Monterey 12.6 M1 Pro
> Compiled with SDL version: 2.24.1  
> SDL video driver: cocoa  
> Locale: en  
> Home Directory: /Users/ojanas/.widelands  
> Configuration File: /Users/ojanas/.widelands/config  
> Data Directory: /Applications/Widelands.app/Contents/MacOS/data  
> Locale Directory: /Applications/Widelands.app/Contents/MacOS/data/locale  
> Executable Directory: /Applications/Widelands.app/Contents/MacOS/  

**Additional context**
File with traceback attached. This error happens every time.

[traceback.txt](https://github.com/widelands/widelands/files/9996989/traceback.txt)

Thank you very much for looking into this.

**Comment by klaus-halfmann** [comment]
Hello @Spectrik thanks for your Bugreport, can you please try as well with the Intel Version?

I will try to reproduce this with the "official" Build and a debug build today.

**Comment by klaus-halfmann** [comment]
* Confirm happens with "Official" Build :-(
* Happens in Debug Build as well
* Happens in official x86 Build as well.

Moral: try all the Tutorial for debugging, too.

Looks like this is an macOS specific, thread / SDL Related Issue:
```
2022-11-13 12:15:36.338 widelands[12122:455929] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000187818418 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000187362ea8 objc_exception_throw + 60
	2   AppKit                              0x000000018a9f4020 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2872
	3   libSDL2-2.0.0.dylib                 0x000000010382b2e8 Cocoa_PumpEventsUntilDate + 84
	4   libSDL2-2.0.0.dylib                 0x000000010382b498 Cocoa_PumpEvents + 56
	5   libSDL2-2.0.0.dylib                 0x00000001037a9108 SDL_PumpEventsInternal + 64
	6   widelands                           0x00000001024dcaf4 _ZN13WLApplication10warp_mouseE7Vector2IiE + 124
	7   widelands                           0x0000000102663c8c _ZN2UI12BaseDropdown19set_list_visibilityEbb + 364
	8   widelands                           0x0000000102a36840 _ZN5LuaUi11LuaDropdown14highlight_itemEP9lua_State + 136
	9   widelands                           0x0000000102ae5798 luaD_precall + 600
	10  widelands                           0x0000000102afd974 luaV_execute + 792
	11  widelands                           0x0000000102ae60f4 unroll + 164
	12  widelands                           0x0000000102ae4ebc luaD_rawrunprotected + 84
	13  widelands                           0x0000000102ae5d34 lua_resume + 244
	14  widelands                           0x0000000102a8915c _ZN12LuaCoroutine6resumeEv + 56
	15  widelands                           0x00000001029bdc48 _ZN9Widelands15CmdLuaCoroutine7executeERNS_4GameE + 48
	16  widelands                           0x00000001029bfdf8 _ZN9Widelands8CmdQueue9run_queueERK8DurationR4Time + 160
	17  widelands                           0x00000001025ade34 _ZN9Widelands4Game5thinkEv + 176
	18  widelands                           0x0000000102674588 _ZN2UI5Panel12logic_threadEv + 180
	19  widelands                           0x00000001024e2174 _ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvvEEEEEEPvSA_ + 44
	20  libsystem_pthread.dylib             0x00000001876be06c _pthread_start + 148
	21  libsystem_pthread.dylib             0x00000001876b8e2c thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      ./widelands
```

@Spectrik Good news: we can reproduce the Bug. Bad News: fixing this will not be _that_ easy.
Please try the tutorial from Release 1.0 for now (There was not a big change, there)

@Noordfrees any idea how to call this lua funcktion `ZN5LuaUi11LuaDropdown14highlight_itemEP9lua_State + 136` from the main thread?

**Comment by klaus-halfmann** [comment]
For the record: Happens in master, too.

**Comment by Noordfrees** [comment]
`ZN5LuaUi11LuaDropdown14highlight_itemEP9lua_State + 136` translates to `LuaDropdown::highlight_item()` which is called from Lua via 

https://github.com/widelands/widelands/blob/2a1614029a4b6e0cef78f79efa782ec91a804528/data/campaigns/tutorial01_basic_control.wmf/scripting/helper_functions_demonstration.lua#L83

https://github.com/widelands/widelands/blob/2a1614029a4b6e0cef78f79efa782ec91a804528/data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua#L57

Lua code is run by the logic thread. You can wrap the implementation of `LuaDropdown::highlight_item()` in a `NoteThreadSafeFunction::instantiate` to force running it from the main thread.

**Comment by Spectrik** [comment]
@klaus-halfmann 

I've tried to install the game via `brew` (intel version I guess) and this time it seems to be ok.

**Comment by klaus-halfmann** [comment]
@Spectrik Please check the version, brew might still be 1.0 (which is actually the workaround you can use)

**Comment by klaus-halfmann** [comment]
> Lua code is run by the logic thread. You can wrap the implementation of `LuaDropdown::highlight_item()` in a `NoteThreadSafeFunction::instantiate` to force running it from the main thread.

a) Do you have an example for that "wrap" for me?
b) There will be a lot of functions that may need this fix. 

I will setup a branch for master for now (I will need the snprintf fix for 1.0, too)

**Comment by Noordfrees** [comment]
Just search for `NoteThreadSafeFunction::instantiate` across the codebase, we use it in many places, for example:
https://github.com/widelands/widelands/blob/2a1614029a4b6e0cef78f79efa782ec91a804528/src/graphic/font_handler.cc#L93-L97

Please add such wrapping only as-needed. I think the two functions of `LuaUi::LuaDropdown` may be the only ones that need it.

**Comment by klaus-halfmann** [comment]
@Spectrik please try this Build: https://github.com/widelands/widelands/suites/9277583464/artifacts/434851631
Its an x86 one, but should work anyway. There may be other bugs (as this as a very early builld of 1.2)
Getting this into 1.1 will take a little longer

**Comment by klaus-halfmann** [comment]
Release for brew was kind of lost at https://github.com/Homebrew/homebrew-core/pull/113841 ?

**Comment by klaus-halfmann** [comment]
@Noordfrees can we
a) merge this into master and a similar on into relase 1.1
b) Can someone please help the homebrew people to get there compile script  fixed
     See https://github.com/orgs/Homebrew/discussions/392 and https://github.com/Homebrew/homebrew-core/pull/113841
    This should be quite simple but Will have enough time for widelands in January only

**Comment by Noordfrees** [comment]
Updated build is up for download under https://github.com/widelands/widelands/releases/download/v1.1/Widelands-1.1-MacOS11.dmg

**Comment by superfloh247** [comment]
Hi,

I downloaded https://github.com/widelands/widelands/releases/download/v1.1/Widelands-1.1-MacOS11.dmg and started the first tutorial

in step3 "I'll show you where to find ..." the menu opens and the menu items are selected one after the other. Then WL completely freezes.

MacOS 14.2, AppleSilicon m1

**Comment by klaus-halfmann** [comment]
@superfloh247 thanks for you report, you can try to use https://github.com/widelands/widelands/releases/download/v1.1/Widelands-1.1-MacOS12-Arm.dmg But I would not assume this fixes the Bug.

If it still happens please file a seperate Bug...

**Comment by vessenes** [comment]
I just experienced this bug in brew --cask install of widelands 1.2.1 on macOS ARM.
