### ISSUE TITLE
Soldiers not immediately requested

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5658]
Ran into this situation several times now:
Sometimes military sites shows soldiers are missing although soldiers are waiting in a warehouse. The requests for the missing soldiers are only made when a soldier arrived at the military site.

**To Reproduce**
1. Load attached save game, one window shows missing soldiers in the tower, one window shows missing soldiers in a Barracks
2. Check soldiers in the warehouse nearby and the headquarters, there are enough soldiers
3. try to make new requests by reducing the amount of soldiers in the military sites. This does not force soldier requests.
4. Wait a minute until a soldier arrives at the Tower
5. Now the missing soldiers are requested and they are on the way

Maybe the soldiers in the warehouse and the headquarters just fulfilled the request to go to the warehouses while the request of the tower was made, so maybe there aren't enough soldiers at all the time they were requested by the military sites. Can't remember anymore if this was the case.

Anyway this is very irritating.

**Expected behavior**
Forcing requests for soldiers by reducing and increasing the amount of soldiers in the military site should be available.
And if soldiers arrive at a warehouse check for missing soldiers in military sites and make a request for them.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.2~git25938 (49127d0@ferry-options-tweaks) Release

Probably this issue was there before #5437 was implemented and get noticed just because of that?

[save game](https://github.com/widelands/widelands/files/10014377/test_1.zip)

**Comment by frankystone** [comment]
Looks like fixed in #5930

**Comment by tothxa** [comment]
@frankystone Doesn't this still affect master? (only fixed in navalwarfare, hence the "fixed" label)

**Comment by frankystone** [comment]
Oh sorry, didn't checked that this is only fixed in naval warefare. I don't know if this still happens in master... less play time this summer.

**Comment by tothxa** [comment]
I was able to reproduce it in current master, and reconfirmed fix in current navalwarfare.

**Comment by frankystone** [comment]
You are unbelievable!

And sorry for the extra work...
