### ISSUE TITLE
Cannot become Red Player in Singleplayer on CometIsland

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5660]
**Describe the bug**

Try Playing Singleplayer on the Map CometIsland, you are always stuck with the Blue Player?

**To Reproduce**

1. Open Singleplayer
2. Choose Map Comet Island
3. Try to make the Red Player "You"
4. Gui uses correct position but switches Colors

(In fact these _are_ different players But the Map description does not match the colors in the end ...)

You can find a Video at: https://magentacloud.de/s/e7BHdHH2tgNLXLJ 

**Expected behavior**

* Colors should not change during this selection
* OR Map description should nor refer to colors.

**Version:**
 - OS: should not matter
 - Widelands Version: master but 1.1 is the same

**Additional context**

Is this just a glitch an we should ignore is?

**Comment by Noordfrees** [comment]
When changing your player slot, all your settings are carried over – tribe, starting condition, team, and also player colour. Don't forget you can change your colour by clicking on the colour button. 

Referring to colours in map descriptions is bad style, they should better say "Player 1" or "The south-eastern player" to be less ambiguous.

**Comment by klaus-halfmann** [comment]
So the "fix" would be to change the description, OK.

**Comment by tothxa** [comment]
> When changing your player slot, all your settings are carried over – tribe, starting condition, team, and also player colour. Don't forget you can change your colour by clicking on the colour button.

I think it would make sense to keep track of whether each player changed their colour, and only carry over the colours if any of the involved players did. Or maybe even only carry over the colour of those players who changed it, and revert their old slot to default if the other player hadn't changed theirs.

**Comment by frankystone** [comment]
> > When changing your player slot, all your settings are carried over – tribe, starting condition, team, and also player colour. Don't forget you can change your colour by clicking on the colour button.
> 
> I think it would make sense to keep track of whether each player changed their colour, and only carry over the colours if any of the involved players did. Or maybe even only carry over the colour of those players who changed it, and revert their old slot to default if the other player hadn't changed theirs.

:+1: 

In the last [tournament on round 3](https://www.widelands.org/forum/topic/5613/?page=1#post-39039) i was a bit confused when i set up the first game for testing, because the blue color was exchanged with the white starting position.
Changing tournament descriptions to something like "4th player against 8th player" makes setting up a game more complicated because one has to count the player slots.

**Comment by frankystone** [comment]
As seen in the last battle royale the colors are important. Another solution might be to add player numbers to the game setup screen. So player colors and player numbers can be different.
