### ISSUE TITLE
MSVC builds are broken

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5675]
since a couple of days our MSVC Builds seem to be broken.
@matthiakl

**Comment by RHolton** [comment]
For some reason, the X64 builds are trying to reinstall and rebuild (some of?) the vcpkg libraries. Looks like the job times out.

Also, the X86 release build errors out. Either one or more package from glbinding was unexpectedly compiled with /GL (whole program optimization) or some libraries were compiled with an older version of the compiler.

Just a guess, but it sounds like the vcpkg libraries are out of date/out of synch. I don't know how to go about updating them for the automated builds.

**Comment by matthiakl** [comment]
This looks to be the same as #5511 again: The Visual Studio and Compiler components were not updated in sync. It has already been reported to github runners and was fixed on Nov 25. It will be deployed this week (usually Wednesday or Thursday).

**Comment by matthiakl** [comment]
New runner image 20221127.1 is deployed and the builds are working again.
