### ISSUE TITLE
Do all tables really need to be sortable by any column?

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5677]
I noticed while working on #5668 that currently the user can change the sorting order of all tables to use any column. This doesn't hurt, but it is unexpected in some cases and can give strange results:

 - tutorials
 - scenarios in a campaign
 - save economy options (has only one column, so it can only be reversed)
 
In some cases it just doesn't make sense, because there are only a few entries:

 - workers in a building
 - campaigns

Should we have a way to disable user sorting of these tables?

**Comment by frankystone** [comment]
> Should we have a way to disable user sorting of these tables?

I think the main use case for sorting tables are on the map selection screens. I do not have any meaning on sorting other tables. In the past it was never be an issue, afaik, also if a player sorted a table by accident. Mostly reopening the window reverts the ordering to the default, so this isn't a big issue, imho.

If it is not too much work i am not against disabling sorting. If it needs much code changes i would leave it at it is right now and wait until user reports they get confused about it.

**Comment by tothxa** [comment]
It would be easy, just an additional bool member variable default initialised to allow sorting, so only disabling would need changes in the users. Plus maybe automatic checks to also disable sorting if there's only one row or column.
