### ISSUE TITLE
Changing between Hero and Rookie causes crash.

### ISSUE THREAD

**Issue by Casteele72** [widelands/widelands#5700]
**Describe the bug**
When switch a fully built military site between "Rookie" and 'Hero' (either way), the game crashes. I am not certain if it was immediate or delayed, but it affected my save file: Now the game crashes when I click the site to bring up the site info window at all. (No error message or window, it just crashes and dumps me to desktop.)

While I have not done extensive testing, it only appears to cause an issue with a fully built and operational site; It does not seem to effect sites still under construction, and allows me to switch the 'When completed" settings.

**To Reproduce**
Build a military site, and change the "prefer rookie/hero" setting. Game crashes (immediately at his point, but it may not have been immediate initially). At this point, it crashes if I click the site at all, without getting as far as the ability to see and change the setting.

**Version:**
 - OS: [e.g. Ubuntu 18-04]
Debian Linux:
$ uname --all
Linux EARTH 5.4.0-0.bpo.4-amd64 # 1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

 - Widelands Version: [e.g. "Build 20", "`73f9eb5c0b26599b72609f3e27de569f49049269`"]
(From the main screen): Version 1.2 ~ git25948 (5ee56b0@master) Release
Note: I am running the FlatPak download version, as I was not able to get any other version to work with my system.
The launcher command is "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=widelands org.widelands.Widelands", if that is helpful in any way. I do not know more than that at this time.

**Additional context**
I do have a save file with the issue. I also have used a memory "trainer" (Game Conqueror, under Linux) at one point to try a scenario with ~5000 of all resources. I have not tried an other version as I have not been able to successfully compile and/or execute any other downloadable packages. (Well, except the Debian upstream version, which is extremely out of date...)

**Comment by Noordfrees** [comment]
This may be the same problem as #5652

**Comment by Casteele72** [comment]
From #5652:

> I think this is related to #5437: The soldier list now wants to show the 12 soldiers stationed in the building plus the 1 soldier assigned to come to the building, totalling 13 soldiers to display. But the display has only 2 rows with 6 columns each, so there isn't enough space. So the display must expand to show an extra row in this case.

This gave me an idea to try something: I loaded the game, paused it, and then was able to click a mil site (a castle) as well as change between Rookie/Hero, both without an immediate crash. It also did _not_ immediately crash when I un-paused. It did crash shortly after, however, when clicking the site again shortly after -- I wanted to see if it had a new Hero assigned. However, it did not appear to be related to needing a new row: It still crashed when I reduced the soldier count so it would not need a new row -- but it still needed an additional spot for the newly assigned hero it wanted to swap. It also crashed when I clicked a tower that did not need an additional row, but did need an additional soldier spot.

I also observed (and was the original reason I was changing assignments) that game kept trying to re-assigned more experienced soldiers repeatedly. Sometimes it would re-assign the soldier that it just replaced. This resulted in a continuous shuffling of soldiers between sites. (Which may be a bug on it's own...?)

**Comment by Casteele72** [comment]
Further information to help identify the source of the issue:

I found I do have _two_ game versions installed in FlatPak: Beta (v1.2) and Stable (v1.1). The problem only seems to exist in Beta/v1.2, but not Stable/v1.1. This suggests that something added or changed since v1.1 is causing the crash. Maybe that will help locate and fix the issue.

**Comment by Casteele72** [comment]
Further information to help identify the source of the issue:

I found I do have _two_ game versions installed in FlatPak: Beta (v1.2) and Stable (v1.1). The problem only seems to exist in Beta/v1.2, but not Stable/v1.1. This suggests that something added or changed since v1.1 is causing the crash. Maybe that will help locate and fix the issue.
