### ISSUE TITLE
Crash during startup when calling glGenFramebuffers()

### ISSUE THREAD

**Issue by gpalino** [widelands/widelands#5721]
**Describe the bug**
Crash dialog after starting exe: Widelands has stopped working.

**To Reproduce**
It is always reproducible on the PC - I've tried version 1.1 and latest HEAD, both with installer and custom compilation.

**Version:**
 - OS: Windows 7 SP1, 64 bit
 - Widelands Version: 1.2~git25988 (fb54e5b@master) Debug

**Additional context**
Attached is the patch I used to find reason, with the help of log messages.
When running exe from gdb inside MSYS2, no usable backtrace is visible.
[w3.patch](https://github.com/widelands/widelands/files/10285964/w3.patch)
[stdout_w3.txt](https://github.com/widelands/widelands/files/10285967/stdout_w3.txt)
[gdb.txt](https://github.com/widelands/widelands/files/10285968/gdb.txt)

**Comment by frankystone** [comment]
Which graphics card is in use?

**Comment by gpalino** [comment]
![graphic_card](https://user-images.githubusercontent.com/28236775/209192487-42bd16f7-2944-4829-8885-f6cf938b3dca.png)
It is Intel Graphics Media Accelerator HD - onboard card of Fujitsu Lifebook E780.

**Comment by hessenfarmer** [comment]
Well I think we can't do much about this as it first seems to be an OpenGL Issue and second we know about issues with some Intel drivers that we can't do much about and third we do not support win7 anymore as nobody of us has still such a machine to test.
