### ISSUE TITLE
Fri05: missing wares during trade

### ISSUE THREAD

**Issue by vworldat** [widelands/widelands#5736]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
The trade goal in the recently introduced Fri05 campaign szenario says: for 7 fruit, fish, barley and honey each you get 1 coal, 1 gold ore, 3 granite, 1 log and 2 iron ore.

Watching the inventory closely I discovered that there is no log and coal coming in. Gold, iron and granite are traded in as depicted.

**To reproduce**
1. Play fri05
2. Send 7 each of fruit, fish, barley and honey to a port
3. See granite and ores going up while log and coal stay the same

**Expected behavior**
I'd love that additional logs and coal :)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/650955/210890823-4e9ec594-08b7-4cff-a3bb-4c1e6e22bd3b.png)

**Version:**
 - OS: "openSUSE 15.4"
 - Widelands Version: "`baecae6176eebc073022a017296e5fdb72128e4d`"

**Comment by hessenfarmer** [comment]
which inventory do you watch, as there are several ones

**Comment by vworldat** [comment]
I'm watching the port doing the trade as well as "wares in storehouses".

**Comment by vworldat** [comment]
Sorry for the inconvenience: after seeing lots of "game speed too high" warnings in the console I reduced speed. Those workers are just so fast the inventory doesn't have time to show the logs and coal! Everything is fine :)
