### ISSUE TITLE
Editor: Can't reach some fields when placing terrains

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5738]
Some fields can't be reached with the mouse cursor anymore. In this screenshot the field below the mouse can't be reached:

![cant_reach_field](https://user-images.githubusercontent.com/6730556/211191207-c7aa90a7-e25c-401c-a684-ac55622bc59f.png)

**To reproduce**
1. Open Editor and create a new map, choose water as terrain
2. Try to place some other terrains

Some fields can't be set with the chosen terrain.

**Expected behavior**
All field s should be reachable

**Version:**
 - OS: archlinux
 - Widelands Version: 1.2~git26011 (3571958@master) Debug

**Additional context**
Some of the latest commits may lead tot this. But i can't say with which version exactly causes it.

**Comment by Noordfrees** [comment]
Apparently caused by https://github.com/widelands/widelands/commit/7ba9a597943bb2f8a70c26a183a1c2fec51092b1#diff-f6df28c5ca0421dd5d79e8f6238cf997a8f571a9dddbf99933317fc6dc09cacc
