### ISSUE TITLE
Slackbuild for widelands needs updating for v1.1

### ISSUE THREAD

**Issue by andy5995** [widelands/widelands#5742]
The Slackbuild for widelands needs to be updated for v1.1. Does anyone have contact with the maintainer listed at https://slackbuilds.org/repository/15.0/games/widelands/ ?

**Comment by hessenfarmer** [comment]
As far as I know the slack package has been created without any involvement from our side.
So @andy5995 feel free to contact the maintainer and or take responsibility for maintaining the slackware packages.
In the latter case you will be listed as maintainer on our homepage if you wish.
@Noordfrees shall we close this issue as it is about packaging for a distro not listed on our official support list.
