### ISSUE TITLE
Scenario scripting in MP Scenario Islands Hopping is not working correctly

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5743]
**Describe the bug**
The scripting seems to have problems with soldiers, as no soldiers are taken to the third island.      
There may be other problems as well, as the scenario is very old

**Comment by klaus-halfmann** [comment]
We had a nice testplay in Version: 1.2~git26021 (bc9c2ca@5622-notifications-mutex)
reaching the third Island was possible but it was completly unclear why and which 
Resources wherer transferred. Our Assumption is that the scenario Luascript is broken
as of some API changes.
* To my surprise the resources from the first Island where transferred during the  last hop.
* The distribution of fertile soil for planting Trees on the second Island is different for player 1 and 2
* The help text should _not_ indicate any tactics what to do, my Guess is, that a Speedrun might do the Job, but getting some trained Soldiers could help in the End. Not sure if we can balance this any further.

It still was fun!

**Comment by hessenfarmer** [comment]
Well,   
from what I found out, everything works as intended except soldiers.
Wares and workers are transferred from the first and second island correctly. And it is indicated in the texts that the production from the first island is transferred to the third island as well. 
soldiers do not work, as HQ and warehousses of any island are worked sequentially and the ser_soldiers command is overwriting the previous values. I am working on it
