### ISSUE TITLE
write replay option is shown when scenario is chosen

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5745]
**Describe the bug**
When a scenario is chosen from the normal game setup (e.g. from the folder Single player scenarios or Multiplayer Scenarios) the option to write replays is shown in the setup, although it is not working.    

**To reproduce**
try to setup a new game with a scenario map.

**Expected behavior**
the tickbox should be greyed out like peaceful in non peaceful win conditions

**Comment by tothxa** [comment]
Ideal (but much harder) solution would be to fix #4531, ie. implement replay writing for scenarios.

**Comment by Noordfrees** [comment]
Closing this as this was quickfixed in #5853, and the "proper" solution is already a separate issue as #4531
