### ISSUE TITLE
MSVC CI Builds are failing 

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5757]
**Describe the bug**
All MSVC builds in our CI chain are failing due to no proper version of the libtool src can be downloaded. 
this is maybe a vcpkg issue but I don't know.

**To reproduce**
Just look at the logs of any recent PR or master

@matthiakl: any idea?

**Comment by matthiakl** [comment]
I already looked at it, but did not create an issue (maybe I should next time, sorry...).
The libtool version vcpkg wants to use is no longer available in the msys repository. This creates a failing dependency chain.
Just waiting for https://github.com/microsoft/vcpkg/pull/28919 to be merged, then deployed on Github runner.

**Comment by hessenfarmer** [comment]
ok the PR got merged but is not yet deployed.  
However while checkiong the deployment I found a log message in the cache section, that a command used by our setup is deprecated maybe this will affect our build actions

**Comment by matthiakl** [comment]
I also noticed the deprecation warning, but it does not affect anything currently. We have time until September 27th to update our actions.
I am working on a branch to update our workflow to resolve the warnings.
