### ISSUE TITLE
Widelands master fails to compile with musl libc

### ISSUE THREAD

**Issue by akdjka** [widelands/widelands#5760]
The issue is the use of __WORDSIZE. 
https://github.com/widelands/widelands/blob/0a899171bffec4f62c028b74cf5c90953963f6ff/src/base/macros.h#L138
glibc defines it in `bits/wordsize.h`, but musl in `bits/reg.h`. I don't quickly see the former being included, so maybe it is incuded implicitly somewhere...anyway the musl header is not.

How about avoiding its use and platform detection altogether and doing instead
```
#include <climits>
#if (SIZE_MAX == 0xffffffffffffffff)
 #define PRIuS "lu"
 #else
 #define PRIuS "u"
 #endif
```
?

**Comment by matthiakl** [comment]
Hi,
please consider our templates for future issues to provide all relevant information.
Which OS are you using?

In glibc `bits/wordsize.h` is included through `<cinttypes>`. In musl `bits/reg.h` is included through `sys/reg.h`. So the easiest way would be to add a `#include <sys/reg.h>` which is also a standard header.

**Comment by akdjka** [comment]
Sorry, if ask GH to reference a line of code in a new issue, it doesn't show a template. I didn't think that going through a different path to report it would give a different result.

Please let me fill the template now:

**Describe the bug**
Widelands 0a899171bf fails to compile with musl libc

**To reproduce**
Steps to reproduce the behavior:
1. ./compile.sh
2.  I get the following error:
```
FAILED: src/base/CMakeFiles/base_md5.dir/md5.cc.o
/usr/lib/llvm/15/bin/clang++ -DASIO_STANDALONE -DUSE_XDG -DWL_USE_GLVND -I/home/m/w/widelands/src -I/home/m/w/widelands/build/src -I/usr/include/minizip -g  -std=c++17  -DDEBUG -g -fsanitize=address -fno-omit-frame-pointer -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-exit-time-destructors -Wno-global-constructors -Wno-padded -Wno-sign-conversion -Wno-missing-noreturn -Wno-switch-enum -Wno-weak-vtables -Wno-unreachable-code -Wno-documentation -Qunused-arguments -Wint-to-void-pointer-cast -Winconsistent-missing-override -Werror -I/usr/include/minizip -Wno-reserved-id-macro -MD -MT src/base/CMakeFiles/base_md5.dir/md5.cc.o -MF src/base/CMakeFiles/base_md5.dir/md5.cc.o.d -o src/base/CMakeFiles/base_md5.dir/md5.cc.o -c /home/m/w/widelands/src/base/md5.cc
In file included from /home/m/w/widelands/src/base/md5.cc:27:
/home/m/w/widelands/src/base/macros.h:138:5: error: '__WORDSIZE' is not defined, evaluates to 0 [-Werror,-Wundef]
#if __WORDSIZE == 64
    ^
1 error generated.
[256/1733] Building CXX object src/base/CMakeFiles/base_exceptions.dir/exceptions.cc.o
```

**Expected behavior**
Widelands should build

**Version:**
 - OS: Gentoo AMD64 with musl and clang
 - Widelands Version: 0a899171bf

**Comment by akdjka** [comment]
Yes, inclusion of `sys/reg.h` should work.
I suggested the fix based on:
https://github.com/rpm-software-management/libdnf/issues/1146
There there is a report than __WORDSIZE causes issues on Mac as well. The check of SIZE_MAX value is quite a bit simpler than the current detection and should be more portable than adding `sys/reg.h` inclusion.

BTW, there is one more compilation issue, in i18n. After working around it (I can't say that the quick change that I did is a fix) the code fails to start opengl.
I suppose I should file 2 more issues for that rather than continuing here, right?

**Comment by akdjka** [comment]
I just tried including `sys/reg.h`.
It works, but prints a warning:
```
[66/1532] Checking macros.h with CodeCheck
/home/m/w/widelands/src/base/macros.h:23: This include block must only contain C++ headers and must come first.
```

**Comment by matthiakl** [comment]
Ok, thanks for the feedback. I see why you want to remove `__WORDSIZE`, but instead of comparing to a raw value `SIZE_MAX` could be compared against `UINT64_MAX`. I think this is more readable.
Can you please try out my patch here https://github.com/matthiakl/widelands/commit/46907aceb9e74505e84bda92103bab7ec5ba7edb (as [patch](https://github.com/matthiakl/widelands/commit/46907aceb9e74505e84bda92103bab7ec5ba7edb.patch)) and see, whether it compiles for you?

If you think the opengl issue is also related to musl, just add it here, if it is something different, open a new ticket.

**Comment by akdjka** [comment]
This one compiles. It still fails to start, I will report it separately later.

One more suggestion here: how about doing printf format detection using SIZE_MAX on all platforms? Seems it would be as correct on Windows as on *nix?

**Comment by matthiakl** [comment]
I opened a PR now with the fix.
> One more suggestion here: how about doing printf format detection using SIZE_MAX on all platforms? Seems it would be as correct on Windows as on *nix?

I'm not sure about it. `PRIu64` is defined as `"llu"` on Windows systems, which might lead to other errors when combined.
https://github.com/widelands/widelands/blob/68df8cb41d71cd642fa0d6d08119c4ba0dd05a7f/src/base/macros.h#L132-L136

If you are interested, you can contribute the dependency list for your system. Gentoo is missing in the `install-dependencies.sh` script.
https://github.com/widelands/widelands/blob/68df8cb41d71cd642fa0d6d08119c4ba0dd05a7f/install-dependencies.sh#L139-L141
