### ISSUE TITLE
Widelands fails to initialize glew on Gentoo/Sway

### ISSUE THREAD

**Issue by akdjka** [widelands/widelands#5762]
**Describe the bug**
I built widelands on my system, but it fails to start.
The log says:
```
[00:00:00.029 real] INFO: Graphics: Try to set Videomode 800x600
[00:00:00.032 real] ERROR: glewInit returns 4
[00:00:00.032 real] ERROR: Your OpenGL installation must be __very__ broken. Unknown error
```

**To reproduce**
./widelands

**Expected behavior**
widelands should start

**Version:**
 - OS: Gentoo with musl and clang. For graphics I use Wayland/Sway. I have XWayland support compiled-in.
 - Widelands Version: https://github.com/matthiakl/widelands/commit/46907aceb9e74505e84bda92103bab7ec5ba7edb

**Additional context**
I see that the error is `GLEW_ERROR_NO_GLX_DISPLAY`. So I checked my glx support...and glxinfo seems fine.
[glewinfo.txt](https://github.com/widelands/widelands/files/10498651/glewinfo.txt)
[glxinfo.txt](https://github.com/widelands/widelands/files/10498652/glxinfo.txt)
[visualinfo.txt](https://github.com/widelands/widelands/files/10498653/visualinfo.txt)

**Comment by matthiakl** [comment]
This is #4958
However, I could not reproduce it myself (OS: void Linux musl, Wayland/Sway). There Widelands runs without problems.
You may try setting `SDL_VIDEODRIVER=x11`
