### ISSUE TITLE
Support macOS Catalina

### ISSUE THREAD

**Issue by Nordsoft91** [widelands/widelands#5767]
For older MacBooks, like mid 2012, it's not possible to upgrade macOS higher than 10.15.7

1.0 version supports it, but 1.1 doesn't.

**Comment by hessenfarmer** [comment]
Well, our policy is to support all OS that are still supported by their vendor. And macOS Catalina fell out of support shortly before our release. 
Anyhow you might try to compile the game yourself.
I don't know whether there is a chance that the provided builds would run on a lower OS version, but for both questions @klaus-halfmann might have some advice.

**Comment by klaus-halfmann** [comment]
I cannot not build this as I am way ahead on a M1 Mac with Ventura 13.3 . @SirVer  had/has such an old machine, but builds tend to fail sooner or later, You can try the Build from him at https://www.widelands.org/~sirver/wl/macos_daily/ which is MACOS_10_9_OR_HIGHER but these are based on head and the latest is from 09-May-2022.

So @Nordsoft91 if these builds are working for you we might ask him to compile 1.2 or such.

**Comment by SirVer** [comment]
@klaus-halfmann My widelands build broke a long time ago and I had the hope I would find the time to fix it. Since nobody complained about if for nearly a year now, I believe(d) the value add is not super high. I do not know right now when I will find the time to fix the build - I am blatantly quite swamped with life right now.

**Comment by hessenfarmer** [comment]
As @SirVer announced he can't provide nighlies any longer on our website. I close this one as won't fix, due to not having any possibility to compile such builds.
