### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5771]
Hi,
This is rather a question about the source code and not a bug.
Can someone please explain or tell me the part of the source code that is responsible for creating production requests for an AI player?
for example, if bread is needed somewhere but there is non in the whole economy, so we need to produce bread. Does this affect bread production somehow? to make it faster? or are bakers producing bread anyway and this has nothing with the total demand or the fact that bread is now needed?
I tried to find a connection between "target_quantity" and the production but I couldn’t find any.
can you also please tell me a part of the source code where a ware_request is issued? I was able to find where worker_requests get issued but never the ware_requests.
Thanks in advance.

**Comment by hessenfarmer** [comment]
the production of any ware is controlled for each player (including AI player) in the same way. Each production site or worker as its production programs. These programs are executed always or in dependency of the economy, but the dependency needs to be set in the production program. These programs are defined in the init.lua files in the data/tribes/ folders. Most common for example is the line: "return=skipped if economy does not need the ware". The neededness of a ware in the economy is determined by checking the amount of wares in the warehouses. If there are less wares on stock then defined by target_quantity a ware will be produced. If more are on stock the production is skipped.  From a coding point of view the production programs are parsed by src/logic/map_objects/tribes/productionprogram.cc and the execution is controlled in the productionsite.cc the neededness is calculated here https://github.com/widelands/widelands/blob/076f336b3c22231900d30b05e3d1017b2ab0659f/src/economy/economy.cc#L507

Ware requests are mostly created by src/economy/inputqueue.cc where all inputqueues of the productionsites are handled. but the ware requests can be created by a portdock as well. Just search for the code fragment "new Request(" to find the instances in our files where a request is created.

**Comment by Ahmad-fadl** [comment]
Thanks for the answer.
If the only dependency will be checked inside the productionprograms.
This means the economy has no influence on, which productionsite should start producing (the nearest one to where this ware is needed for example).
I just want to make sure I understood it correctly.
If the dependency exists and if ware is not needed for now then all productiosites , which produce it, will stop(by skipping the action).
once this ware is needed again, then all productionsites will start producing it at the same time right?
(I didn’t find where ware-requests are created , because I was hoping to find a direct dependency between neediness and initialising a new request, so I was only searching for that  I overlooked it in inputques) but thanks again .

**Comment by hessenfarmer** [comment]
> Thanks for the answer. 

you're welcome 

> If the only dependency will be checked inside the productionprograms. This means the economy has no influence on, which productionsite should start producing (the nearest one to where this ware is needed for example). 

Correct. Production is not based on the location in the economy. However you may have different economies which are evaluated all separately. Furthermore, requests shall be satisfied by warehouses normally (assuming we have at least the target_quantity on stock) and for this the nearest warehouse is preferred. So control for ware availability near a consuming productionsite is by setting storage in warehouses. Additionally we now have the possibility to skip the evaluation of economy needs in productionsites and let them produce idefinitly.     

> I just want to make sure I understood it correctly. If the dependency exists and if ware is not needed for now then all productiosites , which produce it, will stop(by skipping the action). once this ware is needed again, then all productionsites will start producing it at the same time right? 

Correct.

**Comment by Ahmad-fadl** [comment]
One last question.
target quantities for some basic products are calculated by the economy by using the total demand and distributing it to different warehouses, right?
target quantities of only "complementary" wares are adjustable by the player, right?
Sorry for so many questions.

**Comment by hessenfarmer** [comment]
target_quantity can be set in the economy settings for wares where a default_target_quantity is set in the units.lua file in data/tribes/initialization/. This should be the case for wares which need inputs to be produced, where the inputs are needed for another ware as well. Reason is to not waste input wares which are needed for other wares production as well. 
For wares not in the economy settings the target is indefinite, because the wares are produced without inputs needed, or need only a ware that has no other purpose (e.g. grapes for wine). These wares will be produced always as they are always needed

**Comment by Ahmad-fadl** [comment]
Thanks again.

**Comment by hessenfarmer** [comment]
you are welcome
