### ISSUE TITLE
Map options not in foreground of save map menu

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5791]
**To reproduce**
1. Open a map in editor
2. Click on 'Main menu → Save map'
3. Click on 'Show Map Options'
4. The map options window is behind the 'Save map' window. It is only accessible by clicking on 'Close/Cancel' in the 'Save Map' window

**Expected behavior**
The Map options menu should be in the foreground, not covered by the 'Save Map' menu.

**Version:**
 - OS: archlinmux
 - Widelands Version: 1.2~git26063 (abe0827@master) Debug

**Comment by tothxa** [comment]
I think this is a quite annoying regression with probably a not too hard fix to make it required for v1.2.
