### ISSUE TITLE
Workflow checks are failing

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5792]
**Describe the bug**
All workflows are failing codecheck and clang tidy due to an error on the Ubuntu-22.04 runner during dependency installation.

Upstream bug: https://github.com/actions/runner-images/issues/7192

**To reproduce**
1. See recent build logs

**Additional context**
Should we deploy the workaround to reset grub boot devices from https://github.com/actions/runner-images/issues/7192#issuecomment-1445902492 ?

**Comment by tothxa** [comment]
Uh-oh, upstream made it wontfix? https://github.com/actions/runner-images/issues/7192#issuecomment-1446766800

**Comment by tothxa** [comment]
OTOH, do we really need the `apt-get upgrade` in `install_deps.sh`?

**Comment by matthiakl** [comment]
> OTOH, do we really need the apt-get upgrade in install_deps.sh?

Until now it was safer. Otherwise the installation of a package may fail if it depends on an outdated package.
Since the runners are usually updated once per week, the question is, how likely it is for this case to appear.

**Comment by tothxa** [comment]
> > OTOH, do we really need the apt-get upgrade in install_deps.sh?
> 
> Until now it was safer. Otherwise the installation of a package may fail if it depends on an outdated package.

`apt-get update` already makes sure that `apt` will use the current package lists, so if any newly installed dependency of the workflow depends on an updated version of an already installed package, then I believe `apt` will pull in the upgrade along with the install. Also, since we're using LTS stable, dependency version bumps are extremely unlikely.
