### ISSUE TITLE
Keep command history of lua console after map reload

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5793]
When testing lua scripts in the editor it is sometimes needed to reload the map to get a "clean" map without any modifications from a lua script. E.g. i am working on a function `mountain_auto_height()` which should apply heights to mountainous areas automatically. During testing i have to reload the map several times. If i then open the lua script console i see the output from the previous calls, but the entered commands are not available by pressing `↑`. The previously used commands have to be copied again and pasted into the script console.

**Describe the solution you'd like**
Just reloading a map should keep the previously used commands in the history, so they will available when pressing  `↑`.

**Additional context**
Just two questions:
1. Why is the command history restricted to ~5 commands?
2. Writing long commands in the script console isn't possible because there is a limit of character length. I guess this is because the input field is restricted?

**Comment by tothxa** [comment]
Again, you opened an issue about something that also nagged me. :smiley:  I had already planned to improve command history for the lua console. As for longer scripts, I think we could have a button or something to open a multilineeditbox where it would be easier to enter scripts containing loops and if-s.

**Comment by hessenfarmer** [comment]
+1 for the history. 
for longer commands I always used .lua files and the dofile command. Else it's a pain in the ass.

**Comment by tothxa** [comment]
IIRC lua files are also problematic, because you can't specify paths outside of `<installdir>/data`. I plan to also address this part.

**Comment by frankystone** [comment]
Lua files are only problematic if they are part of an addon or scenario. For other scripts it's no problem, like @hessenfarmer  i use also some lua scripts stored in the folder `~/lua_scripts/`. Those can be run without problems within the lua script console by typing e.g. `dofile("/home/kaputtnik/lua_scripts/editor_functions.lua")`. The problem is that you have to call the `dofile`-command on every change of the script to reload it. If you have called some functions from this script in meantime the `dofile`-command isn't available in the history anymore and you have to type, or copy/paste, the command again. The easiest solution would be to have more space in the history, say remember the last 50 commands, even when the map get reloaded.
An autocompletion function would be the icing on the cake :smile: (Type e.g. `dofile` and the autocompletion searches the history for any command that starts with this string and auto completes it. Just like the autocompletion on the bash console).
