### ISSUE TITLE
Required WL version is not checked when add-ons are loaded

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5801]
**Describe the bug**
Incompatible add-ons can be enabled, and this may cause Widelands to crash.

**To reproduce**
1. Unzip [this add-on](https://github.com/widelands/widelands/files/10880235/larger_fonts_updated.zip) in your add-ons directory.
2. Start Widelands 1.1
3. Try to enable the add-on

also:
1. Enable the add-on using current master
2. Start Widelands 1.1
3. See error

**Expected behavior**
1. It shouldn't be possible to enable incompatible add-ons.
2. On starting up, only compatible add-ons should be loaded
3. In general (much harder), more error protection is needed to prevent problems in add-ons crashing the game

**Version:**
 - Widelands Version: v1.1

**Additional context**
See https://www.widelands.org/forum/post/40215/

The `matches_widelands_version()` function is only ever used to set the style of the version string in the list of add-ons. Incompatible add-ons shouldn't even be listed by default, and even if shown, the enable checkbox and the download button should be disabled for them.

`preload_addons()` should also check version compatibility.

"under discussion" whether (and how much) it should be fixed in a v1.1 update. For consideration, here's a minimal patch for v1.1 to prevent incompatible add-ons: [addon_ver_check.patch.txt](https://github.com/widelands/widelands/files/10883584/addon_ver_check.patch.txt)

**Comment by dreirund** [comment]
> *Incompatible add-ons shouldn't even be listed by default, and even if shown, the enable checkbox and the download button should be disabled for them.*

Why not allow the download but just block the enable?

**Comment by tothxa** [comment]
According to https://github.com/widelands/widelands/pull/5879#issuecomment-1528810128 fixing v1.1 is not strictly necessary.
