### ISSUE TITLE
Add Option to enable / disable Diplomacy to the game setup screens

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5816]
As AI will be able to operate Diplomacy soon, new players might end up against all AI players in a team. That might be too difficult. 
In the other way round an experienced player trying to win against all AI in a team might see the AI's leaving the team. 

So an option is needed in the game setup screens for single player and Multiplayer.

re #5774

**Comment by frankystone** [comment]
Disabling AI is also important for AI-Training, imho: I think during Ai-training each AI-Player should be treated as a single player.

**Comment by hessenfarmer** [comment]
> Disabling AI is also important for AI-Training, imho: I think during Ai-training each AI-Player should be treated as a single player.

each Computerplayer is always treated as a single player by the AI and the AI training. However as the decision making algorithm of the AI handling Diplomacy is designed to get trained, we need Diplomacy activated for AI training.
