### ISSUE TITLE
Appveyor x64 builds segfault in test_ai

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#5819]
**Describe the bug**
Appveyor builds on x64 platform are failing during execution of test_ai.

```
FAILED: CMakeFiles/_run_all_tests C:/projects/widelands/build/CMakeFiles/_run_all_tests 
cmd.exe /C "cd /D C:\projects\widelands\build && C:\msys64\mingw64\bin\ctest.exe --output-on-failure"
Test project C:/projects/widelands/build
    Start 1: test_ai
1/6 Test #1: test_ai ..........................***Exception: SegFault  0.05 sec
Adding testcase neuron
Adding testcase neuron_updated_weight
Adding testcase fneuron_position
Adding testcase flag_distance_soft_expiry
Adding testcase flag_distance_below_expiry
Adding testcase flag_distance_after_expiry
Adding testcase flag_distance_expiration_extension
Adding testcase flag_distance_road_builtexpiration_extension
Adding testcase flag_distance_old_removal
Adding testcase new_flag_road_not_prohibited
Adding testcase flag_candidate_init
Adding testcase flag_candidate_winner_score
Adding testcase flag_candidates_sorting
Adding testcase flag_sort_by_air_distance
Adding testcase flag_has_candidate
Log output will be written to: C:\projects\widelands\build\src\ai\test\stdout.txt

```

**Additional context**
Looks like #5433 again, so disabling logging will probably fix it, but maybe there is a better solution.

**Comment by hessenfarmer** [comment]
albeit hours of internet search I am not nearly near any understanding what is going on here.  However the test runs until the end and the output is written to the file correctly.

**Comment by matthiakl** [comment]
When I analysed the linked issue, I found that it might be related to the stderr and stdout redirection (see https://github.com/widelands/widelands/issues/5433#issuecomment-1206482618).
In some cases the file descriptors of the logs are already closed during tear down of the process, but the c runtime wants to flush stderr and stdout again. So maybe it is possible to revert the redirection and close the logfiles manually before the process ends?

**Comment by hessenfarmer** [comment]
either we give this a try or we skip the logging for our unit tests at all. 
As seen above we already write information until the redirection happens to the console. And the console is easier obtainable for our CI environments then the logfiles.
So I am in favour of handling windows like all other builds and simply write to the console

**Comment by hessenfarmer** [comment]
i now skipped redirection completely
