### ISSUE TITLE
Another dependency change on w*dows?

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5827]
**Describe the bug**
Building vcpkg deps fail in the workflow with error message:
```
sdl2-mixer has no feature named libvorbis.
```

**To reproduce**
See https://github.com/widelands/widelands/actions/runs/4541812472/jobs/8006464995?pr=5826
and https://github.com/widelands/widelands/actions/runs/4543971478/jobs/8009387502?pr=5824

**Comment by tothxa** [comment]
Looks like it's another transient error. Sometimes it happens, sometimes it doesn't?

**Comment by hessenfarmer** [comment]
seems not to be transient

**Comment by tothxa** [comment]
It's the worst. It looks like it should be permanent, but still some builds succeed. That just doesn't make sense…

**Comment by hessenfarmer** [comment]
@matthiakl any ideas?

**Comment by matthiakl** [comment]
Offending change is https://github.com/microsoft/vcpkg/commit/812080c89a2b66f7e54ded1f25c62191d5b01d46 , so we should remove libvorbis from the feature list.

> Sometimes it happens, sometimes it doesn't?

This looks like transitioning the runner version. Once all github runners are updated it will always fail.
If it fails, it uses the new vcpkg version https://github.com/microsoft/vcpkg/commits/b81bc3a83, if it succeeds it uses the old version https://github.com/microsoft/vcpkg/commits/cfdeb75bb
You can check the version from the cache key:
> Cache restored from key: 1e88a68ccec2eb374a6a1e02c4fb99951456cd8b4ecd9dc2c13050731ce736ad-**cfdeb75bb**-x86

Edit:
Failing runner image:
> Runner Image
  Image: windows-2022
  Version: 202303**26**.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20230326.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230326.1

Successful runner image:
> Runner Image
  Image: windows-2022
  Version: 202303**14**.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20230314.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230314.1
