### ISSUE TITLE
Pop-up messages steal button clicks

### ISSUE THREAD

**Issue by simply-peachy** [widelands/widelands#5840]
**Describe the bug**

A pop-up message can steal interactions on the world and button clicks on windows which are near the bottom-middle of the screen. This causes the view to zoom to the pop-up location instead of the click going to a button on a window or a click on the world.

**To reproduce**

1. Attempt to click in lower-middle area of world just as a pop-up shows. Particularly evident with several consecutive pop-ups, as they consume more screen space
2. Click is stolen by pop-up and instead, view is moved to location

When dealing with many building windows (e.g. upgrading many mines) this can become very annoying. Building windows always appear to spawn in a random place, and when they spawn near the bottom-middle, the pop-ups also steal clicks from them.

**Expected behavior**

- Pop-ups have minimal window ordering, or...
- Windows do not open in any area where a pop-up can appear, or...
- Pop-ups are disabled when the Inbox is open.

**Version:**
 - OS: Ubuntu 20.04
 - Widelands Version: 1.2~git26093 (ed99eb9@master) Release

**Comment by tothxa** [comment]
I believe this is a problem in #5785. Somehow the mouse pointer is placed where the default button should be before ensuring that the building or field action window is inside the main view. Also the new placement of these windows should consider the menu bar too, and place the windows above the clicked field when it would overlap the menu bar.

**Comment by tothxa** [comment]
#5841 will fix the part that concerns me. (the regression caused by #5785 which I also noticed, and planned to address) Having message pop-ups above windows is the right behaviour in my opinion.

**Comment by simply-peachy** [comment]
Fixed by #5841
