### ISSUE TITLE
Login in Add-On Manager fails with "The entered username or password is invalid: Expected end of stream, received:", but credentials work at widelands.org.

### ISSUE THREAD

**Issue by dreirund** [widelands/widelands#5851]
Please fill out the relevant sections below and delete the rest.

### Describe the bug

I want to log in in the Widelands Add-On Manager with my username which I have registered at widelands.org (and there I can login with my credentials).

After I entered my username and password in the Widelands Add-On Manager, it shows an error popup window

> #### *Wrong Password*
> *The entered username or password is invalid:*  
> *Expected end of stream, received:*  

See screenshot below.

### To reproduce

1. Start Widelands
2. Click on "Add-Ons"
3. Click on "Not logged in"
4. Enter my credentials which work at https://www.widelands.org/accounts/login/
5. See the reported error

### Expected behavior

Succesful login or an error message which is more conclusive

### Screenshots

![Widelands Add-On Manager login error](https://user-images.githubusercontent.com/1590519/231720215-987fb7d2-bbd7-42c8-80f1-174491d6c833.png)

### Version

* OS: [Artix GNU Linux](http://artixlinux.org/) (rolling release)
* Widelands Version: Git checkout from 2023-04-12,  
  `widelands --version`: `1.2~git26101 (fdac328@master)`

**Comment by Noordfrees** [comment]
> Enter my credentials which work at [widelands.org/accounts/login](https://www.widelands.org/accounts/login/)

Quote from the add-on manager's login box:
> Please log in at `https://widelands.org/accounts/register/` ***and set an online gaming password on your profile page***.

For security reasons, authenticating within Widelands doesn't use your website password; use the online gaming password which you can set at https://www.widelands.org/ggz/changepw

**Comment by dreirund** [comment]
> > Enter my credentials which work at [widelands.org/accounts/login](https://www.widelands.org/accounts/login/)
> 
> Quote from the add-on manager's login box:
> 
> > Please log in at `https://widelands.org/accounts/register/` _**and set an online gaming password on your profile page**_.
> 
> For security reasons, authenticating within Widelands doesn't use your website password; use the online gaming password which you can set at https://www.widelands.org/ggz/changepw

OK, my fault. Closing the issue as irrelevant.
