### ISSUE TITLE
Holding down mouse button and moving over the map to place something does not work anymore

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5855]
With commit 1.2~git26104 (059c44a@HEAD) Debug it is possible to hold down the left mouse button and move the mouse  over the map to place e.g. trees on every possible node. This feature got lost between this commit and current master. Now you have to make a click on each node to place something.

**To reproduce**
1. start editor
2. choose an immovabnle (e.g. tree)
3. hold down left mouse button and move the mouse over the map keeping the mouse button pressed
4. there is only one tree placed

The same happens with all map objects and resources including removing.
 
**Expected behavior**
Moving the mouse with button pressed should behave like before: On each possible node a tree should be placed.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.2~git26109 (2bcc891@master) Debug

**Comment by Noordfrees** [comment]
It still works in 167ae865eaae880d1aba3b6dfc21aad768ea34d8 for me, so I guess #5820 might have broken it?

**Comment by frankystone** [comment]
Yes, that's the culprit, i didn't expected that those changes may affect the editor. @tothxa ?

**Comment by tothxa** [comment]
Sorry for missing transitive uses of MapView when doing #5820. #5856 localises the problematic change to watch windows.
