### ISSUE TITLE
Naval Warfare: Make detected enemy portspaces adressable for ships

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5890]
Once an enemy naval attacktarget (ports or port spaces under enemy control) has been found It shall be added to the potential address list of an own ship, to avoid navigating the ship there by hand. 
This might need to have presented the adresses in atabbed way (own ports, own ships, enemy ports, enemy portspaces)

**Comment by Noordfrees** [comment]
How should discovered portspaces be named/distinguished in the list? We can't use coordinates since those are hidden from players in release builds. Maybe with ship name and gametime of first discovery ("Portspace discovered by Uthlande at 1:23:45")?

**Comment by tothxa** [comment]
> How should discovered portspaces be named/distinguished in the list? We can't use coordinates since those are hidden from players in release builds. Maybe with ship name and gametime of first discovery ("Portspace discovered by Uthlande at 1:23:45")?

Probably not worth the trouble, but would be kind of cool: nearest own port and map direction, e.g. North-East of Aalkersem.

**Comment by hessenfarmer** [comment]
Maybe "Portspace <continuous number> of Player <player_name> found at <time>"   I think the shipname is of no interest while the owning player is. time would allow to search in the messages
