### ISSUE TITLE
Buildhelp image names need updating in Tutorial 01

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5899]
**Describe the bug**
#5868 replaced the buildhelp images with mipmapped ones, but the tutorial referred to them by direct path and filename.

**To reproduce**
1. Start Tutorial 01
2. Get to the "How to Build a Quarry" message which expalins the buildhelp icons
3. See error

**Expected behavior**
The correct buildhelp icons should be shown.

**Screenshots**
![tutorial1_buildhelp](https://user-images.githubusercontent.com/80712255/235807088-55a31103-6cf2-4fb4-bdb8-c8a48e3959c2.png)

**Version:**
 - Widelands Version: [82cf848](https://github.com/widelands/widelands/commit/82cf848537cab6232255c9f4a4b8b9485a725723)

**Additional information**
The easy solution is to update the hardcoded names to the scale 1 names. The correct one would be to allow look-up of mipmapped images from Lua?

**Comment by hessenfarmer** [comment]
I think loking up mipmaps would require to have the possibility to show animations in campaign message boxes. So for the moment being the hardcoded way to a single scale 1 picture would be sufficient.

**Comment by Noordfrees** [comment]
Since this code is separate from animations and entirely handled by `ImageCache::get` we should definitely implement the proper fix there, so it still serves the 1x mipmap even when no scale is provided. Sorry for overlooking this :(

**Comment by tothxa** [comment]
> Since this code is separate from animations and entirely handled by `ImageCache::get` we should definitely implement the proper fix there, so it still serves the 1x mipmap even when no scale is provided.

That will be easy indeed, thanks for the tip. Though this will then be separate from the other tweaks I planned for the tutorial.

**Comment by tothxa** [comment]
OK, not so simple after all. There are 3 places involved:

1. The campaign texts are rendered by the richtext engine, which just looks up the image with the default options in
2. `g_image_cache`. The default options are to look up without scaling and
3. allow themes to override by the style manager.

The fallback image we get is provided by the style manager.

I'm not sure whether it would be OK to skip theme lookup in the richtext engine, but scaling should be implemented, because the markup allows it. But that's a separate problem.

I don't think `resolve_template_filename()` should add the "_1" on its own, and try all the way through with both names.

But `ImageCache::get()` is heavily recursive, so it's not trivial to try both ways in the case of a lookup failure.

The "real" lookup in `wui/interactive_base.cc` uses theme lookup and specifies the scale. With the scale index, not the actual scale. So maybe try to figure out the scale index in `rt_render.cc` after all? That would actually do the right thing here… but may cause problems elsewhere… and still does not fix `ImageCache::get()` in general.

This really needs a major refactoring to bring all these together, and make it the base of image file handling of animations too.

OTOH, for the tutorial, specifying "_1" doesn't look all that bad after all…
