### ISSUE TITLE
Editor: Exchange terrain tool

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5919]
Sometimes one want to exchange a specific terrain with another terrain. For example if one want's to exchange no-tree mountains with tree-friendly mountains he has to choose a tool size of one and has to be careful not to change the terrains close to the mountains while moving the mouse.

**Describe the solution you'd like**
There should be a "Replace Terrain" tool which changes only one type of terrain. For example one can choose the terrain which should be removed (e.g. tree unfriendly mountains) and choose a terrain which should be set instead (e.g. tree-friendly mountains). So one can choose a bigger tool size without worrying to alter the map in a not wanted way.

**Describe alternatives you've considered**
No idea.

**Additional context**
Especially for mountains this might be difficult, because there are several tree-unfriendly terrains which might be set on an area of the map before the wanted exchange. So either one should have the possibility to choose more than one terrain for removing and more than one terrain for exchanging, or one has to do the exchange twice: One time for exchanging mountain1 with tree-friendly terrain1 and one time for exchanging mountain2 with tree-friendly terrain2.

**Implementation steps**
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by Noordfrees** [comment]
I think this is a candidate for an add-on once the UI plugin implementation is complete.
