### ISSUE TITLE
Naval Warfare: Port Space sometimes not conquered when attacking Port under construction

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5980]
**Describe the bug**
In opur Training Game I attackes a port under construction. After the port was finished the soldiers conquered the port but not the land. in the reload of the game the land around the portspace was conquered. 

**To reproduce**
1. Attack a port under construction?
2. Wait until the port is finished
3. the land still belongs to the original owner

**Expected behavior**
The land shall be conquered by the invasion crew.

**Comment by Noordfrees** [comment]
I believe #6115 fixed this
