### ISSUE TITLE
FieldActionWindow no longer moves inside parent

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5984]
**Describe the bug**
The field action window no longer moves inside the Widelands window when changing its tab makes it bigger.

**To reproduce**
1. Click on a big building plot to open the field action window. May need out trying until you get a position where the window opens near the bottom of the screen.
2. Switch to the Medium tab.
3. The lower part of the window is cut off, rendering buildings therein inaccessible until manually dragging and repositioning the window.

**Expected behavior**
The window should jump to be fully inside the parent, like it used to in v1.1.

**Screenshots**
After opening the window:
![shot0003](https://github.com/widelands/widelands/assets/48293446/4f341d5c-6dbe-4181-a1b2-abeb456a09bf)
After using the mousewheel to select a different tab:
![shot0004](https://github.com/widelands/widelands/assets/48293446/b11fcd10-ebfa-4b82-9593-b9831fc6d7a8)

**Version:**
 - OS: Debian Unstable
 - Widelands Version: Tournament2023

**Additional context**
Other tabbed windows such as the stock menu are also affected. Seems to be a general problem with `Window::move_inside_parent`.

**Comment by tothxa** [comment]
I believe it's the change in `UniqueWindow::move_inside_parent()`: once they have a position, they don't get moved automatically. I did that to prevent windows jumping inside when the inputs are collapsed and the building is started or stopped. That part may be fixed by the other changes to input queue initialisation now, but that needs testing.

**Comment by tothxa** [comment]
OTOH it can be equally annoying when you adjust a window to the right edge of the screen, then you switch to a different tab and back, and now your window is not at the edge any more.
