### ISSUE TITLE
only trigger tests in workflow if something relevant has changed

### ISSUE THREAD

**Issue by SimonHeimberg** [widelands/widelands#6020]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Tests are also run if only a file changed which has nothing to do with the code
example: https://github.com/widelands/widelands/pull/6019

**Expected behavior**
I suggest to skip tests on obvious cases by using ...

either `paths` or `paths-ignore` for the entire workflow ([workflow-syntax-... on docs.github](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore))
or conditions for some jobs ([using-conditions-... on docs.github](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution))

**some (include) paths for ...**
compile and tests: src/, data/ (should we exclude some content?), test/, cmake/ (?), regression_test.py, (probably some more)
documentation: (is fast anyway) doc/, src/, data/scripting/, data/tribes/, data/world/, data/txts/

**Comment by SimonHeimberg** [comment]
By the way, `build.yaml` only checks json for `data/txts/` which contains one json file.
https://github.com/widelands/widelands/blob/2d5e5dc33957352d8c8cba3f435be315e7574684/.github/workflows/build.yaml#L22
I found more files:
~~~
 2 ./utils/win32
54 ./xdg/translations
 1 ./data/txts
53 ./data/i18n/locales
~~~
Should some of those be checked as well?

**Comment by SimonHeimberg** [comment]
Could one of the test suites also create an artifact? I can only download for MacOS and Windows, but not linux: https://github.com/widelands/widelands/actions/runs/5556166018#artifacts

**Comment by SimonHeimberg** [comment]
To just skip **steps** or **jobs** if some files have changed, this action could help: https://github.com/dorny/paths-filter

**Comment by matthiakl** [comment]
> Could one of the test suites also create an artifact?

Do you have a special reason why you need the Linux artifacts? Most developers use Linux for developing and simply compile it locally. Also because of different distributions the dynamically linked binaries from Ubuntu may not work for you.

Please consider moving this issue into our discussion thread on this topic: https://github.com/widelands/widelands/discussions/5880

**Comment by SimonHeimberg** [comment]
> > Could one of the test suites also create an artifact?
> 
> Do you have a special reason why you need the Linux artifacts? Most developers use Linux for developing and simply compile it locally. Also because of different distributions the dynamically linked binaries from Ubuntu may not work for you.
>
Right, it would likely not work for me because of those libraries.

I would like to see how pr #6017 looks (and test if pr #6001 works on netclient). I use linux but would prefer to not install a build environment for every project I contribute to. Since I wrote this I made some tries anyway but did not yet succeed. :disappointed:
