### ISSUE TITLE
Naval warefare: Assertion `ship->get_ship_type() == ShipType::kWarship' failed.

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#6022]
If a warship is set to guard an expedition ship and you set the destination for the expedition ship to a port the assertion happens as soon the expedition ship arrives at the port.

**To reproduce**
1. Load this save game: [Assertion_not_a_warship.zip](https://github.com/widelands/widelands/files/12061935/Assertion_not_a_warship.zip)
2. Set destination for ship Cato to the Ship Saledus
3. Wait a bit (not sure if this is needed)
4. Set destination for ship Saledus to the port Tarraco
5. As soon Saledus arrives at the port the assertion happens

**Expected behavior**
No assertion

**Version:**
 - OS: archlinux
 - Widelands Version: 1.2~git26244 (e52bb4c@HEAD) Debug (Should be the Tag Tournament 2023)

**Comment by Noordfrees** [comment]
Can you test if this still happens with #6006?

**Comment by frankystone** [comment]
Looks like #6006 solves this issue :+1:
