### ISSUE TITLE
Ships can be used to explore unexplored area

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#6058]
Especially in conjunction with naval warefare:
If you send an expedition into the wide unexplored ocean the captain of the ship (the player) does not know what the ship may find. The ship is sailing into the dark. During exploration the ships explores parts of the map and at some point the captain may decide to sail back, probably to refresh the provision (:smile: ) or to follow a warship.

If the player chooses the destination in the ships window the ship will sail the shortest way back (or to the warship), probably through unexplored areas. Because the captain does not know the map: How is this possible? This results in exploring formerly unknown areas, although the captain does not know them.

**Describe the solution you'd like**
When setting a destination for a ship, the ship should sail only known areas of a map, so only use those fields which are already explored to keep the other parts of a map unknown, a secret.
To find the shortest way, e.g. between two ports, the player has to explore those parts of the map with an expedition or warship first.

**Describe alternatives you've considered**
No other idea.

**Additional context**
This applies also to ferries, but can be neglected, imho.

**Implementation steps**
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by Noordfrees** [comment]
This also applies to lumberjacks and hunters searching for objects to remove, soldiers looking for the way to an enemy militarysite they are separated from by some obstacle, and many more. Pathfinding never takes visibility into account. 

In principle we could simply add a new "`CheckstepSeen`" to the pathfinding functors that test whether a movement step is allowed or not, but if we do this we should do it consistently for *every* movement of *every* player bob IMHO, or the obvious question will be "why can soldiers do that but ships cannot". And this would be a pretty major change – how to handle the case that no movement is possible using only known fields, especially for soldiers or for non-expedition transport ships? Note also that calculating paths between ports is extremely costly so we try to do it once on port completion and then never again. There are probably other complications…

**Comment by tothxa** [comment]
I understand the point that they shouldn't be able to know the shortest path in advance, but on the other hand, it is the task of ships to discover the map. So I don't think it's possible to properly solve this, and I don't think it's much of a problem anyway.

**Comment by hessenfarmer** [comment]
well, for me this is the same thing as happened with Columbus: find the (shorter) way west to india. so it is not completely illogical for a ship knowing where it is (by navigation) to try the direct way to its known destination through unknown waters.      
so -1  from me on changing anything here.

**Comment by frankystone** [comment]
Ok, then :-)
