### ISSUE TITLE
Crash in branch naval-warefare-ai: assertion in marine_main_decisions

### ISSUE THREAD

**Issue by carli2** [widelands/widelands#6080]
```
widelands: /home/carli/sources/widelands/src/ai/defaultai_seafaring.cc:174: bool AI::DefaultAI::marine_main_decisions(const Time&): Zusicherung »tradeships_count >= expeditions_in_progress« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by hessenfarmer** [comment]
well this branch is far from being ready to review. By this filing bugs against a branch in this state is only cluttering the bugs list imho. 
If you want to contribute to the branch we might open a draft PR where we can discuss things, and were changes could be proposed.

**Comment by carli2** [comment]
so it won't be helpful to catch and collect error messages?

**Comment by hessenfarmer** [comment]
collecting error messages is never useless. I will open a draft PR on this brnch and then we could share such information in the PR rather then flooding the bugs list

**Comment by hessenfarmer** [comment]
PR is up #6083
