### ISSUE TITLE
Restarting replays may cause desync

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#6094]
**Describe the bug**
While watching the replays of WorldSavior vs. Mars, I tried to restart, but after restarting the replay desynced almost immediately. When the same file is first watched, it runs through properly.

**To reproduce**
1. Download and unpack the replays from [this forum post](https://www.widelands.org/forum/post/40705/)
2. Start any replay later than 20:35
3. While it's playing, restart it

**Expected behavior**
No desync on restarting of compatible replays

**Version:**
 - OS: antix / Debian buster + backports
 - Widelands Version: Tournament2023 (08-15)

**Additional context**
The 20:05 file can be watched all the way through and it's still restartable. The change causing the problem happens around 03:54 gametime early in the 20:09 file. If you restart earlier, then it can run through, if you restart later, it desyncs at this time.

**Comment by Noordfrees** [comment]
This is a real desync, one of the interesting ones ;)

Relevant sync excerpt:
First run
```
[00:03:54.103 game] DEBUG: [sync:00124587 t=234103] 84
[00:03:54.103 game] DEBUG: [sync:00124588 t=234103] 56 0a 39 b3
```
Second run
```
[00:03:54.103 game] DEBUG: [sync:00124612 t=234103] 84
[00:03:54.103 game] DEBUG: [sync:00124613 t=234103] 82 5a 61 17
```
Sync ID 84 is a random number, and the 4-byte argument is the random number generated. So at this time the random number generator diverges. Perhaps its state is not correctly reloaded.
