### ISSUE TITLE
game title box in multiplayer is not correctly layouted

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#6130]
**Describe the bug**
in the Multiplayersetup screen the box with the game title to be published on the meta server is not showing the text from the beginning, if the previous and remembered title was long. see screenshot
![grafik](https://github.com/widelands/widelands/assets/43039887/d7ae733b-73dd-4def-929c-058283c1564e)

**Comment by Noordfrees** [comment]
Fix would be to calculate the maximum `scrolloffset` in `EditBox` and limit `d->scrolloffset` to that value in every `layout()` call

**Comment by jtorruellas22** [comment]
Hello I was wondering if this bug has been fixed?
