### ISSUE TITLE
Commandline option --editor should open last edited map

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#6138]
`widelands --editor` starts always with a default map size and terrain. Using this command line option it would be nice if the last edited map would be opened in the editor. Just like pressing W in the widelands main menu.

Personally i have created two starters (desktop-files): one starts widelands, the other one starts the editor. But the second one is currently next to useless, because i have to load a map for further editing.

**Describe the solution you'd like**
`widelands --editor` should open the last edited map, if any. If no last edited map can be found, just act like now.
`widelands --editor=/path/to/map` should load the given map.

**Describe alternatives you've considered**
No idea.

**Implementation steps**
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by frankystone** [comment]
Or `widelands --editor` should open the `Load map` dialogue as default.

**Comment by tothxa** [comment]
To me, opening the last map when no map is specified is not the expected behaviour. How about adding another command line option (e.g. `--editor-last` or `--editor-resume`) for your use case?

Load map is better from a user expectation point of view IMO.

Maybe also a `--editor-new` option to round it off?

**Comment by tothxa** [comment]
> What purpose has the `--editor` switch currently? Is there any good reason to just start the editor with a 64x64 map with a default terrain?

Well, if you start up any editor, it's usual that it either starts with a blank document (our current behaviour), or asks whether to do that or open some existing one, usually with a list of recent files. But as `--editor=<file>` opens the file, it may make sense to ask what to open if it gets nothing, but more so if we have the other options.

My idea for `--editor-new` (in case we switch the default to the open dialog) is to open the new map dialog which at least allows setting some parameters for the new map.

**Comment by frankystone** [comment]
What other editors do usually mustn't be valid for widelands, imho.

Anyway: If you think this idea is worth the work and you want to implement it, it's up to you how to implement it :)

Main thing for me is to have the possibility to create a starter which opens the last edited map.
