### ISSUE TITLE
naval warfare: ships shold be attackable although if in battle

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#6161]
from the tournament experience and to keep consistency with land based warfare it should be possible to attack a shipl that is already in battle by just add the new aatacker to the stack of attackers

**Comment by Noordfrees** [comment]
Isn't that already possible, or has that regressed?

**Comment by hessenfarmer** [comment]
it is possible but it seemed like it is not in yesterdays match between Mars and Teayo.    
This might have been mainly due to no single ship clickable and it not being possible to see ships in combat from the list item or from the selected ship window.  
but I will open a new issue for that
