### ISSUE TITLE
Workflow msvc failure: cmake doesn't find brotlidec-static

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#6175]
**Describe the bug**
msvc build in today's workflow build of master failed because of cmake error on missing brotlidec-static.

**To reproduce**
See https://github.com/widelands/widelands/actions/runs/6427093985/job/17457822507

**Expected behavior**
Build succeeds.

**Version:**
 - OS: w*ndows runner image
 - Widelands Version: https://github.com/widelands/widelands/commit/fd8328649b85a3e00e586a370c1b23f13a3db258

**Additional context**
@matthiakl 
Caused by last vcpkg update? If so, we should include a test build of Widelands in the vcpkg update workflow.

Also, why is brotli even needed on w*ndows if not on other platforms?

**Comment by matthiakl** [comment]
> Caused by last vcpkg update? 

Yes, brotli was updated from 1.0.9 to 1.1.0 where they renamed the static library targets.

> If so, we should include a test build of Widelands in the vcpkg update workflow.

Well, we could, but changes in static dependency often also break mingw builds.

> Also, why is brotli even needed on w*ndows if not on other platforms?

On Windows we build a static executable so every secondary dependency must be listed explicitly in the linker.

**Comment by tothxa** [comment]
> > If so, we should include a test build of Widelands in the vcpkg update workflow.
> 
> Well, we could, but changes in static dependency often also break mingw builds.

I think we should do it to avoid having to do quick fixes in situations like this. That was the reason for pinning the vcpkg version in the first place after all.
 
> > Also, why is brotli even needed on w*ndows if not on other platforms?
> 
> On Windows we build a static executable so every secondary dependency must be listed explicitly in the linker.

OK. Next question though: :smiley:  can't it be disabled when we build these deps ourselves?

**Comment by matthiakl** [comment]
> I think we should do it to avoid having to do quick fixes in situations like this. That was the reason for pinning the vcpkg version in the first place after all.

OK, I will add it.

> OK. Next question though: 😃 can't it (and other such dependencies) be disabled when we build these deps ourselves?

No. On Linux system with dynamic linking, when you install the Widelands dependencies those deps are automatically installed with them to properly resolve all links on runtime. On Arch the dependency chain for brotil for example is: sdl2_ttf → freetype2 → brotli. For static linking all of the dependencies must be resolved already during compilation, this is the reason why we have those lists.
