### ISSUE TITLE
Lua Coroutine failed

### ISSUE THREAD

**Issue by spirillen** [widelands/widelands#6176]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
![image](https://github.com/widelands/widelands/assets/44526987/2a36be20-8bf5-4ff9-a0e2-75221c567927)

**To reproduce**
1. Start new random game
2. ![image](https://github.com/widelands/widelands/assets/44526987/c346301e-383f-4113-b018-a156d68717e3)
3. 
![image](https://github.com/widelands/widelands/assets/44526987/493dccfd-3d72-40a0-a92c-8948c738abe6)

**Expected behavior**
Hmm let's see... :thinking: 

**Screenshots**

**Version:**
 - OS: "Ubuntu 22.04"
 - widelands --version
This is Widelands version 1.2~bzr10781-202310060346 Release
[00:00:00.000 real] INFO: Set home directory: /home/spirillen/.local/share/widelands
[00:00:00.000 real] INFO: Set configuration file: /home/spirillen/.config/widelands/config
[00:00:00.000 real] WARNING: No locale translations found in /usr/share/games/widelands/data/locale
[00:00:00.000 real] INFO: selected language: (system language)
[00:00:00.000 real] INFO: using locale en_DK.UTF-8
=========================================================================
This is Widelands version 1.2~bzr10781-202310060346 Release

**Comment by tothxa** [comment]
Oops. We should have properly tested all starting conditions for #6170…

**Comment by spirillen** [comment]
> Oops. We should have properly tested all starting conditions for #6170…
> 
> Thanks for reporting. :)

Can see you added the `amazon` tag, this happened for two others as well, please just don't ask me to remember which from yesterday...

**Comment by tothxa** [comment]
> Can see you added the `amazon` tag, this happened for two others as well, please just don't ask me to remember which from yesterday...

My guess is that one of the computer players must have had Amazons with one of the affected starting conditions (trading outpost, village, fortified village). I've tested it and I got the same message if it was another player. I also tested trading outpost and village of all other tribes (that's what fits on a 8 player map), and it started without any problem.

**Comment by frankystone** [comment]
If i remember correctly there were similar issues with the starting conditions in the past. Maybe there should be a test for this kind of issues? Don't know if it's feasible though.

**Comment by tothxa** [comment]
> If i remember correctly there were similar issues with the starting conditions in the past. Maybe there should be a test for this kind of issues? Don't know if it's feasible though.

I've thought of that too. Maybe it's possible with game templates? I'll try to add tests for all starting conditions for all tribes.
