### ISSUE TITLE
Cannot build with external minizip

### ISSUE THREAD

**Issue by brad0** [widelands/widelands#6266]
**Describe the bug**
Building with external minizip does not work. CMake does not pass along the library path.

**To reproduce**
On a non-Linux OS..
CMake...
make / ninja..
..builds..
..gets to linking stage..
..fails..

**Expected behavior**
CMake passes along the library path and links properly instead of passing a library name without the path.

**Version:**
 - OS: OpenBSD. Applicable to anything non-Linux.
 - Widelands Version: v1.1, but also applies to ToT git.
 - Enabled Add-Ons: whatever the default build is without any additional parameters.

```
ld: error: unable to find library -lminizip
```

Looking at cmake/WlFunctions.cmake I see the header path being added but not the library path.

**Comment by hessenfarmer** [comment]
Hi,
to solve any issue we need more information as outlined in our issue template. somplease consider resubmitting this issue using the template as otherwise we can't do much about it

**Comment by tothxa** [comment]
Specifically, please let us know what operating system you are using, and what commands you used to compile Widelands. E.g. did you use `compile.sh`, or did you run `cmake` and `make` or `ninja` on your own? How is the `minizip` library installed, and which version?

I normally build Widelands with the systemwide `minizip` on Debian buster without any problems.

**Comment by hessenfarmer** [comment]
@widelands/developers 
as we have no valuable information here and the issue submitter @brad0  did not provide any further information I propose to close this as won't fix

**Comment by tothxa** [comment]
Thank you for the info and the PR. :)
