### ISSUE TITLE
Workflow mingw build doesn't find `ninja` and C/C++ compiler

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#6285]
**Describe the bug**
Workflow builds are failing in mingw job with:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**To reproduce**
See:
 - https://github.com/widelands/widelands/actions/runs/7372058568/job/20060435425
 - https://github.com/widelands/widelands/actions/runs/7371563696/job/20059372674?pr=6257
 - https://github.com/widelands/widelands/actions/runs/7371817137/job/20059878798?pr=6282

**Additional context**
First happened in https://github.com/widelands/widelands/actions/runs/7348943728/job/20010113598 but went away on re-running the job. But now it looks like all workflows are failing on this?

**Comment by tothxa** [comment]
Re-running at https://github.com/widelands/widelands/actions/runs/7371563696/job/20060717042?pr=6257 fixed it again... This is not good...

**Comment by matthiakl** [comment]
The reason is that glbinding package dropped 32bit support in latest 3.3.0 release and cannot be updated anymore.
See https://github.com/widelands/widelands/actions/runs/7374445062/job/20064847300#step:3:122
Caused by https://github.com/msys2/MINGW-packages/commit/1f1f2a7b91a5a354ae1759bd8969dac51c2dae72
This is really bad, as we might not be able to get a 32bit build in the CI. As short term workaround I propose to set `fail-fast: false` for the mingw build, to have at least the 64bit running again.

**Comment by matthiakl** [comment]
This issue will grow bigger, while MSYS is dropping more and more 32bit packages: https://github.com/msys2/MINGW-packages/discussions/19326 and https://www.msys2.org/news/

**Comment by tothxa** [comment]
So it's about getting rid of 32bit to reduce their maintenance burden... But we lose a lot of portability testing because of that... I suppose we already don't have a 32bit option for linux runners (also bad)... (is it at least possible to have some 128bit builds or something to avoid a 64bit monoculture? :)))

Isn't it possible to use some fixed older 32bit msys/mingw release for the 32 bit builds?

**Comment by matthiakl** [comment]
> Isn't it possible to use some fixed older 32bit msys/mingw release for the 32 bit builds?

I am trying that in #6287 

Regarding the use of 32bit builds, check release 1.1 here: https://hanadigital.github.io/grev/?user=widelands&repo=widelands
Only 7,5% of the Windows downloads are 32bit.

**Comment by tothxa** [comment]
> Regarding the use of 32bit builds, check release 1.1 here: https://hanadigital.github.io/grev/?user=widelands&repo=widelands Only 7,5% of the Windows downloads are 32bit.

Well, my main point was that building with various bit lengths can help us keeping our code cleaner. (or sometimes dirtier, but aware of where we have portability problems :) But speaking of those download stats, I wouldn't say 32bit w`*`ndows is entirely dead yet (actually its ratio even grew from 1.0 to 1.1), and it's not that much behind the non-w*ndows downloads.

**Comment by hessenfarmer** [comment]
well, I already was afraid we might need to drop our x86 builds sooner or later. It might be sooner though, or we might be forced to build the latest x86 packages ourselves.
A third option would be to stay with the latest packages provided forever, but that might result in incompatible builds and potential security issues. 
So for the moment being I propose to stick with the last glbinding. 
I am not sure whether asking for 32 bit packages by using the provided msys issue template would do much help. But we might ask for providing it until our next release.
